### ISSUE TITLE
[BUG] JobFingerprint - : org.postgresql.util.PSQLException: ERROR: value too long for type character varying(512) 

### ISSUE THREAD

**Issue by gwieczorek-it** [jobrunr/jobrunr#1004]
### JobRunr Version

7.0.1

### JDK Version

openjdk-21

### Your SQL / NoSQL database

Postgres 15

### What happened?

Problem with character encoding when the lowercase version of a character takes up more bytes than its uppercase counterpart.
Long DTO used as job parameter, containing Turkish letter "İ"  - jobfingerprint generated over max 512 characters.
Problems does not apply to the Swedish characters, cose they are uniformly encoded in UTF-8 regardless of their case.

Stack trace:

> org.postgresql.util.PSQLException: ERROR: value too long for type character varying(512)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:144)
	at org.jobrunr.storage.sql.common.db.Sql.insert(Sql.java:117)
	at org.jobrunr.storage.sql.common.JobTable.insertOneJob(JobTable.java:312)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:165)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:283)
	at org.jobrunr.scheduling.AbstractJobScheduler.saveJob(AbstractJobScheduler.java:223)
	at org.jobrunr.scheduling.JobRequestScheduler.create(JobRequestScheduler.java:87)
	at com.fourthwall.app.JobRunrTestEndpoint.test(JobRunrTestEndpoint.kt:37)

Problem probably lays in invalid order of: short_func().toLowerCase() in JobTable -> AbstractJob

>  public String getJobFingerPrint() {
        return this.abbreviateFieldIfTooLong(JobUtils.getJobFingerprint(this.jobDetails), 512);
    }
    
<img width="2261" alt="Screenshot 2024-04-22 at 1 40 17 PM" src="https://github.com/jobrunr/jobrunr/assets/3666757/4ada6de4-2042-49b1-a3d2-a49561b67696">

Above function returns 512 string.length , but :

>.with("jobFingerprint", (job) -> {
            return job.getJobFingerPrint().toLowerCase();
        })
 
 returns 514 string.length 
 
<img width="2148" alt="Screenshot 2024-04-22 at 1 41 50 PM" src="https://github.com/jobrunr/jobrunr/assets/3666757/dc23cd47-6435-4f01-98e1-bc07f41d21fd">

Full input was over 600 chars long:
<img width="2096" alt="Screenshot 2024-04-22 at 1 39 05 PM" src="https://github.com/jobrunr/jobrunr/assets/3666757/5c5bd76c-3c64-4aa7-9fc5-db54359be03f">

### How to reproduce?

```kotlin
data class LargeObject(
    val notRegularCharacters: String = "FİN Hİ Å, Ä i Ö",
    val somethingLong: String = "0123456789".repeat(51),
) : JobRequest {
    override fun getJobRequestHandler()= LargeObjectHandler::class.java
}

@Service
class LargeObjectHandler : JobRequestHandler<LargeObject> {
    override fun run(largeObject: LargeObject) {
        TODO("Not yet implemented")
    }
}

@RequestMapping("/api/jobrunr", produces = [MediaType.APPLICATION_JSON_VALUE])
@RestController
class JobRunrTestEndpoint(
    val jobRequestScheduler: JobRequestScheduler
) {

    @GetMapping("/test")
    fun test() {
        jobRequestScheduler.create(
            JobBuilder.aJob()
                .withName("JobFingeprint max length exceeded")
                .withJobRequest(LargeObject())
        )
    }
}
```

**Comment by rdehuyss** [comment]
Hey @gwieczorek-it ! Can I quickly ask for which company you are working? I'll move this issue to the JobRunr Pro repo.
