### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by itizarsa** [jobrunr/jobrunr#1022]
### Runtime information
- __Timestamp__: 2024-04-29T03:47:14.187011304Z
- __Location__: BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c
- __JobRunr Version__: 7.1.0
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 21.0.3
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 1151328b-6dda-43be-a99b-03b9066f951c
(workerPoolSize: 6, pollIntervalInSeconds: 15, firstHeartbeat: 2024-04-29T03:34:54.090955200Z, lastHeartbeat: 2024-04-29T03:47:13.288078900Z)

#### Concurrent modified jobs:
Job id: 018f22e6-cbae-7918-8a71-bdd091835939
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.386330919Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487649778Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487649778Z) ← ENQUEUED (at 2024-04-29T03:45:16.638374995Z) ← FAILED (at 2024-04-28T04:15:56.471340989Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271480423Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270462901Z) ← ENQUEUED (at 2024-04-28T04:11:57.570186864Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786544411Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487649778Z) ← ENQUEUED (at 2024-04-29T03:45:16.638374995Z) ← FAILED (at 2024-04-28T04:15:56.471340989Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271480423Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270462901Z) ← ENQUEUED (at 2024-04-28T04:11:57.570186864Z) ← SCHEDULED (at 2024-04-28T04:11:41.870469456Z)

Job id: 018f22e5-a3f9-74df-aad4-5166c4e6e593
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.387544996Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487654966Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487654966Z) ← ENQUEUED (at 2024-04-29T03:45:16.885197929Z) ← FAILED (at 2024-04-28T04:15:56.569754881Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271476821Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270461343Z) ← ENQUEUED (at 2024-04-28T04:10:38.468856310Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786541711Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487654966Z) ← ENQUEUED (at 2024-04-29T03:45:16.885197929Z) ← FAILED (at 2024-04-28T04:15:56.569754881Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271476821Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270461343Z) ← ENQUEUED (at 2024-04-28T04:10:38.468856310Z) ← SCHEDULED (at 2024-04-28T04:10:26.169494702Z)

Job id: 018f22e6-d31b-70ba-8d94-671db8a80a1e
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.387708044Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487657064Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487657064Z) ← ENQUEUED (at 2024-04-29T03:45:17.132362704Z) ← FAILED (at 2024-04-28T04:16:07.969508935Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271483726Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270463720Z) ← ENQUEUED (at 2024-04-28T04:11:57.570191715Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786537688Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487657064Z) ← ENQUEUED (at 2024-04-29T03:45:17.132362704Z) ← FAILED (at 2024-04-28T04:16:07.969508935Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271483726Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270463720Z) ← ENQUEUED (at 2024-04-28T04:11:57.570191715Z) ← SCHEDULED (at 2024-04-28T04:11:43.771601463Z)

Job id: 018f22e6-d639-7c73-a7a7-090c06749582
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:07.185402686Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487658882Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487658882Z) ← ENQUEUED (at 2024-04-29T03:45:17.378861948Z) ← FAILED (at 2024-04-28T04:16:07.971622324Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271473507Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270464029Z) ← ENQUEUED (at 2024-04-28T04:11:57.570192441Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786540233Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487658882Z) ← ENQUEUED (at 2024-04-29T03:45:17.378861948Z) ← FAILED (at 2024-04-28T04:16:07.971622324Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271473507Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270464029Z) ← ENQUEUED (at 2024-04-28T04:11:57.570192441Z) ← SCHEDULED (at 2024-04-28T04:11:44.569056303Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.ProcessOrphanedJobsTask.runTask(ProcessOrphanedJobsTask.java:29)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 018f22e6-cbae-7918-8a71-bdd091835939, 018f22e5-a3f9-74df-aad4-5166c4e6e593, 018f22e6-d31b-70ba-8d94-671db8a80a1e, 018f22e6-d639-7c73-a7a7-090c06749582

## Concurrent modified jobs:
Job id: 018f22e6-cbae-7918-8a71-bdd091835939
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.386330919Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487649778Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487649778Z) ← ENQUEUED (at 2024-04-29T03:45:16.638374995Z) ← FAILED (at 2024-04-28T04:15:56.471340989Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271480423Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270462901Z) ← ENQUEUED (at 2024-04-28T04:11:57.570186864Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786544411Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487649778Z) ← ENQUEUED (at 2024-04-29T03:45:16.638374995Z) ← FAILED (at 2024-04-28T04:15:56.471340989Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271480423Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270462901Z) ← ENQUEUED (at 2024-04-28T04:11:57.570186864Z) ← SCHEDULED (at 2024-04-28T04:11:41.870469456Z)

Job id: 018f22e5-a3f9-74df-aad4-5166c4e6e593
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.387544996Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487654966Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487654966Z) ← ENQUEUED (at 2024-04-29T03:45:16.885197929Z) ← FAILED (at 2024-04-28T04:15:56.569754881Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271476821Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270461343Z) ← ENQUEUED (at 2024-04-28T04:10:38.468856310Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786541711Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487654966Z) ← ENQUEUED (at 2024-04-29T03:45:16.885197929Z) ← FAILED (at 2024-04-28T04:15:56.569754881Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271476821Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270461343Z) ← ENQUEUED (at 2024-04-28T04:10:38.468856310Z) ← SCHEDULED (at 2024-04-28T04:10:26.169494702Z)

Job id: 018f22e6-d31b-70ba-8d94-671db8a80a1e
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:06.387708044Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487657064Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487657064Z) ← ENQUEUED (at 2024-04-29T03:45:17.132362704Z) ← FAILED (at 2024-04-28T04:16:07.969508935Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271483726Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270463720Z) ← ENQUEUED (at 2024-04-28T04:11:57.570191715Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786537688Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487657064Z) ← ENQUEUED (at 2024-04-29T03:45:17.132362704Z) ← FAILED (at 2024-04-28T04:16:07.969508935Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271483726Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270463720Z) ← ENQUEUED (at 2024-04-28T04:11:57.570191715Z) ← SCHEDULED (at 2024-04-28T04:11:43.771601463Z)

Job id: 018f22e6-d639-7c73-a7a7-090c06749582
	Job Name: Process
	Job Signature: process.ProcessBOHandler.run(process.ProcessBOJob)
	Local version: 9; Storage version: 10
	Local state: FAILED (at 2024-04-29T03:47:07.185402686Z) ← PROCESSING (updated at 2024-04-29T03:45:44.487658882Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487658882Z) ← ENQUEUED (at 2024-04-29T03:45:17.378861948Z) ← FAILED (at 2024-04-28T04:16:07.971622324Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271473507Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270464029Z) ← ENQUEUED (at 2024-04-28T04:11:57.570192441Z)
	Storage state: PROCESSING (updated at 2024-04-29T03:46:57.786540233Z on BackgroundJobServer 1151328b-6dda-43be-a99b-03b9066f951c and started at 2024-04-29T03:45:44.487658882Z) ← ENQUEUED (at 2024-04-29T03:45:17.378861948Z) ← FAILED (at 2024-04-28T04:16:07.971622324Z) ← PROCESSING (updated at 2024-04-28T04:15:45.271473507Z on BackgroundJobServer eb1d8305-78f9-4dcd-8d55-7a9e1f3f20dc and started at 2024-04-28T04:15:02.270464029Z) ← ENQUEUED (at 2024-04-28T04:11:57.570192441Z) ← SCHEDULED (at 2024-04-28T04:11:44.569056303Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 018f22e6-cbae-7918-8a71-bdd091835939, 018f22e5-a3f9-74df-aad4-5166c4e6e593, 018f22e6-d31b-70ba-8d94-671db8a80a1e, 018f22e6-d639-7c73-a7a7-090c06749582
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 0, 0, 0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 17 more

```

**Comment by rdehuyss** [comment]
Are you manually calling `StorageProvider.save(job)` somewhere in your code?

**Comment by itizarsa** [comment]
No

**Comment by itizarsa** [comment]
### JobRunr Configuration

```
@Bean
public JobScheduler jobScheduler(
		JobActivator activator,
		@Qualifier("jobrunrDataSource") DataSource dataSource,
		SchedulerFilter filter,
		@Value("${jobrunr.dashboard}") boolean dashboard,
		@Value("${jobrunr.background}") boolean background) {
StorageProvider sp = SqlStorageProviderFactory.using(dataSource);

return JobRunr.configure()
			.useJobActivator(activator)
			.useStorageProvider(sp)
			.withJobFilter(filter)
			.useBackgroundJobServerIf(background, Runtime.getRuntime().availableProcessors())
			.useDashboardIf(dashboard)
			.initialize()
			.getJobScheduler();
}

@Bean
public JobActivator jobActivator(ApplicationContext applicationContext) {
	return applicationContext::getBean;
}
```

Framework - Spring Boot

### Create Job

```
	public String create(String name, JobRequest jr, Duration duration, int retry) {
		JobBuilder job = JobBuilder.aJob()
				.withName(name)
				.scheduleIn(duration)
				.withJobRequest(jr)
				.withAmountOfRetries(retry);

		JobId id = BackgroundJobRequest.create(job);

		return id.toString();
	}
```

### Logging & Progress

```
this.jobContext().logger().info("Batches---> " + batches);

JobDashboardProgressBar progressBar = this.jobContext().progressBar(batches);

progressBar.increaseByOne();
```

**Comment by notnaveedkhan** [comment]
Version:
```
org.jobrunr:jobrunr-spring-boot-3-starter:7.4.0
```

Stacktrace:
```
ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
```

Logs
```
2025-09-10 09:15:10.412 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:42, Time:2, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["delete from jobrunr_backgroundjobservers where id = ?"]
Params:[(b79e50bd-968a-4735-bba7-8ceec0a86363)]
2025-09-10 09:15:10.412 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:43, Time:2, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["delete from jobrunr_backgroundjobservers where id = ?"]
Params:[(b79e50bd-968a-4735-bba7-8ceec0a86363)]
2025-09-10 09:15:10.416 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:42, Time:1, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["insert into jobrunr_backgroundjobservers(id, name, workerPoolSize, pollIntervalInSeconds, firstHeartbeat, lastHeartbeat, running, systemTotalMemory, systemFreeMemory, systemCpuLoad, processMaxMemory, processFreeMemory, processAllocatedMemory, processCpuLoad, deleteSucceededJobsAfter, permanentlyDeleteJobsAfter) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"]
Params:[(b79e50bd-968a-4735-bba7-8ceec0a86363,spetro603538,32,15,2025-09-10 09:15:04.381535221,2025-09-10 09:15:10.405264714,1,10165825536,6252982272,0.04801920768307323,4294967296,3879365632,415601664,0.01405944118170493,PT36H,PT72H)]
2025-09-10 09:15:10.426 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:44, Time:2, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select id from jobrunr_backgroundjobservers ORDER BY firstHeartbeat ASC OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY"]
Params:[(1)]
2025-09-10 09:15:10.427 INFO  o.j.s.BackgroundJobServer [No authenticated user] - JobRunr BackgroundJobServer (b79e50bd-968a-4735-bba7-8ceec0a86363) using SQLServerStorageProvider and 32 BackgroundJobPerformers started successfully
2025-09-10 09:15:10.427 INFO  o.j.s.ServerZooKeeper [No authenticated user] - Server ecb0d15a-ca10-486f-806b-19c6c81900cb is master (another BackgroundJobServer)
2025-09-10 09:15:16.451 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:43, Time:34, Success:False
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["insert into jobrunr_backgroundjobservers(id, name, workerPoolSize, pollIntervalInSeconds, firstHeartbeat, lastHeartbeat, running, systemTotalMemory, systemFreeMemory, systemCpuLoad, processMaxMemory, processFreeMemory, processAllocatedMemory, processCpuLoad, deleteSucceededJobsAfter, permanentlyDeleteJobsAfter) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"]
Params:[(b79e50bd-968a-4735-bba7-8ceec0a86363,spetro603538,32,15,2025-09-10 09:15:04.381535221,2025-09-10 09:15:10.405406615,1,10165825536,6252982272,0.0,4294967296,3879128440,415838856,0.0,PT36H,PT72H)]
2025-09-10 09:15:20.409 WARN  c.z.h.p.ProxyLeakTask [No authenticated user] - Connection leak detection triggered for ConnectionID:1 ClientConnectionId: 867dfc5b-2c31-4b7e-9a20-200609dd914a on thread backgroundjob-zookeeper-pool-13-thread-1, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:127)
	at net.ttddyy.dsproxy.support.ProxyDataSource.getConnection(ProxyDataSource.java:72)
	at org.springframework.jdbc.datasource.DelegatingDataSource.getConnection(DelegatingDataSource.java:101)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.announceBackgroundJobServer(DefaultSqlStorageProvider.java:87)
	at org.jobrunr.storage.ThreadSafeStorageProvider.announceBackgroundJobServer(ThreadSafeStorageProvider.java:57)
	at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:75)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-10 09:15:22.455 INFO  c.z.h.p.ProxyLeakTask [No authenticated user] - Previously reported leaked connection ConnectionID:1 ClientConnectionId: 867dfc5b-2c31-4b7e-9a20-200609dd914a on thread backgroundjob-zookeeper-pool-13-thread-1 was returned to the pool (unleaked)
2025-09-10 09:15:25.412 DEBUG n.t.d.l.l.SLF4JQueryLoggingListener [No authenticated user] - 
Name:dataSource, Connection:45, Time:3, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select jobAsJson from jobrunr_jobs with(UPDLOCK, ROWLOCK, READPAST) where state = ? ORDER BY updatedAt ASC OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY"]
Params:[(ENQUEUED,32)]
2025-09-10 09:15:28.460 ERROR o.j.s.ServerZooKeeper [No authenticated user] - An unrecoverable error occurred. Shutting server down...
org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:17)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:163)
	at org.jobrunr.storage.sql.common.db.Sql.insert(Sql.java:129)
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.announce(BackgroundJobServerTable.java:55)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.announceBackgroundJobServer(DefaultSqlStorageProvider.java:88)
	at org.jobrunr.storage.ThreadSafeStorageProvider.announceBackgroundJobServer(ThreadSafeStorageProvider.java:57)
	at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:75)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-09-10 09:15:34.498 INFO  o.j.s.BackgroundJobServer [No authenticated user] - BackgroundJobServer - stopping (may take about PT10S)
2025-09-10 09:15:40.500 INFO  o.j.s.BackgroundJobServer [No authenticated user] - BackgroundJobPerformers - stopping (waiting at most PT10S for jobs to finish)
```
