### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by frko** [jobrunr/jobrunr#1028]
### JobRunr Version

6.1.1

### JDK Version

17.0.4-zulu

### Your SQL / NoSQL database

Redis  6.0.19

### What happened?

Using jobrunr-spring-boot-3-starter  in a spring-boot 3 maven project on a openjdk 17 zulu build   

```
<dependency>
      <groupId>org.jobrunr</groupId>
      <artifactId>jobrunr-spring-boot-3-starter</artifactId>
      <version>6.1.1</version>
  </dependency>
```

Configuring a storage provider bean as follows

<img width="825" alt="image" src="https://github.com/jobrunr/jobrunr/assets/1576993/eae9199b-ac9e-4952-b20d-6c160eff14a3">

Throws an exception where jobrunner internal code invoked a protected method on other internal jobrunner code

### How to reproduce?

Using an annotated method as follows with a redis storage backend called from the ui using a trigger

<img width="910" alt="image" src="https://github.com/jobrunr/jobrunr/assets/1576993/2bce734f-71f9-483a-9332-f3d29712ae14">

<img width="487" alt="image" src="https://github.com/jobrunr/jobrunr/assets/1576993/c8bbda4a-8957-4056-8247-d23684cc4fb5">

### Relevant log output

```shell
Exception in thread "pool-16-thread-9" java.lang.IllegalAccessError: class org.jobrunr.jobs.states.ProcessingState$Creator4JacksonDeserializer319f2c36 tried to access protected method 'void org.jobrunr.jobs.states.ProcessingState.<init>()' │
│     at org.jobrunr.jobs.states.ProcessingState$Creator4JacksonDeserializer319f2c36.createUsingDefault(org/jobrunr/jobs/states/ProcessingState$Creator4JacksonDeserializer.java)                                                                 │
│     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:303)                                                                                                                                      │
│     at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)                                                                                                                                       │
│     at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)                                                                                                               │
│     at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:144)                                                                                                      │
│     at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:110)                                                                                                  │
│     at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:263)                                                                                                                             │
│     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)                                                                                                                   │
│     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)                                                                                                                             │
│     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)                                                                                                                              │
│     at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)                                                                                                                                        │
│     at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:159)                                                                                                               │
│     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)                                                                                                                 │
│     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)                                                                                                                                                     │
│     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)                                                                                                                                                            │
│     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)                                                                                                                                                            │
│     at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:80)                                                                                                                                                │
│     at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)                                                                                                                                                                     │
│     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)                                                                                                                                                      │
│     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)                                                                                                                                                      │
│     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)                                                                                                                                                 │
│     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)                                                                                                                                                          │
│     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)                                                                                                                                                   │
│     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                                                                                                     │
│     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                                                                                                          │
│     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)                                                                                                                                                         │
│     at org.jobrunr.storage.nosql.redis.LettuceRedisStorageProvider.getJobs(LettuceRedisStorageProvider.java:401)                                                                                                                                │
│     at org.jobrunr.storage.nosql.redis.LettuceRedisStorageProvider.getJobPage(LettuceRedisStorageProvider.java:411)                                                                                                                             │
│     at org.jobrunr.storage.ThreadSafeStorageProvider.getJobPage(ThreadSafeStorageProvider.java:143)                                                                                                                                             │
│     at org.jobrunr.dashboard.JobRunrApiHandler.lambda$findJobByState$4(JobRunrApiHandler.java:75)                                                                                                                                               │
│     at org.jobrunr.dashboard.server.http.RestHttpHandler.processRequest(RestHttpHandler.java:76)                                                                                                                                                │
│     at org.jobrunr.dashboard.server.http.RestHttpHandler.lambda$handle$0(RestHttpHandler.java:68)                                                                                                                                               │
│     at java.base/java.util.Optional.ifPresent(Optional.java:178)                                                                                                                                                                                │
│     at org.jobrunr.dashboard.server.http.RestHttpHandler.handle(RestHttpHandler.java:68)                                                                                                                                                        │
│     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)                                                                                                                                                              │
│     at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)                                                                                                                                                                │
│     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)                                                                                                                                                              │
│     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)                                                                                                                                            │
│     at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)                                                                                                                                                              │
│     at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)                                                                                                                                                           │
│     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                                                                                                │
│     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                                                                                                │
│     at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by rdehuyss** [comment]
Hi @frko - 2 things:
- you did not follow community guidelines (you know, the page with text when you create a bug)
- we did not provide support on older versions of JobRunr

**Comment by frko** [comment]
Ok, I indeed used an old version, unlucky enough this happens with the latest version as well.
I will comply as much as possible to the desired ticket standard creation process later today.
Coul you please re-open?

**Comment by rdehuyss** [comment]
Hi @frko - I think the reason you're getting this exception is because you are using [Jackson Afterburner](https://github.com/FasterXML/jackson-module-afterburner) which is deprecated since 2019.

If you can setup a repo that reproduces the issue (and update your profile 😉) that does not use Jackson Afterburner, we're happy to take a look!

**Comment by rdehuyss** [comment]
Scratch that last comment - [the module was moved apparently](https://github.com/FasterXML/jackson-modules-base/blob/2.17/afterburner). 

What I can say is that this is probably caused by afterburner. Can you setup a repo that reproduces it?
