### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by uben01** [jobrunr/jobrunr#1041]
### Runtime information
- __Timestamp__: 2024-05-12T04:53:05.996968180Z
- __Location__: BackgroundJobServer 7317ac83-0450-4931-8a61-e3784771cdd1
- __JobRunr Version__: 7.1.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.11
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 7317ac83-0450-4931-8a61-e3784771cdd1
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-10T16:40:29.430689Z, lastHeartbeat: 2024-05-12T04:52:55.910807Z)
- BackgroundJobServer id: 88e045d5-4b12-43fa-95be-ab9fa8f44d77
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-10T16:43:30.415270Z, lastHeartbeat: 2024-05-12T04:52:58.005021Z)

#### Concurrent modified jobs:
Job id: 018f636b-5920-7551-ad7e-52c3eb2b3969
	Job Name: Contact assigner - correlationId: cd948498-e273-454e-b503-c4757ad2e329, slot: -1
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-12T04:53:05.982266331Z
	Local version: 6; Storage version: 7
	Local state: DELETED (at 2024-05-12T04:53:05.770121866Z) ← SUCCEEDED (at 2024-05-10T16:52:54.186817287Z) ← PROCESSING (updated at 2024-05-10T16:52:53.084381667Z on BackgroundJobServer 88e045d5-4b12-43fa-95be-ab9fa8f44d77 and started at 2024-05-10T16:52:53.084381667Z) ← ENQUEUED (at 2024-05-10T16:52:52.332151902Z) ← AWAITING (at 2024-05-10T16:52:10.656029042Z)
	Storage state: AWAITING (at 2024-05-12T04:53:05.813346608Z) ← SUCCEEDED (at 2024-05-10T16:52:54.186817287Z) ← PROCESSING (updated at 2024-05-10T16:52:53.084381667Z on BackgroundJobServer 88e045d5-4b12-43fa-95be-ab9fa8f44d77 and started at 2024-05-10T16:52:53.084381667Z) ← ENQUEUED (at 2024-05-10T16:52:52.332151902Z) ← AWAITING (at 2024-05-10T16:52:10.656029042Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:27)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 018f636b-5920-7551-ad7e-52c3eb2b3969

## Concurrent modified jobs:
Job id: 018f636b-5920-7551-ad7e-52c3eb2b3969
	Job Name: Contact assigner - correlationId: cd948498-e273-454e-b503-c4757ad2e329, slot: -1
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-12T04:53:05.982266331Z
	Local version: 6; Storage version: 7
	Local state: DELETED (at 2024-05-12T04:53:05.770121866Z) ← SUCCEEDED (at 2024-05-10T16:52:54.186817287Z) ← PROCESSING (updated at 2024-05-10T16:52:53.084381667Z on BackgroundJobServer 88e045d5-4b12-43fa-95be-ab9fa8f44d77 and started at 2024-05-10T16:52:53.084381667Z) ← ENQUEUED (at 2024-05-10T16:52:52.332151902Z) ← AWAITING (at 2024-05-10T16:52:10.656029042Z)
	Storage state: AWAITING (at 2024-05-12T04:53:05.813346608Z) ← SUCCEEDED (at 2024-05-10T16:52:54.186817287Z) ← PROCESSING (updated at 2024-05-10T16:52:53.084381667Z on BackgroundJobServer 88e045d5-4b12-43fa-95be-ab9fa8f44d77 and started at 2024-05-10T16:52:53.084381667Z) ← ENQUEUED (at 2024-05-10T16:52:52.332151902Z) ← AWAITING (at 2024-05-10T16:52:10.656029042Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 018f636b-5920-7551-ad7e-52c3eb2b3969
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:344)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 17 more

```

**Comment by rdehuyss** [comment]
Hi @uben01 , can I know what happened here? Did you requeue a batch job by any chance?
