### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by bucsi** [jobrunr/jobrunr#1047]
Note1: We're seeing a concurrent job modification like this every couple of days. If you need more data, we can look for the other logs as well :) 

Note2: This job runs as one of many batch jobs. We create them with these functions:
```java
public void enqueueLaunchProcessingJobBatch(Campaign campaign) {
        var launchSlots = launchSlotRepository.getLaunchSlotsByCampaignAndStatus(campaign, LaunchSlotStatus.PENDING);
        var launchSlotArray = launchSlots
            .stream()
            .map(LaunchSlot::getLaunchSlot)
            .toArray(Integer[]::new);

        jobScheduler.startBatch(() -> enqueueLaunchProcessingJobs(campaign.getCorrelationId(), launchSlotArray))
                    .<ScheduleFinalizerJob>continueWith((job) -> job.execute(campaign.getCorrelationId()));
    }

public void enqueueLaunchProcessingJobs(UUID correlationId, Integer[] launchSlots) {
    for (var launchSlot : launchSlots) {
        jobScheduler
            .<LaunchCreatorJob>enqueue((job) -> job.execute(correlationId, launchSlot))
            .<ContactAssignerJob>continueWith((job) -> job.execute(correlationId, launchSlot))
            .<ReschedulerJob>continueWith((job) -> job.execute(correlationId, launchSlot));
    }
}
```

### Runtime information
- __Timestamp__: 2024-05-25T05:50:53.604251415Z
- __Location__: BackgroundJobServer 744eafc7-d2ac-486a-aa05-ca0258148992
- __JobRunr Version__: 7.1.2
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.11
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 744eafc7-d2ac-486a-aa05-ca0258148992
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-21T07:25:48.611111Z, lastHeartbeat: 2024-05-25T05:50:46.251594Z)
- BackgroundJobServer id: ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-21T07:25:53.352377Z, lastHeartbeat: 2024-05-25T05:50:41.993036Z)

#### Concurrent modified jobs:
Job id: 018fa693-141f-79e0-831a-637323f1a73d
	Job Name: Contact assigner - correlationId: 362f4cb1-f676-4674-bb73-c6cc7efcfa67, slot: 18
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-25T05:50:53.604182746Z
	Local version: 6; Storage version: 7
	Local state: DELETED (at 2024-05-25T05:50:53.458840872Z) ← SUCCEEDED (at 2024-05-23T17:50:46.297231533Z) ← PROCESSING (updated at 2024-05-23T17:50:42.445989480Z on BackgroundJobServer ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e and started at 2024-05-23T17:50:42.445989480Z) ← ENQUEUED (at 2024-05-23T17:50:42.280916192Z) ← AWAITING (at 2024-05-23T17:50:07.903795252Z)
	Storage state: AWAITING (at 2024-05-25T05:50:53.496593269Z) ← SUCCEEDED (at 2024-05-23T17:50:46.297231533Z) ← PROCESSING (updated at 2024-05-23T17:50:42.445989480Z on BackgroundJobServer ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e and started at 2024-05-23T17:50:42.445989480Z) ← ENQUEUED (at 2024-05-23T17:50:42.280916192Z) ← AWAITING (at 2024-05-23T17:50:07.903795252Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:28)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 018fa693-141f-79e0-831a-637323f1a73d

## Concurrent modified jobs:
Job id: 018fa693-141f-79e0-831a-637323f1a73d
	Job Name: Contact assigner - correlationId: 362f4cb1-f676-4674-bb73-c6cc7efcfa67, slot: 18
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-25T05:50:53.604182746Z
	Local version: 6; Storage version: 7
	Local state: DELETED (at 2024-05-25T05:50:53.458840872Z) ← SUCCEEDED (at 2024-05-23T17:50:46.297231533Z) ← PROCESSING (updated at 2024-05-23T17:50:42.445989480Z on BackgroundJobServer ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e and started at 2024-05-23T17:50:42.445989480Z) ← ENQUEUED (at 2024-05-23T17:50:42.280916192Z) ← AWAITING (at 2024-05-23T17:50:07.903795252Z)
	Storage state: AWAITING (at 2024-05-25T05:50:53.496593269Z) ← SUCCEEDED (at 2024-05-23T17:50:46.297231533Z) ← PROCESSING (updated at 2024-05-23T17:50:42.445989480Z on BackgroundJobServer ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e and started at 2024-05-23T17:50:42.445989480Z) ← ENQUEUED (at 2024-05-23T17:50:42.280916192Z) ← AWAITING (at 2024-05-23T17:50:07.903795252Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 018fa693-141f-79e0-831a-637323f1a73d
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:345)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 17 more

```

### Runtime information
- __Timestamp__: 2024-05-26T18:30:25.245647299Z
- __Location__: BackgroundJobServer ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e
- __JobRunr Version__: 7.1.2
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.11
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: ddab6045-b257-4e03-9a0e-2f4b5f7d7c8e
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-21T07:25:53.352377Z, lastHeartbeat: 2024-05-26T18:30:24.645485Z)
- BackgroundJobServer id: 823c5cee-af58-49ad-97d0-703930baf4be
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-25T18:26:15.868183Z, lastHeartbeat: 2024-05-26T18:30:12.816126Z)

#### Concurrent modified jobs:
Job id: 018fae70-8eb5-7fa2-a4a3-b0727d0fbe85
	Job Name: Contact assigner - correlationId: 66c05eec-32a1-4453-b4ac-6c128e69cae2, slot: 14
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-26T18:30:25.245586719Z
	Local version: 8; Storage version: 9
	Local state: DELETED (at 2024-05-26T18:30:25.151205351Z) ← SUCCEEDED (at 2024-05-25T06:30:22.897740187Z) ← PROCESSING (updated at 2024-05-25T06:30:21.632966069Z on BackgroundJobServer 744eafc7-d2ac-486a-aa05-ca0258148992 and started at 2024-05-25T06:30:21.632966069Z) ← ENQUEUED (at 2024-05-25T06:30:17.975771935Z) ← AWAITING (at 2024-05-25T06:29:23.253490718Z)
	Storage state: AWAITING (at 2024-05-26T18:30:25.208630642Z) ← SUCCEEDED (at 2024-05-25T06:30:22.897740187Z) ← PROCESSING (updated at 2024-05-25T06:30:21.632966069Z on BackgroundJobServer 744eafc7-d2ac-486a-aa05-ca0258148992 and started at 2024-05-25T06:30:21.632966069Z) ← ENQUEUED (at 2024-05-25T06:30:17.975771935Z) ← AWAITING (at 2024-05-25T06:29:23.253490718Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:28)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 018fae70-8eb5-7fa2-a4a3-b0727d0fbe85

## Concurrent modified jobs:
Job id: 018fae70-8eb5-7fa2-a4a3-b0727d0fbe85
	Job Name: Contact assigner - correlationId: 66c05eec-32a1-4453-b4ac-6c128e69cae2, slot: 14
	Job Signature: com.emarsys.estm.service.contactassignment.ContactAssignerJob.execute(java.util.UUID, java.lang.Integer)
	Occurred at: 2024-05-26T18:30:25.245586719Z
	Local version: 8; Storage version: 9
	Local state: DELETED (at 2024-05-26T18:30:25.151205351Z) ← SUCCEEDED (at 2024-05-25T06:30:22.897740187Z) ← PROCESSING (updated at 2024-05-25T06:30:21.632966069Z on BackgroundJobServer 744eafc7-d2ac-486a-aa05-ca0258148992 and started at 2024-05-25T06:30:21.632966069Z) ← ENQUEUED (at 2024-05-25T06:30:17.975771935Z) ← AWAITING (at 2024-05-25T06:29:23.253490718Z)
	Storage state: AWAITING (at 2024-05-26T18:30:25.208630642Z) ← SUCCEEDED (at 2024-05-25T06:30:22.897740187Z) ← PROCESSING (updated at 2024-05-25T06:30:21.632966069Z on BackgroundJobServer 744eafc7-d2ac-486a-aa05-ca0258148992 and started at 2024-05-25T06:30:21.632966069Z) ← ENQUEUED (at 2024-05-25T06:30:17.975771935Z) ← AWAITING (at 2024-05-25T06:29:23.253490718Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:64)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 018fae70-8eb5-7fa2-a4a3-b0727d0fbe85
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:216)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:309)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:190)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:165)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:345)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:205)
	... 17 more

```

**Comment by auloin** [comment]
@bucsi were the parent jobs of `018fae70-8eb5-7fa2-a4a3-b0727d0fbe85` or `018fa693-141f-79e0-831a-637323f1a73d` ever requeued?

**Comment by bucsi** [comment]
@auloin I checked on the dashboard, they were not requeued.

**Comment by auloin** [comment]
The only case where a `SUCCEEDED` job would automatically move to `AWAITING` is when the parent was `ENQUEUED` at least two times... Is it possible to share the tree (Batch -> LaunchCreatorJob -> ContactAssignerJob -> ReschedulerJob)  of one of those jobs (`018fae70-8eb5-7fa2-a4a3-b0727d0fbe85` or `018fa693-141f-79e0-831a-637323f1a73d`)? You can send the `jobAsJson`s by email.

**Comment by rdehuyss** [comment]
I agree this is a bug on our side by comparing the info from this issue and the previous one @uben01 created.

We think we have a solution for this (thanks to @auloin 🤩). 

If the next release of JobRunr Pro does not solve it however, we would like to create a special JobRunr Pro SNAPSHOT version for you with extra logging to find the root cause. Otherwise I'm afraid we will not be able to solve this.
