### ISSUE TITLE
[BUG] ConcurrentModificationException

### ISSUE THREAD

**Issue by wjw465150** [jobrunr/jobrunr#1052]
### JobRunr Version

7.2.0

### JDK Version

openjdk version "17.0.11"

### Your SQL / NoSQL database

no use DB

### What happened?

```
2024-06-06 11:00:27,373 WARN  vm-10-9-centos ws-cooperation-job-1.0-test-runner.jar[18929] org.jobrunr.server.JobHandler.run(JobHandler.java:48) (backgroundjob-zookeeper-pool-5-thread-5) JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.CopyOnWriteArrayList$COWSubList.getArrayChecked(CopyOnWriteArrayList.java:1207)
	at java.base/java.util.concurrent.CopyOnWriteArrayList$COWSubList.toArray(CopyOnWriteArrayList.java:1228)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
	at org.jobrunr.jobs.Job.getStateChangesForJobFilters(Job.java:163)
	at org.jobrunr.jobs.filters.JobPerformingFilters.runOnStateAppliedFilters(JobPerformingFilters.java:29)
	at org.jobrunr.jobs.filters.JobFilterUtils.runOnStateAppliedFilters(JobFilterUtils.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.jobrunr.jobs.filters.JobFilterUtils.runOnStateAppliedFilters(JobFilterUtils.java:45)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:64)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

**Comment by rdehuyss** [comment]
Can you please add the database you're using? JobRunr cannot work without a DB.

**Comment by wjw465150** [comment]
I'm not using a database,I use the default InMemoryStorageProvider.

**Comment by kabutz** [comment]
`import java.util.*;
import java.util.concurrent.*;

public class COWConcurrentSubListDemo {
    public static void main(String... args) {
        var list = new CopyOnWriteArrayList<>(List.of("hello", "world", "!"));

        Thread.ofPlatform().start(() -> {
            while (true) {
                list.add("a");
                list.remove("a");
            }
        });

        while(true) {
            new ArrayList<>(list).subList(0, 2); // works
            // new ArrayList<>(list.subList(0, 2)); // causes ConcurrentModificationException
        }
    }
}
`
