### ISSUE TITLE
Unable to start jobrunr

### ISSUE THREAD

**Issue by surajit16** [jobrunr/jobrunr#106]
`ERROR org.jobrunr.server.ServerZooKeeper.run 45 - An unrecoverable error occurred. Shutting server down...
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:110)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:110)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:92)
	at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:63)
	at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:98)
	at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:66)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:40)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No servers available?!
	... 16 common frames omitted
`

**Comment by rdehuyss** [comment]
Can you please show me how you instantiate JobRunr and which StorageProvider you use?

**Comment by surajit16** [comment]
> Can you please show me how you instantiate JobRunr and which StorageProvider you use?

I am using spring starter. And using the default stodarge i.e. spring.datasource which is mysql.

`org.jobrunr.job-scheduler.enabled=true
org.jobrunr.dashboard.enabled=true`

This error I am getting randomly, I can see server was not started and ZooKeeper is trying to make server as master...

**Comment by rdehuyss** [comment]
Thanks for the swift feedback.
- Do you set the value `org.jobrunr.background-job-server.poll_interval`?
- I assume it is while JobRunr is starting?
- Do you have multiple `BackgroundJobServer`s running?

**Comment by surajit16** [comment]
Thanks @rdehuyss  for support.

Below is my answers

- org.jobrunr.background-job-server.poll_interval is default one 
- Yes.
- No. I am trying to start single server

**Comment by rdehuyss** [comment]
Hmmm, I really can't understand how this is happening:

In the method: [announceBackgroundJobServer](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java#L64-L67) 2 things happen:
- it announces the current BackgroundJobServer (= which is inserting a row in the `jobrunr_backgroundjobservers` table)
- it then queries this table to see which entry is the oldest. In your case, for some reason, it does not find the row it just created.

Can you see a row in the `jobrunr_backgroundjobservers` table?
Are you open for a teams / google hangout session to see what is going on? I'm curious as I really don't understand what is going on...

**Comment by surajit16** [comment]
Well I checked the table, it doesn't have any Job servers running. 

But, dashboard UI was up an running.

**Comment by rdehuyss** [comment]
Indeed, you can run the dashboard UI without having any `BackgroundJobServer` running.

I don't understand why the insert is not working for you - there should be at least one row in the `jobrunr_backgroundjobservers` the moment you enable a `BackgroundJobServer`.

Can you setup a Github repo that reproduces the problem?

**Comment by tan9** [comment]
@surajit16 is your `dataSource.autoCommit` set to `false`?  We suffer from the same issue starting JobRunr.
