### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by ilkou** [jobrunr/jobrunr#1063]
### Runtime information
- __Timestamp__: 2024-05-02T21:34:25.665165Z
- __Location__: BackgroundJobServer 59df0dd6-100c-46c2-bd4d-913928b15c2a
- __JobRunr Version__: 6.2.3
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.9
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 2ae4a143-acba-48ab-a8cb-c637c3399f25
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-02T09:02:26.742861Z, lastHeartbeat: 2024-05-02T21:34:18.335303Z)
- BackgroundJobServer id: 59df0dd6-100c-46c2-bd4d-913928b15c2a
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-02T21:32:16.334539Z, lastHeartbeat: 2024-05-02T21:34:23.967118Z)

#### Concurrent modified jobs:
Job id: 9fe9ecb2-2140-4c34-acc7-bbb1b46c0d99
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-05-02T21:34:23.967433Z on BackgroundJobServer 59df0dd6-100c-46c2-bd4d-913928b15c2a and started at 2024-05-02T21:33:12.222033Z) ← ENQUEUED (at 2024-05-02T21:33:07.138824449Z)
	Storage state: SCHEDULED (at 2024-05-02T21:34:20.224627730Z) ← FAILED (at 2024-05-02T21:34:20.220431419Z) ← PROCESSING (updated at 2024-05-02T21:33:12.222033Z on BackgroundJobServer 59df0dd6-100c-46c2-bd4d-913928b15c2a and started at 2024-05-02T21:33:12.222033Z) ← ENQUEUED (at 2024-05-02T21:33:07.138824449Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 9fe9ecb2-2140-4c34-acc7-bbb1b46c0d99
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:52)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:74)
	... 11 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 9fe9ecb2-2140-4c34-acc7-bbb1b46c0d99
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:70)
	... 11 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 14 more

```

### Runtime information
- __Timestamp__: 2024-05-03T13:21:26.395833Z
- __Location__: BackgroundJobServer 415a6992-85a0-4931-bab2-feb7d5b4e316
- __JobRunr Version__: 6.2.3
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.9
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: f343dad9-f70b-4a2d-921a-0d0570ae6469
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-03T13:18:06.470342Z, lastHeartbeat: 2024-05-03T13:21:21.659253Z)

#### Concurrent modified jobs:
Job id: 6b60cbac-9f37-4302-a054-2e87289a4f5f
	Local version: 12; Storage version: 13
	Local state: SCHEDULED (at 2024-05-03T13:21:25.883982Z) ← FAILED (at 2024-05-03T13:21:25.881273Z) ← PROCESSING (updated at 2024-05-03T13:19:56.891624Z on BackgroundJobServer 415a6992-85a0-4931-bab2-feb7d5b4e316 and started at 2024-05-03T13:18:19.720110Z) ← ENQUEUED (at 2024-05-03T13:18:18.331195Z) ← SCHEDULED (at 2024-05-03T13:18:02.062278Z) ← FAILED (at 2024-05-03T13:18:02.056065Z)
	Storage state: FAILED (at 2024-05-03T13:21:07.580449528Z) ← PROCESSING (updated at 2024-05-03T13:19:40.712729Z on BackgroundJobServer 415a6992-85a0-4931-bab2-feb7d5b4e316 and started at 2024-05-03T13:18:19.720110Z) ← ENQUEUED (at 2024-05-03T13:18:18.331195Z) ← SCHEDULED (at 2024-05-03T13:18:02.062278Z) ← FAILED (at 2024-05-03T13:18:02.056065Z) ← PROCESSING (updated at 2024-05-03T13:17:00.625360Z on BackgroundJobServer d24091d4-f6ee-40a4-89af-c6ba99c35ad7 and started at 2024-05-03T13:16:27.875343Z)
Job id: f5fafede-e4c6-4a90-8af8-b6a8c0b87d35
	Local version: 20; Storage version: 21
	Local state: SCHEDULED (at 2024-05-03T13:21:25.884041Z) ← FAILED (at 2024-05-03T13:21:25.881101Z) ← PROCESSING (updated at 2024-05-03T13:19:56.891661Z on BackgroundJobServer 415a6992-85a0-4931-bab2-feb7d5b4e316 and started at 2024-05-03T13:18:19.720110Z) ← ENQUEUED (at 2024-05-03T13:18:18.331136Z) ← SCHEDULED (at 2024-05-03T13:18:02.062136Z) ← FAILED (at 2024-05-03T13:18:02.054791Z)
	Storage state: FAILED (at 2024-05-03T13:21:07.581570581Z) ← PROCESSING (updated at 2024-05-03T13:19:40.712761Z on BackgroundJobServer 415a6992-85a0-4931-bab2-feb7d5b4e316 and started at 2024-05-03T13:18:19.720110Z) ← ENQUEUED (at 2024-05-03T13:18:18.331136Z) ← SCHEDULED (at 2024-05-03T13:18:02.062136Z) ← FAILED (at 2024-05-03T13:18:02.054791Z) ← PROCESSING (updated at 2024-05-03T13:17:00.625331Z on BackgroundJobServer d24091d4-f6ee-40a4-89af-c6ba99c35ad7 and started at 2024-05-03T13:14:12.857538Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 6b60cbac-9f37-4302-a054-2e87289a4f5f, f5fafede-e4c6-4a90-8af8-b6a8c0b87d35
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:52)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:74)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 6b60cbac-9f37-4302-a054-2e87289a4f5f, f5fafede-e4c6-4a90-8af8-b6a8c0b87d35
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:70)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 13 more

```

### Runtime information
- __Timestamp__: 2024-05-21T21:27:34.238561Z
- __Location__: BackgroundJobServer ec7f7ff4-027b-4ce4-a2a0-e2c1520303fe
- __JobRunr Version__: 6.2.3
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.9
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: a2be1115-4cef-4428-aaf6-9984c0682a4a
(workerPoolSize: 24, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-21T20:36:53.409760Z, lastHeartbeat: 2024-05-21T21:27:24.828907Z)
- BackgroundJobServer id: ec7f7ff4-027b-4ce4-a2a0-e2c1520303fe
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2024-05-21T21:25:30.264942Z, lastHeartbeat: 2024-05-21T21:27:33.035696Z)

#### Concurrent modified jobs:
Job id: 1529ca1c-9f15-45cd-a95f-8245688d0deb
	Local version: 2; Storage version: 3
	Local state: DELETED (at 2024-05-21T21:26:01.793110Z) ← PROCESSING (updated at 2024-05-21T21:26:01.565563Z on BackgroundJobServer ec7f7ff4-027b-4ce4-a2a0-e2c1520303fe and started at 2024-05-21T21:25:46.565916Z) ← ENQUEUED (at 2024-05-21T21:25:41.932275Z)
	Storage state: DELETED (at 2024-05-21T21:25:57.943557Z) ← PROCESSING (updated at 2024-05-21T21:25:46.565916Z on BackgroundJobServer ec7f7ff4-027b-4ce4-a2a0-e2c1520303fe and started at 2024-05-21T21:25:46.565916Z) ← ENQUEUED (at 2024-05-21T21:25:41.932275Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 1529ca1c-9f15-45cd-a95f-8245688d0deb
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:52)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:74)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 1529ca1c-9f15-45cd-a95f-8245688d0deb
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:70)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 13 more

```

**Comment by rdehuyss** [comment]
You are having CpuAllocation (e.g. running on shared hosting, ... ) problems resulting in this problem. 

This is out of our hands I'm afraid.
