### ISSUE TITLE
[BUG] JobScheduler is not able to create recurrent jobs using a JobRequest

### ISSUE THREAD

**Issue by lvdkleij** [jobrunr/jobrunr#1064]
### JobRunr Version

7.2.0

### JDK Version

17.0.2

### Your SQL / NoSQL database

H2

### What happened?

`JobScheduler.class` only allows creation of recurrent jobs via JobLambda
```java
    public String createRecurrently(RecurringJobBuilder recurringJobBuilder) {
        RecurringJob recurringJob = recurringJobBuilder.build(this.jobDetailsGenerator);
        return this.scheduleRecurrently(recurringJob);
    }
```
even though `RecurringJobBuilder.class` provides builders for both JobLambda and JobRequest

```java
    protected RecurringJob build(JobDetailsGenerator jobDetailsGenerator) {
        if (this.jobRunrJob == null) {
            throw new IllegalArgumentException("JobLambda must be present.");
        } else {
            JobDetails jobDetails = jobDetailsGenerator.toJobDetails(this.jobRunrJob);
            return this.build(jobDetails);
        }
    }

    protected RecurringJob build() {
        if (this.jobRequest == null) {
            throw new IllegalArgumentException("JobRequest must be present.");
        } else {
            JobDetails jobDetails = new JobDetails(this.jobRequest);
            return this.build(jobDetails);
        }
    }
```

I would expect that JobScheduler also allows the creation of recurrent jobs using the JobRequest approach. 

The reason I encountered this issue is that I need to schedule a recurring job that utilises dependency injection. This does not appear to be possible with the JobLambda approach.

### How to reproduce?

```kotlin
   
import kotlinx.coroutines.runBlocking
import org.jobrunr.jobs.annotations.Job
import org.jobrunr.jobs.annotations.Recurring
import org.jobrunr.jobs.lambdas.JobRequest
import org.jobrunr.jobs.lambdas.JobRequestHandler
import org.jobrunr.scheduling.BackgroundJob
import org.jobrunr.scheduling.RecurringJobBuilder.aRecurringJob
import org.springframework.stereotype.Component
import org.springframework.stereotype.Service


const val DEFAULT_SCHEDULE = "0 1 * * * *"
const val JOB_ID = "some-scheduler"
const val JOB_NAME = "Schedule something"

@Service
class SomeScheduler {

    @Recurring(id = JOB_ID, cron = DEFAULT_SCHEDULE)
    @Job(name = JOB_NAME)
    fun execute(): Unit = runBlocking {
        val id = "someId"
        val name = "someName"
        val cronSchedule = "1 * * * * *"

        val recurrentJob = aRecurringJob()
            .withId(id)
            .withName(name)
            .withCron(cronSchedule)
            .withJobRequest(MyJobRequest())

        BackgroundJob.createRecurrently(recurrentJob)
    }
}

// From the docs: https://www.jobrunr.io/en/documentation/background-methods/
class MyJobRequest : JobRequest {
    override fun getJobRequestHandler(): Class<MyJobRequestHandler> {
        return MyJobRequestHandler::class.java
    }
}

@Component
class MyJobRequestHandler : JobRequestHandler<MyJobRequest?> {
    @Job(name = "Some neat Job Display Name", retries = 2)
    override fun run(jobRequest: MyJobRequest?) {
        println("Hello I am running")
        println(jobRequest)
    }
}

```

### Relevant log output

```shell
2024-06-30 11:08:50.856  WARN o.j.server.BackgroundJobPerformer - Job(id=01906867-530d-78e1-aa3b-f4122cf4c2a2, jobName='Schedule something') processing failed: An exception occurred during the performance of the job
java.lang.IllegalArgumentException: JobLambda must be present.
	at org.jobrunr.scheduling.RecurringJobBuilder.build(RecurringJobBuilder.java:208)
	at org.jobrunr.scheduling.JobScheduler.createRecurrently(JobScheduler.java:481)
	at org.jobrunr.scheduling.BackgroundJob.createRecurrently(BackgroundJob.java:636)
	at nl.example.scheduler.SomeScheduler$execute$1.invokeSuspend(SomeSheduler.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at nl.example.scheduler.SomeScheduler.execute(SomeSheduler.kt:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.invokeJobMethod(AbstractBackgroundJobRunner.java:65)
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.run(AbstractBackgroundJobRunner.java:39)
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner.run(AbstractBackgroundJobRunner.java:21)
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:95)
	at org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:68)
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

**Comment by rdehuyss** [comment]
Not following community guidelines (profile is missing name and company).

**Comment by rdehuyss** [comment]
And the answer is mentioned in the docs.

**Comment by rdehuyss** [comment]
Thanks for updating your profile. If you use the  `Jobrequestscheduler`, you will be able to do what you want to do.

**Comment by lvdkleij** [comment]
Problem solved. Many thanks, much appreciated.
