### ISSUE TITLE
[BUG] could not update job(id=01905f30-b2ca-78a4-ba81-14b592f8db1e, jobName='yxt:canvasJob') to SUCCEEDED state: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.stateIndexBeforeStateChange" is null

### ISSUE THREAD

**Issue by wjw465150** [jobrunr/jobrunr#1065]
### JobRunr Version

7.2.1

### JDK Version

openjdk version "17.0.11"

### Your SQL / NoSQL database

no use DB

### What happened?

[] 2024-06-28 22:12:27,423 ERROR vm-10-9-centos ws-cooperation-job-1.0-test-runner.jar[20772] org.jobrunr.server.BackgroundJobPerformer.updateJobStateToSucceededAndRunJobFilters(BackgroundJobPerformer.java:118) (backgroundjob-worker-pool-6-thread-5) ERROR - could not update job(id=01905f30-b2ca-78a4-ba81-14b592f8db1e, jobName='yxt:canvasJob') to SUCCEEDED state: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.stateIndexBeforeStateChange" is null
	at org.jobrunr.jobs.Job.hasStateChange(Job.java:153)
	at org.jobrunr.jobs.filters.JobPerformingFilters.runOnStateElectionFilter(JobPerformingFilters.java:24)
	at org.jobrunr.server.BackgroundJobPerformer.saveAndRunStateRelatedJobFilters(BackgroundJobPerformer.java:144)
	at org.jobrunr.server.BackgroundJobPerformer.updateJobStateToSucceededAndRunJobFilters(BackgroundJobPerformer.java:110)
	at org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:69)
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

**Comment by rdehuyss** [comment]
Are you calling the method `Job.getStateChangesForJobFilters()` somewhere in your code?

**Comment by wjw465150** [comment]
> Are you calling the method `Job.getStateChangesForJobFilters()` somewhere in your code?

No

**Comment by rdehuyss** [comment]
Fixed by PR https://github.com/jobrunr/jobrunr/pull/1066.
