### ISSUE TITLE
Schedule Job dependancies not autowiring in Spring

### ISSUE THREAD

**Issue by prabhushan** [jobrunr/jobrunr#107]
**Describe the bug**
I have very common use case where schedulerService.java has a method which should be called recursively. The method should have 1 more spring bean (TestDependancy) and use that . I get Null pointer exception as the spring bean is always null. This is the case especially when i use a datasource (tried with H2 and postgresql too).
Working in-memory alone.

**Environment**
I'm using version 1.3.1
I'm running on JRE / JDK 8
I'm using the following StorageProvider h2 and postgresql
[example-jobrunr.zip](https://github.com/jobrunr/jobrunr/files/6261676/example-jobrunr.zip)

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
JobRunrExampleConfiguration.java

```java
      @Bean
	public DataSource dataSource() {
		DataSourceBuilder dataSourceBuilder = DataSourceBuilder.create();
		dataSourceBuilder.driverClassName("org.h2.Driver");
		dataSourceBuilder.url("jdbc:h2:mem:testdb");
		dataSourceBuilder.username("sa");
		dataSourceBuilder.password("password");
		return dataSourceBuilder.build();

	}

	@Bean
	public JobScheduler initJobRunr(DataSource dataSource) {
		return JobRunr.configure().useStorageProvider(new DefaultSqlStorageProvider(dataSource, DatabaseOptions.CREATE)).useDefaultBackgroundJobServer()
				.initialize();
	}
```
**SampleJobService.java**
```java
	@Autowired
	TestDependancy testDependancy;
....

@Job(name = "The sample job with variable %0", retries = 2)
    public void executeSampleJob(String input) {
        logger.info("The sample job has begun. The variable you passed is {}", input);
        try {
			testDependancy.printSomething(input);
			// Thread.sleep(5000);
		} catch (Exception e) {
            logger.error("Error while executing sample job", e);
        } finally {
            logger.info("Sample job has finished...");
        }
    }

```
```java
	@Override
	public void run(String... args) throws Exception {
		logger.info("RUN #######");

		jobScheduler.<SampleJobService>scheduleRecurrently("recurring-sample-job", x -> x.executeSampleJob("Hello from recurring job"), "* * * * *");
	}

```

**Expected behavior**
TestDependancy in SampleJobService should have resolved and worked

**Additional context**

error log

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.4.RELEASE)

2021-04-05 22:47:02.021  INFO 37844 --- [           main] org.jobrunr.examples.JobRunrApplication  : Starting JobRunrApplication on Tistas-MBP-82 with PID 37844 (/Users/p.shanmughapriyan/git/example-mkyong/target/classes started by p.shanmughapriyan in /Users/p.shanmughapriyan/git/example-mkyong)
2021-04-05 22:47:02.023  INFO 37844 --- [           main] org.jobrunr.examples.JobRunrApplication  : No active profile set, falling back to default profiles: default
2021-04-05 22:47:02.566  INFO 37844 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
2021-04-05 22:47:02.591  INFO 37844 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 17ms. Found 0 JPA repository interfaces.
2021-04-05 22:47:03.055  INFO 37844 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-04-05 22:47:03.068  INFO 37844 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-04-05 22:47:03.068  INFO 37844 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.38]
2021-04-05 22:47:03.162  INFO 37844 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-04-05 22:47:03.163  INFO 37844 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1082 ms
2021-04-05 22:47:03.312  INFO 37844 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-04-05 22:47:03.319  INFO 37844 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-04-05 22:47:03.408  INFO 37844 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2021-04-05 22:47:03.452  INFO 37844 --- [         task-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2021-04-05 22:47:03.497  INFO 37844 --- [         task-1] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.21.Final
2021-04-05 22:47:03.500  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v000__create_migrations_table.sql}
2021-04-05 22:47:03.545  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v001__create_job_table.sql}
2021-04-05 22:47:03.554  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v002__create_recurring_job_table.sql}
2021-04-05 22:47:03.558  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v003__create_background_job_server_table.sql}
2021-04-05 22:47:03.565  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v004__create_job_stats_view.sql}
2021-04-05 22:47:03.579  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v005__update_job_stats_view.sql}
2021-04-05 22:47:03.594  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v006__alter_table_jobs_add_recurringjob.sql}
2021-04-05 22:47:03.633  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v007__alter_table_backgroundjobserver_add_delete_config.sql}
2021-04-05 22:47:03.657  INFO 37844 --- [         task-1] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2021-04-05 22:47:03.664  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v008__alter_table_jobs_increase_jobAsJson_size.sql}
2021-04-05 22:47:03.665  INFO 37844 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration MigrationByPath{path=/org/jobrunr/storage/sql/common/migrations/v009__change_jobrunr_job_counters_to_jobrunr_metadata.sql}
2021-04-05 22:47:03.754  INFO 37844 --- [           main] j.s.t.ScheduledThreadPoolJobRunrExecutor : ThreadManager of type 'ScheduledThreadPool' started
2021-04-05 22:47:03.767  INFO 37844 --- [pool-1-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer (31d07cb6-43e0-492e-9f20-6b83d99a3836) and 64 BackgroundJobPerformers started successfully
2021-04-05 22:47:03.767  INFO 37844 --- [pool-1-thread-1] org.jobrunr.server.ServerZooKeeper       : Server 31d07cb6-43e0-492e-9f20-6b83d99a3836 is master (this BackgroundJobServer)
2021-04-05 22:47:03.802  WARN 37844 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-04-05 22:47:03.820  INFO 37844 --- [         task-1] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2021-04-05 22:47:04.023  INFO 37844 --- [         task-1] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2021-04-05 22:47:04.032  INFO 37844 --- [         task-1] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2021-04-05 22:47:04.115  INFO 37844 --- [           main] j.s.t.ScheduledThreadPoolJobRunrExecutor : ThreadManager of type 'ScheduledThreadPool' started
2021-04-05 22:47:04.115  INFO 37844 --- [pool-3-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer (f5df6ed1-5ae6-4496-871d-3610116c2667) and 64 BackgroundJobPerformers started successfully
2021-04-05 22:47:04.116  INFO 37844 --- [pool-3-thread-1] org.jobrunr.server.ServerZooKeeper       : Server 31d07cb6-43e0-492e-9f20-6b83d99a3836 is master (another BackgroundJobServer)
2021-04-05 22:47:04.153  INFO 37844 --- [           main] o.j.dashboard.JobRunrDashboardWebServer  : JobRunr Dashboard started at http://localhost:8000
2021-04-05 22:47:04.230  INFO 37844 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-04-05 22:47:04.232  INFO 37844 --- [           main] DeferredRepositoryInitializationListener : Triggering deferred initialization of Spring Data repositories…
2021-04-05 22:47:04.232  INFO 37844 --- [           main] DeferredRepositoryInitializationListener : Spring Data repositories initialized!
2021-04-05 22:47:04.244  INFO 37844 --- [           main] org.jobrunr.examples.JobRunrApplication  : Started JobRunrApplication in 2.531 seconds (JVM running for 3.087)
2021-04-05 22:47:04.246  INFO 37844 --- [           main] ication$$EnhancerBySpringCGLIB$$c3a91e4d : RUN #######
2021-04-05 22:47:49.850  INFO 37844 --- [pool-2-thread-2] o.j.examples.services.SampleJobService   : The sample job has begun. The variable you passed is Hello from recurring job
2021-04-05 22:47:49.853 ERROR 37844 --- [pool-2-thread-2] o.j.examples.services.SampleJobService   : Error while executing sample job

java.lang.NullPointerException: null
	at org.jobrunr.examples.services.SampleJobService.executeSampleJob(SampleJobService.java:26) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.invokeJobMethod(AbstractBackgroundJobRunner.java:59) [jobrunr-1.3.1.jar:na]
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.run(AbstractBackgroundJobRunner.java:36) [jobrunr-1.3.1.jar:na]
	at org.jobrunr.server.runner.AbstractBackgroundJobRunner.run(AbstractBackgroundJobRunner.java:19) [jobrunr-1.3.1.jar:na]
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:78) [jobrunr-1.3.1.jar:na]
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:38) [jobrunr-1.3.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2021-04-05 22:47:49.854  INFO 37844 --- [pool-2-thread-2] o.j.examples.services.SampleJobService   : Sample job has finished...
```

**Comment by rdehuyss** [comment]
Hi @prabhushan ,

the reason is that you are creating a BackgroundJobServer yourself via code without Spring integration.

If you remove the following lines from the `JobRunrExampleConfiguration` (line 27-31), all will work well (tested):

```
	@Bean
	public JobScheduler initJobRunr(DataSource dataSource) {
		return JobRunr.configure().useStorageProvider(new DefaultSqlStorageProvider(dataSource, DatabaseOptions.CREATE)).useDefaultBackgroundJobServer()
				.initialize();
	}
```

**Comment by prabhushan** [comment]
Thanks.. I also fixed it via using JobActivator..


	@Bean
	public JobScheduler initJobRunr(DataSource dataSource, ApplicationContext applicationContext) {
		return JobRunr.configure().useStorageProvider(new DefaultSqlStorageProvider(dataSource, DatabaseOptions.CREATE))
				.useJobActivator(applicationContext::getBean).
				useDefaultBackgroundJobServer()
				.initialize();
	}
