### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by itizarsa** [jobrunr/jobrunr#1075]
### Runtime information
- __Timestamp__: 2024-07-22T06:41:06.341772464Z
- __Location__: BackgroundJobServer b9e1445c-293b-4ae9-a8d3-5151e940416b
- __JobRunr Version__: 7.2.2
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 21.0.4
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: b9e1445c-293b-4ae9-a8d3-5151e940416b
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-07-22T05:24:04.265961100Z, lastHeartbeat: 2024-07-22T06:41:02.851245800Z)
- BackgroundJobServer id: 9ee56e3e-aa53-44b6-98f4-000491d6140f
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-07-22T05:30:22.399367900Z, lastHeartbeat: 2024-07-22T06:41:03.558360200Z)

#### Concurrent modified jobs:
Job id: 0190d90b-4fc6-77c6-99b3-da7470d98133
	Job Name: Segment 13179
	Job Signature: loyalty.ordersync.segment.SegmentHandler.run(loyalty.ordersync.segment.SegmentJob)
	Local version: 16; Storage version: 17
	Local state: FAILED (at 2024-07-22T06:41:04.646294106Z) ← PROCESSING (updated at 2024-07-22T06:39:12.842946323Z on BackgroundJobServer 9ee56e3e-aa53-44b6-98f4-000491d6140f and started at 2024-07-22T06:35:18.179487065Z) ← ENQUEUED (at 2024-07-22T06:35:15.444713061Z) ← SCHEDULED (at 2024-07-22T06:05:15.590285814Z)
	Storage state: PROCESSING (updated at 2024-07-22T06:39:37.158651659Z on BackgroundJobServer 9ee56e3e-aa53-44b6-98f4-000491d6140f and started at 2024-07-22T06:35:18.179487065Z) ← ENQUEUED (at 2024-07-22T06:35:15.444713061Z) ← SCHEDULED (at 2024-07-22T06:05:15.590285814Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.ProcessOrphanedJobsTask.runTask(ProcessOrphanedJobsTask.java:29)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 0190d90b-4fc6-77c6-99b3-da7470d98133

## Concurrent modified jobs:
Job id: 0190d90b-4fc6-77c6-99b3-da7470d98133
	Job Name: Segment 13179
	Job Signature: loyalty.ordersync.segment.SegmentHandler.run(loyalty.ordersync.segment.SegmentJob)
	Local version: 16; Storage version: 17
	Local state: FAILED (at 2024-07-22T06:41:04.646294106Z) ← PROCESSING (updated at 2024-07-22T06:39:12.842946323Z on BackgroundJobServer 9ee56e3e-aa53-44b6-98f4-000491d6140f and started at 2024-07-22T06:35:18.179487065Z) ← ENQUEUED (at 2024-07-22T06:35:15.444713061Z) ← SCHEDULED (at 2024-07-22T06:05:15.590285814Z)
	Storage state: PROCESSING (updated at 2024-07-22T06:39:37.158651659Z on BackgroundJobServer 9ee56e3e-aa53-44b6-98f4-000491d6140f and started at 2024-07-22T06:35:18.179487065Z) ← ENQUEUED (at 2024-07-22T06:35:15.444713061Z) ← SCHEDULED (at 2024-07-22T06:05:15.590285814Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 0190d90b-4fc6-77c6-99b3-da7470d98133
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 17 more

```

**Comment by rdehuyss** [comment]
Related to database performance. Please review your database metrics
