### ISSUE TITLE
Instruction 87 not found

### ISSUE THREAD

**Issue by cemremengu** [jobrunr/jobrunr#11]
I am trying to run the task below which gives the error:

```java
@RestController
@RequestMapping("/v1/task/enqueue")
public class TaskController {

  private final JobScheduler jobScheduler;
  private final CsvExportService csv;

  public TaskController(JobScheduler jobScheduler, CsvExportService csv) {
    this.jobScheduler = jobScheduler;
    this.csv = csv;
  }

  @PostMapping(value = "/")
  public ResponseEntity findAll() {
    jobScheduler.<CsvExportService>enqueue(c -> c.export(1, "select * from dual", Path.of("/")));
    return ResponseEntity.ok().build();
  }
}
```

```java
  @Bean
  public JobScheduler initJobRunr(ApplicationContext applicationContext) {
    return JobRunr.configure()
        .useStorageProvider(new MongoDBStorageProvider("localhost", 27017))
        .useJobActivator(applicationContext::getBean)
        .useDefaultBackgroundJobServer()
        .useDashboard()
        .initialize();
  }
```

```stacktrace
java.lang.IllegalArgumentException: Instruction 87 not found
	at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:56) ~[jobrunr-0.9.7.jar:?]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator$JobDetailsFinder$1.visitInsn(JobDetailsAsmGenerator.java:101) ~[jobrunr-0.9.7.jar:?]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2188) ~[asm-7.3.1.jar:7.3.1]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1492) ~[asm-7.3.1.jar:7.3.1]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:717) ~[asm-7.3.1.jar:7.3.1]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401) ~[asm-7.3.1.jar:7.3.1]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.findJobDetailsInByteCode(JobDetailsAsmGenerator.java:58) ~[jobrunr-0.9.7.jar:?]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:38) ~[jobrunr-0.9.7.jar:?]
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:111) ~[jobrunr-0.9.7.jar:?]
	at com.ttgint.myapp.controller.TaskController.findAll(TaskController.java:25) ~[classes/:?]
```

**Comment by cemremengu** [comment]
The error was due to my service not being `void` (it was returning a value). The error message should clearly indicate this however.

**Comment by rdehuyss** [comment]
Thanks for finding this issue! In future versions of JobRunr, this won't be a problem anymore.

However, you will not be able to do anything with the return value (as the background job may run on a different JVM on a different server) but that's probably not an issue, I guess.

**Comment by cemremengu** [comment]
Do you just return null then? If that is the case it might be a problem for primitive return values. Also you should at least log a warning I think telling that the return value is ignored. Otherwise many inexperienced will open issues for this :smile:
