### ISSUE TITLE
[BUG] Unrecognized field "currentValue"

### ISSUE THREAD

**Issue by VN11733** [jobrunr/jobrunr#1107]
### JobRunr Version

7.2.3

### JDK Version

OpenJDK 17.0.5

### Your SQL / NoSQL database

Postgres 12

### What happened?

We've upgraded quarkus-jobrunr-pro version from 6.2.9 to 7.2.3 and now facing with Issue: 
```log
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "currentValue" (class org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress), not marked as ignorable (4 known properties: "succeededAmount", "totalAmount", "failedAmount", "progress"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1212] (through reference chain: org.jobrunr.jobs.Job["metadata"]->java.util.concurrent.ConcurrentHashMap["jobRunrDashboardProgressBar-3"]->org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress["currentValue"])
```
We know for sure that `MigrateFromV6toV7Task` ran and successfully finished it's job:
![image](https://github.com/user-attachments/assets/3c434186-5d68-416d-b169-512c7557f1bd)
Since we found [related issue](https://github.com/jobrunr/jobrunr/issues/1036), we understand that we should provide BatchJob JSON:
```json
{
  "@class": "org.jobrunr.jobs.Job",
  "id": "69ce9780-2471-4d03-bb91-8ab9efc37a3a",
  "version": 4,
  "jobName": "Remove old risk model files from sharepoint",
  "amountOfRetries": null,
  "labels": [],
  "jobSignature": "com.lgim.index.jobrunr.job.handlers.AxiomaRiskModelSPHousekeepingRequestHandler.run(com.lgim.index.jobrunr.requests.AxiomaRiskModelSPHousekeepingRequest)",
  "priority": 0,
  "deleteOnSuccess": null,
  "deleteOnFailure": null,
  "mutex": null,
  "metadata": {
    "@class": "java.util.concurrent.ConcurrentHashMap",
    "jobRunrDashboardLog-3": {
      "logLines": [
        {
          "level": "INFO",
          "logInstant": "2024-01-30T17:30:00.483965399Z",
          "logMessage": "Load started with parameters: {\"source\":\"SHAREPOINT\"}"
        },
        {
          "level": "INFO",
          "logInstant": "2024-01-30T17:30:00.484313386Z",
          "logMessage": "Triggering request to remove old risk model files on SHAREPOINT"
        },
        {
          "level": "ERROR",
          "logInstant": "2024-01-30T17:30:01.290777035Z",
          "logMessage": "Error occurred while deleting the risk model files. com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure"
        },
        {
          "level": "INFO",
          "logInstant": "2024-01-30T17:30:01.295374288Z",
          "logMessage": "Load ended"
        }
      ],
      "@class": "org.jobrunr.jobs.context.JobDashboardLogger$JobDashboardLogLines"
    },
    "jobRunrDashboardProgressBar-3": {
      "currentValue": 0,
      "progress": 0,
      "totalAmount": 1,
      "@class": "org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress"
    }
  },
  "jobDetails": {
    "cacheable": true,
    "className": "com.lgim.index.jobrunr.job.handlers.AxiomaRiskModelSPHousekeepingRequestHandler",
    "staticFieldName": null,
    "methodName": "run",
    "jobParameters": [
      {
        "actualClassName": "com.lgim.index.jobrunr.requests.AxiomaRiskModelSPHousekeepingRequest",
        "className": "com.lgim.index.jobrunr.requests.AxiomaRiskModelSPHousekeepingRequest",
        "object": {
          "configs": "{\"source\":\"SHAREPOINT\"}"
        }
      }
    ]
  },
  "jobHistory": [
    {
      "createdAt": "2024-01-30T17:29:35.197664031Z",
      "state": "SCHEDULED",
      "user": null,
      "previousJobState": null,
      "reason": "Scheduled by recurring job 'Remove old risk model files from sharepoint'",
      "recurringJobId": "HOUSEKEEPING_AXIOMA_RISK_MODEL_SHAREPOINT",
      "scheduledAt": "2024-01-30T17:30:00Z",
      "@class": "org.jobrunr.jobs.states.ScheduledState"
    },
    {
      "createdAt": "2024-01-30T17:30:00.000804265Z",
      "state": "ENQUEUED",
      "user": null,
      "previousJobState": null,
      "reason": null,
      "@class": "org.jobrunr.jobs.states.EnqueuedState"
    },
    {
      "createdAt": "2024-01-30T17:30:00.051542052Z",
      "state": "PROCESSING",
      "user": null,
      "serverId": "0cfd8d0a-baed-4e26-a5ce-7bc4765e0841",
      "serverName": "ip-10-244-8-44.eu-west-2.compute.internal",
      "updatedAt": "2024-01-30T17:30:00.051542052Z",
      "@class": "org.jobrunr.jobs.states.ProcessingState"
    },
    {
      "createdAt": "2024-01-30T17:30:01.295477934Z",
      "state": "FAILED",
      "user": null,
      "doNotRetry": false,
      "exceptionCauseMessage": "com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure",
      "exceptionCauseType": "jakarta.ws.rs.ProcessingException",
      "exceptionMessage": "com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure",
      "exceptionType": "com.lgim.index.jobrunr.services.loads.LoadException",
      "message": "An exception occurred during the performance of the job",
      "stackTrace": "com.lgim.index.jobrunr.services.loads.LoadException: com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure\n\tat com.lgim.index.jobrunr.services.loads.risk.model.AxiomaRiskModelHousekeepingLoader.fetchDataFromSource(AxiomaRiskModelHousekeepingLoader.java:57)\n\tat com.lgim.index.jobrunr.services.loads.Loader.run(Loader.java:20)\n\tat com.lgim.index.jobrunr.services.loads.risk.model.AxiomaRiskModelHousekeepingLoader_ClientProxy.run(Unknown Source)\n\tat com.lgim.index.jobrunr.job.handlers.AxiomaRiskModelSPHousekeepingRequestHandler.run(AxiomaRiskModelSPHousekeepingRequestHandler.java:24)\n\tat com.lgim.index.jobrunr.job.handlers.AxiomaRiskModelSPHousekeepingRequestHandler_ClientProxy.run(Unknown Source)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.invokeJobMethod(AbstractBackgroundJobRunner.java:78)\n\tat org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.run(AbstractBackgroundJobRunner.java:49)\n\tat org.jobrunr.server.runner.AbstractBackgroundJobRunner.run(AbstractBackgroundJobRunner.java:28)\n\tat org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:95)\n\tat org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:66)\n\tat org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:43)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: jakarta.ws.rs.ProcessingException: com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure\n\tat org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:652)\n\tat org.jboss.resteasy.microprofile.client.impl.MpClientInvocation.filterRequest(MpClientInvocation.java:67)\n\tat org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:424)\n\tat org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:134)\n\tat org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:103)\n\tat org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:61)\n\tat jdk.proxy2/jdk.proxy2.$Proxy47.housekeepingSharepoint(Unknown Source)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:168)\n\tat jdk.proxy2/jdk.proxy2.$Proxy50.housekeepingSharepoint(Unknown Source)\n\tat com.lgim.index.jobrunr.services.loads.risk.model.AxiomaRiskModelHousekeepingLoader.runHousekeeping(AxiomaRiskModelHousekeepingLoader.java:63)\n\tat com.lgim.index.jobrunr.services.loads.risk.model.AxiomaRiskModelHousekeepingLoader.fetchDataFromSource(AxiomaRiskModelHousekeepingLoader.java:44)\n\t... 20 more\nCaused by: com.lgim.index.jobrunr.services.loads.risk.model.TokenNotCreatedException: Unable to acquire token from azure\n\tat com.lgim.index.jobrunr.services.loads.risk.model.AuthorizationHeaderFactory.update(AuthorizationHeaderFactory.java:26)\n\tat org.jboss.resteasy.microprofile.client.header.ClientHeadersRequestFilter.lambda$filter$4(ClientHeadersRequestFilter.java:81)\n\tat java.base/java.util.Optional.ifPresent(Optional.java:178)\n\tat org.jboss.resteasy.microprofile.client.header.ClientHeadersRequestFilter.filter(ClientHeadersRequestFilter.java:81)\n\tat org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:644)\n\t... 34 more\n",
      "@class": "org.jobrunr.jobs.states.FailedState"
    }
  ],
  "recurringJobId": "HOUSEKEEPING_AXIOMA_RISK_MODEL_SHAREPOINT",
  "dynamicQueue": null,
  "serverTag": "DEFAULT",
  "jobResult": null,
  "deleteAt": null
}
```

### How to reproduce?

1. Upgrade version from 6.2.9 to 7.2.3
2. Resolve all issues with deprecated methods, changed constructors etc.
3. Replace `PageRequest.ascOnName(200)` usage by `Paging.CursorBasedPage.ascOnName(200)` (don't know whether it is related or not)
4. Run the code.

### Relevant log output

```shell
""2024-09-03 18:25:26,239 WARN  [org.jobrunr.server.JobZooKeeper] (backgroundjob-zookeeper-pool-10-thread-6) JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:92)
	at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
	at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:367)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:48)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jobrunr.storage.sql.common.JobTable.selectJobList(JobTable.java:232)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobList(DefaultSqlStorageProvider.java:337)
	at org.jobrunr.storage.ThreadSafeStorageProvider.getJobList(ThreadSafeStorageProvider.java:201)
	at org.jobrunr.server.tasks.zookeeper.DeleteSucceededJobsTask.getJobsToDelete(DeleteSucceededJobsTask.java:35)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.getItemsToProcess(AbstractJobZooKeeperTask.java:45)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:28)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:28)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:35)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:35)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "currentValue" (class org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress), not marked as ignorable (4 known properties: "succeededAmount", "totalAmount", "failedAmount", "progress"])
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1212] (through reference chain: org.jobrunr.jobs.Job["metadata"]->java.util.concurrent.ConcurrentHashMap["jobRunrDashboardProgressBar-3"]->org.jobrunr.jobs.context.JobDashboardProgressBar$JobDashboardProgress["currentValue"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1771)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:240)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserializeWithType(UntypedObjectDeserializerNR.java:115)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:625)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:449)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserializeWithType(MapDeserializer.java:492)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:147)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:215)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:170)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1380)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4899)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3846)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3814)
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:88)
	... 28 more
```

**Comment by auloin** [comment]
Hi @VN11733, how many of the jobs in your DB have a `dashboardProgressBar` with the field `currentValue`?

**Comment by VN11733** [comment]
hey @auloin, there are 284 job in our DB with this field.

**Comment by auloin** [comment]
@VN11733 are they all in `PROCESSING`?

**Comment by VN11733** [comment]
@auloin there is no job with `PROCESSING` in `jobrunr_jobs` table right now, but it moves it to processing status when a job is in-flight.

**Comment by VN11733** [comment]
we have 104 deleted, 98 failed and 75 succeeded job, if that's reliable

**Comment by auloin** [comment]
@VN11733 Thanks for sharing the numbers. We still need to see how to best fix this issue. If you don't need to re-run the jobs, deleting them should solve the issue on your side. If you still need the jobs but urgently need a fix, you can "manually" update the `jobAsJson` to remove the field.

**Comment by VN11733** [comment]
FYI: we'll clear the table, but I assume it should be fixed anyway. Thanks for quick answer and detailed instruction.

**Comment by rdehuyss** [comment]
We'll close it for now as it is a migration issue only with a workaround.
