### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by anika-tam** [jobrunr/jobrunr#1131]
### Runtime information
- __Timestamp__: 2024-09-19T09:01:48.482961425Z
- __Location__: BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97
- __JobRunr Version__: 7.1.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 21
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 90b96c8e-d05d-4f96-8ec8-b3ed171cd5f0
(workerPoolSize: 512, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-19T03:21:36.943256Z, lastHeartbeat: 2024-09-19T09:01:44.926217Z)
- BackgroundJobServer id: 75315e8e-f476-4e43-b1db-3a460da8ed97
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-19T08:57:27.199465Z, lastHeartbeat: 2024-09-19T09:01:32.124321Z)

#### Concurrent modified jobs:
Job id: 01920983-1fe8-7a1f-8119-501b9dafc500
	Job Name: Profile 384815 enrolled workflow 199
	Job Signature: com.gobysend.processor.services.workflows.WorkflowExecutorJobService.triggerWorkflowForProfile(java.lang.Long,java.lang.Long,java.lang.String,java.lang.Long)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-19T09:01:31.947241458Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759727130Z) ← ENQUEUED (at 2024-09-19T09:00:41.320661671Z)
	Storage state: SCHEDULED (at 2024-09-19T09:01:45.173637952Z) ← FAILED (at 2024-09-19T09:01:45.173184320Z) ← PROCESSING (updated at 2024-09-19T09:00:42.759727130Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759727130Z) ← ENQUEUED (at 2024-09-19T09:00:41.320661671Z)
Job id: 01920983-1fd4-744f-9e03-372af7d75858
	Job Name: Profile 384813 enrolled workflow 199
	Job Signature: com.gobysend.processor.services.workflows.WorkflowExecutorJobService.triggerWorkflowForProfile(java.lang.Long,java.lang.Long,java.lang.String,java.lang.Long)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-19T09:01:31.947242750Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759725714Z) ← ENQUEUED (at 2024-09-19T09:00:41.291479463Z)
	Storage state: SCHEDULED (at 2024-09-19T09:01:45.173539436Z) ← FAILED (at 2024-09-19T09:01:45.173054794Z) ← PROCESSING (updated at 2024-09-19T09:00:42.759725714Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759725714Z) ← ENQUEUED (at 2024-09-19T09:00:41.291479463Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 01920983-1fe8-7a1f-8119-501b9dafc500, 01920983-1fd4-744f-9e03-372af7d75858

## Concurrent modified jobs:
Job id: 01920983-1fe8-7a1f-8119-501b9dafc500
	Job Name: Profile 384815 enrolled workflow 199
	Job Signature: com.gobysend.processor.services.workflows.WorkflowExecutorJobService.triggerWorkflowForProfile(java.lang.Long,java.lang.Long,java.lang.String,java.lang.Long)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-19T09:01:31.947241458Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759727130Z) ← ENQUEUED (at 2024-09-19T09:00:41.320661671Z)
	Storage state: SCHEDULED (at 2024-09-19T09:01:45.173637952Z) ← FAILED (at 2024-09-19T09:01:45.173184320Z) ← PROCESSING (updated at 2024-09-19T09:00:42.759727130Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759727130Z) ← ENQUEUED (at 2024-09-19T09:00:41.320661671Z)
Job id: 01920983-1fd4-744f-9e03-372af7d75858
	Job Name: Profile 384813 enrolled workflow 199
	Job Signature: com.gobysend.processor.services.workflows.WorkflowExecutorJobService.triggerWorkflowForProfile(java.lang.Long,java.lang.Long,java.lang.String,java.lang.Long)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-19T09:01:31.947242750Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759725714Z) ← ENQUEUED (at 2024-09-19T09:00:41.291479463Z)
	Storage state: SCHEDULED (at 2024-09-19T09:01:45.173539436Z) ← FAILED (at 2024-09-19T09:01:45.173054794Z) ← PROCESSING (updated at 2024-09-19T09:00:42.759725714Z on BackgroundJobServer 75315e8e-f476-4e43-b1db-3a460da8ed97 and started at 2024-09-19T09:00:42.759725714Z) ← ENQUEUED (at 2024-09-19T09:00:41.291479463Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 12 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 01920983-1fe8-7a1f-8119-501b9dafc500, 01920983-1fd4-744f-9e03-372af7d75858
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 12 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 15 more

```

**Comment by rdehuyss** [comment]
Closing due to not following [community guidelines](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D) (missing Github profile information).
