### ISSUE TITLE
[BUG] Kotlin 1.7 is not supported when implementing JobLambda interface and running JobScheduler::enqueue

### ISSUE THREAD

**Issue by sindy-senorita** [jobrunr/jobrunr#1132]
### JobRunr Version

7.3.0

### JDK Version

corretto-17.0.12

### Your SQL / NoSQL database

postgres 14

### What happened?

Using JobLambda and JobScheduler::enqueue(). Got error `The Kotlin version 1.7 is unsupported`. Any way to work around this? But first, sorry if "bug" is not the correct issue type (I'd be willing to change the issue if that helps)

### How to reproduce?

I need to wrap the execution with other stuffs related to the app. So I extended JobLambda interface. But it fails with kotlin version 1.7 unsupported exception.

```kotlin
   data class Task(
    val id: String,
    val action: (() -> Unit)? = null,
) : JobLambda {
    override fun run() {
        this.action?.invoke()
    }
}

// in some other classes
@Service
class SchedulerRunner(private val jobScheduler: JobScheduler) {  // using jobScheduler bean provided in starter
  fun launchTaskImmediately(task: Task) {
          jobScheduler.enqueue(task) // this throw the exception (full exception stack below)
  }
}

// :"main"
scheduledRunner.launchTaskImmediately(
            Task("launch-task-immidiately-id", otherService::doStuffs),
)
```
using ` org.jobrunr:jobrunr-spring-boot-2-starter:7.3.0` on springboot 2.7.2 and kotlin 1.7.10

### Relevant log output

```shell
nested exception is java.lang.UnsupportedOperationException: The Kotlin version 1.7 is unsupported] with root cause
java.lang.UnsupportedOperationException: The Kotlin version 1.7 is unsupported
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder$1.visit(KotlinJobDetailsFinder.java:61)
	at org.objectweb.asm.ClassReader.readElementValue(ClassReader.java:3154)
	at org.objectweb.asm.ClassReader.readElementValues(ClassReader.java:3006)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:609)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:425)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:90)
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder.parse(KotlinJobDetailsFinder.java:98)
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder.<init>(KotlinJobDetailsFinder.java:41)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:16)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.lambda$getJobDetails$0(CachingJobDetailsGenerator.java:85)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.initJobDetails(CachingJobDetailsGenerator.java:133)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.initOrGetJobDetails(CachingJobDetailsGenerator.java:113)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:84)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:48)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:125)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:107)
	at com.xxx.runner.SchedulerRunner.launchTaskImmediately(SchedulerRunner.kt:72)
...
```

**Comment by rdehuyss** [comment]
We dropped support for Kotlin 1.7 already a while ago. 

We normally only support the 2 latest major versions (1.9 and 2.0) but we also support still support Kotlin 1.8 exceptionally.
