### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by geirsagberg** [jobrunr/jobrunr#1138]
### Runtime information
- __Timestamp__: 2024-09-12T14:15:55.702904297Z
- __Location__: BackgroundJobServer f5f8e3e6-bdc1-40dd-9057-8afbee03d11a
- __JobRunr Version__: 6.3.1
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 21.0.4
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: f5f8e3e6-bdc1-40dd-9057-8afbee03d11a
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-12T14:14:50.627702Z, lastHeartbeat: 2024-09-12T14:15:50.665215Z)

#### Concurrent modified jobs:
Job id: fc2620db-0c1f-40c0-9048-ab8148d6ae84
	Job Name: Load vegobjekter of type 762, page 6/501
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-12T14:15:55.692978892Z on BackgroundJobServer f5f8e3e6-bdc1-40dd-9057-8afbee03d11a and started at 2024-09-12T14:15:35.880486027Z) ← ENQUEUED (at 2024-09-12T14:09:23.972421081Z)
	Storage state: PROCESSING (updated at 2024-09-12T14:15:38.091058746Z on BackgroundJobServer f5f8e3e6-bdc1-40dd-9057-8afbee03d11a and started at 2024-09-12T14:15:35.880486027Z) ← ENQUEUED (at 2024-09-12T14:09:23.972421081Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: fc2620db-0c1f-40c0-9048-ab8148d6ae84

## Concurrent modified jobs:
Job id: fc2620db-0c1f-40c0-9048-ab8148d6ae84
	Job Name: Load vegobjekter of type 762, page 6/501
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-12T14:15:55.692978892Z on BackgroundJobServer f5f8e3e6-bdc1-40dd-9057-8afbee03d11a and started at 2024-09-12T14:15:35.880486027Z) ← ENQUEUED (at 2024-09-12T14:09:23.972421081Z)
	Storage state: PROCESSING (updated at 2024-09-12T14:15:38.091058746Z on BackgroundJobServer f5f8e3e6-bdc1-40dd-9057-8afbee03d11a and started at 2024-09-12T14:15:35.880486027Z) ← ENQUEUED (at 2024-09-12T14:09:23.972421081Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: fc2620db-0c1f-40c0-9048-ab8148d6ae84
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 0, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 13 more

```

### Runtime information
- __Timestamp__: 2024-09-12T18:26:59.502690343Z
- __Location__: BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac
- __JobRunr Version__: 6.3.1
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 21.0.4
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 20eba450-4432-4e2a-9258-d745d5c710ac
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-12T18:04:27.316123Z, lastHeartbeat: 2024-09-12T18:26:58.900138Z)

#### Concurrent modified jobs:
Job id: c3582046-f181-4794-9d16-e05d5d1846e7
	Job Name: Load vegobjekter of type 83, page 13/1089
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 18; Storage version: 19
	Local state: PROCESSING (updated at 2024-09-12T18:26:59.489618231Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:22.061577374Z) ← ENQUEUED (at 2024-09-12T18:10:46.617071406Z)
	Storage state: PROCESSING (updated at 2024-09-12T18:25:41.737635046Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:22.061577374Z) ← ENQUEUED (at 2024-09-12T18:10:46.617071406Z)
Job id: ef0c7f89-fa70-4522-af32-ce85387311e3
	Job Name: Load vegobjekter of type 500, page 13/21
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 18; Storage version: 19
	Local state: PROCESSING (updated at 2024-09-12T18:26:59.489618490Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:15.136730982Z) ← ENQUEUED (at 2024-09-12T18:10:19.098883908Z)
	Storage state: PROCESSING (updated at 2024-09-12T18:25:41.737635428Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:15.136730982Z) ← ENQUEUED (at 2024-09-12T18:10:19.098883908Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: c3582046-f181-4794-9d16-e05d5d1846e7, ef0c7f89-fa70-4522-af32-ce85387311e3

## Concurrent modified jobs:
Job id: c3582046-f181-4794-9d16-e05d5d1846e7
	Job Name: Load vegobjekter of type 83, page 13/1089
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 18; Storage version: 19
	Local state: PROCESSING (updated at 2024-09-12T18:26:59.489618231Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:22.061577374Z) ← ENQUEUED (at 2024-09-12T18:10:46.617071406Z)
	Storage state: PROCESSING (updated at 2024-09-12T18:25:41.737635046Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:22.061577374Z) ← ENQUEUED (at 2024-09-12T18:10:46.617071406Z)
Job id: ef0c7f89-fa70-4522-af32-ce85387311e3
	Job Name: Load vegobjekter of type 500, page 13/21
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 18; Storage version: 19
	Local state: PROCESSING (updated at 2024-09-12T18:26:59.489618490Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:15.136730982Z) ← ENQUEUED (at 2024-09-12T18:10:19.098883908Z)
	Storage state: PROCESSING (updated at 2024-09-12T18:25:41.737635428Z on BackgroundJobServer 20eba450-4432-4e2a-9258-d745d5c710ac and started at 2024-09-12T18:21:15.136730982Z) ← ENQUEUED (at 2024-09-12T18:10:19.098883908Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: c3582046-f181-4794-9d16-e05d5d1846e7, ef0c7f89-fa70-4522-af32-ce85387311e3
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [1, 0, 0, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 13 more

```

### Runtime information
- __Timestamp__: 2024-09-16T22:33:04.629926974Z
- __Location__: BackgroundJobServer d3063bc9-3c44-47ec-a9f6-326f70b26e30
- __JobRunr Version__: 6.3.1
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 21.0.4
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: d3063bc9-3c44-47ec-a9f6-326f70b26e30
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-16T19:20:55.365122Z, lastHeartbeat: 2024-09-16T22:33:03.273333Z)

#### Concurrent modified jobs:
Job id: 945c00e1-ce1d-4b51-886c-8262f3a516c0
	Job Name: Load vegobjekter of type 967, page 46/80
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-16T22:33:04.614954621Z on BackgroundJobServer d3063bc9-3c44-47ec-a9f6-326f70b26e30 and started at 2024-09-16T22:32:46.396317472Z) ← ENQUEUED (at 2024-09-16T22:13:45.997279255Z)
	Storage state: PROCESSING (updated at 2024-09-16T22:32:47.017850582Z on BackgroundJobServer d3063bc9-3c44-47ec-a9f6-326f70b26e30 and started at 2024-09-16T22:32:46.396317472Z) ← ENQUEUED (at 2024-09-16T22:13:45.997279255Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 945c00e1-ce1d-4b51-886c-8262f3a516c0

## Concurrent modified jobs:
Job id: 945c00e1-ce1d-4b51-886c-8262f3a516c0
	Job Name: Load vegobjekter of type 967, page 46/80
	Job Signature: no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobHandler.run(no.vegvesen.vt.nvdb.apiles.feature.loader.application.jobs.LoadVegobjekterJobRequest)
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2024-09-16T22:33:04.614954621Z on BackgroundJobServer d3063bc9-3c44-47ec-a9f6-326f70b26e30 and started at 2024-09-16T22:32:46.396317472Z) ← ENQUEUED (at 2024-09-16T22:13:45.997279255Z)
	Storage state: PROCESSING (updated at 2024-09-16T22:32:47.017850582Z on BackgroundJobServer d3063bc9-3c44-47ec-a9f6-326f70b26e30 and started at 2024-09-16T22:32:46.396317472Z) ← ENQUEUED (at 2024-09-16T22:13:45.997279255Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 10 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 945c00e1-ce1d-4b51-886c-8262f3a516c0
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:97)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:188)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 10 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 1, 1, 1, 1, 1, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:179)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:184)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:90)
	... 13 more

```

**Comment by rdehuyss** [comment]
Hi @geirsagberg - you're on a rather old version of JobRunr, we only provide support for the latest version for OSS.

On top of that, you have CPU allocation problems (e.g. really long GC cycles) which may result in such behaviour. Have you looked into that?

So please upgrade before  creating an issue.

**Comment by geirsagberg** [comment]
Thanks, will upgrade and look into the GC cycles.
