### ISSUE TITLE
[BUG] ElasticSearchStorageProvider Index 0 out of bounds for length 0 

### ISSUE THREAD

**Issue by tksarul** [jobrunr/jobrunr#1150]
### JobRunr Version

7.3.1

### JDK Version

jdk 21

### Your SQL / NoSQL database

Elasticsearch

### What happened?

```
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.server.JobHandler.run(JobHandler.java:44) ~[jobrunr-7.3.1.jar:7.3.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[na:na]
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[na:na]
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[na:na]
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[na:na]
	at org.jobrunr.jobs.JobListVersioner.validateJobs(JobListVersioner.java:24) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.storage.nosql.elasticsearch.ElasticSearchStorageProvider.save(ElasticSearchStorageProvider.java:497) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.storage.StorageProvider.getJobsToProcess(StorageProvider.java:166) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getJobsToProcess(ThreadSafeStorageProvider.java:150) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.server.tasks.steward.OnboardNewWorkTask.runTask(OnboardNewWorkTask.java:39) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.server.tasks.Task.run(Task.java:48) ~[jobrunr-7.3.1.jar:7.3.1]
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36) ~[jobrunr-7.3.1.jar:7.3.1]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305) ~[na:na]
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36) ~[jobrunr-7.3.1.jar:7.3.1]
	... 7 common frames omitted

2024-11-03T22:42:42.602+05:30  INFO 53980 --- [pool-7-thread-2] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer - stopping (may take about PT10S)
2024-11-03T22:42:42.602+05:30  INFO 53980 --- [pool-7-thread-2] org.jobrunr.server.BackgroundJobServer   : BackgroundJobPerformers - stopping (waiting at most PT10S for jobs to finish)
2024-11-03T22:42:52.899+05:30  INFO 53980 --- [pool-7-thread-2] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer and BackgroundJobPerformers stopped
2024-11-03T22:42:52.901+05:30  INFO 53980 --- [pool-7-thread-3] org.jobrunr.server.ServerZooKeeper       : Server 899a1cbe-24d7-479c-b2ed-f53079f443cf is master (another BackgroundJobServer)
```

### How to reproduce?

use elastic search storage provider

**Comment by tksarul** [comment]
I have the fix for this issue. Kindly give me the permission to push my code in to other branch and initiate the pull request.

**Comment by auloin** [comment]
Fixed by https://github.com/jobrunr/jobrunr/pull/1151
