### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by minond** [jobrunr/jobrunr#1152]
### Runtime information
- __Timestamp__: 2024-11-07T00:25:45.112100Z
- __Location__: BackgroundJobServer ceb40e09-7cca-4e67-8287-63962362e18b
- __JobRunr Version__: 7.2.3
- __StorageProvider__: org.jobrunr.storage.sql.sqlserver.SQLServerStorageProvider
- __Java Version__: 11.0.19
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: ceb40e09-7cca-4e67-8287-63962362e18b
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2024-11-06T23:24:13.583124Z, lastHeartbeat: 2024-11-07T00:25:36.645895Z)
- BackgroundJobServer id: 797806dd-d784-40cb-bb44-c30dad9966a7
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2024-11-06T23:28:13.759466Z, lastHeartbeat: 2024-11-07T00:25:34.618524Z)

#### Concurrent modified jobs:
Job id: 01930403-2417-792b-a37d-56f7bf46166d
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681707Z) ← SCHEDULED (at 2024-11-07T00:25:34.998708Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317541Z) ← SCHEDULED (at 2024-11-07T00:25:34.998708Z)
Job id: 01930403-2418-702a-be68-c603dc155dbb
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681716Z) ← SCHEDULED (at 2024-11-07T00:25:35.000191Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317554Z) ← SCHEDULED (at 2024-11-07T00:25:35.000191Z)
Job id: 01930403-2418-702a-be68-c603dc155dbc
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681718Z) ← SCHEDULED (at 2024-11-07T00:25:35.000243Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317555Z) ← SCHEDULED (at 2024-11-07T00:25:35.000243Z)
Job id: 01930403-2418-702a-be68-c603dc155dbd
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681719Z) ← SCHEDULED (at 2024-11-07T00:25:35.000406Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317556Z) ← SCHEDULED (at 2024-11-07T00:25:35.000406Z)
Job id: 01930403-2418-702a-be68-c603dc155dbe
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681721Z) ← SCHEDULED (at 2024-11-07T00:25:35.000442Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317557Z) ← SCHEDULED (at 2024-11-07T00:25:35.000442Z)
Job id: 01930403-2418-702a-be68-c603dc155dbf
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681723Z) ← SCHEDULED (at 2024-11-07T00:25:35.000478Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317557Z) ← SCHEDULED (at 2024-11-07T00:25:35.000478Z)
Job id: 01930403-2418-702a-be68-c603dc155dc0
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681724Z) ← SCHEDULED (at 2024-11-07T00:25:35.000532Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317558Z) ← SCHEDULED (at 2024-11-07T00:25:35.000532Z)
Job id: 01930403-2418-702a-be68-c603dc155dc1
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681726Z) ← SCHEDULED (at 2024-11-07T00:25:35.000563Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317559Z) ← SCHEDULED (at 2024-11-07T00:25:35.000563Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 01930403-2417-792b-a37d-56f7bf46166d, 01930403-2418-702a-be68-c603dc155dbb, 01930403-2418-702a-be68-c603dc155dbc, 01930403-2418-702a-be68-c603dc155dbd, 01930403-2418-702a-be68-c603dc155dbe, 01930403-2418-702a-be68-c603dc155dbf, 01930403-2418-702a-be68-c603dc155dc0, 01930403-2418-702a-be68-c603dc155dc1

## Concurrent modified jobs:
Job id: 01930403-2417-792b-a37d-56f7bf46166d
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681707Z) ← SCHEDULED (at 2024-11-07T00:25:34.998708Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317541Z) ← SCHEDULED (at 2024-11-07T00:25:34.998708Z)
Job id: 01930403-2418-702a-be68-c603dc155dbb
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681716Z) ← SCHEDULED (at 2024-11-07T00:25:35.000191Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317554Z) ← SCHEDULED (at 2024-11-07T00:25:35.000191Z)
Job id: 01930403-2418-702a-be68-c603dc155dbc
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681718Z) ← SCHEDULED (at 2024-11-07T00:25:35.000243Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317555Z) ← SCHEDULED (at 2024-11-07T00:25:35.000243Z)
Job id: 01930403-2418-702a-be68-c603dc155dbd
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681719Z) ← SCHEDULED (at 2024-11-07T00:25:35.000406Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317556Z) ← SCHEDULED (at 2024-11-07T00:25:35.000406Z)
Job id: 01930403-2418-702a-be68-c603dc155dbe
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681721Z) ← SCHEDULED (at 2024-11-07T00:25:35.000442Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317557Z) ← SCHEDULED (at 2024-11-07T00:25:35.000442Z)
Job id: 01930403-2418-702a-be68-c603dc155dbf
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681723Z) ← SCHEDULED (at 2024-11-07T00:25:35.000478Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317557Z) ← SCHEDULED (at 2024-11-07T00:25:35.000478Z)
Job id: 01930403-2418-702a-be68-c603dc155dc0
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681724Z) ← SCHEDULED (at 2024-11-07T00:25:35.000532Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317558Z) ← SCHEDULED (at 2024-11-07T00:25:35.000532Z)
Job id: 01930403-2418-702a-be68-c603dc155dc1
	Job Name: Schedule Email Dispatch
	Job Signature: voze.worker.jobs.emails.ScheduleEmailDispatchHandler.run(voze.worker.jobs.emails.ScheduleEmailDispatchHandler$Request)
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2024-11-07T00:25:37.681726Z) ← SCHEDULED (at 2024-11-07T00:25:35.000563Z)
	Storage state: ENQUEUED (at 2024-11-07T00:25:35.317559Z) ← SCHEDULED (at 2024-11-07T00:25:35.000563Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 01930403-2417-792b-a37d-56f7bf46166d, 01930403-2418-702a-be68-c603dc155dbb, 01930403-2418-702a-be68-c603dc155dbc, 01930403-2418-702a-be68-c603dc155dbd, 01930403-2418-702a-be68-c603dc155dbe, 01930403-2418-702a-be68-c603dc155dbf, 01930403-2418-702a-be68-c603dc155dc0, 01930403-2418-702a-be68-c603dc155dc1
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 0, 0, 0, 0, 0, 0, 0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 17 more

```

**Comment by auloin** [comment]
Hi @minond, this issue is probably linked to the CpuAllocationNotification reported on the dashboard. Please look into that. Also, in the latest version (v7.3.1 and higher) the dashboard provides some tips to diagnose these exceptions.

**Comment by minond** [comment]
> Hi @minond, this issue is probably linked to the CpuAllocationNotification reported on the dashboard. Please look into that. Also, in the latest version (v7.3.1 and higher) the dashboard provides some tips to diagnose these exceptions.
> 
> Feel free to re-open, if your investigations conclude that JobRunr is the root cause.

I'll upgrade and check the CPU allocation issue. Thanks!
