### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by LorenzoPetraroli** [jobrunr/jobrunr#1156]
### Runtime information
- __Timestamp__: 2024-09-24T12:58:45.404350300Z
- __Location__: BackgroundJobServer 39e66e36-1e08-4afb-a6b3-022ac479c7d1
- __JobRunr Version__: 7.2.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.10
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 11c634bc-e8b0-4c6d-873a-ba31d2a7e6d0
(workerPoolSize: 16, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-24T10:19:50.306825Z, lastHeartbeat: 2024-09-24T12:58:39.308586Z)
- BackgroundJobServer id: 39e66e36-1e08-4afb-a6b3-022ac479c7d1
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2024-09-24T12:49:34.725354Z, lastHeartbeat: 2024-09-24T12:58:04.009369Z)

#### Concurrent modified jobs:
Job id: 0192241b-a9a6-72f4-a040-83f95286589f
	Job Name: Producer PEC
	Job Signature: it.parsec326.pi.email.service.ScheduledTaskService.producePecTasks()
	Local version: 3; Storage version: 5
	Local state: SUCCEEDED (at 2024-09-24T12:58:44.014494100Z) ← PROCESSING (updated at 2024-09-24T12:58:04.014370Z on BackgroundJobServer 39e66e36-1e08-4afb-a6b3-022ac479c7d1 and started at 2024-09-24T12:57:30.449465600Z) ← ENQUEUED (at 2024-09-24T12:57:25.687904088Z) ← SCHEDULED (at 2024-09-24T12:57:25.670150775Z)
	Storage state: ENQUEUED (at 2024-09-24T12:58:40.752958056Z) ← SCHEDULED (at 2024-09-24T12:58:37.808465006Z) ← FAILED (at 2024-09-24T12:58:37.796906202Z) ← PROCESSING (updated at 2024-09-24T12:57:30.449465600Z on BackgroundJobServer 39e66e36-1e08-4afb-a6b3-022ac479c7d1 and started at 2024-09-24T12:57:30.449465600Z) ← ENQUEUED (at 2024-09-24T12:57:25.687904088Z) ← SCHEDULED (at 2024-09-24T12:57:25.670150775Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.steward.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:17)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 0192241b-a9a6-72f4-a040-83f95286589f

## Concurrent modified jobs:
Job id: 0192241b-a9a6-72f4-a040-83f95286589f
	Job Name: Producer PEC
	Job Signature: it.parsec326.pi.email.service.ScheduledTaskService.producePecTasks()
	Local version: 3; Storage version: 5
	Local state: SUCCEEDED (at 2024-09-24T12:58:44.014494100Z) ← PROCESSING (updated at 2024-09-24T12:58:04.014370Z on BackgroundJobServer 39e66e36-1e08-4afb-a6b3-022ac479c7d1 and started at 2024-09-24T12:57:30.449465600Z) ← ENQUEUED (at 2024-09-24T12:57:25.687904088Z) ← SCHEDULED (at 2024-09-24T12:57:25.670150775Z)
	Storage state: ENQUEUED (at 2024-09-24T12:58:40.752958056Z) ← SCHEDULED (at 2024-09-24T12:58:37.808465006Z) ← FAILED (at 2024-09-24T12:58:37.796906202Z) ← PROCESSING (updated at 2024-09-24T12:57:30.449465600Z on BackgroundJobServer 39e66e36-1e08-4afb-a6b3-022ac479c7d1 and started at 2024-09-24T12:57:30.449465600Z) ← ENQUEUED (at 2024-09-24T12:57:25.687904088Z) ← SCHEDULED (at 2024-09-24T12:57:25.670150775Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 12 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 0192241b-a9a6-72f4-a040-83f95286589f
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 12 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 1, 1]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:21)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 15 more

```

**Comment by rdehuyss** [comment]
Closing due to not following [community guidelines](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D).

Please add more info to your github profile.
