### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by cengugr** [jobrunr/jobrunr#1162]
### Runtime information
- __Timestamp__: 2024-11-28T13:30:28.465262733Z
- __Location__: BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5
- __JobRunr Version__: 7.1.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 49754f72-5e6f-4402-8d11-a377d6a469c5
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2024-11-27T14:50:31.387336Z, lastHeartbeat: 2024-11-28T13:30:39.856670Z)

#### Concurrent modified jobs:
Job id: 019371ff-9d18-7622-a9f3-516fb662930e
	Job Name: IPSourceCheckJob
	Job Signature: com.livane.cronjob.job.IPSourceCheckJob.execute()
	Local version: 1065; Storage version: 1068
	Local state: SCHEDULED (at 2024-11-28T13:28:22.444533257Z) ← FAILED (at 2024-11-28T13:28:05.393486205Z) ← PROCESSING (updated at 2024-11-28T13:26:10.595784573Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T09:00:07.413868590Z) ← ENQUEUED (at 2024-11-28T08:59:57.616784817Z) ← SCHEDULED (at 2024-11-28T08:59:57.592476907Z)
	Storage state: ENQUEUED (at 2024-11-28T13:28:54.310624389Z) ← SCHEDULED (at 2024-11-28T13:27:42.800459260Z) ← FAILED (at 2024-11-28T13:27:40.469916141Z) ← PROCESSING (updated at 2024-11-28T13:26:43.856007681Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T09:00:07.413868590Z) ← ENQUEUED (at 2024-11-28T08:59:57.616784817Z) ← SCHEDULED (at 2024-11-28T08:59:57.592476907Z)
Job id: 019372db-267f-746d-862a-9268c01c1d62
	Job Name: DailyAlarmReportJob
	Job Signature: com.livane.cronjob.job.DailyAlarmReportJob.execute()
	Local version: 106; Storage version: 109
	Local state: SCHEDULED (at 2024-11-28T13:28:27.448529379Z) ← FAILED (at 2024-11-28T13:28:11.723276244Z) ← PROCESSING (updated at 2024-11-28T13:26:10.595789163Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T12:59:56.461751728Z) ← ENQUEUED (at 2024-11-28T12:59:45.162209071Z) ← SCHEDULED (at 2024-11-28T12:59:45.151427411Z)
	Storage state: PROCESSING (updated at 2024-11-28T13:29:15.336613572Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T12:59:56.461751728Z) ← ENQUEUED (at 2024-11-28T12:59:45.162209071Z) ← SCHEDULED (at 2024-11-28T12:59:45.151427411Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:69)
	at org.jobrunr.server.tasks.Task.convertAndProcessJobs(Task.java:55)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.convertAndProcessManyJobs(AbstractJobZooKeeperTask.java:30)
	at org.jobrunr.server.tasks.zookeeper.AbstractJobZooKeeperTask.processManyJobs(AbstractJobZooKeeperTask.java:23)
	at org.jobrunr.server.tasks.zookeeper.ProcessOrphanedJobsTask.runTask(ProcessOrphanedJobsTask.java:29)
	at org.jobrunr.server.tasks.Task.run(Task.java:43)
	at org.jobrunr.server.JobHandler.lambda$run$0(JobHandler.java:36)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobHandler.run(JobHandler.java:36)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 019371ff-9d18-7622-a9f3-516fb662930e, 019372db-267f-746d-862a-9268c01c1d62

## Concurrent modified jobs:
Job id: 019371ff-9d18-7622-a9f3-516fb662930e
	Job Name: IPSourceCheckJob
	Job Signature: com.livane.cronjob.job.IPSourceCheckJob.execute()
	Local version: 1065; Storage version: 1068
	Local state: SCHEDULED (at 2024-11-28T13:28:22.444533257Z) ← FAILED (at 2024-11-28T13:28:05.393486205Z) ← PROCESSING (updated at 2024-11-28T13:26:10.595784573Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T09:00:07.413868590Z) ← ENQUEUED (at 2024-11-28T08:59:57.616784817Z) ← SCHEDULED (at 2024-11-28T08:59:57.592476907Z)
	Storage state: ENQUEUED (at 2024-11-28T13:28:54.310624389Z) ← SCHEDULED (at 2024-11-28T13:27:42.800459260Z) ← FAILED (at 2024-11-28T13:27:40.469916141Z) ← PROCESSING (updated at 2024-11-28T13:26:43.856007681Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T09:00:07.413868590Z) ← ENQUEUED (at 2024-11-28T08:59:57.616784817Z) ← SCHEDULED (at 2024-11-28T08:59:57.592476907Z)
Job id: 019372db-267f-746d-862a-9268c01c1d62
	Job Name: DailyAlarmReportJob
	Job Signature: com.livane.cronjob.job.DailyAlarmReportJob.execute()
	Local version: 106; Storage version: 109
	Local state: SCHEDULED (at 2024-11-28T13:28:27.448529379Z) ← FAILED (at 2024-11-28T13:28:11.723276244Z) ← PROCESSING (updated at 2024-11-28T13:26:10.595789163Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T12:59:56.461751728Z) ← ENQUEUED (at 2024-11-28T12:59:45.162209071Z) ← SCHEDULED (at 2024-11-28T12:59:45.151427411Z)
	Storage state: PROCESSING (updated at 2024-11-28T13:29:15.336613572Z on BackgroundJobServer 49754f72-5e6f-4402-8d11-a377d6a469c5 and started at 2024-11-28T12:59:56.461751728Z) ← ENQUEUED (at 2024-11-28T12:59:45.162209071Z) ← SCHEDULED (at 2024-11-28T12:59:45.151427411Z)

	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:60)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:67)
	... 14 more
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 019371ff-9d18-7622-a9f3-516fb662930e, 019372db-267f-746d-862a-9268c01c1d62
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:119)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:202)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:114)
	at org.jobrunr.server.tasks.Task.saveAndRunJobFilters(Task.java:63)
	... 14 more
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0, 0]
	at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:183)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:198)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:112)
	... 17 more

```

**Comment by rdehuyss** [comment]
Closing due to not following [community guidelines](https://github.com/jobrunr/jobrunr/issues/new?assignees=&labels=&projects=&template=bug_template.yml&title=%5BBUG%5D) and not using the latest version.
