### ISSUE TITLE
[BUG] Jobrunr ignores connectionProvider in some cases

### ISSUE THREAD

**Issue by alexandraknopf-wk** [jobrunr/jobrunr#1166]
### JobRunr Version

7.3.2

### JDK Version

Oracle OpenJDK 17.0.9

### Your SQL / NoSQL database

Aurora MySQL 3.4.3

### What happened?

Jobrunr failed to start

### How to reproduce?

```kotlin
jobRequestScheduler = JobRunrPro.configure()
            // Provide this mapper so that we can use Kotlin data classes.
            .useJsonMapper(JacksonJsonMapper(jacksonObjectMapper()))
            .useStorageProvider(sp)
            .withJobFilter(DefaultRetryFilter(
                PerJobRetryPolicy(
                    ExponentialBackoffRetryPolicy(),
                    DoNotRetryPolicy.ifException { e -> e is RetryableException }
                )
            ))
            .useBackgroundJobServerIf(runAsServer) // false to only submit jobs
            .initialize()
            .jobRequestScheduler
```
```kotlin
MySqlStorageProvider(
                        dataSource,
                        "",
                        {
                            val connection = dataSource.connection
                            connection.setCatalog(schemaName)
                            connection
                        },
                        DatabaseOptions(false)
                    )
```

### Relevant log output

```shell
message: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
     stacktrace: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
 at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
 at org.jobrunr.storage.sql.common.DatabaseCreator$MigrationsTableLocker.waitUntilMigrationsAreDone(DatabaseCreator.java:407)
 at org.jobrunr.storage.sql.common.DatabaseCreator$MigrationsTableLocker.access$300(DatabaseCreator.java:344)
 at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrations(DatabaseCreator.java:164)
 at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrations(DatabaseCreator.java:120)
 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.setUpStorageProvider(DefaultSqlStorageProvider.java:89)
 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.<init>(DefaultSqlStorageProvider.java:74)
 at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.<init>(DefaultSqlStorageProvider.java:61)
 at org.jobrunr.storage.sql.mysql.MySqlStorageProvider.<init>(MySqlStorageProvider.java:35)
 at org.jobrunr.storage.sql.mysql.MySqlStorageProvider.<init>(MySqlStorageProvider.java:31)
 at org.jobrunr.storage.sql.mysql.MySqlStorageProvider.<init>(MySqlStorageProvider.java:27)
 at org.jobrunr.storage.sql.mysql.MySqlStorageProvider.<init>(MySqlStorageProvider.java:19)
 at com.workiva.graph.services.jobrunner.JobRunner.<init>(JobRunner.kt:19)
 at com.workiva.graph.Main.lambda$runJobRunner$7(Main.java:328)
 at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.SQLException: No database selected
 at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
 at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)
 at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:968)
 at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
 at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
 at org.jobrunr.storage.sql.common.DatabaseCreator$MigrationsTableLocker.isMigrationsTableLocked(DatabaseCreator.java:417)
 at org.jobrunr.storage.sql.common.DatabaseCreator$MigrationsTableLocker.waitUntilMigrationsAreDone(DatabaseCreator.java:400)
 ... 13 common frames omitted
```

**Comment by rdehuyss** [comment]
Hi @alexandraknopf-wk - I think this is unrelated to JobRunr but how you setup your connection. Your connection string is missing the table so hence this error (at least we cannot see this with the info you gave).

If you're sure you've configured everything correctly and still see the same error, can you create a small repo reproducing the issue? Once you have a reproducer, please comment on this issue or reopen it.

**Comment by rdehuyss** [comment]
Now I understand what you're talking about... The `ConnectionProvider` you're injecting was never meant to be used that way. It's to be used only by JobRunr internally and relates to transaction management.

JobRunr and JobRunr Pro have always expected to get a `DataSource` referencing the schema or database and what you're asking is currently not available in JobRunr / JobRunr Pro. 

We can add this as a feature to JobRunr Pro but we've done already quite some support and feature development for Workiva. If you'd like this feature implemented, please reach out to nicholas@jobrunr.io.

**Comment by rdehuyss** [comment]
I'm also moving this issue to Pro as it is related to JobRunr Pro.
