### ISSUE TITLE
[BUG] jobrunr does not start with cockroachdb

### ISSUE THREAD

**Issue by if6was9** [jobrunr/jobrunr#1175]
### JobRunr Version

7.3.2

### JDK Version

Amazon 21

### Your SQL / NoSQL database

CockroachDB 24.2.5

### What happened?

JobRunr is unable to initialize completely due to an autobox failure.

The column `jobrunr_backgroundjobservers.running` is defined as `int` which represents a boolean value.

However, the JDBC driver returns it as a java `Long` from ResultSet.getObject().

This code fails to interpret the `java.lang.Long` correctly:

https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/utils/reflection/autobox/BooleanTypeAutoboxer.java#L15-L21

https://github.com/jobrunr/jobrunr/blob/master/core/src/main/resources/org/jobrunr/storage/sql/db2/migrations/v003__create_background_job_server_table.sql#L8

NOTE: Changing the column type to `bool` appears to work around the issue.

### How to reproduce?

1) Create tables
2) Start jobrunr
3) Exception is thrown from this point:

https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/storage/sql/common/BackgroundJobServerTable.java#L75

### Relevant log output

```
00:14:22.343 [backgroundjob-zookeeper-pool-1-thread-1] ERROR org.jobrunr.server.ServerZooKeeper -- An unrecoverable error occurred. Shutting server down...
java.lang.UnsupportedOperationException: Cannot autobox 1 of type java.lang.Long to java.lang.Boolean
	at org.jobrunr.utils.reflection.autobox.BooleanTypeAutoboxer.autobox(BooleanTypeAutoboxer.java:22)
	at org.jobrunr.utils.reflection.autobox.BooleanTypeAutoboxer.autobox(BooleanTypeAutoboxer.java:7)
	at org.jobrunr.utils.reflection.autobox.Autoboxer.lambda$autobox$1(Autoboxer.java:37)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.jobrunr.utils.reflection.autobox.Autoboxer.autobox(Autoboxer.java:37)
	at org.jobrunr.utils.reflection.ReflectionUtils.autobox(ReflectionUtils.java:280)
	at org.jobrunr.storage.sql.common.db.SqlResultSet.asBoolean(SqlResultSet.java:29)
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$signalServerAlive$0(BackgroundJobServerTable.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:44)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.signalServerAlive(BackgroundJobServerTable.java:76)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java:98)
	at org.jobrunr.storage.ThreadSafeStorageProvider.signalBackgroundJobServerAlive(ThreadSafeStorageProvider.java:62)
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAlive(ServerZooKeeper.java:98)
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:82)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
00:14:22.350 [Thread-1] INFO  o.jobrunr.server.BackgroundJobServer -- BackgroundJobServer - stopping (may take about
```

**Comment by rdehuyss** [comment]
Hi Rob, I don't think we mention somewhere we support CockroachDB.

The supported databases are visible here in our [tests](https://github.com/jobrunr/jobrunr/tree/master/core/src/test/java/org/jobrunr/storage/sql).

I don't think we want to support any other DB in the open-source version, we try to support databases that are in the Top 10 in db-engines ranking.
