### ISSUE TITLE
org.jobrunr.scheduling.exceptions.JobClassNotFoundException

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#140]
**Describe the bug**
when the application restarts the app search for the job on a database which is not available as it,s name contains  hashcode

**Environment**
I'm using version 3.0.1
I'm running on JDK15, springboot
I'm using the following StorageProvider sql stroage

org.jobrunr.scheduling.exceptions.JobClassNotFoundException
org.jobrunr.scheduling.exceptions.JobClassNotFoundException: com.saudivts.mofa.bio.job.management.jobs.enrollment.SubmitEnrollmentJob$$EnhancerBySpringCGLIB$$4fce18f2.execute()
	at org.jobrunr.utils.JobUtils.getJobClass(JobUtils.java:41)
	at org.jobrunr.utils.JobUtils.getJobMethod(JobUtils.java:46)
	at org.jobrunr.utils.JobUtils.assertJobExists(JobUtils.java:55)
	at org.jobrunr.server.runner.BackgroundJobWithIocRunner.supports(BackgroundJobWithIocRunner.java:19)
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$0(BackgroundJobServer.java:168)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.jobrunr.server.BackgroundJobServer.getBackgroundJobRunner(BackgroundJobServer.java:169)
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:77)
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:38)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by rdehuyss** [comment]
This is already solved in release 3.1.0.

Please upgrade to the latest version.
