### ISSUE TITLE
[BUG] No servers available

### ISSUE THREAD

**Issue by dtrouillet** [jobrunr/jobrunr#141]
**Describe the bug**
Sometimes I have trouble with zookeeper. I have this stack trace :

**Environment**
I'm using version <your JobRunr version>
I'm running on JRE / JDK <your jre/jdk version> 
I'm using the following StorageProvider <your storageprovider> 

```2021-06-04 13:54:54.535  INFO 124807 --- [pool-2-thread-1] o.j.s.ServerZooKeeper                    : Removed 1 server(s) that timed out
2021-06-04 13:54:54.538 ERROR 124807 --- [pool-2-thread-1] o.j.s.ServerZooKeeper                    : An unrecoverable error occurred. Shutting server down...

org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:109) ~[jobrunr-3.0.1.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:109) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:92) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:63) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:98) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:73) ~[jobrunr-3.0.1.jar:?]
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:42) [jobrunr-3.0.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: No servers available?!
	... 15 more 
```

**To Reproduce**
I don't know how to reproduce this behaviour, I hava no other stacktrace in my log. This issue is encountered after several hours of up time

**Expected behavior**
Zookeeper not shutdown

**Additional context**
Indeed I have no hearthbeat after this exception. And I have only one server

**Comment by rdehuyss** [comment]
Can you provide me with the other requested info like JobRunr version and StorageProvider?

Also, what did you use as pollIntervalInSeconds?

**Comment by dtrouillet** [comment]
I use JobRunr 3.0.1 with Postgres and JobRunr's Spring Boot Starter(project is https://github.com/informatique-cdc/ebad/).

The pollIntervalInSeconds is 2 seconds.

**Comment by rdehuyss** [comment]
Can you change pollIntervalInSeconds to at least 5?

I'm thinking about putting 5 as a minimum.

**Comment by dtrouillet** [comment]
OK thanks for your advice. I try this monday and I tell you more.

**Comment by dtrouillet** [comment]
Hi @rdehuyss,

Seems to be OK. My server is up and running from 2 days without trouble.

Thanks ;)

**Comment by rdehuyss** [comment]
Hi @dtrouillet , great - thx for the feedback.

My gut feeling tells me that your Postgres server is under a lot of load. I tried to reproduce your issue (with pollIntervalInSeconds set to 2) on my local pc this weekend and was unable to break it, even when processing a lot of jobs.

One thing I'm considering is an option to enable collecting of anonymous data (how much time does the JobZookeeper take, ... ) and if you enable it, you would be able to compare it to data from other users. This way, you could immediately see that the time spent inside the Zookeeper run method is short or long. What do you think about this idea?

**Comment by dtrouillet** [comment]
I just looked at the resource usage history of my Postgres server and it is using very few resources. And it's been several weeks since I had an interval of 2 seconds without encountering any problems.

I think this is a good idea, unfortunately I am not allowed to share this kind of information as it is currently on a production environment in my company.

Besides, I have no errors on my other test environments.

Thank you very much for this help.
