### ISSUE TITLE
[BUG] SQL Server not compatible with Latin1_General_100_CI_AS_SC_UTF8 collation

### ISSUE THREAD

**Issue by abdo2011** [jobrunr/jobrunr#142]
**Describe the bug**

**Environment**
I'm using version 3.0.1
I'm running on JRE / JDK 15 
I'm using the following StorageProvider sqlserver 19

**To Reproduce**
set db encoding LATIN1_GENERAL_100_CI_AS_SC_UTF8 and restart the application.

the application start  will fail with exception:

Caused by: java.lang.IllegalStateException: Error running database migration v001__create_job_table.sql
	... 90 common frames omitted
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column or parameter 'jobAsJson' has type 'text' and collation 'Latin1_General_100_CI_AS_SC_UTF8'. The legacy LOB types do not support UTF-8 or UTF-16 encodings. Use types varchar(max), nvarchar(max) or a collation which does not have the _SC or _UTF8 flags.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:872) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:767) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:743) ~[mssql-jdbc-8.4.1.jre8.jar:na]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
	at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrationStatement(DatabaseCreator.java:113) ~[jobrunr-3.0.1.jar:na]
	at org.jobrunr.storage.sql.common.DatabaseCreator.runMigration(DatabaseCreator.java:95) ~[jobrunr-3.0.1.jar:na]
	... 89 common frames omitted
	Suppressed: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot invoke a rollback operation when the AutoCommit mode is set to "true".
		at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234) ~[mssql-jdbc-8.4.1.jre8.jar:na]
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.rollback(SQLServerConnection.java:3445) ~[mssql-jdbc-8.4.1.jre8.jar:na]
		at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396) ~[HikariCP-3.4.5.jar:na]
		at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java) ~[HikariCP-3.4.5.jar:na]
		at org.jobrunr.storage.sql.common.db.Transaction.close(Transaction.java:36) ~[jobrunr-3.0.1.jar:na]
		at org.jobrunr.storage.sql.common.DatabaseCreator.runMigration(DatabaseCreator.java:93) ~[jobrunr-3.0.1.jar:na]
		... 89 common frames omitted

-------------------
Thanks & Regards

**Comment by rdehuyss** [comment]
Should be solved in release 3.1.1. Please report back if this is not the case.
