### ISSUE TITLE
JobRunr: NoSuchBeanDefinitionException using Interface Bean instance 

### ISSUE THREAD

**Issue by douglas-pacheco** [jobrunr/jobrunr#145]
My test controller is able to enqueue the job execution , but the job is never actually executed.
The Background JobService is unable to find my interface bean. 

In Debug mode while trying to resolve my bean's name I can see my IoC containing all application beans, including one from the class implementing my interface

I've also tried sing a class reference instead of an interface one...same result.

Even so, I got the following exception

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'br.com.orderby.webservices.integracoes.services.ICadastradorOperacoes' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.1.jar:5.3.1]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1179) ~[spring-context-5.3.1.jar:5.3.1]
	at org.jobrunr.server.runner.BackgroundJobWithIocRunner.supports(BackgroundJobWithIocRunner.java:21) ~[jobrunr-1.1.0.jar:na]
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$0(BackgroundJobServer.java:133) ~[jobrunr-1.1.0.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[na:na]
	at org.jobrunr.server.BackgroundJobServer.getBackgroundJobRunner(BackgroundJobServer.java:134) ~[jobrunr-1.1.0.jar:na]
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:77) ~[jobrunr-1.1.0.jar:na]
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:38) ~[jobrunr-1.1.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

My Service Interface and Class :

package br.com.orderby.webservices.integracoes.services;

@Service("cadastradorOperacoes")

public interface ICadastradorOperacoes {

	void testeAgendamentoRotina(String a, String b);
}

package br.com.orderby.webservices.integracoes.services;

@Service("cadastradorOperacoes")

public class CadastradorOperacoes implements ICadastradorOperacoes{
	
	
	@Override
	public void testeAgendamentoRotina(String a, String b) {
		System.out.println("teste da rotina agendada pelo JobRunr imprime:" + " param" + a + "param"+ b);

	}
	
	
}

My Test Controller

package br.com.orderby.webservices.integracoes.controllers.internal;

@RestController

@RequestMapping(value="/teste")

public class TesteController {

	@Autowired
	private JobScheduler jobScheduler;
	
	@Autowired
	@Qualifier("cadastradorOperacoes")
	private ICadastradorOperacoes cadastradorOperacoes;

	@PostMapping("/online")
	public Object test() {
		
		
		jobScheduler.enqueue(() -> cadastradorOperacoes.testeAgendamentoRotina("1","2"));

		return null;

	}
}

My Configuration class

package br.com.orderby.webservices.integracoes.config;

public class JobRunrConfig {
	
	@Bean
	public StorageProvider storageProvider(ApplicationContext applicationContext) {
		return new DefaultSqlStorageProvider(applicationContext.getBean(DataSource.class), DatabaseOptions.SKIP_CREATE);
	}

	@Bean
	public JobActivator jobActivator(ApplicationContext applicationContext) {
		return applicationContext::getBean;
	}
	
	@Bean
	public BackgroundJobServerConfiguration confJobServer() {
		return BackgroundJobServerConfiguration
				.usingStandardBackgroundJobServerConfiguration()
				.andWorkerCount(4)
				.andDeleteSucceededJobsAfter(Duration.ofDays(1L))
				.andPermanentlyDeleteDeletedJobsAfter(Duration.ofDays(3L))
				.andPollIntervalInSeconds(20);
	}
	
	
	@Bean
	public BackgroundJobServer backgroundJobServer(StorageProvider storageProvider, JobActivator jobActivator, BackgroundJobServerConfiguration configuration) {
	    BackgroundJobServer backgroundJobServer = new BackgroundJobServer(storageProvider, jobActivator, configuration);
	    backgroundJobServer.start();
	    return backgroundJobServer;
	}
	
    @Bean
    public JobScheduler initJobRunr(JobActivator activator, BackgroundJobServer backgroundJobServer, DefaultSqlStorageProvider SQLServerProvider) {
        return JobRunr.configure()
        	    .useStorageProvider(SQLServerProvider)
                .useJobActivator(activator)
                .useBackgroundJobServer(backgroundJobServer)
        	    .useJmxExtensions()  
        	    .useDashboard(3685)
        	    .initialize();
    }
    

}

At last, my root class

package br.com.orderby.webservices.integracoes;

@SpringBootApplication

@Import(JobRunrConfig.class)

@ComponentScan({ "br.com.orderby.webservices.integracoes"})

public class IntegracoesApplication {

	public static void main(String[] args) {
		SpringApplication.run(IntegracoesApplication.class, args);
	}
	
}

**Comment by rdehuyss** [comment]
Hi @douglas-pacheco ,

first of all - thanks for your interest in JobRunr. Small tip - instead of copying all the code in the issue, could you create a small github repo reproducing your problem. I did that and it takes quite some time whereas when there is already an existing repo, I can just clone it and investigate. Also, please always try to create issues against the latest version of a library - you are still using JobRunr 1.1.0 whereas I've recently released version 3.1.1. The bug you are experiencing may already be solved in the newer version.

I tried to reproduce it (both with JobRunr 1.1.0 and JobRunr 3.1.1) but was unable to do so: see https://github.com/rdehuyss/jobrunr-145.

![image](https://user-images.githubusercontent.com/567842/121313531-c8284080-c906-11eb-917b-3f2eac5712b2.png)

Console output:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.4)

2021-06-09 09:34:34.890  INFO 1740005 --- [           main] b.c.o.w.i.IntegracoesApplication         : Starting IntegracoesApplication using Java 1.8.0_292 on rdehuyss-laptop with PID 1740005 (/home/ronald/Projects/Personal/Temp/jobrunr-145/target/classes started by ronald in /home/ronald/Projects/Personal/Temp/jobrunr-145)
2021-06-09 09:34:34.892  INFO 1740005 --- [           main] b.c.o.w.i.IntegracoesApplication         : No active profile set, falling back to default profiles: default
2021-06-09 09:34:35.404  INFO 1740005 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-06-09 09:34:35.408  INFO 1740005 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-06-09 09:34:35.408  INFO 1740005 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.44]
2021-06-09 09:34:35.433  INFO 1740005 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-06-09 09:34:35.433  INFO 1740005 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 515 ms
2021-06-09 09:34:35.471  INFO 1740005 --- [           main] j.s.t.ScheduledThreadPoolJobRunrExecutor : ThreadManager of type 'ScheduledThreadPool' started
2021-06-09 09:34:35.473  INFO 1740005 --- [pool-1-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer (7582f445-acdd-4390-9c7e-97c08aaf9be2) and 4 BackgroundJobPerformers started successfully
2021-06-09 09:34:35.474  INFO 1740005 --- [pool-1-thread-1] org.jobrunr.server.ServerZooKeeper       : Server 7582f445-acdd-4390-9c7e-97c08aaf9be2 is master (this BackgroundJobServer)
2021-06-09 09:34:35.482  INFO 1740005 --- [           main] o.j.dashboard.JobRunrDashboardWebServer  : JobRunr Dashboard started at http://localhost:3685/dashboard
2021-06-09 09:34:35.543  INFO 1740005 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-06-09 09:34:35.629  INFO 1740005 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2021-06-09 09:34:35.635  INFO 1740005 --- [           main] b.c.o.w.i.IntegracoesApplication         : Started IntegracoesApplication in 0.931 seconds (JVM running for 1.206)
2021-06-09 09:34:47.673  INFO 1740005 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-06-09 09:34:47.673  INFO 1740005 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-06-09 09:34:47.674  INFO 1740005 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
teste da rotina agendada pelo JobRunr imprime: param1param2
```
