### ISSUE TITLE
Instruction 100 not found

### ISSUE THREAD

**Issue by androoshk08** [jobrunr/jobrunr#148]
Hello,

I get an error **_"Caused by: java.lang.IllegalArgumentException: Instruction 100 not found"_** for which I cannot find the cause. Can you help with providing a link to documentation where these error codes are explained?  

The problem occurs at using method:  _**BackgroundJob.enqueue**_. I guess some parameter is not ok, but I cannot understand what is the problem from the stacktrace. 

This is the entire stacktrace:

```
2021-06-10 17:52:00.174 ERROR [reportservice:scheduling-1::] o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
	at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:61)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator$JobDetailsFinder$1.visitInsn(JobDetailsAsmGenerator.java:89)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2177)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1481)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:711)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.findJobDetailsInByteCode(JobDetailsAsmGenerator.java:46)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:26)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:80)
	at org.jobrunr.scheduling.BackgroundJob.enqueue(BackgroundJob.java:39)
	at io.finapi.reportservice.domain.services.report.TriggersJobRunner.startTriggersProcessing(TriggersJobRunner.java:55)
	at io.finapi.reportservice.domain.services.report.ContinuousReportScheduler.scheduleContinuousReports(ContinuousReportScheduler.java:39)
	at io.finapi.reportservice.domain.services.report.ContinuousReportScheduler$$FastClassBySpringCGLIB$$a5393188.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAspect.traceBackgroundThread(TraceSchedulingAspect.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at io.finapi.reportservice.domain.services.report.ContinuousReportScheduler$$EnhancerBySpringCGLIB$$1b98c1c4.scheduleContinuousReports(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Instruction 100 not found
	... 51 common frames omitted
```

**Comment by rdehuyss** [comment]
Can you show me how you enqueued/schedule a job?

**Comment by androoshk08** [comment]
After discussing with Ronald, I was able to understand the problem was that subtraction was done when calling the BackgroundJob.enqueue. 

This is the initial piece of code:
`final var enqueue = BackgroundJob.enqueue(
() -> sendTriggerEvents(triggers,
dtoConversionService.toAllReportsResourceDto(childReports.get(numberOfChildren - 2)),
dtoConversionService.toAllReportsResourceDto(childReports.get(numberOfChildren - 1)),
reportCC.getTriggerCallbackHandle(),
reportCC.getTriggerCallback()));`


I changed the code by passing a variable as parameter and do the substraction before calling the enqueue method. This did the trick. 
`final var previousReport = childReports.get(numberOfChildren - 2);
            final var latestReport = childReports.get(numberOfChildren - 1);
            final var enqueue = BackgroundJob.enqueue(
                    () -> sendTriggerEvents(triggers,
                            dtoConversionService.toAllReportsResourceDto(previousReport),
                            dtoConversionService.toAllReportsResourceDto(latestReport),
                            reportCC.getTriggerCallbackHandle(),
                            reportCC.getTriggerCallback()));`
