### ISSUE TITLE
[BUG] DeletedState cannot be cast to class ProcessingState

### ISSUE THREAD

**Issue by dtrouillet** [jobrunr/jobrunr#153]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
When I Delete Processing Job from Jobrunr Dashboard I have this stacktrace and my background server is shutdown. At the next start the Job is re-run>

```

2021-06-21 15:06:53.740 ERROR 46241 --- [pool-9-thread-2] o.j.s.JobZooKeeper : FATAL - JobRunr encountered too many processing exceptions. Shutting down.
--
&nbsp;
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-3.0.1.jar:?]
at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:92) [jobrunr-3.0.1.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassCastException: class org.jobrunr.jobs.states.DeletedState cannot be cast to class org.jobrunr.jobs.states.ProcessingState (org.jobrunr.jobs.states.DeletedState and org.jobrunr.jobs.states.ProcessingState are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @224b4d61)
at org.jobrunr.jobs.Job.updateProcessing(Job.java:125) ~[jobrunr-3.0.1.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:198) ~[jobrunr-3.0.1.jar:?]
at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:152) ~[jobrunr-3.0.1.jar:?]
at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:80) ~[jobrunr-3.0.1.jar:?]
... 6 more
&nbsp;
2021-06-21 15:07:13.747 INFO 46241 --- [pool-9-thread-2] o.j.s.BackgroundJobServer : BackgroundJobServer and BackgroundJobPerformers stopped
```

**Environment**
I'm using JobRunr version: 3.1.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): OpenJDK 1.11.0_6 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): PostgreSQL

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).

Run https://github.com/informatique-cdc/ebad then launch batch and delete the job from jobrunr dashboard

**Expected behavior**
The job is deleted without error

**Additional context**

**Comment by dtrouillet** [comment]
Bad version used... 3.0.1 instead of 3.1.2. Sorry.
But I don't  understand why deleted jobs list is order by date in asc instead of desc.

Sorry for this bug report
