### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by edherbs135** [jobrunr/jobrunr#166]
### Runtime information
- __Timestamp__: 2021-07-09T20:40:13.635179Z
- __Location__: BackgroundJobServer d8c1f7d5-d0c3-41e4-8ad4-5107f63208e0
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.InMemoryStorageProvider
- __Java Version__: 11.0.8
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: d8c1f7d5-d0c3-41e4-8ad4-5107f63208e0
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-07-08T21:51:27.548930Z, lastHeartbeat: 2021-07-09T20:40:12.626493Z)

#### Concurrent modified jobs:
Job id: 0067f129-24b0-455e-9e4d-739403ef230b
	Local version: 14; Storage version: 15
	Local state: PROCESSING; Storage state: ENQUEUED
	Local last updated: 2021-07-09T20:40:13.627790Z; Storage last updated: 2021-07-09T20:40:08.968432Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:206)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:152)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by rdehuyss** [comment]
Please update to the latest version. This issue is (normally) solved.
