### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by aperhaite-stylyze** [jobrunr/jobrunr#167]
### Runtime information
- __Timestamp__: 2021-04-14T14:15:42.012Z
- __Location__: BackgroundJobServer 9c4da44b-ede8-4c58-bcda-f080c6540b9f
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider
- __Java Version__: 1.8.0_45
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 9c4da44b-ede8-4c58-bcda-f080c6540b9f
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-04-14T13:03:40.011Z, lastHeartbeat: 2021-04-14T14:15:40.015Z)

#### Concurrent modified jobs:
Job id: 10bc5f73-3fb5-4133-ac7b-e034cb355cb5
	Local version: 6; Storage version: 8
	Local state: PROCESSING; Storage state: ENQUEUED
	Local last updated: 2021-04-14T14:15:42.009Z; Storage last updated: 2021-04-14T14:15:41.982Z

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:199)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:147)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by rdehuyss** [comment]
Please update to the latest version. This issue is (normally) solved. If you still encounter this after updating, you can reopen this issue.

Also, after updating JobRunr, please dismiss the issue.
