### ISSUE TITLE
[BUG]java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hxbb00** [jobrunr/jobrunr#19]
**Describe the bug**
`org.jobrunr.storage.AbstractStorageProvider` throw java.util.ConcurrentModificationException
```java
this.onChangeListeners.forEach((listener) -> {
                    listener.onChange(jobStats);
                });
```
maybe onChangeListeners has changed when do foreach?

**Environment**
I'm using version 0.9.7
I'm running on JRE / JDK 1.8

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```java
Exception in thread "Timer-0" java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.jobrunr.storage.AbstractStorageProvider.notifyOnChangeListeners(AbstractStorageProvider.java:61)
	at org.jobrunr.storage.AbstractStorageProvider$SendJobStatsUpdate.run(AbstractStorageProvider.java:67)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by rdehuyss** [comment]
Already fixed in dev branch: https://github.com/jobrunr/jobrunr/blob/issue15/core/src/main/java/org/jobrunr/storage/AbstractStorageProvider.java#L26

**Comment by hxbb00** [comment]
okay

**Comment by rdehuyss** [comment]
Let's keep it open until it is merged in master...
