### ISSUE TITLE
[BUG] Error logging is wrong in case of long GC

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#191]
**Are you running the latest version of JobRunr?**
Yes
**Describe the bug**
JobRunr reports it is restarting after a fatal exception:

```
2021-08-09 20:01:27,990419 ERROR [backgroundjob-zookeeper-pool-2-thread-1] o.j.s.ServerZooKeeper: An unrecoverable error occurred. Shutting server down...
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)
at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:112)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:112)
at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:124)
at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:63)
at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:90)
at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:65)
at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:38)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalStateException: No servers available?!
... 15 more
2021-08-09 20:01:29,460164 ERROR [backgroundjob-zookeeper-pool-2-thread-1] o.j.s.BackgroundJobServer: JobRunr BackgroundJobServer failed to start
2021-08-09 20:01:45,776334 INFO [Thread-5] o.j.s.BackgroundJobServer: BackgroundJobServer and BackgroundJobPerformers stopped
2021-08-09 20:01:45,776793 INFO [backgroundjob-zookeeper-pool-2-thread-1] o.j.s.BackgroundJobServer: JobRunr BackgroundJobServer (772b0173-bde0-41b1-835e-7986da32aa0b) and 1 BackgroundJobPerformers started successfully
2021-08-09 20:01:45,777089 INFO [backgroundjob-zookeeper-pool-2-thread-1] o.j.s.ServerZooKeeper: Server 772b0173-bde0-41b1-835e-7986da32aa0b is master (this BackgroundJobServer)
```

**Environment**
I'm using JobRunr version: 3.2.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 1.8
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Does not matter

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
@SpringJUnitConfig
@SpringBootTest
@ActiveProfiles(profiles = "test")
@Slf4j
@Tag("integration")
public class JobRunrStopTheWorldTest {

    @Autowired
    private LogService logService;

    @Autowired
    private JobScheduler jobScheduler;

    @Test
    public void test() throws InterruptedException {

        log.info("Scheduling job 1");
        jobScheduler.enqueue(() -> logService.log("1"));
        log.info("Letting job 1 execute");
        Thread.sleep(2000);

        log.info("Scheduling job 2");
        jobScheduler.enqueue(() -> logService.log("2"));
        log.info("Stopping the world");
        stopTheWorld(15000);
        stopTheWorld(15000);

        log.info("Letting JobRunr to recover after stop the world");
        Thread.sleep(10000);
        log.info("Scheduling job 3");
        jobScheduler.enqueue(() -> logService.log("3"));

        log.info("Final wait");
        Thread.sleep(120000);
        log.info("Exiting");
    }

    public static void stopTheWorld(long millis) {
        long timestamp = System.currentTimeMillis();
        while (timestamp + millis > System.currentTimeMillis()) {
            System.gc();
        }
    }
}
```

**Expected behavior**
I expect correct logging

**Additional context**
Caused by a full GC which took 23 sec

**Comment by rdehuyss** [comment]
Fixed with commit f73dfd2b0178ccbf77b9837ab9924b5548584333
