### ISSUE TITLE
[BUG] Full GC of more than 20 sec causes JobRunr to stop

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#192]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
A full GC of more than 20 sec causes JobRunr to stop in case the pollIntervalInSeconds = 5

```
2021-08-09 20:01:27,990419 ERROR [backgroundjob-zookeeper-pool-2-thread-1] o.j.s.ServerZooKeeper: An unrecoverable error occurred. Shutting server down...
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)
at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:112)
at java.base/java.util.Optional.orElseThrow(Optional.java:403)
at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:112)
at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:124)
at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:63)
at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:90)
at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:65)
at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:38)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IllegalStateException: No servers available?!
... 15 more

```

**Environment**
I'm using JobRunr version: 3.2.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 1.8
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Does not matter

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
@SpringJUnitConfig
@SpringBootTest
@ActiveProfiles(profiles = "test")
@Slf4j
@Tag("integration")
public class JobRunrStopTheWorldTest {

    @Autowired
    private LogService logService;

    @Autowired
    private JobScheduler jobScheduler;

    @Test
    public void test() throws InterruptedException {

        log.info("Scheduling job 1");
        jobScheduler.enqueue(() -> logService.log("1"));
        log.info("Letting job 1 execute");
        Thread.sleep(2000);

        log.info("Scheduling job 2");
        jobScheduler.enqueue(() -> logService.log("2"));
        log.info("Stopping the world");
        stopTheWorld(15000);
        stopTheWorld(15000);

        log.info("Letting JobRunr to recover after stop the world");
        Thread.sleep(10000);
        log.info("Scheduling job 3");
        jobScheduler.enqueue(() -> logService.log("3"));

        log.info("Final wait");
        Thread.sleep(120000);
        log.info("Exiting");
    }

    public static void stopTheWorld(long millis) {
        long timestamp = System.currentTimeMillis();
        while (timestamp + millis > System.currentTimeMillis()) {
            System.gc();
        }
    }
}
```

**Expected behavior**
JobRunr continues to work

**Comment by rdehuyss** [comment]
Solved with commit 0fbf20a96a46c8f2b43d91fca1146b62f1e9f021
