### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by davis-ching** [jobrunr/jobrunr#216]
### Runtime information
- __Timestamp__: 2021-09-02T06:20:54.990019Z
- __Location__: BackgroundJobServer 0e849acb-3c26-4cb0-983b-3fd58d638e8a
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 0e849acb-3c26-4cb0-983b-3fd58d638e8a
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-09-02T06:11:23.937Z, lastHeartbeat: 2021-09-02T06:20:53.938Z)

#### Concurrent modified jobs:
Job id: fb6746d9-3182-47fd-a4a5-f7c6fc8b663d
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2021-09-02T06:20:54.961580Z) ← SCHEDULED (at 2021-09-02T06:20:24.941382Z)
	Storage state: ENQUEUED (at 2021-09-02T06:20:54.949857Z) ← SCHEDULED (at 2021-09-02T06:20:24.941382Z)
Job id: 7979ce56-829f-440b-ab53-e68c7d70193d
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2021-09-02T06:20:54.961581Z) ← SCHEDULED (at 2021-09-02T06:20:24.944446Z)
	Storage state: ENQUEUED (at 2021-09-02T06:20:54.949863Z) ← SCHEDULED (at 2021-09-02T06:20:24.944446Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:113)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2021-08-30T06:19:50.441889Z
- __Location__: BackgroundJobServer 507ddaae-52a7-49d7-906b-dd3aed1c5311
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 507ddaae-52a7-49d7-906b-dd3aed1c5311
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-08-30T06:19:48.699Z, lastHeartbeat: 2021-08-30T06:19:48.700Z)

#### Concurrent modified jobs:
Job id: 10ce4723-587a-47bc-ab93-90464146cedd
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332267Z) ← SUCCEEDED (at 2021-08-24T08:29:48.746948Z) ← PROCESSING (at 2021-08-24T08:29:48.616801Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165575Z) ← SUCCEEDED (at 2021-08-24T08:29:48.746948Z) ← PROCESSING (at 2021-08-24T08:29:48.616801Z)
Job id: d4043e5b-c8b8-452d-a737-71190d40b9a6
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332269Z) ← SUCCEEDED (at 2021-08-24T08:45:03.722725Z) ← PROCESSING (at 2021-08-24T08:45:03.602275Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165576Z) ← SUCCEEDED (at 2021-08-24T08:45:03.722725Z) ← PROCESSING (at 2021-08-24T08:45:03.602275Z)
Job id: 090f1c8d-bfe2-4a51-89fe-e31c9f8076f9
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332270Z) ← SUCCEEDED (at 2021-08-24T08:59:48.755950Z) ← PROCESSING (at 2021-08-24T08:59:48.610328Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165577Z) ← SUCCEEDED (at 2021-08-24T08:59:48.755950Z) ← PROCESSING (at 2021-08-24T08:59:48.610328Z)
Job id: 5154ffc9-b40a-4321-9d67-c411dc2afe21
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332271Z) ← SUCCEEDED (at 2021-08-24T09:14:48.663251Z) ← PROCESSING (at 2021-08-24T09:14:48.610165Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165578Z) ← SUCCEEDED (at 2021-08-24T09:14:48.663251Z) ← PROCESSING (at 2021-08-24T09:14:48.610165Z)
Job id: b2d41917-9508-43a4-9f27-21f770c01024
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332272Z) ← SUCCEEDED (at 2021-08-24T09:30:03.742987Z) ← PROCESSING (at 2021-08-24T09:30:03.601551Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165579Z) ← SUCCEEDED (at 2021-08-24T09:30:03.742987Z) ← PROCESSING (at 2021-08-24T09:30:03.601551Z)
Job id: 00435246-7f9a-492d-845e-effd7928dea9
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332274Z) ← SUCCEEDED (at 2021-08-24T09:45:03.835621Z) ← PROCESSING (at 2021-08-24T09:45:03.615733Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165580Z) ← SUCCEEDED (at 2021-08-24T09:45:03.835621Z) ← PROCESSING (at 2021-08-24T09:45:03.615733Z)
Job id: f71a1c6e-1d6f-44bb-a610-004ee15655bb
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332275Z) ← SUCCEEDED (at 2021-08-24T09:59:48.767405Z) ← PROCESSING (at 2021-08-24T09:59:48.611484Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165581Z) ← SUCCEEDED (at 2021-08-24T09:59:48.767405Z) ← PROCESSING (at 2021-08-24T09:59:48.611484Z)
Job id: 1c0e4cd7-c9a9-49d3-ab5d-e1164054319e
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332276Z) ← SUCCEEDED (at 2021-08-24T10:15:03.746503Z) ← PROCESSING (at 2021-08-24T10:15:03.600696Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165582Z) ← SUCCEEDED (at 2021-08-24T10:15:03.746503Z) ← PROCESSING (at 2021-08-24T10:15:03.600696Z)
Job id: 0febcb72-111e-4349-8406-d2dde756e936
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332276Z) ← SUCCEEDED (at 2021-08-24T10:29:48.737613Z) ← PROCESSING (at 2021-08-24T10:29:48.605200Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165583Z) ← SUCCEEDED (at 2021-08-24T10:29:48.737613Z) ← PROCESSING (at 2021-08-24T10:29:48.605200Z)
Job id: 6c9ab840-bc83-4565-9ee7-e4aec336027e
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332277Z) ← SUCCEEDED (at 2021-08-24T10:44:48.744132Z) ← PROCESSING (at 2021-08-24T10:44:48.606017Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165584Z) ← SUCCEEDED (at 2021-08-24T10:44:48.744132Z) ← PROCESSING (at 2021-08-24T10:44:48.606017Z)
Job id: 3ccb5e29-66b5-473f-bb2a-e17b74027ed8
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2021-08-30T06:19:50.332278Z) ← SUCCEEDED (at 2021-08-24T11:00:03.708917Z) ← PROCESSING (at 2021-08-24T11:00:03.602114Z)
	Storage state: DELETED (at 2021-08-30T06:19:50.165585Z) ← SUCCEEDED (at 2021-08-24T11:00:03.708917Z) ← PROCESSING (at 2021-08-24T11:00:03.602114Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:129)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:95)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2021-08-24T11:14:48.602860Z
- __Location__: BackgroundJobServer 54c99c8c-3feb-4a55-bbf0-075ec2abc020
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 54c99c8c-3feb-4a55-bbf0-075ec2abc020
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-08-24T07:28:32.586Z, lastHeartbeat: 2021-08-24T11:14:47.587Z)

#### Concurrent modified jobs:
Job id: dbc05fd2-29e3-4a8f-bd51-bc55219b8a24
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2021-08-24T11:14:48.598305Z) ← SCHEDULED (at 2021-08-24T11:14:03.592293Z)
	Storage state: ENQUEUED (at 2021-08-24T11:14:48.594280Z) ← SCHEDULED (at 2021-08-24T11:14:03.592293Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:113)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2021-08-30T08:24:46.850833Z
- __Location__: BackgroundJobServer 8024ba73-194f-4d7d-b26d-85879db3d7b1
- __JobRunr Version__: Unable to determine version
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 8024ba73-194f-4d7d-b26d-85879db3d7b1
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2021-08-30T07:56:15.822Z, lastHeartbeat: 2021-08-30T08:24:45.823Z)

#### Concurrent modified jobs:
Job id: 9f4eef80-f5bb-4459-b7aa-83537812d0eb
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2021-08-30T08:24:46.841180Z) ← SCHEDULED (at 2021-08-30T08:24:16.830111Z)
	Storage state: ENQUEUED (at 2021-08-30T08:24:46.833923Z) ← SCHEDULED (at 2021-08-30T08:24:16.830111Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:113)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by rdehuyss** [comment]
Which version of JobRunr are you using?

**Comment by davis-ching** [comment]
> Which version of JobRunr are you using?

		<dependency>
			<groupId>org.jobrunr</groupId>
			<artifactId>jobrunr-spring-boot-starter</artifactId>
			<version>3.2.1</version>
		</dependency>

**Comment by rdehuyss** [comment]
Is your MongoDB clustered/sharded? Are you running multiple instances?

**Comment by davis-ching** [comment]
> Is your MongoDB clustered/sharded? Are you running multiple instances?

MongoDB is clustered. I'm running it on Kubernetes. But only one pod (instance) running.

**Comment by rdehuyss** [comment]
How do you construct your MongoDBStorageProvider / MongoClient?

**Comment by davis-ching** [comment]
> How do you construct your MongoDBStorageProvider / MongoClient?

I use obrunr-spring-boot-starter's out-of-the-box configuration and spring-boot-starter-data-mongodb for mongo connection with the instruction on https://www.jobrunr.io/en/documentation/configuration/spring/.

**Comment by rdehuyss** [comment]
Ok - reason is here: https://stackoverflow.com/questions/57351910/why-does-spring-data-mongodb-1-10-not-support-readconcern-option

More info here: https://docs.mongodb.com/manual/core/read-isolation-consistency-recency/#real-time-order
