### ISSUE TITLE
[BUG] JobRunrException.shouldNotHappenException : Direct self-reference leading to cycle

### ISSUE THREAD

**Issue by levinanton** [jobrunr/jobrunr#217]
**Are you running the latest version of JobRunr?**

Yes

**Describe the bug**

Hitting `org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)` where stacktrace suggest opening a bug ticket: 
>JobRunr encountered a problematic exception. Please create a bug report

Full stacktrace below:

```
2021-09-03 10:45:19.940  WARN 95625 --- [pool-1-thread-2] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.serialize(JacksonJsonMapper.java:41) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.jobs.mappers.JobMapper.serializeJob(JobMapper.java:16) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.storage.InMemoryStorageProvider.deepClone(InMemoryStorageProvider.java:313) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.storage.InMemoryStorageProvider.saveJob(InMemoryStorageProvider.java:326) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.storage.InMemoryStorageProvider.save(InMemoryStorageProvider.java:162) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:94) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.server.BackgroundJobServer.scheduleJob(BackgroundJobServer.java:204) ~[jobrunr-3.2.1.jar:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_202]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_202]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_202]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_202]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_202]
	at org.jobrunr.server.JobZooKeeper.processRecurringJobs(JobZooKeeper.java:177) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.server.JobZooKeeper.checkForRecurringJobs(JobZooKeeper.java:107) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:92) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75) ~[jobrunr-3.2.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_202]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:836) [na:1.8.0_202]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.jobrunr.jobs.Job["jobDetails"]->org.jobrunr.jobs.JobDetails["jobParameters"]->java.util.ArrayList[0]->self.ref.HttpClient["restTemplate"]->org.springframework.web.client.RestTemplate["messageConverters"]->java.util.ArrayList[3]->org.springframework.http.converter.xml.SourceHttpMessageConverter["transformerFactory"]->com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl["_errorListener"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1277) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:945) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:722) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:640) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:730) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:640) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:147) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:25) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serializeWithType(AsArraySerializerBase.java:260) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:730) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3058) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388) ~[jackson-core-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1838) ~[jackson-core-2.11.4.jar:2.11.4]
	at org.jobrunr.utils.mapper.jackson.modules.JobParameterSerializer.serialize(JobParameterSerializer.java:21) ~[jobrunr-3.2.1.jar:na]
	at org.jobrunr.utils.mapper.jackson.modules.JobParameterSerializer.serialize(JobParameterSerializer.java:10) ~[jobrunr-3.2.1.jar:na]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:755) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4409) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3663) ~[jackson-databind-2.11.4.jar:2.11.4]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.serialize(JacksonJsonMapper.java:39) ~[jobrunr-3.2.1.jar:na]
	... 26 common frames omitted
```

**Environment**

I'm using JobRunr version: `3.2.1`
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): `JDK 1.8.0_201`
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): `org.jobrunr.storage.InMemoryStorageProvider`

**How to Reproduce**

* Clone https://github.com/levinanton/jobrunr-self-ref-reproducer
* Execute `mvn spring-boot:run`

Job is scheduled here https://github.com/levinanton/jobrunr-self-ref-reproducer/blob/main/src/main/java/self/ref/Startup.java#L30
Job itself is here https://github.com/levinanton/jobrunr-self-ref-reproducer/blob/main/src/main/java/self/ref/JobExecutor.java#L10

**Expected behavior**

No `com.fasterxml.jackson.databind.exc.InvalidDefinitionException` is thrown.

**Additional context**

-

**Comment by rdehuyss** [comment]
This part of the exception says it all - your parameters are not serializable: 
`Direct self-reference leading to cycle (through reference chain: org.jobrunr.jobs.Job["jobDetails"]->org.jobrunr.jobs.JobDetails["jobParameters"]->java.util.ArrayList[0]->self.ref.HttpClient["restTemplate"]->org.springframework.web.client.RestTemplate["messageConverters"]->java.util.ArrayList[3]->org.springframework.http.converter.xml.SourceHttpMessageConverter["transformerFactory"]->com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl["_errorListener"])`

Instead of passing your httpClient as a parameter, just have it injected (via `@Autowired` or via constructor injection) in the `JobExecutor`.

See also the best practices page on [jobrunr.io](https://www.jobrunr.io).
