### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by theexiile1305** [jobrunr/jobrunr#229]
### Runtime information
- __Timestamp__: 2021-09-17T07:13:50.996925Z
- __Location__: BackgroundJobServer 6e0cbb8e-cdb1-4a10-b8fa-ca13e3d8e6c5
- __JobRunr Version__: 3.2.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 11.0.11
- __Is running from nested jar__: false

### Background Job Servers
No items available

#### Concurrent modified jobs:
Job id: fda4c6f9-3135-42e6-85ce-8831f932bf06
	Local version: 4; Storage version: 5
	Local state: FAILED (at 2021-09-17T07:13:50.912289Z) ← PROCESSING (at 2021-09-17T07:12:39.868323Z) ← ENQUEUED (at 2021-09-16T16:00:00.325260Z)
	Storage state: SUCCEEDED (at 2021-09-17T07:13:03.325458Z) ← PROCESSING (at 2021-09-17T07:12:39.868323Z) ← ENQUEUED (at 2021-09-16T16:00:00.325260Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForOrphanedJobs(JobZooKeeper.java:120)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:94)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment]
Several fixes were done for this in JobRunr 4.0.0. Please upgrade to the latest version.
