### ISSUE TITLE
[BUG] Unknown INVOKESPECIAL instruction: <method name>

### ISSUE THREAD

**Issue by AlexDenisov** [jobrunr/jobrunr#23]
**Describe the bug**

I'm trying to schedule a job, but hitting the following exception:

```
Caused by: java.lang.IllegalStateException: Unknown INVOKESPECIAL instruction: javaTarJob
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:32) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.instructions.InvokeSpecialInstruction.invokeInstruction(InvokeSpecialInstruction.java:27) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.instructions.AbstractJVMInstruction.invokeInstructionAndPushOnStack(AbstractJVMInstruction.java:16) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.JobDetailsFinderContext.invokeInstructions(JobDetailsFinderContext.java:78) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.JobDetailsFinderContext.getJobDetails(JobDetailsFinderContext.java:71) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator$JobDetailsFinder.getJobDetails(JobDetailsAsmGenerator.java:135) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.findJobDetailsInByteCode(JobDetailsAsmGenerator.java:59) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:38) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:81) ~[jobrunr-0.9.11.jar:?]
	at org.jobrunr.scheduling.BackgroundJob.enqueue(BackgroundJob.java:41) ~[jobrunr-0.9.11.jar:?]
	at jobs.JobService.analyzeJavaTar(JobService.scala:12) ~[?:?]
```

The `JobService.scala` looks like this:

```scala
class JobService {
  def analyzeJavaTar(tarPath: String): UUID = {
    BackgroundJob.enqueue(() => javaTarJob(JobContext.Null, tarPath)).asUUID
  }

  private def javaTarJob(ctx: JobContext, tarPath: String): Unit = {
    /// omitted
  }
}
```

**Environment**

I'm using version 0.9.11.
I'm running on JRE / JDK adoptopenjdk-13.jdk on macOS.

**To Reproduce**

The snippet causing the issue is above. Here is the initialization code:

```scala
  val dataSource = new SQLiteDataSource
  dataSource.setUrl("jdbc:sqlite:/tmp/annotation-server.sqlite")
  val storageProvider = new DefaultSqlStorageProvider(dataSource)

  JobRunr.configure()
    .useStorageProvider(storageProvider)
    .useDefaultBackgroundJobServer()
    .useDashboard()
    .initialize()
```

**Expected behavior**

I expect the job to be scheduled :)

**Additional context**

I'm using JobRunr as part of the PlayFramework app written in Scala.

**Comment by rdehuyss** [comment]
This is probably because you are using Scala. They compile their lambda's to a different format than standard Java. I'll look into it but this may be very difficult to solve. Kotlin suffers from the same problem.

**Comment by AlexDenisov** [comment]
Making `javaTarJob` non-private solves the problem, so I guess I can close this issue.

**Comment by rdehuyss** [comment]
Ok, glad to hear!
