### ISSUE TITLE
[BUG] Enqueue JobRequest not working with Kotlin 1.5

### ISSUE THREAD

**Issue by tedliang** [jobrunr/jobrunr#238]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
Enqueue JobRequest not working with Kotlin 1.5

**Environment**
I'm using JobRunr version: 4.0.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk 11.0.9.1
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): InMemoryStorageProvider
**How to Reproduce**
Run the JobRequestSchedulerTest (see below) will get the following error:
```
Did you register all necessary Jackson Modules?
org.jobrunr.JobRunrException: Did you register all necessary Jackson Modules?
	at app//org.jobrunr.JobRunrException.configurationException(JobRunrException.java:61)
	at app//org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:66)
	at app//org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
	at app//org.jobrunr.storage.InMemoryStorageProvider.deepClone(InMemoryStorageProvider.java:300)
	at app//org.jobrunr.storage.InMemoryStorageProvider.saveJob(InMemoryStorageProvider.java:312)
	at app//org.jobrunr.storage.InMemoryStorageProvider.save(InMemoryStorageProvider.java:149)
	at app//org.jobrunr.storage.StorageProviderForTest.save(StorageProviderForTest.java:98)
	at app//org.jobrunr.scheduling.AbstractJobScheduler.saveJob(AbstractJobScheduler.java:133)
	at app//org.jobrunr.scheduling.AbstractJobScheduler.enqueue(AbstractJobScheduler.java:115)
	at app//org.jobrunr.scheduling.JobRequestScheduler.enqueue(JobRequestScheduler.java:77)
	at app//org.jobrunr.scheduling.JobRequestScheduler.enqueue(JobRequestScheduler.java:60)
	at app//org.jobrunr.scheduling.BackgroundJobRequest.enqueue(BackgroundJobRequest.java:38)
	at app//org.jobrunr.scheduling.JobRequestSchedulerTest.test enqueue JobRequest(JobRequestSchedulerTest.kt:51)
```

**Expected behavior**
Pass the test

**Additional context**
jackson-module-kotlin is required

language-support/jobrunr-kotlin-15-support/src/test/kotlin/org/jobrunr/scheduling/JobRequestSchedulerTest.kt
```
package org.jobrunr.scheduling

import org.assertj.core.api.Assertions.assertThat
import org.awaitility.Awaitility.await
import org.awaitility.Durations.TEN_SECONDS
import org.jobrunr.configuration.JobRunr
import org.jobrunr.jobs.annotations.Job
import org.jobrunr.jobs.lambdas.JobRequest
import org.jobrunr.jobs.lambdas.JobRequestHandler
import org.jobrunr.jobs.states.StateName.*
import org.jobrunr.server.BackgroundJobServerConfiguration.usingStandardBackgroundJobServerConfiguration
import org.jobrunr.storage.InMemoryStorageProvider
import org.jobrunr.storage.StorageProviderForTest
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class JobRequestSchedulerTest {

    private lateinit var storageProvider: StorageProviderForTest

    @BeforeEach
    fun setUp() {
        storageProvider = StorageProviderForTest(InMemoryStorageProvider())
        JobRunr.configure()
            .useStorageProvider(storageProvider)
            .useBackgroundJobServer(
                usingStandardBackgroundJobServerConfiguration().andPollIntervalInSeconds(5)
            )
            .initialize()
    }

    @AfterEach
    fun cleanUp() {
        JobRunr.destroy()
    }

    class KotlinJobRequest(val input: String) : JobRequest {
        override fun getJobRequestHandler() = KotlinJobRequestHandler::class.java
    }

    class KotlinJobRequestHandler : JobRequestHandler<KotlinJobRequest> {
        @Job(name = "Some neat Job Display Name", retries = 2)
        override fun run(jobRequest: KotlinJobRequest) {
            println("Running simple job request in background: " + jobRequest.input)
        }
    }

    @Test
    fun `test enqueue JobRequest`() {
        val jobId = BackgroundJobRequest.enqueue(KotlinJobRequest("some input"))

        await().atMost(TEN_SECONDS).until {
            storageProvider.getJobById(jobId).state == SUCCEEDED
        }

        val job = storageProvider.getJobById(jobId)
        assertThat(job.jobStates.map { it.name }).containsExactly(
            ENQUEUED, PROCESSING, SUCCEEDED
        )
    }
}
```

**Comment by tedliang** [comment]
Possible solution: #237 and add dependency jackson-module-kotlin
