### ISSUE TITLE
[BUG] Potential daylight savings bug - Background server times out and does not restart

### ISSUE THREAD

**Issue by LabaBL** [jobrunr/jobrunr#248]
**Are you running the latest version of JobRunr?**
This occurred in two of our applications, one running 3.2.1 and one running 4.0.1.

**Describe the bug**
At the moment of daylight savings change, when the clock went from 03:00 -> 02:00, Jobrunr noted that the background server timed out and threw and unrecoverable error: "An unrecoverable error occurred. Shutting server down..."
The poll interval for both servers is set to the default 5 seconds, and based on this I note that it is the first polling attempt after the time change that causes the error. (See stacktrace below).
After the error was thrown the background server failed to restart, and an application restart was required to start a working Backgroundserver once again.

Is it possible that the logic responsible for detecting server timeouts does not take into account the change to winter daylight savings time? I did not encounter a similar problem in the spring at the summer daylight savings change.

**Environment**
I'm using JobRunr version: 3.2.1 / 4.0.1.
I'm running on JRE / JDK: "openjdk 14.0.2 2020-07-14"
I'm using the following StorageProvider: MySQLStorageProvider

**Expected behavior**
Nothing happens at the moment of daylight savings change, and everything keeps executing as expected.

**Stacktrace**
```
2021-10-31 02:10:38,657 INFO {Redacted log line, inserted for time reference}
2021-10-31 02:41:03,845 INFO {Redacted log line, inserted for time reference}
2021-10-31 02:00:04,739 INFO org.jobrunr.server.ServerZooKeeper [backgroundjob-zookeeper-pool-2-thread-1] Removed 1 server(s) that timed out
2021-10-31 02:00:04,745 ERROR org.jobrunr.server.ServerZooKeeper [backgroundjob-zookeeper-pool-2-thread-1] An unrecoverable error occurred. Shutting server down...
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)
        at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:112)
        at java.base/java.util.Optional.orElseThrow(Optional.java:401)
        at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:112)
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:124)
        at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:63)
        at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:90)
        at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:65)
        at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:38)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: No servers available?!
        ... 15 common frames omitted
2021-10-31 02:00:04,761 ERROR org.jobrunr.server.BackgroundJobServer [backgroundjob-zookeeper-pool-2-thread-1] JobRunr BackgroundJobServer failed to start
2021-10-31 02:00:04,797 INFO org.jobrunr.server.BackgroundJobServer [Thread-191] BackgroundJobServer and BackgroundJobPerformers stopped
```

**Comment by rdehuyss** [comment]
Yes, I think you are correct. Will need to think about how to since this elegantly. 

At least I have about six months time to find a good fix 😅.

**Comment by LabaBL** [comment]
Thanks for your quick response!
Please let me know if you need any further information.

**Comment by rdehuyss** [comment]
Hi @LabaBL , this is related to MySQL. See also https://stackoverflow.com/questions/1646171/mysql-datetime-fields-and-daylight-savings-time-how-do-i-reference-the-extra

**Comment by rdehuyss** [comment]
Ok, looked into this and closing it as I don't think it's JobRunr's responsibility to fix this.

The fix is making sure the JDBC connection string is correct.

```
jdbc:mysql://localhost:3306/yourdatabaase?serverTimezone=UTC&useLegacyDatetimeCode=false
```

Even Baeldung has [an article about it](https://www.baeldung.com/mysql-jdbc-timezone-spring-boot) :smiling_face_with_tear:

**Comment by LabaBL** [comment]
Hi @rdehuyss 
Thank you for the response.

However, I have difficulties understanding how your suggestion would fix the problem, as:
- We already specify a "serverTimezone" in our connection string, specifically "Europe/Copenhagen". 
- "useLegacyDatetimeCode" is a legacy property that was dropped between connector 5.1 to 8.0 - We currently utilize the 8.0.22 connector. ([MySQL properties changed from 5.1 to 8.0](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-properties-changed.html))

As far as I understand your comment, our setup should therefore already utilize a correctly configured JDBC connection string, and the problem should not have presented itself. However, this was not the case. 
I am unsure if I am missing something essential, but I have a hard time grasping how this is not something that JobRunr is expected to handle.

Side note: The Baeldung article you referenced uses the [8.0.12 connector](https://github.com/eugenp/tutorials/blob/master/persistence-modules/spring-boot-mysql/pom.xml), but they reference the 5.1 version of the connector. This seems to be an oversight or misundestanding on their part.

**Comment by rdehuyss** [comment]
Thanks for the feedback. Then I'm open for a PR to fix this as my time is very limited for the moment.
