### ISSUE TITLE
[BUG] Unable to deserialize older job parameters

### ISSUE THREAD

**Issue by benallard** [jobrunr/jobrunr#254]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
```
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-4.0.1.jar:na]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:81) ~[jobrunr-4.0.1.jar:na]
	at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20) ~[jobrunr-4.0.1.jar:na]
	at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:189) ~[jobrunr-4.0.1.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_131]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:42) ~[jobrunr-4.0.1.jar:na]
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_131]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_131]
	at org.jobrunr.storage.sql.common.JobTable.selectJobsByState(JobTable.java:117) ~[jobrunr-4.0.1.jar:na]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobs(DefaultSqlStorageProvider.java:224) ~[jobrunr-4.0.1.jar:na]
	at com.acme.datainit.JobRunrRequeueFailedJobs.run(JobRunrRequeueFailedJobs.java:40) ~[acme.jar.jar:2021.36.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:258) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443) ~[spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325) ~[spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) [spring-web-4.3.30.RELEASE.jar:4.3.30.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4701) [catalina.jar:8.5.53]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167) [catalina.jar:8.5.53]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:8.5.53]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743) [catalina.jar:8.5.53]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719) [catalina.jar:8.5.53]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) [catalina.jar:8.5.53]
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:614) [catalina.jar:8.5.53]
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1823) [catalina.jar:8.5.53]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `long` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.jobrunr.jobs.Job["jobDetails"]->org.jobrunr.jobs.JobDetails["jobParameters"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLongPrimitive(StdDeserializer.java:852) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:573) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:550) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3261) ~[jackson-databind-2.12.3.jar:2.12.3]
	at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:33) ~[jobrunr-4.0.1.jar:na]
	at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:18) ~[jobrunr-4.0.1.jar:na]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516) ~[jackson-databind-2.12.3.jar:2.12.3]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:77) ~[jobrunr-4.0.1.jar:na]
	... 43 common frames omitted
```

**Environment**
I'm using JobRunr version: 4.0.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): 8
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): postgres

**How to Reproduce**
Upgrade jobrunr version, start server

**Expected behavior**
enqueued jobs start getting processed.

**Additional context**

**Comment by benallard** [comment]
That's probably the part it's shoking on:

``` json
 "jobParameters": [
      {
        "className": "long",
        "actualClassName": "java.lang.Long",
        "object": [
          "java.lang.Long",
          1807893
        ]
      },
```

**Comment by benallard** [comment]
Thanks.

**Comment by feiniao33** [comment]
I found that when I upgrade my app's jobrunr to any version above v4.0.1 even v5, I will get MismatchedInputException which get no exception in v4.0.1 or even v3. I think there must be a mistake in v4.0.2 Bugfixes most probably #254. Hope someone come to fix it.

**Comment by feiniao33** [comment]
> I found that when I upgrade my app's jobrunr to any version above v4.0.1 even v5, I will get MismatchedInputException which get no exception in v4.0.1 or even v3. I think there must be a mistake in v4.0.2 Bugfixes most probably #254. Hope someone come to fix it.

15:49:06.161 [backgroundjob-zookeeper-pool-1-thread-2] WARN  org.jobrunr.server.JobZooKeeper - JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
               at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
               at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:81)
               at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
               at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:189)
               at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
               at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:42)
               at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
               at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
               at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
               at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
               at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
               at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
               at org.jobrunr.storage.sql.common.JobTable.selectJobsByState(JobTable.java:117)
               at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobs(DefaultSqlStorageProvider.java:224)
               at org.jobrunr.storage.ThreadSafeStorageProvider.getJobs(ThreadSafeStorageProvider.java:132)
               at org.jobrunr.server.JobZooKeeper.checkForEnqueuedJobs(JobZooKeeper.java:161)
               at org.jobrunr.server.JobZooKeeper.onboardNewWorkIfPossible(JobZooKeeper.java:151)
               at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
               at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
               at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
               at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
               at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
               at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[D` from Floating-point value (token `JsonToken.VALUE_NUMBER_FLOAT`)
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.jobrunr.jobs.Job["jobDetails"]->org.jobrunr.jobs.JobDetails["jobParameters"]->java.util.ArrayList[0])
               at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
               at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
               at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
               at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers.handleNonArray(PrimitiveArrayDeserializers.java:226)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$DoubleDeser.deserialize(PrimitiveArrayDeserializers.java:889)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$DoubleDeser.deserialize(PrimitiveArrayDeserializers.java:863)
               at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
               at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
               at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3261)
               at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:34)
               at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:18)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
               at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
               at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
               at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
               at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
               at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:77)
               ... 22 common frames omitted
