### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by murmuror** [jobrunr/jobrunr#266]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-11-22 18:09:59.380 ERROR 22361 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:761) ~[spring-boot-2.6.0.jar:2.6.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748) ~[spring-boot-2.6.0.jar:2.6.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.0.jar:2.6.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.0.jar:2.6.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.0.jar:2.6.0]
	at com.example.elasticjob.JobApplication.main(JobApplication.java:23) ~[classes/:na]
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:81) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder$1.visitInsn(AbstractJobDetailsFinder.java:46) ~[jobrunr-4.0.2.jar:na]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2213) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[asm-9.2.jar:9.2]
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:90) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:19) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:70) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:36) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:515) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:479) ~[jobrunr-4.0.2.jar:na]
	at org.jobrunr.scheduling.BackgroundJob.scheduleRecurrently(BackgroundJob.java:475) ~[jobrunr-4.0.2.jar:na]
	at com.example.elasticjob.JobApplication.lambda$jobRunner$0(JobApplication.java:33) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758) ~[spring-boot-2.6.0.jar:2.6.0]
	... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: Instruction 191 not found
	... 21 common frames omitted
```

**Environment**
I'm using JobRunr version: 4.0.2 & springboot-2.6.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): Zulu11.52+13-CA (build 11.0.13+8-LTS) apple silicon arm64
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...):  mysql8.0

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
@SpringBootApplication
public class JobApplication {

    public static void main(String[] args) {
        SpringApplication.run(JobApplication.class, args);
    }

    @Bean
    public ApplicationRunner jobRunner() {
        return  args -> {
            BackgroundJob.enqueue(() -> {
                System.out.println("executed");
            });

            BackgroundJob.scheduleRecurrently("every5minutes", Cron.every5minutes(), () -> {
                System.out.println("every5minutes: executed");
                if (new Random().nextBoolean()) {
                    throw new RuntimeException("test error");
                }
            });

            BackgroundJob.schedule(Instant.now().plusSeconds(20), () -> {
                System.out.println("Instant.now().plusSeconds(20)");
            });
        };
    }
    
    @Bean
    public JobScheduler initJobRunr(DataSource dataSource, JobActivator jobActivator) {
        JobRunrConfiguration.JobRunrConfigurationResult initialize = JobRunr.configure()
                .useJobActivator(jobActivator)
                .useStorageProvider(SqlStorageProviderFactory.using(dataSource))
                .useBackgroundJobServer()
                .useDashboard(8000)
                .initialize();
        return initialize.getJobScheduler();
    }

}
```

**Expected behavior**

start correctly~

**Additional context**

**Comment by rdehuyss** [comment]
JobRunr was meant to be used with easy job lambda's (i.e. calling other services that can throw exceptions). You are throwing an exception from within the lambda itself, which is not supported. 

If you would extract the code below to a separate service, all would work fine:

```
if (new Random().nextBoolean()) {
                    throw new RuntimeException("test error");
                }
```
