### ISSUE TITLE
[BUG]  DB deadlock when updating jobrunr_backgroundjobservers

### ISSUE THREAD

**Issue by ccostin93** [jobrunr/jobrunr#275]
**Are you running the latest version of JobRunr?**
No, 4.0.2, but based on 4.0.3 (latest at the moment this issue was created) changelog there shouldn't be a difference.

**Describe the bug**
We encountered deadlock errors after integrating the library. When running multiple app instances, a database deadlock error was detected when the framework updates the `jobrunr_backgroundjobservers` table. 
The deadlock leads to the backgroundjob server crashing and restart quick after.

**Environment**
I'm using JobRunr version: 4.0.2
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): jdk-11.0.11+9
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Aurora Serverless MySQL mode (https://aws.amazon.com/rds/aurora/mysql-features/#High_Availability_and_Durability) with a MariaDB connector

**How to Reproduce**
Unfortunately, we were not able to intentionally reproduce the deadlock, but it happens daily at random hours.

**Expected behavior**
No deadlocks appear during the app runtime.

**Additional context**
Stacktrace:
```
java.sql.SQLException: Deadlock found when trying to get lock; try restarting transaction
	at o.m.j.i.p.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694)
	at o.m.j.i.p.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556)
	at o.m.j.i.p.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519)
	at o.m.j.i.p.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 18 common frames omitted
Wrapped by: o.m.j.i.u.e.MariaDbSqlException: Deadlock found when trying to get lock; try restarting transaction
	at o.m.j.i.u.e.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at o.m.j.i.p.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at o.m.j.i.p.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at o.m.j.i.p.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at o.m.j.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 17 common frames omitted
Wrapped by: j.s.SQLTransactionRollbackException: (conn=47) Deadlock found when trying to get lock; try restarting transaction
	at o.m.j.i.u.e.ExceptionFactory.createException(ExceptionFactory.java:76)
	at o.m.j.i.u.e.ExceptionFactory.create(ExceptionFactory.java:158)
	at o.m.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at o.m.j.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at o.m.j.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at o.m.j.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181)
	at c.z.h.p.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at c.z.h.p.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at o.j.storage.sql.common.db.Sql.delete(Sql.java:130)
	at o.j.s.s.c.BackgroundJobServerTable.removeAllWithLastHeartbeatOlderThan(BackgroundJobServerTable.java:84)
	at o.j.s.s.c.DefaultSqlStorageProvider.removeTimedOutBackgroundJobServers(DefaultSqlStorageProvider.java:129)
	... 10 common frames omitted
Wrapped by: o.j.storage.StorageException: java.sql.SQLTransactionRollbackException: (conn=47) Deadlock found when trying to get lock; try restarting transaction
	at o.j.s.s.c.DefaultSqlStorageProvider.removeTimedOutBackgroundJobServers(DefaultSqlStorageProvider.java:133)
	at o.j.s.ThreadSafeStorageProvider.removeTimedOutBackgroundJobServers(ThreadSafeStorageProvider.java:73)
	at o.j.server.ServerZooKeeper.deleteServersThatTimedOut(ServerZooKeeper.java:105)
	at o.j.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:77)
	at o.j.server.ServerZooKeeper.run(ServerZooKeeper.java:49)
	at j.u.c.Executors$RunnableAdapter.call(Executors.java:515)
	at j.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at j.u.c.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:829)
```

database deadlock log:
```
2021-11-24 17:49:39 0x2ad52c8297002021-11-24 17:49:39 0x2ad52c829700
*** (1) TRANSACTION:
TRANSACTION 97467758, ACTIVE 0 sec starting index read
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s)
MySQL thread id 70, OS thread handle 47094265939712, query id 34658 10.1.8.185 schema updating
delete from jobrunr_backgroundjobservers where lastHeartbeat < '2021-11-24 18:49:19.556853'
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 176 page no 3 n bits 0 index PRIMARY of table `schema`.`jobrunr_backgroundjobservers` trx id 97467758 lock_mode X locks rec but not gap waiting
Record lock, heap no 5 PHYSICAL RECORD: n_fields 17; compact format; info bits 0
 0: len=30; bufptr=0x2ad509450225; hex= 32666232396362362d396663642d346365642d616663372d333464623135; asc 2fb29cb6-9fcd-4ced-afc7-34db15; (total 36 bytes);
 1: len=6; bufptr=0x2ad509450249; hex= 000005cf3d6d; asc     =m;;
 2: len=7; bufptr=0x2ad50945024f; hex= 33000003f114f4; asc 3      ;;
 3: len=4; bufptr=0x2ad509450256; hex= 80000008; asc     ;;
 4: len=4; bufptr=0x2ad50945025a; hex= 80000005; asc     ;;
 5: len=8; bufptr=0x2ad50945025e; hex= 99ab3123440d9323; asc   1#D  #;;
 6: len=8; bufptr=0x2ad509450266; hex= 99ab312c6708739f; asc   1,g s ;;
 7: len=4; bufptr=0x2ad50945026e; hex= 80000001; asc     ;;
 8: len=8; bufptr=0x2ad509450272; hex= 8000000040000000; asc     @   ;;
 9: len=8; bufptr=0x2ad50945027a; hex= 800000001d941000; asc         ;;
 10: len=2; bufptr=0x2ad509450282; hex= 8000; asc   ;;
 11: len=8; bufptr=0x2ad509450284; hex= 800000002e670000; asc     .g  ;;
 12: len=8; bufptr=0x2ad50945028c; hex= 80000000265b0738; asc     &[ 8;;
 13: len=8; bufptr=0x2ad509450294; hex= 80000000080bf8c8; asc         ;;
 14: len=2; bufptr=0x2ad50945029c; hex= 8000; asc   ;;
 15: len=5; bufptr=0x2ad50945029e; hex= 5054333648; asc PT36H;;
 16: len=5; bufptr=0x2ad5094502a3; hex= 5054373248; asc PT72H;;
*** (2) TRANSACTION:
TRANSACTION 97467757, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
LOCK WAIT 3 lock struct(s), heap size 1136, 2 row lock(s), undo log entries 1
MySQL thread id 68, OS thread handle 47094294656768, query id 34657 10.1.9.224 schema updating
update jobrunr_backgroundjobservers SET lastHeartbeat = '2021-11-24 18:49:39.553887', systemFreeMemory = 496242688, systemCpuLoad = 0.0020957234449760767, processFreeMemory = 643499832, processAllocatedMemory = 135002312, processCpuLoad = 0.0020957234449760767 where id = '2fb29cb6-9fcd-4ced-afc7-34db15ba9f4f'
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 176 page no 3 n bits 0 index PRIMARY of table `schema`.`jobrunr_backgroundjobservers` trx id 97467757 lock_mode X locks rec but not gap
Record lock, heap no 5 PHYSICAL RECORD: n_fields 17; compact format; info bits 0
 0: len=30; bufptr=0x2ad509450225; hex= 32666232396362362d396663642d346365642d616663372d333464623135; asc 2fb29cb6-9fcd-4ced-afc7-34db15; (total 36 bytes);
 1: len=6; bufptr=0x2ad509450249; hex= 000005cf3d6d; asc     =m;;
 2: len=7; bufptr=0x2ad50945024f; hex= 33000003f114f4; asc 3      ;;
 3: len=4; bufptr=0x2ad509450256; hex= 80000008; asc     ;;
 4: len=4; bufptr=0x2ad50945025a; hex= 80000005; asc     ;;
 5: len=8; bufptr=0x2ad50945025e; hex= 99ab3123440d9323; asc   1#D  #;;
 6: len=8; bufptr=0x2ad509450266; hex= 99ab312c6708739f; asc   1,g s ;;
 7: len=4; bufptr=0x2ad50945026e; hex= 80000001; asc     ;;
 8: len=8; bufptr=0x2ad509450272; hex= 8000000040000000; asc     @   ;;
 9: len=8; bufptr=0x2ad50945027a; hex= 800000001d941000; asc         ;;
 10: len=2; bufptr=0x2ad509450282; hex= 8000; asc   ;;
 11: len=8; bufptr=0x2ad509450284; hex= 800000002e670000; asc     .g  ;;
 12: len=8; bufptr=0x2ad50945028c; hex= 80000000265b0738; asc     &[ 8;;
 13: len=8; bufptr=0x2ad509450294; hex= 80000000080bf8c8; asc         ;;
 14: len=2; bufptr=0x2ad50945029c; hex= 8000; asc   ;;
 15: len=5; bufptr=0x2ad50945029e; hex= 5054333648; asc PT36H;;
 16: len=5; bufptr=0x2ad5094502a3; hex= 5054373248; asc PT72H;;
*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 176 page no 5 n bits 0 index jobrunr_bgjobsrvrs_lsthb_idx of table `schema`.`jobrunr_backgroundjobservers` trx id 97467757 lock_mode X locks rec but not gap waiting
Record lock, heap no 3 PHYSICAL RECORD: n_fields 2; compact format; info bits 0
 0: len=8; bufptr=0x2ad5093fc0b0; hex= 99ab312c62080ad5; asc   1,b   ;;
 1: len=30; bufptr=0x2ad5093fc0b8; hex= 32666232396362362d396663642d346365642d616663372d333464623135; asc 2fb29cb6-9fcd-4ced-afc7-34db15; (total 36 bytes);
*** WE ROLL BACK TRANSACTION (1)
```

**Comment by rdehuyss** [comment]
I'm again amazed by MySQL - I've not encountered this with any other database.

The official documentation says:
> Always be prepared to re-issue a transaction if it fails due to deadlock. Deadlocks are not dangerous. Just try again.

See [How to Minimize and Handle Deadlocks](https://dev.mysql.com/doc/refman/8.0/en/innodb-deadlocks-handling.html) and [StackOverflow](https://stackoverflow.com/questions/15412838/deadlock-issue-when-transaction-tries-to-accuire-a-lock-its-already-holding). 

Still considering what I should do with this.

**Comment by ccostin93** [comment]
@rdehuyss Thanks for the quick response. I saw that you already added a retrying logic https://github.com/jobrunr/jobrunr/commit/d242620830d3a2f80adb73516dbfdd9cd7ce4e6d. Do you have an idea on when a new version will be released?

**Comment by rdehuyss** [comment]
Hi @ccostin93 ,

life is quite busy for the moment - probably somewhere end of next week or so.
