### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by arkusiarun** [jobrunr/jobrunr#280]
### Runtime information
- __Timestamp__: 2021-12-07T09:01:47.131Z
- __Location__: BackgroundJobServer aa514aa0-1275-495d-99a4-822c21eba9f2
- __JobRunr Version__: 4.0.0
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 1.8.0_281
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: aa514aa0-1275-495d-99a4-822c21eba9f2
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2021-12-07T07:02:26.730Z, lastHeartbeat: 2021-12-07T09:01:42.304Z)

#### Concurrent modified jobs:
Job id: ed60a60e-f4f1-43c4-ad56-4abca5042aac
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2021-12-07T09:01:47.097Z) ← SCHEDULED (at 2021-12-07T09:01:47.049Z)
	Storage state: ENQUEUED (at 2021-12-07T09:01:47.074Z) ← SCHEDULED (at 2021-12-07T09:01:47.049Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:206)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:190)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:112)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rdehuyss** [comment]
Hi @arkusiarun - does this happen a lot? Was this by any chance after you opened your laptop?
