### ISSUE TITLE
[BUG] JobRunr encountered a problematic exception (Instruction 133 not found)

### ISSUE THREAD

**Issue by dzolo** [jobrunr/jobrunr#289]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
Spring Boot application with background repeat job with `LocalDate#minusDays`.

**Environment**
I'm using JobRunr version: 4.0.5
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk version "11.0.11" 2021-04-20
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): InMemoryStorageProvider

**How to Reproduce**

```java
@Component
public class ApplicationStartup implements ApplicationListener<ApplicationReadyEvent> {

  @Autowired
  private JobScheduler jobScheduler;

  @Override
  public void onApplicationEvent(ApplicationReadyEvent event) {
    jobScheduler.scheduleRecurrently("some-id", Cron.daily(0, 30), () -> LocalDate.now().minusDays(90)));
  }
}
```

I get:
```
...
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:81) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder$1.visitInsn(AbstractJobDetailsFinder.java:46) ~[jobrunr-4.0.5.jar:na]
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2213) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[asm-9.2.jar:9.2]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[asm-9.2.jar:9.2]
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:90) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:19) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:70) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:36) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:515) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:479) ~[jobrunr-4.0.5.jar:na]
	...
Caused by: java.lang.IllegalArgumentException: Instruction 133 not found
	... 99 common frames omitted
```

**Expected behavior**
Run a background job.

**Additional context**
If i remove `minusDays(90)` then it works.

**Comment by rdehuyss** [comment]
Indeed, but I don't think I will fix this unless there is a very good reason. You can just extract the minusDays before you schedule the job and pass the result. The lambda you are creating now, cannot also not be cached.

Don't forget that recurring jobs also serialize their parameters, so the recurring job will always have a fixed date (if run now, this would be somewhere around 19 September and this would stay the same, also a week from now.)

**Comment by dzolo** [comment]
OK. I didn't know about caching of parameters.
