### ISSUE TITLE
[Recurring - CRON] It is possible to use '#' to specify day-of-week field?

### ISSUE THREAD

**Issue by alvaro-nogueira** [jobrunr/jobrunr#300]
I want to create Recurring job that only runs at first Monday of a Month, like: cron = "0 0 10 ? * MON#1"
I'm able to do it with Quartz and wtith Spring @Schedule, but with jobrunr I'm getting this error:

```
Caused by: org.jobrunr.scheduling.cron.InvalidCronExpressionException: invalid day_of_week field: "mon#1".
	at org.jobrunr.scheduling.cron.CronFieldParser.parseLiteral(CronFieldParser.java:184) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.cron.CronFieldParser.parse(CronFieldParser.java:110) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.cron.CronExpression.create(CronExpression.java:135) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:535) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:496) ~[jobrunr-4.0.5.jar:na]
	at org.jobrunr.scheduling.JobScheduler.scheduleRecurrently(JobScheduler.java:461) ~[jobrunr-4.0.5.jar:na]
```

Is there any support for this feature in jobrunr?

**Comment by rdehuyss** [comment]
No, that's currently not supported. Feel free to open a PR that fixes it.
