### ISSUE TITLE
Repeated ConcurrentSqlModificationException leading to JobRunr shutting down the application

### ISSUE THREAD

**Issue by william00179** [jobrunr/jobrunr#316]
We currently have two services using JobRunr. 

Service A is a Spring Boot service using the starter and the following configuration in application.yaml

```yaml
org:
  jobrunr:
    background-job-server:
      enabled: true
    database:
      skip-create: true
```

We have seen no issues with this service and its been running JobRunr in production for some time now.

We recently included JobRunr in Service B, also a Spring Boot application using the starter. We created a new set of tables for this service with a different prefix `service_b_` and configuration in `application.yaml`

```yaml
org:
  jobrunr:
    background-job-server:
      enabled: true
    database:
      skip-create: true
      table-prefix: service_b_
```
Service B runs fine and processes jobs, but the masters logs are filled with the following exception

```
2022-01-14 09:07:30.168  WARN 1 --- [pool-6-thread-2] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:18) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:140) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:119) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:66) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:349) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:182) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:140) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100) ~[jobrunr-4.0.3.jar:na]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77) ~[jobrunr-4.0.3.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
 ```

Eventually, there will be a different exception and the application will restart

```
2022-01-14 09:14:47.321 ERROR 1 --- [pool-6-thread-2] org.jobrunr.server.JobZooKeeper          : FATAL - JobRunr encountered too many processing exceptions. Shutting down.

org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:84) ~[jobrunr-4.0.6.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:18) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:140) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:119) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:66) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:349) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:182) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:140) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100) ~[jobrunr-4.0.6.jar:na]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77) ~[jobrunr-4.0.6.jar:na]
        ... 6 common frames omitted

2022-01-14 09:14:57.332  INFO 1 --- [pool-6-thread-2] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer shutdown requested - waiting for jobs to finish (at most 10 seconds)
2022-01-14 09:14:57.332  INFO 1 --- [pool-6-thread-2] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer and BackgroundJobPerformers stopped
2022-01-14 09:14:58.589  WARN 1 --- [nio-8080-exec-6] i.m.c.instrument.internal.DefaultGauge   : Failed to apply the value function for the gauge 'jobrunr.background-job-server.first-heartbeat'. Note that subsequent logs will be logged at debug level.

java.lang.NullPointerException: Cannot invoke "java.time.Instant.getEpochSecond()" because the return value of "org.jobrunr.storage.BackgroundJobServerStatus.getFirstHeartbeat()" is null
        at org.jobrunr.server.metrics.BackgroundJobServerMetricsBinder.lambda$registerBackgroundJobServerMetrics$6(BackgroundJobServerMetricsBinder.java:29) ~[jobrunr-4.0.6.jar:na]
        at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54) ~[micrometer-core-1.8.1.jar:1.8.1]
        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:280) ~[micrometer-registry-prometheus-1.8.1.jar:1.8.1]
        at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:70) ~[micrometer-registry-prometheus-1.8.1.jar:1.8.1]
        at io.prometheus.client.Collector.collect(Collector.java:46) ~[simpleclient-0.12.0.jar:na]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:197) ~[simpleclient-0.12.0.jar:na]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:212) ~[simpleclient-0.12.0.jar:na]
        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152) ~[simpleclient-0.12.0.jar:na]
        at io.prometheus.client.exporter.common.TextFormat.writeOpenMetrics100(TextFormat.java:202) ~[simpleclient_common-0.12.0.jar:na]
        at org.springframework.boot.actuate.metrics.export.prometheus.TextOutputFormat$2.write(TextOutputFormat.java:62) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:58) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.3.14.jar:5.3.14]
        at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:74) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter.handle(AbstractWebMvcEndpointHandlerMapping.java:336) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler.handle(AbstractWebMvcEndpointHandlerMapping.java:421) ~[spring-boot-actuator-2.6.2.jar:2.6.2]
        at jdk.internal.reflect.GeneratedMethodAccessor150.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.14.jar:5.3.14]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.14.jar:5.3.14]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]
...
2022-01-14 09:15:00.257  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:00.276  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:00.278  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:00.602  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:00.634  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:00.918  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:00.922  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:01.179  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:01.183  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:01.574  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:01.578  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:02.026  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:02.034  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:02.234  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:02.239  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-01-14 09:15:02.603  INFO 1 --- [ionShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-01-14 09:15:02.769  INFO 1 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
 ```

**Environment**
I'm using JobRunr version: 4.0.6
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): adoptopenjdk:16-jre-hotspot
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgres

**Comment by william00179** [comment]
This issue was caused by an issue with the metadata table such that it has lost the expected row with ID `succeeded-jobs-counter-cluster` adding this row again per the migration has resolved the issue.

Would you be open to a PR to check for this metadata's row on start and insert it again if its not there to prevent this particular issue?

If not please feel free to close this.

**Comment by rdehuyss** [comment]
The question is: how come the row was not there initially? Do you know?

**Comment by rdehuyss** [comment]
Closing as you created the tables manually and forgot to add the row.
