### ISSUE TITLE
[BUG] Incrementing successful jobs fails on MySQL

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#317]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
```
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:84)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.jobrunr.storage.StorageException: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect CHAR(10) value: '11.000000000000000000000000000000'
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:352)
	at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:182)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:140)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
```

**Environment**
I'm using JobRunr version: 4.0.6
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): NA
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): MySQL

**Comment by rdehuyss** [comment]
Solved in v5.0.0 branch.
