### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abdo2011** [jobrunr/jobrunr#336]
**Describe the bug**
WARN  --- [backgroundjob-zookeeper-pool-4-thread-2]  --- org.jobrunr.server.JobZooKeeper: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.storage.StorageException: com.microsoft.sqlserver.jdbc.SQLServerException: Connection reset
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:201)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:101)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:201)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:191)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:113)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Connection reset
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3151)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2062)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6596)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7760)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:2800)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2678)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2079)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdateAll(Sql.java:175)
	at org.jobrunr.storage.sql.common.db.Sql.updateAll(Sql.java:160)
	at org.jobrunr.storage.sql.common.JobTable.updateAllJobs(JobTable.java:197)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:107)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:196)
	... 13 common frames omitted
	Suppressed: java.sql.SQLException: Connection is closed
		at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
		at jdk.proxy4/jdk.proxy4.$Proxy156.rollback(Unknown Source)
		at com.zaxxer.hikari.pool.ProxyConnection.rollback(ProxyConnection.java:396)
		at com.zaxxer.hikari.pool.HikariProxyConnection.rollback(HikariProxyConnection.java)
		at org.jobrunr.storage.sql.common.db.Transaction.close(Transaction.java:36)
		at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:195)
		... 13 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2054)
	... 29 common frames omitted
2022-01-25 00:08:47,602 WARN  --- [backgroundjob-zookeeper-pool-4-thread-1]  --- com.zaxxer.hikari.pool.PoolBase: HikariPool-1 - Failed to validate connection ConnectionID:22 ClientConnectionId: ca574ec1-fd4a-4915-a570-fb2a71da0ab6 (The connection is closed.). Possibly consider using a shorter maxLifetime value.
2022-01-25 00:08:47,603 WARN  --- [mssql-timeout-task-1-ca574ec1-fd4a-4915-a570-fb2a71da0ab6]  --- com.microsoft.sqlserver.jdbc.TDSCommand: TDSCommand@aa3376e (SQLServerStatement:193 executeXXX): Command could not be timed out. Reason: Socket closed
2022-01-25 00:08:47,808 WARN  --- [backgroundjob-zookeeper-pool-4-thread-2]  --- com.zaxxer.hikari.pool.ProxyConnection: HikariPool-1 - Connection ConnectionID:23 ClientConnectionId: 4b7bd25a-ff37-42e2-9cb8-6f23c2700751 marked as broken because of SQLSTATE(08S01), ErrorCode(0)

**Environment**
I'm using JobRunr version: 3.2.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292):17 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): MS sql server 

****we need to set org.jobrunr.database.maxLifetime=55000

**Comment by rdehuyss** [comment]
Not using latest version of JobRunr.

The connection lifetime is not managed by JobRunr but by your Datasource.
