### ISSUE TITLE
 The JobScheduler has not been initialized when start the application

### ISSUE THREAD

**Issue by engahmedtahaa** [jobrunr/jobrunr#341]
when we start the application we have the below exception we are using the latest jobrunr version 

5d-4e7e-856a-17e5826d8a1d, jobName='com.saudivts.mofa.bio.job.management.jobs.enrollment.SubmitEnrollmentJob.execute()') processing failed: An exception occurred during the performance of the job
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.invokeJobMethod(AbstractBackgroundJobRunner.java:60)
        at org.jobrunr.server.runner.AbstractBackgroundJobRunner$BackgroundJobWorker.run(AbstractBackgroundJobRunner.java:37)
        at org.jobrunr.server.runner.AbstractBackgroundJobRunner.run(AbstractBackgroundJobRunner.java:19)
        at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:78)
        at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:38)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalStateException: The JobScheduler has not been initialized. Use the fluent JobRunr.configure() API to setup JobRunr or set the JobScheduler via the static setter method.
        at org.jobrunr.scheduling.BackgroundJob.verifyJobScheduler(BackgroundJob.java:551)
        at org.jobrunr.scheduling.BackgroundJob.enqueue(BackgroundJob.java:74)
        at com.saudivts.mofa.bio.job.management.jobs.enrollment.SubmitEnrollmentJob.execute(SubmitEnrollmentJob.java:27)
        at com.saudivts.mofa.bio.job.management.jobs.enrollment.SubmitEnrollmentJob$$FastClassBySpringCGLIB$$62d9c694.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
        at com.saudivts.mofa.bio.job.management.jobs.enrollment.SubmitEnrollmentJob$$EnhancerBySpringCGLIB$$7ca1980.execute(<generated>)
        ... 15 common frames omitted

**Comment by rdehuyss** [comment]
See your other issue. This is also a warning as you already have created quite some issues like these. On subsequent failure to follow the guidelines, I'll block you from creating issues here.

**Comment by rdehuyss** [comment]
And please read the stacktrace before creating issues as it says how to solve it.
