### ISSUE TITLE
[BUG] Exceptions in log when shutting down application

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#39]
**Describe the bug**
I see these exceptions in the logs when shutting down the server:

```java
2020-09-25 09:49:10,202 ERROR [org.job.sto.AbstractStorageProvider] (Timer-0) Error notifying JobStorageChangeListeners - please create a bug report (with the stacktrace attached): org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
    at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
    at org.jobrunr.storage.sql.common.db.dialect.DialectFactory.forDataSource(DialectFactory.java:25)
    at org.jobrunr.storage.sql.common.db.Sql.using(Sql.java:49)
    at org.jobrunr.storage.sql.common.BackgroundJobServerTable.<init>(BackgroundJobServerTable.java:33)
    at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.backgroundJobServerTable(DefaultSqlStorageProvider.java:236)
    at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getBackgroundJobServers(DefaultSqlStorageProvider.java:86)
    at org.jobrunr.storage.AbstractStorageProvider.notifyBackgroundJobServerStatusChangeListeners(AbstractStorageProvider.java:120)
    at org.jobrunr.storage.AbstractStorageProvider.access$100(AbstractStorageProvider.java:21)
    at org.jobrunr.storage.AbstractStorageProvider$SendJobStatsUpdate.run(AbstractStorageProvider.java:163)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Caused by: java.sql.SQLException: This pool is closed and does not handle any more connections!
    at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:192)
    at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
    at org.jobrunr.storage.sql.common.db.dialect.DialectFactory.forDataSource(DialectFactory.java:18)
    ... 9 more
```

**Environment**
I'm using version 1.0.0
I'm running on JRE / JDK Quarkus

**Comment by bgalek** [comment]
I see similiar behaviour in spring-boot
```
2022-01-03 17:51:41.978  WARN 53786 --- [        Timer-0] o.j.storage.AbstractStorageProvider      : Error notifying JobStorageChangeListeners

org.jobrunr.storage.StorageException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "JOBRUNR_JOBS_STATS" not found; SQL statement:
select * from jobrunr_jobs_stats ORDER BY total ASC LIMIT ? OFFSET ? [42102-200]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:62) ~[jobrunr-4.0.5.jar:na]

```
