### ISSUE TITLE
[BUG] Not able to bring up job run dashboard in JBOSS EAP 7.3

### ISSUE THREAD

**Issue by yexianseng** [jobrunr/jobrunr#397]
HI Team , 

We are counter the issue when we deploy the jobrunr into JBOSS 7.3 with JDK 11 , it is looking for sun/misc/ServiceConfigurationError which is not expected ,can help suggest ? attach full log for reference . 
When i was test it in intellij with embedded tomcat , all is good . And if we disable dashboard from config , can bring up jobrunr . 

JobRunr version: 4.0.9 , JDK ZULU 11 , JBOSS EAP 7.3

Part A starting log ::::
Calling "C:\test_abc\jboss-eap-7.3\bin\standalone.conf.bat"
Setting JAVA property to "C:\Program Files\Zulu\zulu-11\bin\java"
===============================================================================
  JBoss Bootstrap Environment
  JBOSS_HOME: "C:\test_abc\jboss-eap-7.3"
  JAVA: "C:\Program Files\Zulu\zulu-11\bin\java"
  JAVA_OPTS: "-Dprogram.name=standalone.bat -Xms1G -Xmx1G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Xlog:gc*:file="\"C:\test_abc\jboss-eap-7.3\standalone\log\gc.log\"":time,uptimemillis:filecount=5,filesize=3M  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED"
===============================================================================
10:52:02,024 INFO  [org.jboss.modules] (main) JBoss Modules version 1.9.1.Final-redhat-00001

Part B warning log ： 
10:52:37,866 INFO  [org.hibernate.validator.internal.util.Version] (background-preinit) HV000001: Hibernate Validator 6.0.18.Final-redhat-00001
10:52:37,935 INFO  [stdout] (ServerService Thread Pool -- 86)
10:52:37,935 INFO  [stdout] (ServerService Thread Pool -- 86)   .   ____          _            __ _ _
10:52:37,941 INFO  [stdout] (ServerService Thread Pool -- 86)  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
10:52:37,946 INFO  [stdout] (ServerService Thread Pool -- 86) ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
10:52:37,946 INFO  [stdout] (ServerService Thread Pool -- 86)  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
10:52:37,947 INFO  [stdout] (ServerService Thread Pool -- 86)   '  |____| .__|_| |_|_| |_\__, | / / / /
10:52:37,949 INFO  [stdout] (ServerService Thread Pool -- 86)  =========|_|==============|___/=/_/_/_/
10:52:37,950 INFO  [stdout] (ServerService Thread Pool -- 86)  :: Spring Boot ::                (v2.6.3)
10:52:37,950 INFO  [stdout] (ServerService Thread Pool -- 86)
10:52:38,103 INFO  [com.test.test.ServletInitializer] (ServerService Thread Pool -- 86) Starting ServletInitializer using Java 11.0.7 on 10CNL5CG03772SM with PID 9884 (started by chaochen in C:\test_abc\jboss-eap-7.3\bin)
10:52:38,104 INFO  [com.test.test.ServletInitializer] (ServerService Thread Pool -- 86) The following profiles are active: dev
10:52:38,285 INFO  [org.springframework.context.annotation.ConfigurationClassParser] (ServerService Thread Pool -- 86) Properties location [] not resolvable: Could not open ServletContext resource [/]
10:52:38,288 INFO  [org.springframework.context.annotation.ConfigurationClassParser] (ServerService Thread Pool -- 86) Properties location [] not resolvable: Could not open ServletContext resource [/]
10:52:41,231 WARN  [org.jboss.modules.define] (Thread-113) Failed to define class io.micrometer.core.instrument.binder.jersey.server.MetricsApplicationEventListener in Module "deployment.test-test-1.0.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link io/micrometer/core/instrument/binder/jersey/server/MetricsApplicationEventListener (Module "deployment.test-test-1.0.war" from Service Module Loader): org/glassfish/jersey/server/monitoring/ApplicationEventListener
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1096)
        at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
        at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
        at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
        at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
        at org.jboss.modules.Module.loadModuleClass(Module.java:731)
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)

Part C error log ： 
0:53:31,694 INFO  [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] (ServerService Thread Pool -- 86)

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
10:53:31,715 ERROR [org.springframework.boot.SpringApplication] (ServerService Thread Pool -- 86) Application run failed: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at deployment.test-test-1.0.war//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at deployment.test-test-1.0.war//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
        at deployment.test-test-1.0.war//org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 41 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//com.sun.net.httpserver.HttpServer.create(HttpServer.java:110)
        at deployment.test-test-1.0.war//org.jobrunr.dashboard.server.WebServer.<init>(WebServer.java:26)
        at deployment.test-test-1.0.war//org.jobrunr.dashboard.JobRunrtestWexServer.start(JobRunrtestWexServer.java:68)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration.testWexServer(JobRunrAutoConfiguration.java:97)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69.CGLIB$testWexServer$1(<generated>)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69$$FastClassBySpringCGLIB$$18621138.invoke(<generated>)
        at deployment.test-test-1.0.war//org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at deployment.test-test-1.0.war//org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69.testWexServer(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 42 more
Caused by: java.lang.ClassNotFoundException: sun.misc.ServiceConfigurationError from [Module "deployment.test-test-1.0.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 56 more

10:53:31,721 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 86) MSC000001: Failed to start service jboss.deployment.unit."test-test-1.0.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.unit."test-test-1.0.war".undertow-deployment: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
        ... 8 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at deployment.test-test-1.0.war//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at deployment.test-test-1.0.war//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
        at deployment.test-test-1.0.war//org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155)
        at deployment.test-test-1.0.war//org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97)
        at deployment.test-test-1.0.war//org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
        at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
        ... 10 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
        ... 41 more
Caused by: java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
        at deployment.test-test-1.0.war//com.sun.net.httpserver.HttpServer.create(HttpServer.java:110)
        at deployment.test-test-1.0.war//org.jobrunr.dashboard.server.WebServer.<init>(WebServer.java:26)
        at deployment.test-test-1.0.war//org.jobrunr.dashboard.JobRunrtestWexServer.start(JobRunrtestWexServer.java:68)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration.testWexServer(JobRunrAutoConfiguration.java:97)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69.CGLIB$testWexServer$1(<generated>)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69$$FastClassBySpringCGLIB$$18621138.invoke(<generated>)
        at deployment.test-test-1.0.war//org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at deployment.test-test-1.0.war//org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at deployment.test-test-1.0.war//org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$6dc4f69.testWexServer(<generated>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.test-test-1.0.war//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 42 more
Caused by: java.lang.ClassNotFoundException: sun.misc.ServiceConfigurationError from [Module "deployment.test-test-1.0.war" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
        ... 56 more

10:53:31,734 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "test-test-1.0.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"test-test-1.0.war\".undertow-deployment" => "java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
    Caused by: java.lang.ClassNotFoundException: sun.misc.ServiceConfigurationError from [Module \"deployment.test-test-1.0.war\" from Service Module Loader]"}}
10:53:31,810 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 44) WFLYSRV0010: Deployed "test-test-1.0.war" (runtime-name : "test-test-1.0.war")
10:53:31,812 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."test-test-1.0.war".undertow-deployment: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testWexServer' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.dashboard.JobRunrtestWexServer]: Factory method 'testWexServer' threw exception; nested exception is java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
WFLYCTL0448: 1 additional services are down due to their dependencies being missing or failed
10:53:31,924 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
10:53:31,928 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
10:53:31,934 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
10:53:31,935 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: JBoss EAP 7.3.0.GA (WildFly Core 10.1.2.Final-redhat-00001) started (with errors) in 90509ms - Started 523 of 753 services (3 services failed or missing dependencies, 374 services are lazy, passive or on-demand)

**Comment by rdehuyss** [comment]
This is not a class from JobRunr: `org.jobrunr.dashboard.JobRunrtestWexServer` so I cannot give support on this.

Please also format your issues.

**Comment by wuyuan2009123** [comment]
[rdehuyss](https://github.com/rdehuyss)   I have the same problem ,java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
Caused by: java.lang.NoClassDefFoundError: sun/misc/ServiceConfigurationError
