### ISSUE TITLE
Migration issue for MongoDB

### ISSUE THREAD

**Issue by sanyaivanov** [jobrunr/jobrunr#408]
**Version of Jobrunr:** [5.0.0](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.0.0)

**Description of bug:**
At the start of the application, jobrunr cannot run migration for MongoDB and falls with an exception attached below. 

The main problem when method `isNoSqlMigration` of the class `RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider` tries find NoSQL migration by path and path `org/jobrunr/storage/nosql/mongo/migrations/` returns true we create an instance of `NoSqlMigrationByZipEntry` which try to call `ReflectionUtils.loadClass(ReflectionUtils.toClassNameFromFileName(name))` but the name is directory not a class and this path throws `ClassNotFoundException`.

**Logs:**
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [com/*******/gateway/***/configuration/JobRunnerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'storageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
2022-04-06T17:31:52.869864600Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
2022-04-06T17:31:52.869878700Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
2022-04-06T17:31:52.869895400Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
2022-04-06T17:31:52.869956900Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
2022-04-06T17:31:52.869977100Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
2022-04-06T17:31:52.870051700Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2022-04-06T17:31:52.870073000Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2022-04-06T17:31:52.870087200Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2022-04-06T17:31:52.870104400Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2022-04-06T17:31:52.870210000Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2022-04-06T17:31:52.870220600Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
2022-04-06T17:31:52.870237100Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
2022-04-06T17:31:52.870249700Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
2022-04-06T17:31:52.870424900Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
2022-04-06T17:31:52.870444800Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
2022-04-06T17:31:52.870485100Z 	... 27 common frames omitted
2022-04-06T17:31:52.870503200Z Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [com/*******/gateway/***/configuration/JobRunnerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'storageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
2022-04-06T17:31:52.870527000Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
2022-04-06T17:31:52.870544200Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
2022-04-06T17:31:52.870563600Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
2022-04-06T17:31:52.870577800Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
2022-04-06T17:31:52.870593300Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
2022-04-06T17:31:52.870610600Z 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
2022-04-06T17:31:52.870628000Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
2022-04-06T17:31:52.870643900Z 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
2022-04-06T17:31:52.870656300Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
2022-04-06T17:31:52.870686800Z 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
2022-04-06T17:31:52.870706800Z 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
2022-04-06T17:31:52.870727700Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
2022-04-06T17:31:52.870744000Z 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
2022-04-06T17:31:52.870796700Z 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
2022-04-06T17:31:52.870812700Z 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
2022-04-06T17:31:52.870885000Z 	... 41 common frames omitted
2022-04-06T17:31:52.871112000Z Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'storageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
2022-04-06T17:31:52.871130300Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
2022-04-06T17:31:52.871141800Z 	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
2022-04-06T17:31:52.871152600Z 	... 55 common frames omitted
2022-04-06T17:31:52.871186100Z Caused by: java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
2022-04-06T17:31:52.871225400Z 	at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrations(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:24)
2022-04-06T17:31:52.871286000Z 	at org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:27)
2022-04-06T17:31:52.871304900Z 	at org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:22)
2022-04-06T17:31:52.871321700Z 	at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.getMigrations(NoSqlDatabaseCreator.java:59)
2022-04-06T17:31:52.871499600Z 	at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrations(NoSqlDatabaseCreator.java:28)
2022-04-06T17:31:52.871529200Z 	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.runMigrations(MongoDBStorageProvider.java:469)
2022-04-06T17:31:52.871546200Z 	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.setUpStorageProvider(MongoDBStorageProvider.java:147)
2022-04-06T17:31:52.871562700Z 	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:128)
2022-04-06T17:31:52.871638300Z 	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:113)
2022-04-06T17:31:52.871661200Z 	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:93)
2022-04-06T17:31:52.871676500Z 	at com.*******.gateway.***.configuration.JobRunnerConfiguration.storageProvider(JobRunnerConfiguration.java:25)
2022-04-06T17:31:52.871805000Z 	at com.*******.gateway.***.configuration.JobRunnerConfiguration$$EnhancerBySpringCGLIB$$f78a960c.CGLIB$storageProvider$1(<generated>)
2022-04-06T17:31:52.871837300Z 	at com.*******.gateway.***.configuration.JobRunnerConfiguration$$EnhancerBySpringCGLIB$$f78a960c$$FastClassBySpringCGLIB$$868782d1.invoke(<generated>)
2022-04-06T17:31:52.871853400Z 	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
2022-04-06T17:31:52.871864100Z 	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
2022-04-06T17:31:52.871912800Z 	at com.*******.gateway.***.configuration.JobRunnerConfiguration$$EnhancerBySpringCGLIB$$f78a960c.storageProvider(<generated>)
2022-04-06T17:31:52.871932000Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-04-06T17:31:52.871971200Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-04-06T17:31:52.871989100Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-04-06T17:31:52.872003700Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-04-06T17:31:52.872017100Z 	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
2022-04-06T17:31:52.872183300Z 	... 56 common frames omitted
2022-04-06T17:31:52.872199900Z Caused by: java.lang.ClassNotFoundException: org.jobrunr.storage.nosql.mongo.migrations.
2022-04-06T17:31:52.872217200Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
2022-04-06T17:31:52.872233800Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
2022-04-06T17:31:52.872269000Z 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
2022-04-06T17:31:52.872287800Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
2022-04-06T17:31:52.872304100Z 	at java.base/java.lang.Class.forName0(Native Method)
2022-04-06T17:31:52.872320000Z 	at java.base/java.lang.Class.forName(Class.java:315)
2022-04-06T17:31:52.872332200Z 	at org.jobrunr.utils.reflection.ReflectionUtils.loadClass(ReflectionUtils.java:104)
2022-04-06T17:31:52.872368100Z 	at org.jobrunr.storage.nosql.common.migrations.NoSqlMigrationByZipEntry.<init>(NoSqlMigrationByZipEntry.java:18)
2022-04-06T17:31:52.872384500Z 	at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrationsFromZipInputStream(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:33)
2022-04-06T17:31:52.872406300Z 	at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrations(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:19)
2022-04-06T17:31:52.872431900Z 	... 76 common frames omitted
```

**Environment:**
I'm using JobRunr version: [5.0.0](https://mvnrepository.com/artifact/org.jobrunr/jobrunr/5.0.0)
I'm running on JRE / JDK : `13.0.1`
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): `MongoDB: MongoDBStorageProvider`

**How to Reproduce:**
Start an application with jobrnr version 5.0.0 and  MongoDBStorageProvider.

**Expected behavior:**
Performing the migration properly and starting the spring boot application

**Comment by rdehuyss** [comment]
Cannot reproduce... what I think is happening is that you have altered or treeshaken your application and not all necessary classes are available anymore. I also don't think you are running on JDK 13. Must be 11 or lower as you would otherwise be using the `NoSqlMigrationByPath` instead of `NoSqlMigrationByZipEntry`

Below the output of running a simple example using JobRunr and Mongo on JDK 17 (I'm on M1 and JDK13 is not an option). I know however of a lot of other companies running JobRunr on Java 13 with Mongo without troubles.

```java
rdehuyss@Ronalds-MacBook-Pro jobrunr-demo % java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
rdehuyss@Ronalds-MacBook-Pro jobrunr-demo % docker run -d -p 27017:27017 mongo:4.4
8de9a7622c4adc6d3cd9cf10248b4d0b62f4d039e45ee913017daa349d142207
rdehuyss@Ronalds-MacBook-Pro jobrunr-demo % java -jar ./build/libs/spring-jobRunr-demo-0.0.1-SNAPSHOT.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.6.5)

2022-04-06 20:51:53.567  INFO 40908 --- [           main] c.s.j.SpringJobRunrDemoApplication       : Starting SpringJobRunrDemoApplication using Java 17.0.1 on Ronalds-MacBook-Pro.local with PID 40908 (/Users/rdehuyss/Projects/Personal/jobrunr/examples/jobrunr-demo/build/libs/spring-jobRunr-demo-0.0.1-SNAPSHOT.jar started by rdehuyss in /Users/rdehuyss/Projects/Personal/jobrunr/examples/jobrunr-demo)
2022-04-06 20:51:53.568  INFO 40908 --- [           main] c.s.j.SpringJobRunrDemoApplication       : No active profile set, falling back to 1 default profile: "default"
2022-04-06 20:51:53.922  INFO 40908 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data MongoDB repositories in DEFAULT mode.
2022-04-06 20:51:53.927  INFO 40908 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 2 ms. Found 0 MongoDB repository interfaces.
2022-04-06 20:51:54.008  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration' of type [org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$$EnhancerBySpringCGLIB$$7ec4c608] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.010  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration' of type [org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration$$EnhancerBySpringCGLIB$$bdfc1172] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.011  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration' of type [org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.012  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSettingsConfiguration' of type [org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration$MongoClientSettingsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.034  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoClientSettings' of type [com.mongodb.MongoClientSettings] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.035  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoConnectionPoolMetricsConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoConnectionPoolMetricsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.037  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.051  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'management.metrics.export.simple-org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleProperties' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.053  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'simpleConfig' of type [org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimplePropertiesConfigAdapter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.054  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.054  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'micrometerClock' of type [io.micrometer.core.instrument.Clock$1] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.062  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'simpleMeterRegistry' of type [io.micrometer.core.instrument.simple.SimpleMeterRegistry] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.063  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoConnectionPoolTagsProvider' of type [io.micrometer.core.instrument.binder.mongodb.DefaultMongoConnectionPoolTagsProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.066  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoMetricsConnectionPoolListener' of type [io.micrometer.core.instrument.binder.mongodb.MongoMetricsConnectionPoolListener] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.067  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoMetricsConnectionPoolListenerClientSettingsBuilderCustomizer' of type [org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoConnectionPoolMetricsConfiguration$$Lambda$414/0x0000000800ed9500] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.067  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoCommandMetricsConfiguration' of type [org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoCommandMetricsConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.070  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoCommandTagsProvider' of type [io.micrometer.core.instrument.binder.mongodb.DefaultMongoCommandTagsProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.070  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoMetricsCommandListener' of type [io.micrometer.core.instrument.binder.mongodb.MongoMetricsCommandListener] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.070  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoMetricsCommandListenerClientSettingsBuilderCustomizer' of type [org.springframework.boot.actuate.autoconfigure.metrics.mongo.MongoMetricsAutoConfiguration$MongoCommandMetricsConfiguration$$Lambda$415/0x0000000800edb420] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.072  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.data.mongodb-org.springframework.boot.autoconfigure.mongo.MongoProperties' of type [org.springframework.boot.autoconfigure.mongo.MongoProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.073  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongoPropertiesCustomizer' of type [org.springframework.boot.autoconfigure.mongo.MongoPropertiesClientSettingsBuilderCustomizer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.096  INFO 40908 --- [           main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2022-04-06 20:51:54.119  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mongo' of type [com.mongodb.client.internal.MongoClientImpl] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.120  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$JobRunrJacksonAutoConfiguration' of type [org.jobrunr.spring.autoconfigure.JobRunrAutoConfiguration$JobRunrJacksonAutoConfiguration$$EnhancerBySpringCGLIB$$d27fd6fc] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.132  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jobRunrJsonMapper' of type [org.jobrunr.utils.mapper.jackson.JacksonJsonMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.136  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jobMapper' of type [org.jobrunr.jobs.mappers.JobMapper] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.141  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.jobrunr-org.jobrunr.spring.autoconfigure.JobRunrProperties' of type [org.jobrunr.spring.autoconfigure.JobRunrProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.154  INFO 40908 --- [localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:1, serverValue:2}] to localhost:27017
2022-04-06 20:51:54.154  INFO 40908 --- [localhost:27017] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:2, serverValue:1}] to localhost:27017
2022-04-06 20:51:54.154  INFO 40908 --- [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=25030125}
2022-04-06 20:51:54.187  INFO 40908 --- [           main] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:3, serverValue:3}] to localhost:27017
2022-04-06 20:51:54.204  INFO 40908 --- [           main] o.j.s.nosql.common.NoSqlDatabaseCreator  : Running migration NoSqlMigrationByPath{path=/org/jobrunr/storage/nosql/mongo/migrations/M001_CreateJobCollection.class}
2022-04-06 20:51:54.269  INFO 40908 --- [           main] o.j.s.nosql.common.NoSqlDatabaseCreator  : Running migration NoSqlMigrationByPath{path=/org/jobrunr/storage/nosql/mongo/migrations/M002_CreateRecurringJobCollection.class}
2022-04-06 20:51:54.281  INFO 40908 --- [           main] o.j.s.nosql.common.NoSqlDatabaseCreator  : Running migration NoSqlMigrationByPath{path=/org/jobrunr/storage/nosql/mongo/migrations/M003_CreateBackgroundJobServerCollection.class}
2022-04-06 20:51:54.293  INFO 40908 --- [           main] o.j.s.nosql.common.NoSqlDatabaseCreator  : Running migration NoSqlMigrationByPath{path=/org/jobrunr/storage/nosql/mongo/migrations/M004_CreateJobStatsCollection.class}
2022-04-06 20:51:54.296  INFO 40908 --- [           main] o.j.s.nosql.common.NoSqlDatabaseCreator  : Running migration NoSqlMigrationByPath{path=/org/jobrunr/storage/nosql/mongo/migrations/M005_CreateMetadataCollectionAndDropJobStats.class}
2022-04-06 20:51:54.316  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'storageProvider' of type [org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.320  INFO 40908 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'jobScheduler' of type [org.jobrunr.scheduling.JobScheduler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-04-06 20:51:54.429  INFO 40908 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-04-06 20:51:54.434  INFO 40908 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-04-06 20:51:54.434  INFO 40908 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.60]
2022-04-06 20:51:54.468  INFO 40908 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-04-06 20:51:54.468  INFO 40908 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 876 ms
2022-04-06 20:51:54.717  INFO 40908 --- [           main] j.s.t.ScheduledThreadPoolJobRunrExecutor : ThreadManager of type 'ScheduledThreadPool' started
2022-04-06 20:51:54.740  INFO 40908 --- [pool-2-thread-2] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:4, serverValue:5}] to localhost:27017
2022-04-06 20:51:54.740  INFO 40908 --- [pool-1-thread-1] org.mongodb.driver.connection            : Opened connection [connectionId{localValue:5, serverValue:4}] to localhost:27017
2022-04-06 20:51:54.748  INFO 40908 --- [pool-1-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer (a1adc25a-1f2a-4415-afda-1ac0543d85e3) using MongoDBStorageProvider and 80 BackgroundJobPerformers started successfully
2022-04-06 20:51:54.748  INFO 40908 --- [pool-1-thread-1] org.jobrunr.server.ServerZooKeeper       : Server a1adc25a-1f2a-4415-afda-1ac0543d85e3 is master (this BackgroundJobServer)
2022-04-06 20:51:54.880  INFO 40908 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-04-06 20:51:54.901  INFO 40908 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-04-06 20:51:54.909  INFO 40908 --- [           main] c.s.j.SpringJobRunrDemoApplication       : Started SpringJobRunrDemoApplication in 1.71 seconds (JVM running for 1.9)
The recurring job has begun.
Recurring job has finished...
```
