### ISSUE TITLE
[BUG]Jobrunr failed to start With Jobrunr (jobrunr-spring-boot-starter 5.0.0) version when storage is Mongo Db after dockerized the application

### ISSUE THREAD

**Issue by ereshzealous** [jobrunr/jobrunr#416]
**Are you running the latest version of JobRunr?**
Yes / No
Yes

**Describe the bug**
I was trying to dockerize the spring boot application for the version jobrunr-spring-boot-starter:5.0.0. There was no issue with the previous version ie., 4.0.10. The application boot up successfully all the beans from Jobrunr Autoconfiguration are successfully loaded and the application started successfully in docker container. 

I want to set the default retry for all the jobs to 5, so I migrated to 5.0.0. But had ran into issue, when run through docker not as standalone.
This issue is not seen in previous versions of JobRunr

The stack trace is 
```log
job-runr-mongo-springboot-jobrunr-dashboard-1  | 2022-04-11 08:50:16.837  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'recurringJobPostProcessor' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'recurringJobPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
mogodb_1                                       | {"t":{"$date":"2022-04-11T08:50:16.840+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn2","msg":"Interrupted operation as its client disconnected","attr":{"opId":36}}
mogodb_1                                       | {"t":{"$date":"2022-04-11T08:50:16.841+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.28.0.3:34164","uuid":"989c5224-6559-49e6-a719-e3767444a8ad","connectionId":1,"connectionCount":1}}
mogodb_1                                       | {"t":{"$date":"2022-04-11T08:50:16.841+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn2","msg":"Connection ended","attr":{"remote":"172.28.0.3:34166","uuid":"8ccdf66f-0c77-41d2-b9c3-d1bb576349c8","connectionId":2,"connectionCount":0}}
job-runr-mongo-springboot-jobrunr-dashboard-1  | 2022-04-11 08:50:16.861  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 
job-runr-mongo-springboot-jobrunr-dashboard-1  | 
job-runr-mongo-springboot-jobrunr-dashboard-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
job-runr-mongo-springboot-jobrunr-dashboard-1  | 2022-04-11 08:50:16.877 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
job-runr-mongo-springboot-jobrunr-dashboard-1  | 
job-runr-mongo-springboot-jobrunr-dashboard-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'recurringJobPostProcessor' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'recurringJobPostProcessor' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:270) ~[spring-context-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:762) ~[spring-context-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:567) ~[spring-context-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.5.jar!/:2.6.5]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at com.spring.jonrunr.JobrunrMongoApplication.main(JobrunrMongoApplication.java:10) ~[classes!/:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobScheduler' defined in class path resource [org/jobrunr/spring/autoconfigure/JobRunrAutoConfiguration.class]: Unsatisfied dependency expressed through method 'jobScheduler' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        ... 27 common frames omitted
job-runr-mongo-springboot-jobrunr-dashboard-1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageProvider' defined in class path resource [org/jobrunr/spring/autoconfigure/storage/JobRunrMongoDBStorageAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        ... 41 common frames omitted
job-runr-mongo-springboot-jobrunr-dashboard-1  | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception; nested exception is java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        ... 55 common frames omitted
job-runr-mongo-springboot-jobrunr-dashboard-1  | Caused by: java.lang.UnsupportedOperationException: Unable to load migrations from classpath.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrations(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:24) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:27) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:22) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.getMigrations(NoSqlDatabaseCreator.java:59) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrations(NoSqlDatabaseCreator.java:28) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.runMigrations(MongoDBStorageProvider.java:469) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.setUpStorageProvider(MongoDBStorageProvider.java:147) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:128) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:109) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration.mongoDBStorageProvider(JobRunrMongoDBStorageAutoConfiguration.java:29) ~[jobrunr-spring-boot-starter-5.0.0.jar!/:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration$$EnhancerBySpringCGLIB$$8f40574f.CGLIB$mongoDBStorageProvider$0(<generated>) ~[jobrunr-spring-boot-starter-5.0.0.jar!/:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration$$EnhancerBySpringCGLIB$$8f40574f$$FastClassBySpringCGLIB$$24b42546.invoke(<generated>) ~[jobrunr-spring-boot-starter-5.0.0.jar!/:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration$$EnhancerBySpringCGLIB$$8f40574f.mongoDBStorageProvider(<generated>) ~[jobrunr-spring-boot-starter-5.0.0.jar!/:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.17.jar!/:5.3.17]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        ... 56 common frames omitted
job-runr-mongo-springboot-jobrunr-dashboard-1  | Caused by: java.lang.ClassNotFoundException: org.jobrunr.storage.nosql.mongo.migrations.
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[app.jar:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at java.base/java.lang.Class.forName(Class.java:315) ~[na:na]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.utils.reflection.ReflectionUtils.loadClass(ReflectionUtils.java:104) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.migrations.NoSqlMigrationByZipEntry.<init>(NoSqlMigrationByZipEntry.java:18) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrationsFromZipInputStream(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:33) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.getMigrations(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.java:19) ~[jobrunr-5.0.0.jar!/:5.0.0]
job-runr-mongo-springboot-jobrunr-dashboard-1  |        ... 75 common frames omitted
job-runr-mongo-springboot-jobrunr-dashboard-1  | 
job-runr-mongo-springboot-jobrunr-dashboard-1 exited with code 1
```

**Environment**
I'm using JobRunr version: 5.0.0
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292):jdk 11
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Mongo DB

**How to Reproduce**
Please find it here
https://github.com/ereshzealous/job-runr-mongo

**Expected behavior**
The expected behavior application should start up even in a standalone or docker container.

**Additional context**
No

**Comment by ereshzealous** [comment]
With the same configuration, Jobrunr successfully deployed with docker containerization with the data store as Postgres for the 5.0.0 version only. Please find the sample here https://github.com/ereshzealous/jobrunr-demo
