### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by GayathryS** [jobrunr/jobrunr#422]
### Runtime information
- __Timestamp__: 2022-04-15T05:19:05.434Z
- __Location__: BackgroundJobServer bcc18ff1-3851-4db9-ac9b-f0b9d14e367d
- __JobRunr Version__: 3.1.2
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 1.8.0_321
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: bcc18ff1-3851-4db9-ac9b-f0b9d14e367d
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-14T07:09:45.961Z, lastHeartbeat: 2022-04-15T05:19:04.356Z)

#### Concurrent modified jobs:
Job id: e278020f-c855-423a-8d72-d015e162a410
	Local version: 22; Storage version: 36
	Local state: DELETED (at 2022-04-15T05:19:05.410Z) ← FAILED (at 2022-04-13T05:08:08.137Z) ← PROCESSING (at 2022-04-13T05:08:08.100Z)
	Storage state: DELETED (at 2022-04-13T06:23:25.943Z) ← ENQUEUED (at 2022-04-13T05:55:07.345Z) ← ENQUEUED (at 2022-04-13T05:55:07.156Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:208)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:192)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:130)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:96)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

### Runtime information
- __Timestamp__: 2022-04-18T04:36:38.670Z
- __Location__: BackgroundJobServer a731aea5-782d-4dca-bb97-3b3c2a66472c
- __JobRunr Version__: 3.1.2
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 1.8.0_321
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: a731aea5-782d-4dca-bb97-3b3c2a66472c
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-18T04:36:37.410Z, lastHeartbeat: 2022-04-18T04:36:37.441Z)

#### Concurrent modified jobs:
Job id: e278020f-c855-423a-8d72-d015e162a410
	Local version: 22; Storage version: 36
	Local state: DELETED (at 2022-04-18T04:36:38.593Z) ← FAILED (at 2022-04-13T05:08:08.137Z) ← PROCESSING (at 2022-04-13T05:08:08.100Z)
	Storage state: DELETED (at 2022-04-13T06:23:25.943Z) ← ENQUEUED (at 2022-04-13T05:55:07.345Z) ← ENQUEUED (at 2022-04-13T05:55:07.156Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:208)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:192)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:130)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:96)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by rdehuyss** [comment]
Please upgrade to the latest version of JobRunr.
