### ISSUE TITLE
[BUG] Upgrading from 4.0.10 to 5.0.1 is throwing exception for existing recurring jobs upon starting JobRunr

### ISSUE THREAD

**Issue by ms-precisely** [jobrunr/jobrunr#424]
Hi Team,

**Are you running the latest version of JobRunr?**
 No (Because upgrading to latest version is causing issues as described below)

**Describe the bug**
I am using BackgroundJob.scheduleRecurrently for recurring jobs. When upgrading to the latest 5.0.1 version, The JobRunr throws exception on server start up, since a property name has been changed from cronExpression to scheduleExpression in RecurringJob class of 5.x.x. Below is the error stacktrace

2022-04-21 10:48:18.995 ERROR 28372 --- [pool-5-thread-1] o.j.s.BackgroundJobServer                : Unexpected exception running `CheckIfAllJobsExistTask`

org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:84) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.jobs.mappers.JobMapper.deserializeRecurringJob(JobMapper.java:28) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.storage.nosql.mongo.mapper.JobDocumentMapper.toRecurringJob(JobDocumentMapper.java:91) ~[jobrunr-5.0.1.jar:5.0.1]
	at com.mongodb.client.internal.MappingIterable$1.accept(MappingIterable.java:62) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:123) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:59) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:69) ~[mongodb-driver-sync-4.4.2.jar:?]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.getRecurringJobs(MongoDBStorageProvider.java:357) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getRecurringJobs(ThreadSafeStorageProvider.java:173) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.server.tasks.CheckIfAllJobsExistTask.getDistinctRecurringJobSignaturesThatDoNotExistAnymore(CheckIfAllJobsExistTask.java:50) ~[jobrunr-5.0.1.jar:5.0.1]
	at org.jobrunr.server.tasks.CheckIfAllJobsExistTask.run(CheckIfAllJobsExistTask.java:31) ~[jobrunr-5.0.1.jar:5.0.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "cronExpression" (class org.jobrunr.jobs.RecurringJob), not marked as ignorable (8 known properties: "jobDetails", "zoneId", "version", "jobSignature", "scheduleExpression", "jobName", "id", "createdAt"])
 at [Source: (String)"{"version":0,"jobSignature":"com.precisely.schedule.schedulerservice.mq.SchedulerMQJobRequestProducerService.execute(com.precisely.discovery.saas.common.profiling.schedule.SchedulerJobTask)","jobName":"com.precisely.schedule.schedulerservice.mq.SchedulerMQJobRequestProducerService.execute(SchedulerJobTask(scheduleId=6260249c8d85b92411ff0527, tenantId=10001abc, scheduleJobDetails=ScheduleJobDetails(jobType=RUN_PROFILE, entityType=PROFILE, entityId=8a8a81157d70d79e017d746aed010f0b, jobRunOptions=n"[truncated 666 chars]; line: 1, column: 1139] (through reference chain: org.jobrunr.jobs.RecurringJob["cronExpression"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597) ~[jackson-databind-2.13.2.2.jar:2.13.2.2]
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:80) ~[jobrunr-5.0.1.jar:5.0.1]
	... 16 more

2022-04-21 10:48:19.623  INFO 28372 --- [pool-4-thread-1] o.j.s.BackgroundJobServer                : JobRunr BackgroundJobServer (c41c24f5-e314-4f70-9acb-1561704fb40d) using MongoDBStorageProvider and 7 BackgroundJobPerformers started successfully

**Environment**
I'm using JobRunr version: 4.0.10
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292):  java 11 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): MongoDB

**How to Reproduce**
Using JobRunr version 4.0.10 schedule recurring jobs. Now upgrade the version to 5.0.1 and restart the server.

**Expected behavior**
There is a breaking change in the major version 5 of JobRunr. Is there any script available that can be applied to the StorageProvider and the version upgrade can be seamless in this case.

**Additional context**
My scheduling application that uses JobRunr is already in production so if there is any script for DB upgrade as well, it will be helpful.

Thanks.

**Comment by rdehuyss** [comment]
Hi @ms-precisely ,

this was mentioned as a breaking change in the release notes of JobRunr 5.0.0.

Please star the Github repo if you are enjoying JobRunr.

**Comment by ms-precisely** [comment]
Thank you for the quick response Ronald.
