### ISSUE TITLE
[BUG] After Mongo Error no enqueued jobs are processed 

### ISSUE THREAD

**Issue by pdavidson** [jobrunr/jobrunr#443]
**Are you running the latest version of JobRunr?** Yes - Pro 5.0.4
If no, please first upgrade to the latest JobRunr version and check whether the issue still exists.

**Describe the bug**
Mongo exception throw, jobs are continued to be enqueued, but no jobs are processed since the error.
```
com.mongodb.MongoCommandException: Command failed with error 16945: 'Exceeded memory limit for $group or $lookup. Pass allowDiskUse:true to opt in.' on server hats-dw-docdb.prod-cloud.appdetex.com:27017. The full response is {"ok": 0.0, "operationTime": {"$timestamp": {"t": 1651596748, "i": 1}}, "code": 16945, "errmsg": "Exceeded memory limit for $group or $lookup. Pass allowDiskUse:true to opt in."}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:418) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:342) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:117) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:348) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:228) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$4(CommandOperationHelper.java:210) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$executeRetryableRead$5(CommandOperationHelper.java:207) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:213) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeRetryableRead(CommandOperationHelper.java:193) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:195) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:306) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:46) ~[mongodb-driver-core-4.4.0.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191) ~[mongodb-driver-sync-4.4.0.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135) ~[mongodb-driver-sync-4.4.0.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92) ~[mongodb-driver-sync-4.4.0.jar:na]
	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:121) ~[mongodb-driver-sync-4.4.0.jar:na]
	at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:59) ~[mongodb-driver-sync-4.4.0.jar:na]
	at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:69) ~[mongodb-driver-sync-4.4.0.jar:na]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.getAwaitingJobsOnOtherJobWithState(MongoDBStorageProvider.java:507) ~[jobrunr-pro-5.0.4.jar:5.0.4]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getAwaitingJobsOnOtherJobWithState(ThreadSafeStorageProvider.java:247) ~[jobrunr-pro-5.0.4.jar:5.0.4]
	at org.jobrunr.server.JobZooKeeper.checkForAwaitingJobs(JobZooKeeper.java:150) ~[jobrunr-pro-5.0.4.jar:5.0.4]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:109) ~[jobrunr-pro-5.0.4.jar:5.0.4]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:84) ~[jobrunr-pro-5.0.4.jar:5.0.4]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Environment**
I'm using JobRunr version: 5.0.4
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): Temurin 17
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): DocumentDB

**Comment by pdavidson** [comment]
Closing as this appears to be a coincidence for the root cause
