### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by canhvinhdev** [jobrunr/jobrunr#444]
### Runtime information
- __Timestamp__: 2022-04-29T07:01:02.114448Z
- __Location__: BackgroundJobServer 5022d134-ff8e-4a89-ae2b-3fe80462a98b
- __JobRunr Version__: 4.0.5
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 5022d134-ff8e-4a89-ae2b-3fe80462a98b
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2022-04-29T06:23:28.025Z, lastHeartbeat: 2022-04-29T07:00:59.712Z)

#### Concurrent modified jobs:
Job id: 157a3c7f-a693-4394-b953-eaa6807ce7a4
	Local version: 47; Storage version: 48
	Local state: DELETED (at 2022-04-29T06:59:32.013503Z) ← PROCESSING (at 2022-04-29T06:59:31.997016Z on BackgroundJobServer 5022d134-ff8e-4a89-ae2b-3fe80462a98b) ← ENQUEUED (at 2022-04-29T06:48:12.895441Z)
	Storage state: DELETED (at 2022-04-29T06:59:24.788867Z) ← PROCESSING (at 2022-04-29T06:59:16.984535Z on BackgroundJobServer 5022d134-ff8e-4a89-ae2b-3fe80462a98b) ← ENQUEUED (at 2022-04-29T06:48:12.895441Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2022-05-04T05:06:57.351273Z
- __Location__: BackgroundJobServer 7c4c0e5f-9c2a-489f-bd5a-f3d4cdca550b
- __JobRunr Version__: 4.0.5
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 7c4c0e5f-9c2a-489f-bd5a-f3d4cdca550b
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2022-05-04T05:04:40.647Z, lastHeartbeat: 2022-05-04T05:06:55.954Z)

#### Concurrent modified jobs:
Job id: 85fcddc7-9268-4875-9c4a-a27e00744ce9
	Local version: 75; Storage version: 77
	Local state: DELETED (at 2022-05-04T05:05:27.180892Z) ← PROCESSING (at 2022-05-04T05:05:27.151889Z on BackgroundJobServer 7c4c0e5f-9c2a-489f-bd5a-f3d4cdca550b) ← ENQUEUED (at 2022-05-04T05:05:02.733537Z)
	Storage state: ENQUEUED (at 2022-05-04T05:06:52.741414Z) ← DELETED (at 2022-05-04T05:05:24.519711Z) ← PROCESSING (at 2022-05-04T05:05:12.151177Z on BackgroundJobServer 7c4c0e5f-9c2a-489f-bd5a-f3d4cdca550b)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2022-05-05T09:28:56.462177Z
- __Location__: BackgroundJobServer d667ed5a-2350-44bd-b4e9-f21bde13e396
- __JobRunr Version__: 4.0.5
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: d667ed5a-2350-44bd-b4e9-f21bde13e396
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2022-05-05T08:05:04.633Z, lastHeartbeat: 2022-05-05T09:28:52.228Z)

#### Concurrent modified jobs:
Job id: 247b6d74-6a13-4bda-b67f-81d1c8b8d4f9
	Local version: 108; Storage version: 109
	Local state: DELETED (at 2022-05-05T09:27:26.328892Z) ← PROCESSING (at 2022-05-05T09:27:26.317296Z on BackgroundJobServer d667ed5a-2350-44bd-b4e9-f21bde13e396) ← ENQUEUED (at 2022-05-05T09:00:51.274855Z)
	Storage state: DELETED (at 2022-05-05T09:27:14.361328Z) ← PROCESSING (at 2022-05-05T09:27:11.298843Z on BackgroundJobServer d667ed5a-2350-44bd-b4e9-f21bde13e396) ← ENQUEUED (at 2022-05-05T09:00:51.274855Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2022-05-04T04:57:36.498229Z
- __Location__: BackgroundJobServer decac751-e2a5-4470-9845-9e36f74c4d40
- __JobRunr Version__: 4.0.5
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 11.0.12
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: decac751-e2a5-4470-9845-9e36f74c4d40
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2022-05-04T04:53:19.407Z, lastHeartbeat: 2022-05-04T04:57:35.069Z)

#### Concurrent modified jobs:
Job id: 85fcddc7-9268-4875-9c4a-a27e00744ce9
	Local version: 72; Storage version: 73
	Local state: DELETED (at 2022-05-04T04:56:06.235204Z) ← PROCESSING (at 2022-05-04T04:56:06.220363Z on BackgroundJobServer decac751-e2a5-4470-9845-9e36f74c4d40) ← ENQUEUED (at 2022-05-04T04:54:05.861802Z)
	Storage state: DELETED (at 2022-05-04T04:56:03.822860Z) ← PROCESSING (at 2022-05-04T04:55:51.194733Z on BackgroundJobServer decac751-e2a5-4470-9845-9e36f74c4d40) ← ENQUEUED (at 2022-05-04T04:54:05.861802Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:205)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:92)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by rdehuyss** [comment]
Please upgrade to the latest version first.

Thanks

**Comment by rdehuyss** [comment]
Is this in your local laptop?
