### ISSUE TITLE
[BUG] Jobrunr shutdown on unrecoverable error but left spring context running

### ISSUE THREAD

**Issue by fabiofalci** [jobrunr/jobrunr#445]
**Are you running the latest version of JobRunr?**
Running v5.0.1, just saw the release of v5.1.0.

**Describe the bug**
It seems there was some database connection issues at some point.

```
<#773241dc> o.p.u.PSQLException: This connection has been closed.
	at o.p.j.PgConnection.checkClosed(PgConnection.java:877)
	at o.p.j.PgConnection.setNetworkTimeout(PgConnection.java:1610)
	at c.z.h.pool.PoolBase.setNetworkTimeout(PoolBase.java:566)
	at c.z.h.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at c.z.h.p.HikariPool.getConnection(HikariPool.java:186)
	at c.z.h.p.HikariPool.getConnection(HikariPool.java:162)
	at c.z.h.HikariDataSource.getConnection(HikariDataSource.java:128)
	at o.j.s.s.c.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:174)
	... 10 common frames omitted
Wrapped by: <#66d42ee1> j.s.SQLTransientConnectionException: HikariPool - Connection is not available, request timed out after 30000ms.
	at c.z.h.p.HikariPool.createTimeoutException(HikariPool.java:696)
	at c.z.h.p.HikariPool.getConnection(HikariPool.java:197)
	at c.z.h.p.HikariPool.getConnection(HikariPool.java:162)
	at c.z.h.HikariDataSource.getConnection(HikariDataSource.java:128)
	at o.j.s.s.c.DefaultSqlStorageProvider.getJobStats(DefaultSqlStorageProvider.java:343)
	... 12 common frames omitted
Wrapped by: <#653b4055> o.j.s.StorageException: java.sql.SQLTransientConnectionException: HikariPool - Connection is not available, request timed out after 30000ms.
	at o.j.s.s.c.DefaultSqlStorageProvider.getJobStats(DefaultSqlStorageProvider.java:346)
	at o.j.s.AbstractStorageProvider.notifyJobStatsOnChangeListeners(AbstractStorageProvider.java:73)
	at o.j.s.s.c.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:177)
	at o.j.s.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:105)
	at o.j.s.BackgroundJobPerformer.saveAndRunStateRelatedJobFilters(BackgroundJobPerformer.java:135)
	at o.j.s.BackgroundJobPerformer.updateJobStateToProcessingRunJobFiltersAndReturnIfProcessingCanStart(BackgroundJobPerformer.java:66)
	at o.j.s.BackgroundJobPerformer.run(BackgroundJobPerformer.java:41)
	at j.u.c.Executors$RunnableAdapter.call(Unknown Source)
	at j.u.c.FutureTask.run(Unknown Source)
	at j.u.c.ScheduledThre...
```

A few of those.

I then see that jobrunr started to shutdown: `An unrecoverable error occurred. Shutting server down...`
However that didn't stop the spring context, so the service was still running and producing jobs but not processing them.

**Environment**
I'm using JobRunr version: 5.0.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): openjdk version "11.0.15" 2022-04-19 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): Postgres 

**How to Reproduce**
A database connection issue is required.

**Expected behavior**
I would expected jobrunr to shutdown the spring context as well, that, in our case, would trigger a creation of another instance.

Even though I'll try to check database connections, so it doesn't happen again I do think jobrunr should not get stuck like that.

**Additional context**
There was 2 job servers. One got stuck (I mean it was accepting jobs but not processing them) and the other was running the jobs fine.

However some weeks before that, on v4.0.10, it did happen where the 2 jobs servers had the database issue, making both stuck.

Using jobrunr-spring-boot-starter.

**Comment by fabiofalci** [comment]
I see. I guess I'll have to manually control that bean then, in case of a shutdown.

**Comment by rdehuyss** [comment]
Or ask your management to get the Pro version ;-).

Is there a reason why you would not do that?

**Comment by fabiofalci** [comment]
We are still evaluating it :)  
Although we did push to prod on a small use case, we're still checking if we are going to use more.

**Comment by rdehuyss** [comment]
Thanks for that feedback - I really appreciate it! I also reached out to LinkedIn and can give perhaps some more info of customers using JobRunr and seeing +20% developer productivity for a reason I could never image.
