### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by jmrsnt** [jobrunr/jobrunr#502]
### Runtime information
- __Timestamp__: 2022-06-28T09:45:02.143491Z
- __Location__: BackgroundJobServer f17cd82d-6121-4365-90c4-9afa8322f6bd
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 11.0.15
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: f17cd82d-6121-4365-90c4-9afa8322f6bd
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2022-06-28T09:39:57.750009Z, lastHeartbeat: 2022-06-28T09:44:58.845968Z)

#### Concurrent modified jobs:
Job id: 23feca0f-4951-4873-9807-04e43c769c10
__Local version__: 8; Storage version: 9
__Local state__: ENQUEUED (at 2022-06-28T09:44:52.393641Z) <- SCHEDULED (at 2022-06-28T09:44:38.666043Z) <- FAILED (at 2022-06-28T09:44:38.664105Z) <- PROCESSING (updated at 2022-06-28T09:44:37.874556Z on BackgroundJobServer f17cd82d-6121-4365-90c4-9afa8322f6bd and started at 2022-06-28T09:44:02.928232Z) <- ENQUEUED (at 2022-06-28T09:43:54.873505Z) <- SCHEDULED (at 2022-06-28T09:43:43.582580Z)
__Storage state__: SCHEDULED (at 2022-06-28T09:44:38.666043Z) <- FAILED (at 2022-06-28T09:44:38.664105Z) <- PROCESSING (updated at 2022-06-28T09:44:37.874556Z on BackgroundJobServer f17cd82d-6121-4365-90c4-9afa8322f6bd and started at 2022-06-28T09:44:02.928232Z) <- ENQUEUED (at 2022-06-28T09:43:54.873505Z) <- SCHEDULED (at 2022-06-28T09:43:43.582580Z) <- FAILED (at 2022-06-28T09:43:43.580315Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:196)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:119)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:98)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment]
Hi @jmrsnt , any reason why you closed this? What happened?

**Comment by jmrsnt** [comment]
Hi, @rdehuyss. Thanks for the feedback. This exception occurred after scheduling a Job that had a load of 2.7GB of data, however, when deleting the tables and the view, generated by migrations, and restarting the application, the job successfully executed. I don't know exactly why, but it fixed it.

**Comment by rdehuyss** [comment]
Can I ask how you arrived on 2.7 GB of data? These are corner cases I'm interested in...
