### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by dmurphy-ambra** [jobrunr/jobrunr#534]
### Runtime information
- __Timestamp__: 2022-08-09T00:10:32.795Z
- __Location__: BackgroundJobServer 3c393f4c-576a-473c-b3db-cab7e3bc417a
- __JobRunr Version__: 5.1.9
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 1.8.0-adoptopenjdk
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 3f565764-7d2e-401e-a8b3-7ccc521beb6c
(workerPoolSize: 128, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-08T20:04:24.589Z, lastHeartbeat: 2022-08-09T00:10:29.175Z)
- BackgroundJobServer id: 3c393f4c-576a-473c-b3db-cab7e3bc417a
(workerPoolSize: 128, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-08T20:04:27.409Z, lastHeartbeat: 2022-08-09T00:10:18.925Z)

#### Concurrent modified jobs:
Job id: f8deff21-311f-36a1-9c33-6461d165edfb
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2022-08-09T00:10:32.792Z on BackgroundJobServer 3c393f4c-576a-473c-b3db-cab7e3bc417a and started at 2022-08-09T00:10:24.208Z) ← ENQUEUED (at 2022-08-09T00:10:24.197Z)
	Storage state: PROCESSING (updated at 2022-08-09T00:10:32.728Z on BackgroundJobServer 3f565764-7d2e-401e-a8b3-7ccc521beb6c and started at 2022-08-09T00:10:32.728Z) ← ENQUEUED (at 2022-08-09T00:10:32.716Z) ← SCHEDULED (at 2022-08-09T00:10:32.580Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:236)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Runtime information
- __Timestamp__: 2022-08-09T01:21:51.844Z
- __Location__: BackgroundJobServer 3f565764-7d2e-401e-a8b3-7ccc521beb6c
- __JobRunr Version__: 5.1.9
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 1.8.0-adoptopenjdk
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 3f565764-7d2e-401e-a8b3-7ccc521beb6c
(workerPoolSize: 128, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-08T20:04:24.589Z, lastHeartbeat: 2022-08-09T01:21:45.460Z)

#### Concurrent modified jobs:
Job id: fbb9f38a-b147-31f8-8147-b0bd31dd5840
	Local version: 2; Storage version: 4
	Local state: DELETED (at 2022-08-09T01:21:21.819Z) ← PROCESSING (updated at 2022-08-09T01:21:21.817Z on BackgroundJobServer 3f565764-7d2e-401e-a8b3-7ccc521beb6c and started at 2022-08-09T01:21:17.949Z) ← ENQUEUED (at 2022-08-09T01:21:17.839Z)
	Storage state: SCHEDULED (at 2022-08-09T01:21:21.841Z) ← FAILED (at 2022-08-09T01:21:21.841Z) ← PROCESSING (updated at 2022-08-09T01:21:21.836Z on BackgroundJobServer 3f565764-7d2e-401e-a8b3-7ccc521beb6c and started at 2022-08-09T01:21:21.836Z) ← ENQUEUED (at 2022-08-09T01:21:21.821Z) ← SCHEDULED (at 2022-08-09T01:21:21.773Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:236)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:93)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rdehuyss** [comment]
# SevereJobRunrException occurred in BackgroundJobServer 86f27c5f-6a89-41ad-9509-26b9c4ab28ed: Could not resolve ConcurrentJobModificationException

### Runtime information
- __Timestamp__: 2022-08-08T20:32:37.767Z
- __Location__: BackgroundJobServer 86f27c5f-6a89-41ad-9509-26b9c4ab28ed
- __JobRunr Version__: 5.1.9
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 1.8.0-adoptopenjdk
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 86f27c5f-6a89-41ad-9509-26b9c4ab28ed
(workerPoolSize: 288, pollIntervalInSeconds: 15, firstHeartbeat: 2022-08-08T19:30:04.275Z, lastHeartbeat: 2022-08-08T20:32:35.427Z)

### Diagnostics from exception
#### Concurrent modified jobs:
Job id: 5d7df19e-4112-306a-b4a4-26edb5bfe9e5
    Local version: 3; Storage version: 4
    Local state: DELETED (at 2022-08-08T20:31:52.739Z) ← PROCESSING (updated at 2022-08-08T20:31:52.738Z on BackgroundJobServer 86f27c5f-6a89-41ad-9509-26b9c4ab28ed and started at 2022-08-08T20:31:37.738Z) ← ENQUEUED (at 2022-08-08T20:31:37.730Z) ← SCHEDULED (at 2022-08-08T20:31:22.730Z)
    Storage state: SCHEDULED (at 2022-08-08T20:31:52.752Z) ← FAILED (at 2022-08-08T20:31:52.751Z) ← PROCESSING (updated at 2022-08-08T20:31:52.750Z on BackgroundJobServer 86f27c5f-6a89-41ad-9509-26b9c4ab28ed and started at 2022-08-08T20:31:52.750Z) ← ENQUEUED (at 2022-08-08T20:31:52.742Z) ← SCHEDULED (at 2022-08-08T20:31:42.029Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
    at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:236)
    at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:93)
    at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```
