### ISSUE TITLE
[BUG] double[] array parameters are not supported in enqueued method after v4.0.2: Cannot deserialize value of type `[D` 

### ISSUE THREAD

**Issue by feiniao33** [jobrunr/jobrunr#536]
> I found that when I upgrade my app's jobrunr to any version above v4.0.1 even v5, I will get MismatchedInputException which get no exception in v4.0.1 or even v3. I think there must be a mistake in v4.0.2 Bugfixes most probably #254. Hope someone come to fix it.

```
15:49:06.161 [backgroundjob-zookeeper-pool-1-thread-2] WARN  org.jobrunr.server.JobZooKeeper - JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
               at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
               at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:81)
               at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
               at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:189)
               at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
               at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:42)
               at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
               at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
               at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
               at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
               at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
               at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
               at org.jobrunr.storage.sql.common.JobTable.selectJobsByState(JobTable.java:117)
               at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobs(DefaultSqlStorageProvider.java:224)
               at org.jobrunr.storage.ThreadSafeStorageProvider.getJobs(ThreadSafeStorageProvider.java:132)
               at org.jobrunr.server.JobZooKeeper.checkForEnqueuedJobs(JobZooKeeper.java:161)
               at org.jobrunr.server.JobZooKeeper.onboardNewWorkIfPossible(JobZooKeeper.java:151)
               at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
               at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
               at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
               at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
               at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
               at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
               at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `[D` from Floating-point value (token `JsonToken.VALUE_NUMBER_FLOAT`)
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.jobrunr.jobs.Job["jobDetails"]->org.jobrunr.jobs.JobDetails["jobParameters"]->java.util.ArrayList[0])
               at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
               at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1601)
               at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1375)
               at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1280)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers.handleNonArray(PrimitiveArrayDeserializers.java:226)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$DoubleDeser.deserialize(PrimitiveArrayDeserializers.java:889)
               at com.fasterxml.jackson.databind.deser.std.PrimitiveArrayDeserializers$DoubleDeser.deserialize(PrimitiveArrayDeserializers.java:863)
               at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
               at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
               at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3261)
               at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:34)
               at org.jobrunr.utils.mapper.jackson.modules.JobParameterDeserializer.deserialize(JobParameterDeserializer.java:18)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
               at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
               at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
               at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
               at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
               at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
               at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3548)
               at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3516)
               at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.deserialize(JacksonJsonMapper.java:77)
               ... 22 common frames omitted

```

**Comment by feiniao33** [comment]
double[] xValues;
double[] yValues;
jobScheduler.enqueue(()->this.run(this.xValues,this.yValues))

just like this code snippet, it won't work from v4.0.2 to newer versions.

**Comment by rdehuyss** [comment]
Please follow the bug report guidelines in the future. Fixing the layout of your github issue costs me time. If you do not know how to do so, see https://letmegooglethat.com/?q=how+to+format+github+issue

**Comment by feiniao33** [comment]
> Please follow the bug report guidelines in the future. Fixing the layout of your github issue costs me time. If you do not know how to do so, see https://letmegooglethat.com/?q=how+to+format+github+issue

Thanks a lot. Sorry about the format. Next time I will be careful about it. Thanks for fixing the bug.

**Comment by rdehuyss** [comment]
Thanks, appreciate it! Please star the repo if you're happy with the quick support.

**Comment by feiniao33** [comment]
> Thanks, appreciate it! Please star the repo if you're happy with the quick support.

Of course I appreciate it a lot. Starred and thanks for the effort.

**Comment by rdehuyss** [comment]
Just to avoid confusing: I meant that I appreciate it that you will next time be careful about formatting. :smile:.

I don't want to sound cocky ;-)

**Comment by feiniao33** [comment]
> Just to avoid confusing: I meant that I appreciate it that you will next time be careful about formatting. :smile:.
> 
> I don't want to sound cocky ;-)

Hahahah... It's the first time I found a real bug in using the package so I just ignore the format and I don't even think of such a quickly bugfix. I just really appreciate it.😄
