### ISSUE TITLE
[Feature] Support for Wildfly

### ISSUE THREAD

**Issue by Kristoffer-Smedlund** [jobrunr/jobrunr#564]
**Describe the bug**
When using JobRunr while running the application in Wildfly and using the MongoDBStorageProvider an exception is thrown.
When JobRunr tries to run the migrations for mongodb it dynamically looks up the files' URL. Using Wildfly the URL will be of type "vfs://" since it uses VFS (virtual file system). This is not supported by JobRunrs ClassPathResourceProvider.getFileSystemProviderByScheme

The following is the stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Unknown FileSystem required vfs
	at deployment.checkout-api.war//org.jobrunr.utils.resources.ClassPathResourceProvider.getFileSystemProviderByScheme(ClassPathResourceProvider.java:123)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at deployment.checkout-api.war//org.jobrunr.utils.resources.ClassPathResourceProvider.getFileSystemProvider(ClassPathResourceProvider.java:100)
	at deployment.checkout-api.war//org.jobrunr.utils.resources.ClassPathResourceProvider.toPath(ClassPathResourceProvider.java:81)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.common.migrations.DefaultNoSqlMigrationProvider.getMigrations(DefaultNoSqlMigrationProvider.java:16)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:27)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(NoSqlDatabaseMigrationsProvider.java:22)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.getMigrations(NoSqlDatabaseCreator.java:59)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrations(NoSqlDatabaseCreator.java:28)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.runMigrations(MongoDBStorageProvider.java:480)
	at deployment.checkout-api.war//org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.setUpStorageProvider(MongoDBStorageProvider.java:144)
```

**Environment**
I'm using JobRunr version: 5.2.0
I'm running on JRE / JDK: java zulu-17.34.19
I'm using the following StorageProvider: MongoDBStorageProvider

**How to Reproduce**
Run your code by building a WAR file and deploy it in a Wildfly application server. Use MongoDBStorageProvider. It will not start any job.

**Expected behavior**
It should support VFS.

**Comment by rdehuyss** [comment]
As the group of wildfly users is really small and it requires quite some effort to support it, I won't be developing this feature in my free time.

Feel free to create a PR for it. If not, I may be open to develop this if you would take a Pro subscription.
