### ISSUE TITLE
[BUG]Encountering exception when using Job Runner Pro Librayr

### ISSUE THREAD

**Issue by nagabhushanss** [jobrunr/jobrunr#575]
**Are you running the latest version of JobRunr?**
Yes( 5.1.9)

**Describe the bug**
We are seeing the below exception in the background server of Job Runner and it is not able to trigger the jobs when ever below exception is encountered

```java
2022-09-28 09:29:56.297  WARN 1 --- [ool-17-thread-2] o.j.s.JobZooKeeper                       : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

java.lang.NullPointerException: null
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.lambda$getRecurringJobIds$8(MongoDBStorageProvider.java:407) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at com.mongodb.client.internal.MappingIterable$1.accept(MappingIterable.java:62) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:123) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:59) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:69) ~[mongodb-driver-sync-4.4.2.jar:?]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.getRecurringJobIds(MongoDBStorageProvider.java:408) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getRecurringJobIds(ThreadSafeStorageProvider.java:196) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.processRecurringJobs(JobZooKeeper.java:200) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.checkForRecurringJobs(JobZooKeeper.java:115) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:98) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:78) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Environment**
I'm using JobRunr version: 5.1.9
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): JRE 1.8
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): MongoDBStorageProvider

**How to Reproduce**
This is happening on the backround job server during triggering of jobs

**Expected behavior**
No Exception and job Should get triggerred

**Additional context**

**Comment by nagabhushanss** [comment]
2022-09-28 09:29:56.297  WARN 1 --- [ool-17-thread-2] o.j.s.JobZooKeeper                       : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

java.lang.NullPointerException: null
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.lambda$getRecurringJobIds$8(MongoDBStorageProvider.java:407) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at com.mongodb.client.internal.MappingIterable$1.accept(MappingIterable.java:62) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:123) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:59) ~[mongodb-driver-sync-4.4.2.jar:?]
	at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:69) ~[mongodb-driver-sync-4.4.2.jar:?]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.getRecurringJobIds(MongoDBStorageProvider.java:408) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getRecurringJobIds(ThreadSafeStorageProvider.java:196) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.processRecurringJobs(JobZooKeeper.java:200) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.checkForRecurringJobs(JobZooKeeper.java:115) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:98) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:78) ~[jobrunr-pro-5.1.9.jar:5.1.9]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

**Comment by rdehuyss** [comment]
Can I know which company you are? This way, i can easily contact you to find the root cause of this.

**Comment by nagabhushanss** [comment]
Precisely..We have procured Pro License and some of my team members are working to get access to Pro Community.
Additionally if you can answer some of our queries posted in https://github.com/jobrunr/jobrunr/discussions/574 it would really help

**Comment by rdehuyss** [comment]
Hi @nagabhushanss ,

this exception happens when upgrading from JobRunr 4.0 to JobRunr 5.0. See following release notes:

See the blog post: https://www.jobrunr.io/en/blog/2022-03-30-jobrunr-v5.0.0/ 
__Please make sure to have no recurring jobs nor scheduled jobs in your application before upgrading.__

I was able to add an extra check that makes sure this exception will not happen though.

This bug report will also move to the JobRunr Pro Github repo.
