### ISSUE TITLE
JobRunr BackgroundJobServer failed to start In DB2_10.5[BUG]

### ISSUE THREAD

**Issue by VincentRoy-Git** [jobrunr/jobrunr#588]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
2022-10-21 13:55:57.555 ERROR 5397 --- [backgroundjob-zookeeper-pool-1-thread-1] org.jobrunr.server.ServerZooKeeper       : An unrecoverable error occurred. Shutting server down...

org.jobrunr.storage.StorageException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=LIMIT;;FETCH FIRST <n> ROWS ONLY, DRIVER=4.25.13
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:62) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:35) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[na:1.8.0_262]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[na:1.8.0_262]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[na:1.8.0_262]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_262]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[na:1.8.0_262]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_262]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[na:1.8.0_262]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:97) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:115) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:74) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:114) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:70) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:47) ~[jobrunr-5.1.0.jar!/:5.1.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_262]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_262]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_262]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_262]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_262]
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=LIMIT;;FETCH FIRST <n> ROWS ONLY, DRIVER=4.25.13
	at com.ibm.db2.jcc.am.b6.a(b6.java:810) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.b6.a(b6.java:66) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.b6.a(b6.java:140) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k3.c(k3.java:2824) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k3.d(k3.java:2808) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k3.a(k3.java:2234) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.a(k4.java:8242) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.t4.ab.i(ab.java:206) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.t4.ab.b(ab.java:96) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.t4.p.a(p.java:32) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.t4.av.i(av.java:150) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k3.al(k3.java:2203) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.bq(k4.java:3730) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.a(k4.java:4609) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.b(k4.java:4182) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.bd(k4.java:780) ~[jcc-11.1.4.4.jar!/:na]
	at com.ibm.db2.jcc.am.k4.executeQuery(k4.java:745) ~[jcc-11.1.4.4.jar!/:na]
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213) ~[druid-1.2.11.jar!/:1.2.11]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:59) ~[jobrunr-5.1.0.jar!/:5.1.0]
	... 21 common frames omitted

2022-10-21 13:55:57.559 ERROR 5397 --- [backgroundjob-zookeeper-pool-1-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer failed to start

**Environment**
I'm using JobRunr version: (5.3.0)
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): (Java 1.8.0_262)
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): (DB2/NT64 10.5) 

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
@SpringBootApplication
public class HmsApplication implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("doc.html").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**").addResourceLocations("classpath:/META-INF/resources/webjars/");
    }

    public static void main(String[] args) {
        SpringApplication.run(HmsApplication.class, args);
    }

    @Bean
    public JobRunrConfigurationResult initJobRunr(ApplicationContext applicationContext) {
        return JobRunr.configure()
                .useJobActivator(applicationContext::getBean)
                .useStorageProvider(SqlStorageProviderFactory
                        .using(applicationContext.getBean(DataSource.class)))
                .useBackgroundJobServer()
                .useDashboard(8001)
                .initialize();
    }

    @Bean
    public JobScheduler initJobScheduler(JobRunrConfigurationResult jobRunrConfigurationResult) {
        return jobRunrConfigurationResult.getJobScheduler();
    }

    @Bean
    public JobRequestScheduler initJobRequestScheduler(JobRunrConfigurationResult jobRunrConfigurationResult) {
        return jobRunrConfigurationResult.getJobRequestScheduler();
    }

}
```

**Expected behavior**

**Additional context**

**Comment by rdehuyss** [comment]
I do not provide support on the OSS version unless you are not running the latest version. You are running 5.1 whereas the latest is 5.3.
