### ISSUE TITLE
Unrecoverable error on time change due to daylight saving timezone change

### ISSUE THREAD

**Issue by raffig** [jobrunr/jobrunr#598]
**Are you running the latest version of JobRunr?**
Yes

**Describe the bug**
It seems that jobrunr does not handle daylight time zone change properly. We have a couple of jobrunr containers on a server that has daylight timezone change enabled. On 30.10.2022 at 02:00 all our containers died with following exception:

```
2022-10-30 02:00:04,126 ERROR - An unrecoverable error occurred. Shutting server down...
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$3(BackgroundJobServerTable.java:98) ~[jobrunr-5.3.0.jar:5.3.0]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:98) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:116) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:74) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:115) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:79) ~[jobrunr-5.3.0.jar:5.3.0]
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:49) [jobrunr-5.3.0.jar:5.3.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: No servers available?!
	... 15 more
```

I presume that following happened:
All servers had heartbeat around 03:00 (or a little bit before). Then, at 03:00 time has been shifted to 02:00, thus jobrunr could not find any living server, subsequently it considered itself unable to handle further request and shut down:

```
2022-10-30 02:00:04,128  INFO - BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
2022-10-30 02:00:04,159  INFO - BackgroundJobServer and BackgroundJobPerformers stopped
```

I also presume that similar thing may occur on 26.03.2023 when time will be shifted from 02:00 to 03:00 due to another timezone change.

**Comment by rdehuyss** [comment]
Please provide all the details requested in the issue template otherwise the issue will be closed.

**Comment by rdehuyss** [comment]
See #248. Probably related to MySQL.

**Comment by raffig** [comment]
Issue #248 is related, however, the recognition of reason given in that issue is incorrect. Reason is not MySQL, but algorithm itself or way of storing dates in databases. I'm pretty sure about that, because one of our instance using MS SQL Server suffered from exactly the same issue. I presume that the source reason is that you use (for storage or for calculation) local date time instead of UTC time or simply timestamp. Contraty to local date time those measures are continual, thus resistant to such changes.

**Comment by dmurphy-ambra** [comment]
We just experienced this as well, using a Postgresql back-end.

**Comment by rdehuyss** [comment]
@dmurphy-ambra could you provide me with your logs right when this happened?

**Comment by dmurphy-ambra** [comment]
@rdehuyss 
```
2022-10-30 01:00:08,115 [backgroundjob-zookeeper-pool-2-thread-1] INFO  org.jobrunr.server.ServerZooKeeper - Removed 2 server(s) that timed out
2022-10-30 01:00:08,116 [Thread-160314] INFO  org.jobrunr.server.BackgroundJobServer - BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete -
 max 10 seconds)
2022-10-30 01:00:08,127 [Thread-160314] INFO  org.jobrunr.server.BackgroundJobServer - BackgroundJobServer and BackgroundJobPerformers stopped
2022-10-30 01:00:08,131 [Thread-160314] ERROR org.jobrunr.server.BackgroundJobServer - An unrecoverable error occurred. Shutting server down...
org.jobrunr.storage.StorageException: No servers available?!
        at org.jobrunr.storage.sql.common.BackgroundJobServerTable.lambda$getLongestRunningBackgroundJobServerId$4(BackgroundJobServerTable.java:100)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.jobrunr.storage.sql.common.BackgroundJobServerTable.getLongestRunningBackgroundJobServerId(BackgroundJobServerTable.java:100)
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getLongestRunningBackgroundJobServerId(DefaultSqlStorageProvider.java:123)
        at org.jobrunr.storage.ThreadSafeStorageProvider.getLongestRunningBackgroundJobServerId(ThreadSafeStorageProvider.java:87)
        at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:113)
        at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:78)
        at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:49)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by rdehuyss** [comment]
Ok - I was finally able to reproduce this.

**Comment by rdehuyss** [comment]
For those interested in what happened: https://www.jobrunr.io/en/blog/2022-11-05-jobrunr-and-daylight-saving-time/

**Comment by patkujawa-wf** [comment]
Thanks for that write-up, quite a gotcha!

**Comment by s-evgheni** [comment]
@rdehuyss even hugely popular open source libraries such us Hibernate had their moment of shame in the past with this particular problem.

That's why things like this exist:
https://github.com/montrosesoftware/DbAssist/wiki


At the end Hibernate engineers solved it by introducing a configuration property whose sole purpose was to call the proper PreparedStatement.setTimestamp() method in the JDBC layer 😄

https://in.relation.to/2016/09/12/jdbc-time-zone-configuration-property/

**Comment by s-evgheni** [comment]
> I still don’t agree that we need to save a TimeZone in the TIMESTAMP(6) WITH TIME ZONE to save a simple database Timestamp. What if … we transform the Instant to a LocalDateTime in UTC Timezone? Wouldn’t that work?

Imagine that you have your DB setup in the UTC and your JVM is running in something else (eg. Australia/Sydney).
Now imagine that you have two instants like 2022-04-02 02:50:00+11:00 and 2022-04-02 02:10:00+10:00, 20 minutes apart.

Now because you're using LocalDateTime as input and because your JVM time zone isn't UTC what you tell the database is to store 2022-04-02 02:50:00 and 2022-04-02 02:10:00. Note that now the dates are in a different order and 40 minutes apart. You have silent data truncation.
That's why TIMESTAMP WITH TIME ZONE are preferred methods of storage even if you're using UTC.

**timestamps with time zones are 20 minutes apart**
2017-04-02 02:50:00+11:00 and 2017-04-02 02:10:00+10:00

**timestamps w/o timezones are 40 minutes apart:**
2017-04-02 02:50:00            and 2017-04-02 02:10:00 )

**Comment by rdehuyss** [comment]
Hi @s-evgheni - thanks for your valuable input! If only I had found the link with the article from Vlad Mihalcea  earlier :-).

Regarding your last remark: indeed, that's something I did not think of. Lucky I chose another solution which I think is correct (and I hope you can confirm this).

What happens now in JobRunr with LocalDateTime is that it is converted to an Instant, so in your example this dates will become:
2022-04-02T02:50:00+11:00 => 2022-04-01T15:50:00Z
2022-04-02T02:10:00+10:00 => 2022-04-01T16:10:00Z

As these Instant's (with 20 minutes difference) are then saved with calendar UTC (so, still 20 minutes apart in the DB), I think everything is implemented correct now.

Looking forward to your feedback!

**Comment by raffig** [comment]
Well, let ma add my two cents, after reading those commens and @rdehuyss blog post.

First of all we have to understand one important thing - time is linear. This is extremly important for further analysis.

**Timestamp** is number of seconds / milliseconds since EPOCH (whatever it means). It has **no timezone**! It is just a n integer that is increased by one every second/millisecond. For simplicity lets assume that we measure timestamp in seconds.

Second one: do note use timestamp and timezone in one sentence ;-) - this simplifies the thing pretty much :-)

Everything else, like UTC, timezones, local time, etc, all that stuff, daylight saving is just a **presentation** of timestamp.

It means that timestamp of value: `1668762900` is:
Nov 18 2022 09:15:00 in Abidjan - they are in Africa
Nov 18 2022 19:15:00 in Port Moresby they are somwhere on the Pacific
Nov 18 2022 21:15:00 in Norfolk and they are in Pacific to but use DST

As you can see it is mearly **presentation** of the same timestamp.

In my opinion most of time values kept in databases could be kept in two ways:
1. As simple timestamp in a field that is integer. Disadvantage of this option is that you cannot easily view it as date/time without using database specific function
2. As a datetime in UTC in standard datetime field that every database supports - now you see it as a date/time.

Every time you have to make a **presentation** of the certain date/time to the user you have to know what is her current timezone and calculate her local time. It is easy in both cases - from timestamp or from UTC.

In this particular case, as far as I understand this, there is actually no point in using date time at all - timestamp should be used. From what I understand (correct me if I'm wrong) the feature is:
1. Check the heartbeat - if server is alive store current time
2. Check servers that are still alive, meaning that they have heartbeat time not older than some period of time

What could be done here is... simply store a heartbeat *timestamp*. It means that you simply store value `1668762900`. 5 seconds later the timestamp is: `1668762905`. So simply `1668762905 - 1668762900 = 5` -> ok, this server was alive 5 seconds ago, so it is probably fine. Do I have to worry about timezones? No. DST? No. Not at all, I just use plain integers. Almost nothing can go wrong.

What if I want to check in GUI/REST when the server was last time seen? Well, first of all, I have to specify what is *my, recipient* timezone. If I live in Warsaw, then the server was last time seen on Nov 18 2022 10:15:00 (accrodingly to Warsaw time). But If I live in Darwin, then the server was last seen on Nov 18 2022 18:45:05 (accordingly to Darwin time).

Summarizing my point is that unless you have some important business needs there is absolutely no point in storing time in database other than as a timestamp (or UTC time for some sort of reading covenience), because other ways are just plain conversions from timestamp to some local recipient's conditions, so you can do this in upper layers, not the storage one.

Best regards!

**Comment by rdehuyss** [comment]
Hi @raffig - I completely agree with you. I considered using a Long (`millisSinceEpoch`) but that would cause other consequences. That's why in the end I chose the UTC timestamps. 

Thanks for your input!

**Comment by rdehuyss** [comment]
Solved in JobRunr branch v6
