### ISSUE TITLE
[BUG] Trying to schedule a job fails when using Kotlin lambdas

### ISSUE THREAD

**Issue by marko-tisma** [jobrunr/jobrunr#611]
**Are you running the latest version of JobRunr?**
Yes 

**Describe the bug**
I have a Kotlin function in a Spring project that accepts one function of type `() -> Unit` as its parameter. I want to schedule or enqueue a `JobLambda` that executes the parameter function in its body, like so:
```java
fun test(f: () -> Unit) {
    BackgroundJob.enqueue { f() }
}
```
When I try to run this function, a `NoSuchBeanDefinition` exception is thrown.
```java
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.demo.DemoApplication$run$1' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172) ~[spring-context-5.3.23.jar:5.3.23]
	at org.jobrunr.server.runner.BackgroundJobWithIocRunner.supports(BackgroundJobWithIocRunner.java:21) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$0(BackgroundJobServer.java:222) ~[jobrunr-5.3.1.jar:5.3.1]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at org.jobrunr.server.BackgroundJobServer.getBackgroundJobRunner(BackgroundJobServer.java:223) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:87) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:62) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:41) ~[jobrunr-5.3.1.jar:5.3.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

I have tried passing the `JobLambda` in a variety of other ways, including passing it as a `Runnable` and using Java and passing it as a Java Lambda, which also did not work.

**Environment**
I'm using JobRunr version: 5.3.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): Amazon Corretto 17.0.4
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): PostgreSQL

**How to Reproduce**
Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
```java
fun test(f: () -> Unit) {
    BackgroundJob.enqueue { f() }
}

test { println("test") }
```
**Additional context**
I have the following dependencies in my project:
```
  implementation("org.jobrunr:jobrunr:5.3.1")
  implementation("org.jobrunr:jobrunr-spring-boot-starter:5.3.1")
  implementation("org.jobrunr:jobrunr-kotlin-support:3.1.2")
```

**Comment by rdehuyss** [comment]
You cannot pass any function - JobRunr won't be able to analyse it (as it is a parameter).

In your case, you can either use a JobRequest / JobRequestHandler or have a look at the tests in the github repo of what is possible.
