### ISSUE TITLE
[BUG] Start Error in new version

### ISSUE THREAD

**Issue by fawks96** [jobrunr/jobrunr#623]
**Are you running the latest version of JobRunr?**
No

**Describe the bug**
In maven version jobrunr-spring-boot-starter lower than 3.2.1(including), My application can start well.
In maven version jobrunr-spring-boot-starter higher than 3.2.1 ,My application start fail.
Here is the trace:
```java
2022-11-24 16:53:40.851|||Application run failed
org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
 at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
 at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
 at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
 at java.base/java.lang.Iterable.forEach(Iterable.java:75)
 at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
 at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
 at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
 at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
 at me.akey.mxm.imservice.ImServiceApplication.main(ImServiceApplication.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
 at springfox.documentation.spring.web.WebMvcPatternsRequestConditionWrapper.getPatterns(WebMvcPatternsRequestConditionWrapper.java:56)
 at springfox.documentation.RequestHandler.sortedPaths(RequestHandler.java:113)
 at springfox.documentation.spi.service.contexts.Orderings.lambda$byPatternsCondition$3(Orderings.java:89)
 at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:473)
 at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
 at java.base/java.util.TimSort.sort(TimSort.java:234)
 at java.base/java.util.Arrays.sort(Arrays.java:1307)
 at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
 at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
 at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
 at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
 at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
 at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
 at springfox.documentation.spring.web.plugins.WebMvcRequestHandlerProvider.requestHandlers(WebMvcRequestHandlerProvider.java:81)
 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
 at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.withDefaults(AbstractDocumentationPluginsBootstrapper.java:107)
 at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.buildContext(AbstractDocumentationPluginsBootstrapper.java:91)
 at springfox.documentation.spring.web.plugins.AbstractDocumentationPluginsBootstrapper.bootstrapDocumentationPlugins(AbstractDocumentationPluginsBootstrapper.java:82)
 at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:100)
 at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
 ... 14 common frames omitted

```

**Environment**
I'm running on Java 17
I'm using the following StorageProvider :
```java
    @Bean
    public StorageProvider storageProvider(JobMapper jobMapper){
        final JedisRedisStorageProvider jedisRedisStorageProvider=new JedisRedisStorageProvider(getJedisPool(), rateLimit().withoutLimits());
        jedisRedisStorageProvider.setJobMapper(new JobMapper(new JacksonJsonMapper()));
        return jedisRedisStorageProvider;
    }
```

**How to Reproduce**
Use jedisRedisStorageProvider and maven version higher than 3.2.1 and start the application.

**Comment by rdehuyss** [comment]
This is not related to JobRunr.
