### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by tornabene** [jobrunr/jobrunr#627]
### Runtime information
- __Timestamp__: 2022-11-24T19:53:41.069Z
- __Location__: BackgroundJobServer 1dea68f1-c970-4217-81e0-3d9729d13820
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.oracle.OracleStorageProvider
- __Java Version__: 1.8.0_275
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 10a9ab62-3bb7-421d-9d99-e7664e9106e9
(workerPoolSize: 50, pollIntervalInSeconds: 15, firstHeartbeat: 2022-11-24T20:51:00.616Z, lastHeartbeat: 2022-11-24T20:52:01.766Z)

#### Concurrent modified jobs:
Job id: ffab2998-66a9-4e3d-94c2-803a767412d7
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2022-11-24T19:53:40.693Z on BackgroundJobServer 1dea68f1-c970-4217-81e0-3d9729d13820 and started at 2022-11-24T19:53:30.612Z) ¿ ENQUEUED (at 2022-11-24T19:53:24.635Z) ¿ SCHEDULED (at 2022-11-24T19:53:24.177Z)
	Storage state: FAILED (at 2022-11-24T20:52:02.531Z) ¿ PROCESSING (updated at 2022-11-24T19:53:30.612Z on BackgroundJobServer 1dea68f1-c970-4217-81e0-3d9729d13820 and started at 2022-11-24T19:53:30.612Z) ¿ ENQUEUED (at 2022-11-24T19:53:24.635Z) ¿ SCHEDULED (at 2022-11-24T19:53:24.177Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by rdehuyss** [comment]
Your servers are not in the same timezone (or you can time travel).

See: 
* FAILED (at 2022-11-24T**20:52:02.531Z**)
* PROCESSING (updated at 2022-11-24T**19:53:40.693Z**)
