### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by MikeyBower93** [jobrunr/jobrunr#631]
Raising as per request from the dashboard (please note that I can confirm it has now processed them, I just thought it was still worth raising).

### Runtime information
- __Timestamp__: 2022-12-03T18:44:38.486375588Z
- __Location__: BackgroundJobServer 4f30adf6-2837-4687-a514-65af497ce396
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17-ea
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 83bb1874-5eaa-4a47-8713-381df3272665
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-02T17:11:49.646379Z, lastHeartbeat: 2022-12-03T18:44:33.570665Z)
- BackgroundJobServer id: 4f30adf6-2837-4687-a514-65af497ce396
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2022-12-02T17:17:36.840266Z, lastHeartbeat: 2022-12-03T18:44:33.223292Z)

#### Concurrent modified jobs:
Job id: 4bd1c7ec-df19-483d-bfd1-8e462d1d85b2
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2022-12-03T18:44:33.250267722Z on BackgroundJobServer 4f30adf6-2837-4687-a514-65af497ce396 and started at 2022-12-03T18:43:34.128253404Z) ← ENQUEUED (at 2022-12-03T18:43:25.229310317Z)
	Storage state: SCHEDULED (at 2022-12-03T18:44:37.985751345Z) ← FAILED (at 2022-12-03T18:44:37.985354900Z) ← PROCESSING (updated at 2022-12-03T18:43:34.128253404Z on BackgroundJobServer 4f30adf6-2837-4687-a514-65af497ce396 and started at 2022-12-03T18:43:34.128253404Z) ← ENQUEUED (at 2022-12-03T18:43:25.229310317Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)

```

**Comment by rdehuyss** [comment]
Hi @MikeyBower93, do you have any custom Job Filters by any chance?

**Comment by rdehuyss** [comment]
Are you running on shared hosting (cloud infrastructure)?

Reason that I'm asking is that your timestamps are really strange: the time between when the job is updated (2022-12-03T18:44:33.250267722Z) and when the exception happened (2022-12-03T18:44:38.486375588Z) is almost 5 seconds whereas normally this typically should take only a couple of ms.

**Comment by MikeyBower93** [comment]
We run on AWS ECS. We have 2 servers running as separate pods, and we store our Job information in an AWS Postgres RDS which is in the same region as our ECS cluster.
