### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: null, when attempting to queue a job

### ISSUE THREAD

**Issue by luketoh94-imc** [jobrunr/jobrunr#633]
**Are you running the latest version of JobRunr?**
Yes, version 5.3.1

**Describe the bug**
java.lang.IllegalArgumentException: null, when attempting to queue a job
```java
09:12:01.704 [tomcat-http--11] ERROR c.i.iss.monitoring.ExceptionMonitor - [22f1b7bb-092c-4aae-82bd-af299b0b97f6] Error while processing request {requestURI=/iss/api/quotes/test, user=admin}
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.objectweb.asm.ClassVisitor.<init>(Unknown Source) ~[asm-5.1.jar:5.1]
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.<init>(AbstractJobDetailsFinder.java:17) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:19) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:94) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:76) ~[jobrunr-5.3.1.jar:5.3.1]
	at com.imc.iss.web.controller.QuotesController.Test(QuotesController.java:833) ~[core-0.0.2-SNAPSHOT.jar:0.0.2-SNAPSHOT]
```

**Environment**
I'm using JobRunr version: 5.3.1
I'm running on JRE / JDK (e.g. OpenJDK 1.8.0_292): jdk8 
I'm using the following StorageProvider (e.g. Oracle / MongoDB / ...): sqlserver 

**How to Reproduce**
Code to enqueue job
```java
jobScheduler.enqueue(() -> System.out.println("BackgroundJob enqueue"));
```
jobScheduler bean
```java
	@Bean
	public JobScheduler jobScheduler(final ApplicationContext applicationContext, final JobActivator jobActivator)
	{
		final SQLServerDataSource dataSource = new SQLServerDataSource();
		dataSource.setURL("jdbc:sqlserver://localhost;databaseName=jobrunr;");
		dataSource.setUser("localhost");
		dataSource.setPassword("");

		final StorageProvider p = new SQLServerStorageProvider(dataSource);

		final JsonMapper jsonMapper = new JacksonJsonMapper();
		final JobMapper jobMapper = new JobMapper(jsonMapper);
		p.setJobMapper(jobMapper);
		final JobScheduler s = new JobScheduler(p);

		JobRunr.configure().useStorageProvider(p).useJobActivator(jobActivator).useBackgroundJobServer().useJmxExtensions().useDashboard().initialize();

		return s;

	}
```

**Expected behavior**
Job getting queued and subsequently run.

**Additional context**

**Comment by rdehuyss** [comment]
Your ASM version is out of date - you should use at least ASM 9.

See https://search.maven.org/artifact/org.jobrunr/jobrunr/5.3.1/jar. You are using ASM 5.2 which is already 6 years old.
