### ISSUE TITLE
[BUG] Running simple kotlin lambda job fails

### ISSUE THREAD

**Issue by igr** [jobrunr/jobrunr#646]
### JobRunr Version

5.3.1

### JDK Version

17

### Your SQL / NoSQL database

Postgres 15

### What happened?

Look the code, SpringBoot kotlin application:

```kt
@Service
class AppStartedSpring(
    val jobScheduler: JobScheduler
) : AppStarted {
    val log by LoggerDelegate()

    override fun invoke() {
        log.info("App started")

        jobScheduler.scheduleRecurrently(Cron.every30seconds()) {
            log.info("hello")
        }
    }
}
```

It is a simple service. It gets log injected using:

```kt
class LoggerDelegate<in R : Any> : ReadOnlyProperty<R, Logger> {
    override fun getValue(thisRef: R, property: KProperty<*>)
        = getLogger(getClassForLogging(thisRef.javaClass))
}
```

However, when I want to log from the lambda, I get the following error:

```
No qualifying bean of type 'ch.qos.logback.classic.Logger' available
```

as it seems that Runr tries to inject used `log` reference in lambda - which is wrong.

How can I turn this off? I don't need Runr to inject anything for me.

### How to reproduce?

Use the code in the description.

### Relevant log output

```shell
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ch.qos.logback.classic.Logger' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1148) ~[spring-context-6.0.2.jar:6.0.2]
	at org.jobrunr.server.runner.BackgroundJobWithIocRunner.supports(BackgroundJobWithIocRunner.java:21) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$0(BackgroundJobServer.java:222) ~[jobrunr-5.3.1.jar:5.3.1]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at org.jobrunr.server.BackgroundJobServer.getBackgroundJobRunner(BackgroundJobServer.java:223) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:87) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:62) ~[jobrunr-5.3.1.jar:5.3.1]
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:41) ~[jobrunr-5.3.1.jar:5.3.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]

```
```

**Comment by rdehuyss** [comment]
At runtime, JobRunr only knows the following: `log.info("hello")`;

As it needs an object for `log`, it will try to search it in the IoC container.

Please have a look in the [Kotlin tests](https://github.com/jobrunr/jobrunr/blob/master/language-support/jobrunr-kotlin-17-support/src/test/kotlin/org/jobrunr/scheduling/JobSchedulerTest.kt#L75-L90) on how to use it.

Other option is to use the [JobRequest examples](https://github.com/jobrunr/jobrunr/blob/master/language-support/jobrunr-kotlin-17-support/src/test/kotlin/org/jobrunr/scheduling/JobRequestSchedulerTest.kt).

**Comment by igr** [comment]
But I am passing an instance (a lambda) that is already wired?

I just want to pass an instance to Runr - why it matters where it comes from and why Runr is looking for anything inside of it in runtime? I just want to understand how this part works.

I didnt expect Runr to do anything with wiring, that is all. Does it actually create _a new instance_ of the provided job when needed?

**Comment by igr** [comment]
I got it, Runr creates a new instance of a job. I probably missed that in the documentation.

The thing is that the above code looks ok, and it _should_ be working (if this is advertised like that). I am not a fan of runtime magic that decides if something is working or not; would like to sort that in compile time.🤷‍♂️

**Comment by igr** [comment]
Sorted out with the `JobRequestScheduler`. Thank you!

**Comment by rdehuyss** [comment]
Indeed, that's why the JobRequestScheduler exists.
