### ISSUE TITLE
[BUG] does not work for a plain java class and method

### ISSUE THREAD

**Issue by jhsenjaliya** [jobrunr/jobrunr#648]
### JobRunr Version

5.3.2

### JDK Version

11

### Your SQL / NoSQL database

Na - In memory

### What happened?

with plain java, class calling the recurrentSchedule with a local method with parameter is throwing this error , 

This happens because none of the BackgroundJobRunner can pass supports(Job) method.

```org.jobrunr.JobRunrException: Could not find a BackgroundJobRunner: either no JobActivator is registered, your Background Job Class is not registered within the IoC container or your Job does not have a default no-arg constructor.
	at org.jobrunr.JobRunrException.problematicConfigurationException(JobRunrException.java:51)
	at org.jobrunr.server.BackgroundJobServer.lambda$getBackgroundJobRunner$1(BackgroundJobServer.java:224)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.jobrunr.server.BackgroundJobServer.getBackgroundJobRunner(BackgroundJobServer.java:224)
	at org.jobrunr.server.BackgroundJobPerformer.runActualJob(BackgroundJobPerformer.java:87)
	at org.jobrunr.server.BackgroundJobPerformer.performJob(BackgroundJobPerformer.java:62)
	at org.jobrunr.server.BackgroundJobPerformer.run(BackgroundJobPerformer.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)```


is there any Plan java example( without framework) example that I can refer to check on this ?

### How to reproduce?

```java
 JobRunr.configure()
                .useStorageProvider(new InMemoryStorageProvider())
                .useBackgroundJobServer()
                .useDashboard()
                .initialize();

BackgroundJob.scheduleRecurrently("testId", "0/10 * * * * *", () -> runTest(param1));

 public void runTest(Parameter param) {
            log.info("Starting to execute job " + param.getId() + " in thread: " + Thread.currentThread());

    }

```

**Comment by rdehuyss** [comment]
@jhsenjaliya : could you post your complete example / class ? E.g. where is the `log` logger coming from?

**Comment by jhsenjaliya** [comment]
Yes sure, 
```java
import com.google.common.util.concurrent.AbstractScheduledService;
import com.google.common.util.concurrent.ServiceManager;
import lombok.extern.slf4j.Slf4j;
import org.jobrunr.configuration.JobRunr;
import org.jobrunr.scheduling.BackgroundJob;
import org.jobrunr.storage.InMemoryStorageProvider;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

@Slf4j
public class JobSchedulerTest extends AbstractScheduledService {

    final String testParam;
    public JobSchedulerTest(String testParam) {
        this.testParam = testParam;
    }

    @Override
    protected void runOneIteration() {
        try {
            log.info("checking for any new job to schedule since last check.");
            List<String> newJobsToSchedule = Arrays.asList("job1", "job2");

            newJobsToSchedule.parallelStream().forEach(job -> {
                    BackgroundJob.scheduleRecurrently(job, "0/10 * * * * *", () -> runTest(job));
                    // Following works with simple String param, dont work with custom Object, it just remains in processing job
//                    BackgroundJob.scheduleRecurrently(job, "0/10 * * * * *", () -> runAsync(job).join());
                // Following works as simple example, not it does not work with SLF4j lombok logger though
//                    BackgroundJob.scheduleRecurrently(job.getId(), "0/10 * * * * *", () -> System.out.println("test run"));
                // Following does not work, saying can not take multiple task...
//                    BackgroundJob.scheduleRecurrently(job.getId(), "0/40 * * * * *", () ->
//                        {
//                            log.info("started job:"+ job);
//                            log.info("ended job:"+ job);
//                        }
//                    );
            });

        } catch (Throwable e) {
            log.error("error running the job launcher iteration", e);
        }
    }

    public void runTest(String job) {
        log.info("Preparing to execute job " + job + " in thread: " + Thread.currentThread());
    }
    public CompletableFuture<Void> runAsync(String job) {
        return CompletableFuture
                .runAsync(() -> {
                        log.info("Preparing to execute job " + job + " in thread: " + Thread.currentThread());
                });
    }

    @Override
    protected void startUp() throws Exception {
        log.info("setting up job scheduler service");
        JobRunr.configure()
                .useStorageProvider(new InMemoryStorageProvider())
                .useBackgroundJobServer()
                .useDashboard()
                .initialize();

        log.info("new job scheduler service at every 5 seconds...[STARTED] ");
    }

    @Override
    protected void shutDown() throws Exception {
        log.info("new job launcher service...[STOPPED]");
    }

    @Override
    protected Scheduler scheduler() {
        return Scheduler.newFixedDelaySchedule(0, 5, TimeUnit.SECONDS);
    }


    public static void main(String[] args) throws InstantiationException {

        ServiceManager serviceManager = new ServiceManager(Arrays.asList(new JobSchedulerTest("testConstructorParam")));
        serviceManager.startAsync().awaitHealthy();

    }
}
```

**Comment by rdehuyss** [comment]
Allrighty - the reason you get this exception is because of the fact that your class `JobSchedulerTest` requires a constructor which JobRunr cannot resolve.

When you schedule your job with `BackgroundJob.scheduleRecurrently(job, "0/10 * * * * *", () -> runTest(job))`, JobRunr will serialize the following info to json (so it can also be executed on a different jvm on another server):
- classname: `your.packagename.JobSchedulerTest.`
- method: `runTest`
- args: JSON presentation of the param, in this case either the String "job1" or "job2".

The problem comes when JobRunr wants to run the job - it needs an instance of `JobSchedulerTest` (perhaps on a different JVM) but cannot construct one since it has constructor requiring an argument.

If you have a public default constructor with no arguments, all should work.

I find this a strange test though: creating recurring jobs in parallel 😕 ? What would be the use case?

**Comment by jhsenjaliya** [comment]
Thanks @rdehuyss , Thanks for looking into this, I was just surprised on why the `runAsync` method works then.
anyway, trying to restructure this to meet that requirements.
the use-case here are that, user may have many jobs to schedule and the platform needs to take those and update the schedule to run the job accordingly. so once I have list of job with any updated schedule, I actually schedule it with JobRunr to run it periodically, until the program runs, and hense keeping things in memory, as on restart I always schedule all to begin with.

**Comment by rdehuyss** [comment]
No problem @jhsenjaliya ! Feel free to star the repo if you're happy with JobRunr.
