### ISSUE TITLE
[BUG] Jobs fail with "Orphaned job" error

### ISSUE THREAD

**Issue by ilopmar** [jobrunr/jobrunr#654]
### JobRunr Version

5.3.2

### JDK Version

openjdk version "17.0.5" 2022-10-18 LTS

### Your SQL / NoSQL database

Postgresql 12.6

### What happened?

We have long running jobs that download and upload big files to different places and take a considerable amount of time to finish. We've seen the following error a few times every day:

```
java.lang.IllegalThreadStateException: Job was too long in PROCESSING state without being updated.
	at org.jobrunr.server.JobZooKeeper.lambda$checkForOrphanedJobs$2(JobZooKeeper.java:126)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:215)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForOrphanedJobs(JobZooKeeper.java:126)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:98)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Taking a look at the code it seems that this happens when a job hasn't been updated in 60 seconds (default 15 seconds polling multiplied by 4). It always happens with the jobs that process the bigger files because the download takes time and depending on network conditions it can take some minutes to finish.

I'm wondering if this way of checking the orphaned jobs can be improved in some way or maybe the time to consider a job orphaned can be configured instead of being calculated as it is now.

### How to reproduce?

It's hard to reproduce because it depends on network conditions. I'm able to reproduce it locally while debugging trying to download very big files that take a lot of time and also setting break points in some parts of the code to "stop" the execution.

**Comment by rdehuyss** [comment]
Hi @ilopmar, that's really strange as some users have jobs that take hours without bumping into this issue. The job indeed gets updated every 15sec by a background thread (so completely unrelated to your code) and something is preventing this. Are you running on shared hosting? If so, something may be eating your CPU. Or are you perhaps doing a lot of IO which results in a lot of GC?

**Comment by ilopmar** [comment]
Thanks for the quick reply. We are running on kubernetes and we have defined the resources limits to 2 CPU and 2 GB RAM with 8 JobRunr workers.
We indeed are doing a lot of IO because all those 8 workers download/upload big files so when all of them are running at the same time basically there's a lot of IO during the transfers.

> The job indeed gets updated every 15sec by a background thread (so completely unrelated to your code) and something is preventing this.

Do you think of something that can be preventing the job being updated but the mentioned background thread? Or maybe some parts of JobRunr code I can take a look or increase the log level in some classes to try to understand why the jobs don't get updated.

**Comment by rdehuyss** [comment]
You can increase all logging in the following package: `org.jobrunr.server`. Please also enable verbose GC logging (`-verbose:gc`)

Like I said, the only thing I've seen preventing the update by means of the background thread is a stop-the-world GC. 

Other thing you could do is increase the pollIntervalInSeconds but this will not fix the root cause.

**Comment by ilopmar** [comment]
More information after some debugging. 

Enabling GC logging doesn't show anything significant. There are some pauses but they are pretty fast, about 2-3 milliseconds.

I forgot to mention that we are using `UseStorageProviderJobConcurrentJobModificationResolverPolicy` as the concurrent job modification policy. I've seen that when `JobZooKeeper` tries to save the updated job sometimes the update fails because it the expected result after the update is not correct ([here](https://github.com/jobrunr/jobrunr/blob/a7565b17b18338ba2be0bf586f1e8578d5667218/core/src/main/java/org/jobrunr/storage/sql/common/db/Sql.java#L173-L173)). That throws a concurrent modification exception that is handled using the defined policy that at the end fails the job and interrupt the thread (this thread interruption is another issue we are seen sometimes).

**Comment by ilopmar** [comment]
We've found that the problem is related to how the jobs that are being processed are updated in `JobZooKeeper`. They are kept in memory in the map `currentlyProcessedJobs`. Then, in the method `updateJobsThatAreBeingProcessed` the jobs are retrieved from that map, converted to a list and processed:

https://github.com/jobrunr/jobrunr/blob/a7565b17b18338ba2be0bf586f1e8578d5667218/core/src/main/java/org/jobrunr/server/JobZooKeeper.java#L89-L92

The problem is that the jobs in the map are not updated so when they change, the `version` is modified but the list is not updated anymore with the new value.

I did a quick test replacing the original method with the following version that retrieves an updated list of the jobs from the store provider (Postgresql in my case):
```java
void updateJobsThatAreBeingProcessed() {
    LOGGER.debug("Updating currently processed jobs... ");
    List<Job> jobList = currentlyProcessedJobs.keySet().stream()
            .map(job -> storageProvider.getJobById(job.getId()))
            .collect(toList());
    processJobList(jobList, this::updateCurrentlyProcessingJob);
}
```

With this snapshot locally everything works and I can't reproduce the "orphaned" error anymore.

I can't extend `JobZooKeeper` to add this behaviour because it is instantiated in `BackgroundJobServer` constructor:

https://github.com/jobrunr/jobrunr/blob/a7565b17b18338ba2be0bf586f1e8578d5667218/core/src/main/java/org/jobrunr/server/BackgroundJobServer.java#L87-L87

But in a private method that can't be overriden :-(

**Comment by jhchee** [comment]
@rdehuyss We have the same encountering as well (cron job that has run for multiple hours). However, we didn't override any of the internals. What we don't understand the job filter doesn't intercept this as error and the error fails silently.
