### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by tiarebalbi** [jobrunr/jobrunr#659]
### Runtime information
- __Timestamp__: 2023-01-11T17:24:49.541426258Z
- __Location__: BackgroundJobServer d9f00087-bca7-4fbe-958d-84caabc212c4
- __JobRunr Version__: 5.3.2
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 17.0.5
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: d9f00087-bca7-4fbe-958d-84caabc212c4
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T17:16:17.393Z, lastHeartbeat: 2023-01-11T17:24:47.805Z)
- BackgroundJobServer id: 07fe540b-2bb5-4049-bcee-e7e0f7a4bdf6
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T17:22:54.850Z, lastHeartbeat: 2023-01-11T17:24:40.033Z)

#### Concurrent modified jobs:
Job id: 2a045850-ef06-4c92-ab4b-75451f9a7433
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-01-11T17:24:49.534822553Z) ← SCHEDULED (at 2023-01-11T17:22:56.964659990Z)
	Storage state: ENQUEUED (at 2023-01-11T17:24:49.519101941Z) ← SCHEDULED (at 2023-01-11T17:22:56.964659990Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2023-01-11T16:42:31.943305520Z
- __Location__: BackgroundJobServer 5a30821b-c150-4a0d-8630-f74c39a31a6f
- __JobRunr Version__: 5.3.2
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 17.0.5
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 5a30821b-c150-4a0d-8630-f74c39a31a6f
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:30:28.787Z, lastHeartbeat: 2023-01-11T16:42:29.517Z)
- BackgroundJobServer id: b4dfb48d-839b-4fc8-9401-79f155472b46
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:32:46.146Z, lastHeartbeat: 2023-01-11T16:42:31.745Z)
- BackgroundJobServer id: cf79b2a0-0a72-4dd9-9995-ed669eff3065
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:32:47.258Z, lastHeartbeat: 2023-01-11T16:42:17.814Z)
- BackgroundJobServer id: 97a06da0-fb7b-4a25-9887-c12fa39707d9
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:36:31.575Z, lastHeartbeat: 2023-01-11T16:42:17.198Z)
- BackgroundJobServer id: cea9e04b-9ebf-49a4-9cdd-9044d63df03b
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:36:33.801Z, lastHeartbeat: 2023-01-11T16:42:19.160Z)
- BackgroundJobServer id: 35a3f4cf-80b7-47ce-b591-d5d94a0e5b0e
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:36:36.049Z, lastHeartbeat: 2023-01-11T16:42:21.419Z)
- BackgroundJobServer id: 0e1a6b7d-476c-4803-ae38-515b4f1d4507
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:40:32.204Z, lastHeartbeat: 2023-01-11T16:42:17.493Z)
- BackgroundJobServer id: b3c1bb2f-61cb-4a26-b4c3-c38b9232372e
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:40:33.288Z, lastHeartbeat: 2023-01-11T16:42:18.431Z)
- BackgroundJobServer id: e3c1c9d3-61df-49c1-83c2-feec9ec3c9c2
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:40:35.517Z, lastHeartbeat: 2023-01-11T16:42:20.674Z)
- BackgroundJobServer id: 43921b5d-dafd-4f84-8182-be6c616ea4d9
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:40:36.367Z, lastHeartbeat: 2023-01-11T16:42:21.508Z)

#### Concurrent modified jobs:
Job id: cefc643e-a69e-4c45-a908-673cd0904abf
	Local version: 1; Storage version: 1
	Local state: ENQUEUED (at 2023-01-11T16:42:31.936914662Z) ← SCHEDULED (at 2023-01-11T16:40:38.954664487Z)
	Storage state: SCHEDULED (at 2023-01-11T16:40:38.954664487Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

### Runtime information
- __Timestamp__: 2023-01-11T17:00:06.516318520Z
- __Location__: BackgroundJobServer cea9e04b-9ebf-49a4-9cdd-9044d63df03b
- __JobRunr Version__: 5.3.2
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 17.0.5
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: cea9e04b-9ebf-49a4-9cdd-9044d63df03b
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:36:33.801Z, lastHeartbeat: 2023-01-11T17:00:04.844Z)
- BackgroundJobServer id: c9d0525d-d108-46c3-9d81-751ad0b0c75b
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:47:39.171Z, lastHeartbeat: 2023-01-11T16:59:55.107Z)
- BackgroundJobServer id: 3f20ef65-4314-42fb-8686-8aad0d5705e9
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:47:45.172Z, lastHeartbeat: 2023-01-11T17:00:00.789Z)
- BackgroundJobServer id: 69958653-0c12-4b66-8b65-2093632f2482
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:47:59.442Z, lastHeartbeat: 2023-01-11T17:00:00.227Z)
- BackgroundJobServer id: 72d9b45f-3990-41f4-a684-fa9501c671ad
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:48:05.242Z, lastHeartbeat: 2023-01-11T17:00:05.860Z)
- BackgroundJobServer id: 97c3be62-2d6c-4eb3-8ac5-6bfcd048e6d5
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:48:19.444Z, lastHeartbeat: 2023-01-11T17:00:05.040Z)
- BackgroundJobServer id: 4bc0231a-6c98-493c-8c15-a337344ba66c
(workerPoolSize: 1, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-11T16:50:34.615Z, lastHeartbeat: 2023-01-11T17:00:05.172Z)

#### Concurrent modified jobs:
Job id: 1a6f614c-d651-4ebf-aa12-7a967b151549
	Local version: 1; Storage version: 1
	Local state: ENQUEUED (at 2023-01-11T17:00:06.510571601Z) ← SCHEDULED (at 2023-01-11T16:59:51.461490134Z)
	Storage state: SCHEDULED (at 2023-01-11T16:59:51.461490134Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by rdehuyss** [comment]
Is it possible for you to setup a repo that reproduces this? You are encountering errors I've never seen before.

**Comment by tiarebalbi** [comment]
I can prepare the example but the issue is not with the code itself. This issue only happens when I run my application on Kubernetes.

It's a spring boot app running on Kubernetes. Each application has 2 containers running (they use the same database). The error starts when the number of containers in the deployment scales up...

```
org.jobrunr.database.database-name=demo
```

**Comment by tiarebalbi** [comment]
Here's the demo project to reproduce the issue

https://github.com/tiarebalbi/jobrunr-issue-demo

**Comment by rdehuyss** [comment]
I don't have time to look at this before beginning of February to be honest, sorry for that.

The thing is - I know of companies who have up to 17 servers inside a cluster without this issue so I find this quite strange.

**Comment by rdehuyss** [comment]
Hi @tiarebalbi , I created an issue on your repo as with me the pods are not even starting. Can you have a look at that? See https://github.com/tiarebalbi/jobrunr-issue-demo/issues/1 for more info.

**Comment by rdehuyss** [comment]
Closing stale issue. Feel free to comment so I can reopen the issue if you can setup a reproducible scenario.
