### ISSUE TITLE
[BUG] SQL Server not compatible with 'Latin1_General_100_BIN2_UTF8' collation

### ISSUE THREAD

**Issue by krja** [jobrunr/jobrunr#665]
### JobRunr Version

3.2.0

### JDK Version

1.8.0_202

### Your SQL / NoSQL database

SQL Server

### What happened?

Recently I changed charset encoding of my SQL Server to Latin1_General_100_BIN2_UTF8. After that the jobrunr fails on start up during the process of creating tables.

### How to reproduce?

Having SQL Server with Latin1_General_100_BIN2_UTF8 charset start jobrunr.

### Relevant log output

```shell
Caused by: java.lang.IllegalStateException: Error running database migration v002__create_recurring_job_table.sql

                ... 125 common frames omitted

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Column or parameter 'jobAsJson' has type 'text' and collation 'Latin1_General_100_BIN2_UTF8'. The legacy LOB types do not support UTF-8 or UTF-16 encodings. Use types varchar(max), nvarchar(max) or a collation which does not have the _SC or _UTF8 flags.

                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:907)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:802)

                at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)

                at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)

                at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:775)

                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.lang.reflect.Method.invoke(Method.java:498)

                at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)

                at com.sun.proxy.$Proxy101.execute(Unknown Source)

                at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrationStatement(DatabaseCreator.java:127)

                at org.jobrunr.storage.sql.common.DatabaseCreator.runMigration(DatabaseCreator.java:109)

                ... 124 common frames omitted
```

**Comment by rdehuyss** [comment]
Closing this without answer as not following community guidelines:

> As this is an open-source project where we try to make a living from,
we kindly ask you to have a complete Github Personal Profile (Name and Company details or LinkedIn Profile).

I'm really sorry but I don't see why I should provide free support if you're not willing to provide me the above details.

**Comment by krja** [comment]
@rdehuyss I have updated my profile.

**Comment by rdehuyss** [comment]
Thanks, @krja . As soon as I have some time, I'll have a look. Can I ask why you changed the charset encoding of your SQL Server?

**Comment by krja** [comment]
Previously I was using SQL_latin1_General_CP1_CI_AS. It was working fine with jobrunr but it has a problem with case sensitivity when comes to columns of type varchar. To test this you can create table with one column of type varchar(10). Then you apply unique index on that column. Then you insert two values: 'AA' and 'aa'. The second insert will fail due to unique constraint because this charset doesn't differentiate case of the values.
