### ISSUE TITLE
Can't access protected constructors in java17

### ISSUE THREAD

**Issue by dopato** [jobrunr/jobrunr#669]
### JobRunr Version

5.1.7

### JDK Version

openjdk64-17.0.5

### Your SQL / NoSQL database

mysql5_7

### What happened?

Have been trying to use java11 library from a java17 project and using a local jobrunr SNAPSHOT baked with java17 and got same error.

It seems that somehow, java17 cannot access protected constructors around the Job class (and all its statuses).

I changed the one from SucceededState and then was complaining about ProcessingState.

I ended up changing:

AbstractJobState
AllowedJobStateStateChanges
DeleteState
FailedState
JobDetails
Job
JobDetails
JobParametes
ProcessingState
RecurringJob
ScheduleState
SucceededState

I can't tell you if all of them are needed. 

But as soon as I changed those modifier it started deserializing all the jobs stuck into DB.

### How to reproduce?

Using either java11 lib in a java17 project or compile jobrunr with java17 in local. 

If you use both in java17 I had to deserialize in a Completable future for the exception to pop up. 

### Relevant log output

```shell
java.lang.IllegalAccessError: class org.jobrunr.jobs.states.SucceededState$Creator4JacksonDeserializer054f2a6b tried to access protected method 'void org.jobrunr.jobs.states.SucceededState.<init>()' (org.jobrunr.jobs.states.SucceededState$Creator4JacksonDeserializer054f2a6b is in unnamed module of loader com.fasterxml.jackson.module.afterburner.util.MyClassLoader @6ebaf2a8; org.jobrunr.jobs.states.SucceededState is in unnamed module of loader 'app')
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:30)
	at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:201)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:42)
	at java.base/java.util.Spliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jobrunr.storage.sql.common.JobTable.selectJobsByState(JobTable.java:133)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobs(DefaultSqlStorageProvider.java:237)
	at org.jobrunr.storage.ThreadSafeStorageProvider.getJobs(ThreadSafeStorageProvider.java:128)
	at org.jobrunr.server.JobZooKeeper.lambda$checkForSucceededJobsThanCanGoToDeletedState$3(JobZooKeeper.java:140)
	at org.jobrunr.server.JobZooKeeper.getJobsToProcess(JobZooKeeper.java:261)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:198)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:141)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:103)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:80)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rdehuyss** [comment]
I'm using JobRunr (the one from maven central and also one that I locally build) all the time within Java 17 and do not encounter this problem.

On top of that, there is an automated test that confirms that JobRunr works on all recent JVM's: see the [JDK Test](https://github.com/jobrunr/jobrunr/blob/master/tests/e2e-vm-jdk/src/test/java/org/jobrunr/tests/fromhost/JdkTest.java#L97-L109).

Feel free to reopen this issue if you have a github repo where you can reproduce the issue. Or feel free to contact me for support.
