### ISSUE TITLE
[BUG] bind address in use / unable to get a resource from pool Redis, tomcat redeploy issue

### ISSUE THREAD

**Issue by Azyl** [jobrunr/jobrunr#67]
**Describe the bug**
After we perform a redeploy of our application which is a Spring application deployed as a war application on a tomcat 9 server the application is unable to start due to the following exception:

`

io-8080-exec-50] INFO  2020-11-19 07:26:54,436 com.pixolut.stylyze.config.MongoTemplateConfig: {} partner.db.uri property not set for this environment.
[nio-8080-exec-50] INFO  2020-11-19 07:26:54,548 org.jobrunr.server.threadpool.ScheduledThreadPoolJobRunrExecutor: {} ThreadManager of type 'ScheduledThreadPool' started
[Timer-0] WARN  2020-11-19 07:26:54,626 org.jobrunr.storage.AbstractStorageProvider: {} Error notifying JobStorageChangeListeners
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getJedis(JedisRedisStorageProvider.java:456)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getJobStats(JedisRedisStorageProvider.java:401)
	at org.jobrunr.storage.AbstractStorageProvider.notifyJobStatsOnChangeListeners(AbstractStorageProvider.java:81)
	at org.jobrunr.storage.AbstractStorageProvider$SendJobStatsUpdate.run(AbstractStorageProvider.java:164)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 7 more
[Thread-335] INFO  2020-11-19 07:26:54,749 org.jobrunr.server.BackgroundJobServer: {} JobRunr BackgroundJobServer (3a580251-d03c-4616-8320-3400656eac34) and 8 BackgroundJobPerformers started successfully
[nio-8080-exec-50] WARN  2020-11-19 07:26:54,750 org.springframework.web.context.support.XmlWebApplicationContext: {} Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerController' defined in file [/opt/tomcat/webapps/ROOT/WEB-INF/classes/com/pixolut/stylyze/controller/api/v4/schedulers/SchedulerController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerManagerServiceImpl': Unsatisfied dependency expressed through field 'dezignableSchedulers'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JobRunr' defined in com.pixolut.stylyze.scheduler.JobRunRConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use
[nio-8080-exec-50] INFO  2020-11-19 07:26:54,754 com.pixolut.stylyze.tool.MongoTemplateHolder: {} Close mongodb client...
[nio-8080-exec-50] INFO  2020-11-19 07:26:54,754 org.mongodb.driver.connection: {} Closed connection [connectionId{localValue:8, serverValue:2865}] to 127.0.0.1:27017 because the pool has been closed.
[nio-8080-exec-50] INFO  2020-11-19 07:26:54,754 org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor: {} Shutting down ExecutorService
[nio-8080-exec-50] ERROR 2020-11-19 07:26:54,755 org.springframework.web.servlet.DispatcherServlet: {} Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerController' defined in file [/opt/tomcat/webapps/ROOT/WEB-INF/classes/com/pixolut/stylyze/controller/api/v4/schedulers/SchedulerController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerManagerServiceImpl': Unsatisfied dependency expressed through field 'dezignableSchedulers'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JobRunr' defined in com.pixolut.stylyze.scheduler.JobRunRConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$1055/1993476078.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:702)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:716)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:591)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:530)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:170)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:779)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'schedulerManagerServiceImpl': Unsatisfied dependency expressed through field 'dezignableSchedulers'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JobRunr' defined in com.pixolut.stylyze.scheduler.JobRunRConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1402)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$1055/1993476078.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 40 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'JobRunr' defined in com.pixolut.stylyze.scheduler.JobRunRConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1318)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$1055/1993476078.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	... 55 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: java.net.BindException: Address already in use
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 71 more
Caused by: java.lang.IllegalStateException: java.net.BindException: Address already in use
	at org.jobrunr.dashboard.server.TeenyWebServer.<init>(TeenyWebServer.java:31)
	at org.jobrunr.dashboard.JobRunrDashboardWebServer.start(JobRunrDashboardWebServer.java:57)
	at org.jobrunr.configuration.JobRunrConfiguration.useDashboardIf(JobRunrConfiguration.java:210)
	at com.pixolut.stylyze.scheduler.JobRunRConfig.initJobRunr(JobRunRConfig.java:43)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$6c29390c.CGLIB$initJobRunr$0(<generated>)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$6c29390c$$FastClassBySpringCGLIB$$c2981751.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$6c29390c.initJobRunr(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 72 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:437)
	at sun.nio.ch.Net.bind(Net.java:429)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
	at org.jobrunr.dashboard.server.TeenyWebServer.<init>(TeenyWebServer.java:26)
	... 85 more

[8524793-thread-2] WARN  2020-11-19 07:26:55,547 org.jobrunr.server.JobZooKeeper: {} JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getJedis(JedisRedisStorageProvider.java:456)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getJobs(JedisRedisStorageProvider.java:278)
	at org.jobrunr.storage.ThreadSafeStorageProvider.getJobs(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.JobZooKeeper.checkForEnqueuedJobs(JobZooKeeper.java:168)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 13 more

[Timer-0] WARN  2020-11-19 05:01:28,748 org.jobrunr.storage.AbstractStorageProvider: {} Error notifying JobStorageChangeListeners
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.util.Pool.getResource(Pool.java:59)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:288)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getJedis(JedisRedisStorageProvider.java:456)
	at org.jobrunr.storage.nosql.redis.JedisRedisStorageProvider.getBackgroundJobServers(JedisRedisStorageProvider.java:131)
	at org.jobrunr.storage.AbstractStorageProvider.notifyBackgroundJobServerStatusChangeListeners(AbstractStorageProvider.java:122)
	at org.jobrunr.storage.AbstractStorageProvider.access$100(AbstractStorageProvider.java:21)
	at org.jobrunr.storage.AbstractStorageProvider$SendJobStatsUpdate.run(AbstractStorageProvider.java:166)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:759)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:402)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349)
	at redis.clients.jedis.util.Pool.getResource(Pool.java:50)
	... 8 more`

**Environment**
I'm using version 1.20
I'm running on JDK 1.8 
I'm using the following StorageProvider Redis Storage Provider 
The application is packaged by Spring and deployed on a tomcat 8 server

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.

JobRunr is configured as follows:

```java
@Bean(name = "JobRunr")
  @DependsOn("initializeRedisConnectionPool")
  public JobScheduler initJobRunr(ApplicationContext applicationContext, JedisPool jedisPool) {
    JobRunrConfiguration jobRunrConfiguration =
        JobRunr.configure()
            .useStorageProvider(new JedisRedisStorageProvider(jedisPool))
            .useJobActivator(applicationContext::getBean)
            .useDefaultBackgroundJobServerIf(
                backgroundJobServerEnabled, backgroundJobServerWorkerCount)
            .withJobFilter(new RetryFilter(backgroundJobServerDefaultRetry))
            .useDashboardIf(dashboardEnabled, dashboardPort);
    if (backgroundJobServerEnabled) {
      return jobRunrConfiguration.useJmxExtensions().initialize();
    } else {
      return jobRunrConfiguration.initialize();
    }
  }


With recurrent jobs like

BackgroundJob.scheduleRecurrently(
        "UpdateFullPricingAndPromoFile-BG",
        BergdorfgoodmanPricingImportScheduler::scheduledImportUpdateFullPricingAndPromoFile,
        Cron.every10minutes());
```

**Expected behavior**
The new re-deployed application should start normally when a new war is deployed without having to restart tomcat itself

**Additional context**

**Comment by rdehuyss** [comment]
Hi @Azyl,

I'm sure I already fixed 2 out of 3 problems but I'm a little bit short on time and won't be able to test if it also fixes the following error:

```
[8524793-thread-2] WARN 2020-11-19 07:26:55,547 org.jobrunr.server.JobZooKeeper: {} JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
```

To be honest, I also don't understand it completely as I expect Spring/Tomcat to create a new `JedisPool` (which is open and ready to use) and a new `JobScheduler` bean using this new `JedisPool` bean. I re-opened the issue to follow up on this error. Can you retest once a new release is available?

The other errors should be fixed now thanks to some Spring magic I just learned:
- I added a shutdown method on the `JobScheduler` bean. This bean delegates to the static JobRunr class and shuts down everything that is started.
- The magick? Spring automatically calls each shutdown method on all beans when redeploying/shutting down. See https://stackoverflow.com/questions/44756872/spring-core-default-bean-destroy-method for more info.


One more question: why are you not using the `spring-boot-jobrunr-starter`?

**Comment by rdehuyss** [comment]
Never mind - thinking about, all is solved.

**Comment by Azyl** [comment]
Hi @rdehuyss ,

Thank you for the help on this matter, I have tested the latest version and deployments are now working as expected.

Extra thank you for the new useJmxExtensionsIf method as it makes everything look cleaner.

Regarding your question, this is a project started a long time ago and we updated it to lets say modern time but the project due to its dependencies and set-up is using Spring (not spring boot) a war packaging and a dedicated tomcat server.

I actually think that a lot of these "older" monolitic projects would be a good candidate for your library, however please note that on such projects the focus will lie on these recurent background job where a lot of the business process take place.

I would be nice if we can have filters/search input field on the job pages so that we may easily come through the large of number of jobs.

Another nice feature to have is to have some auditing regarding the dashboard and if any manual actions is performed on the jobs (triggering, deleting, etc).



I only encountered a single use case that I could not fit with the help of your library:

We have in this project some base classes and they are extended to fit the need of a diferent customer, for example an SftImporter and Client1SftImporter and Client2SftImporter that extends SftImporter and only overrides one method from the base class like getImportCredentials() and because the job activator uses getBean(Type type) we will get an error as we have 2 beans of the same type (the base type). It would be nice if we could use the getBean(String name, Type type).

Overall is a wonderful project that you started, something missing from the spring eco systems.

I recommended to our client to contact you regarding a pro license as I would like to see this further expanded.

**Comment by Azyl** [comment]
I would like to leave this here for others in case they encounter the same issue.

Even after the proper shutdown with beans destroy methods we sometimes saw errors with redeploying our application.

After a little bit of digging it seems that the issue was caused by the fact that we had multiple Spring ApplicationContexts and this caused mbeans names to clash (so you either do not use jmx or you can set endpoints.jmx.uniqueNames property to true so that MBean names are always unique.)
