### ISSUE TITLE
[BUG] Recurring job with single JobContext parameter throws IllegalStateException

### ISSUE THREAD

**Issue by swyftify** [jobrunr/jobrunr#689]
### JobRunr Version

6.0.0

### JDK Version

OpenJDK 11.0.15

### Your SQL / NoSQL database

Postgres 14

### What happened?

When i add a method parameter of `JobContext` to a recurring job, similar to your suggestion: https://stackoverflow.com/questions/73745947/how-to-get-job-context-for-recurring-job

During the build step i get (using Quarkus):
`Build step org.jobrunr.quarkus.extension.deployment.JobRunrExtensionProcessor#findRecurringJobAnnotationsAndScheduleThem threw an exception: java.lang.IllegalStateException: Methods annotated with org.jobrunr.quarkus.annotations.Recurring can only have zero parameters or a single parameter of type JobContext.`

I tried doing the same thing with your example quarkus project, but i get a similar error there. 

### How to reproduce?

```
  @Recurring(id = "jb", cron = "*/1 * * * *")
  @Job(name = "Job")
  public void recurringJob(JobContext jobContext) {
     System.out.print("Text");
  }
```

### Relevant log output

```shell
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.jobrunr.quarkus.extension.deployment.JobRunrExtensionProcessor#findRecurringJobAnnotationsAndScheduleThem threw an exception: java.lang.IllegalStateException: Methods annotated with org.jobrunr.quarkus.annotations.Recurring can only have zero parameters or a single parameter of type JobContext.
        at org.jobrunr.quarkus.extension.deployment.RecurringJobsFinder.getJobDetails(RecurringJobsFinder.java:83)
        at org.jobrunr.quarkus.extension.deployment.RecurringJobsFinder.findRecurringJobsAndScheduleThem(RecurringJobsFinder.java:43)
        at org.jobrunr.quarkus.extension.deployment.JobRunrExtensionProcessor.findRecurringJobAnnotationsAndScheduleThem(JobRunrExtensionProcessor.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by rdehuyss** [comment]
@swyftify : did you read the community guidelines on creating bugs?
