### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by steamrolla** [jobrunr/jobrunr#692]
### Runtime information
- __Timestamp__: 2023-01-30T19:05:48.519901Z
- __Location__: BackgroundJobServer dcbc4453-be90-4a6f-a456-c6e1270abe10
- __JobRunr Version__: 5.3.2
- __StorageProvider__: org.jobrunr.storage.sql.common.DefaultSqlStorageProvider
- __Java Version__: 11.0.16.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 7e1c1d6e-b92d-4f9b-9304-1b6957ec3cc6
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-01-24T04:10:42.545638Z, lastHeartbeat: 2023-01-31T01:05:48.086151Z)

#### Concurrent modified jobs:
Job id: 623d747a-a576-49c0-abfd-ea95672e7921
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-01-30T19:05:48.297095Z on BackgroundJobServer dcbc4453-be90-4a6f-a456-c6e1270abe10 and started at 2023-01-30T19:05:17.802522Z) ← ENQUEUED (at 2023-01-30T19:05:10.248057Z)
	Storage state: FAILED (at 2023-01-30T19:05:20.468413Z) ← PROCESSING (updated at 2023-01-30T19:05:17.802522Z on BackgroundJobServer dcbc4453-be90-4a6f-a456-c6e1270abe10 and started at 2023-01-30T19:05:17.802522Z) ← ENQUEUED (at 2023-01-30T19:05:10.248057Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment]
Hi @steamrolla - are you running on shared hosting or is this perhaps from a laptop? Or did you stop one of the Background Job Servers?

The server where the issue happened (dcbc4453-be90-4a6f-a456-c6e1270abe10) appears not to be active anymore as it is not in the list of active background job servers.

**Comment by rdehuyss** [comment]
Hi @steamrolla - could you help me with the above?

**Comment by steamrolla** [comment]
Hey @rdehuyss, yes, I believe this came from our dev environment where we have developers sometimes running our app locally against the same DB as a dedicated node up in the cloud.

**Comment by rdehuyss** [comment]
Close as related to DEV laptop against dev DB.
