### ISSUE TITLE
[BUG] Payload document size is larger than maximum

### ISSUE THREAD

**Issue by aperhaite-neimanmarcus** [jobrunr/jobrunr#701]
### JobRunr Version

jobrunr-spring-boot-starter version 5.3.3

### JDK Version

openjdk 19

### Your SQL / NoSQL database

MongoDB 4.0.27

### What happened?

We have a long Job that processes a lot of records. That jobs logs some data after every processed batch. After some millions of processed data, JobRunr failed to save data into MongoDB.
A possible solution would be to truncate the logs when a threshold is reached. 

### How to reproduce?

```java
  // Try to save some millions of logs for a Job in JobRunr
```

### Relevant log output

```shell
2023-02-21T14:28:30.800+02:00	2023-02-21T12:28:30.797Z ERROR 1 --- [pool-6-thread-2] org.jobrunr.server.JobZooKeeper : FATAL - JobRunr encountered too many processing exceptions. Shutting down.
2023-02-21T14:28:30.800+02:00	org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
2023-02-21T14:28:30.800+02:00	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:83) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
2023-02-21T14:28:30.800+02:00	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
2023-02-21T14:28:30.800+02:00	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
2023-02-21T14:28:30.800+02:00	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
2023-02-21T14:28:30.800+02:00	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
2023-02-21T14:28:30.800+02:00	at java.base/java.lang.Thread.run(Thread.java:1589) ~[na:na]
2023-02-21T14:28:30.800+02:00	Caused by: org.bson.BsonMaximumSizeExceededException: Payload document size is larger than maximum of 16793600.
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:68) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:164) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:134) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:60) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:328) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:302) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:373) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:278) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:208) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:181) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:212) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:76) ~[mongodb-driver-core-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:212) ~[mongodb-driver-sync-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.client.internal.MongoCollectionImpl.executeBulkWrite(MongoCollectionImpl.java:448) ~[mongodb-driver-sync-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.client.internal.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:428) ~[mongodb-driver-sync-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at com.mongodb.client.internal.MongoCollectionImpl.bulkWrite(MongoCollectionImpl.java:423) ~[mongodb-driver-sync-4.8.0.jar!/:na]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:276) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:217) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75) ~[jobrunr-5.3.3.jar!/:5.3.3]
2023-02-21T14:28:30.800+02:00	... 6 common frames omitted
2023-02-21T14:28:30.800+02:00	2023-02-21T12:28:30.799Z INFO 1 --- [pool-6-thread-2] org.jobrunr.server.BackgroundJobServer : BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
2023-02-21T14:28:31.132+02:00
```

**Comment by rdehuyss** [comment]
Closing due to not following community guidelines (missing profile information).
