### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by vugt143** [jobrunr/jobrunr#703]
### Runtime information
- __Timestamp__: 2022-09-26T07:19:01.553113300Z
- __Location__: BackgroundJobServer 6c690742-b82a-4b7f-9427-53ba73788265
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.4.1
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 5392d0da-f4c2-4075-b828-392caa9b4757
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-09-26T03:18:28.293162Z, lastHeartbeat: 2022-09-26T03:18:58.331466Z)
- BackgroundJobServer id: 572276a5-f72a-4b12-9d57-569e0a591f29
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-09-26T03:18:28.302601Z, lastHeartbeat: 2022-09-26T03:18:58.329712Z)
- BackgroundJobServer id: 4594181c-fab5-4e29-a191-41eaeed86319
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-09-26T03:18:29.415386Z, lastHeartbeat: 2022-09-26T03:18:59.437163Z)
- BackgroundJobServer id: 6c690742-b82a-4b7f-9427-53ba73788265
(workerPoolSize: 96, pollIntervalInSeconds: 10, firstHeartbeat: 2022-09-26T07:17:34.812645Z, lastHeartbeat: 2022-09-26T07:18:54.678386Z)

#### Concurrent modified jobs:
Job id: 432a2df5-917a-42b8-a152-010958296be4
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2022-09-26T07:18:58.524783400Z) ← SUCCEEDED (at 2022-09-25T07:18:46.385653129Z) ← PROCESSING (updated at 2022-09-25T07:18:46.384034122Z on BackgroundJobServer 572276a5-f72a-4b12-9d57-569e0a591f29 and started at 2022-09-25T07:18:46.384034122Z) ← ENQUEUED (at 2022-09-25T07:18:46.374326109Z) ← SCHEDULED (at 2022-09-25T07:18:46.371208649Z)
	Storage state: DELETED (at 2022-09-26T07:18:49.383067864Z) ← SUCCEEDED (at 2022-09-25T07:18:46.385653129Z) ← PROCESSING (updated at 2022-09-25T07:18:46.384034122Z on BackgroundJobServer 572276a5-f72a-4b12-9d57-569e0a591f29 and started at 2022-09-25T07:18:46.384034122Z) ← ENQUEUED (at 2022-09-25T07:18:46.374326109Z) ← SCHEDULED (at 2022-09-25T07:18:46.371208649Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:196)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:137)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2022-12-19T06:24:23.585049905Z
- __Location__: BackgroundJobServer e0b514e4-60a3-435e-9a76-5fb1ce3da34f
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: e0b514e4-60a3-435e-9a76-5fb1ce3da34f
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-12-19T06:24:12.287600Z, lastHeartbeat: 2022-12-19T06:24:22.297143Z)
- BackgroundJobServer id: 5d8fd5f2-6e28-46eb-8475-6ed5ad70cbf7
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-12-19T06:24:13.352760Z, lastHeartbeat: 2022-12-19T06:24:23.364881Z)
- BackgroundJobServer id: e8afd5ca-0328-408f-b1d2-50af1d757236
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2022-12-19T06:24:16.373795Z, lastHeartbeat: 2022-12-19T06:24:16.375962Z)
- BackgroundJobServer id: aa6839d1-0680-4859-9631-69fccef90d62
(workerPoolSize: 96, pollIntervalInSeconds: 10, firstHeartbeat: 2022-12-19T13:23:30.673385Z, lastHeartbeat: 2022-12-19T13:24:23.047507Z)

#### Concurrent modified jobs:
Job id: 7a843250-9892-4bab-bcec-7c54712cc62a
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2022-12-19T06:24:23.299083590Z) ← SUCCEEDED (at 2022-12-18T06:24:22.394284572Z) ← PROCESSING (updated at 2022-12-18T06:24:22.389277923Z on BackgroundJobServer e0b514e4-60a3-435e-9a76-5fb1ce3da34f and started at 2022-12-18T06:24:22.389277923Z) ← ENQUEUED (at 2022-12-18T06:24:22.379530891Z) ← SCHEDULED (at 2022-12-18T06:24:22.376610488Z)
	Storage state: DELETED (at 2022-12-19T06:24:24.933012600Z) ← SUCCEEDED (at 2022-12-18T06:24:22.394284572Z) ← PROCESSING (updated at 2022-12-18T06:24:22.389277923Z on BackgroundJobServer e0b514e4-60a3-435e-9a76-5fb1ce3da34f and started at 2022-12-18T06:24:22.389277923Z) ← ENQUEUED (at 2022-12-18T06:24:22.379530891Z) ← SCHEDULED (at 2022-12-18T06:24:22.376610488Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:196)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:137)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2023-01-09T03:11:09.851438600Z
- __Location__: BackgroundJobServer 536a67f8-9615-452b-a6ff-60d37e94b98c
- __JobRunr Version__: 5.1.4
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.5
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: 9c3ba9b1-ba87-490f-9fd2-6bbe4ea4ecd1
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2023-01-08T20:10:57.497456Z, lastHeartbeat: 2023-01-08T20:11:07.510016Z)
- BackgroundJobServer id: c9b6a987-7472-4106-a680-f37b8d877d6c
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2023-01-08T20:10:58.272406Z, lastHeartbeat: 2023-01-08T20:11:08.285470Z)
- BackgroundJobServer id: 6b6cdabd-8fbe-4a29-b62f-112abe8738cb
(workerPoolSize: 8, pollIntervalInSeconds: 10, firstHeartbeat: 2023-01-08T20:11:00.089194Z, lastHeartbeat: 2023-01-08T20:11:00.094795Z)
- BackgroundJobServer id: 536a67f8-9615-452b-a6ff-60d37e94b98c
(workerPoolSize: 96, pollIntervalInSeconds: 10, firstHeartbeat: 2023-01-09T03:10:14.319597Z, lastHeartbeat: 2023-01-09T03:11:06.714394Z)

#### Concurrent modified jobs:
Job id: f98b5712-26c2-412f-8cb8-e55e9303eda9
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2023-01-09T03:11:08.472713500Z) ← SUCCEEDED (at 2023-01-08T03:11:06.780601426Z) ← PROCESSING (updated at 2023-01-08T03:11:06.778954068Z on BackgroundJobServer c9b6a987-7472-4106-a680-f37b8d877d6c and started at 2023-01-08T03:11:06.778954068Z) ← ENQUEUED (at 2023-01-08T03:11:06.768703379Z) ← SCHEDULED (at 2023-01-08T03:11:06.757078149Z)
	Storage state: DELETED (at 2023-01-09T03:11:08.532492039Z) ← SUCCEEDED (at 2023-01-08T03:11:06.780601426Z) ← PROCESSING (updated at 2023-01-08T03:11:06.778954068Z on BackgroundJobServer c9b6a987-7472-4106-a680-f37b8d877d6c and started at 2023-01-08T03:11:06.778954068Z) ← ENQUEUED (at 2023-01-08T03:11:06.768703379Z) ← SCHEDULED (at 2023-01-08T03:11:06.757078149Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:212)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:196)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:137)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:100)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:77)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
I don't provide support it you're not using the latest version of JobRunr. Please upgrade.

**Comment by vugt143** [comment]
Ok. Let me upgrade to the lastest version. Thanks
