### ISSUE TITLE
[BUG] Background Server Automatic Restart (JobRunR Pro)

### ISSUE THREAD

**Issue by neldrak** [jobrunr/jobrunr#709]
### JobRunr Version

5.3.1

### JDK Version

OpenJDK Java 11

### Your SQL / NoSQL database

HANA :)

### What happened?

Hey Ronald
again, this is my private github account. I'm the guy working for the 3 letter software company working on the weather risk project for a big agricultural company ;)

We recently came across this and I wanted to check in with you to see if we are doing something wrong or if it is a HANA querk or something.

The HANA DB was unavailable (happens ;)), so the background server shuts down. Which is ok.

```
An unrecoverable error occurred. Shutting server down...
org.jobrunr.storage.StorageException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.

```
But I thought that it would then later try to recover?

> JobRunr Pro has your back
> JobRunr Pro increases resilience for this and pauses all job processing as soon as the StorageProvider goes down. It continues to monitor the database whether it comes up again and if so, automatically restarts processing on all the different BackgroundJobServers.
> 

Do we need to enable this somewhere?
Also I think a button in the Dashboard would be great to start a new background server.
Right now we need to fully restart the app instance, which is not ideal.

Thanks!

### How to reproduce?

Have a HANA, have it run out of connections (easier then you think!) and then just wait and see.

### Relevant log output

```shell
org.jobrunr.storage.StorageException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java:97)
	at org.jobrunr.storage.ThreadSafeStorageProvider.signalBackgroundJobServerAlive(ThreadSafeStorageProvider.java:72)
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAlive(ServerZooKeeper.java:92)
	at org.jobrunr.server.ServerZooKeeper.signalBackgroundJobServerAliveAndDoZooKeeping(ServerZooKeeper.java:76)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.signalBackgroundJobServerAlive(DefaultSqlStorageProvider.java:92)
	... 10 more
```

**Comment by rdehuyss** [comment]
Hi @neldrak , JobRunr Pro 6.1 made improvements in that regard. 

Can you upgrade and see whether you still have issues?

**Comment by rdehuyss** [comment]
Feel free to reopen a new issue if you still encounter it with 6.1.

**Comment by neldrak** [comment]
Hey!
Thansk for the help.
Will try, but we also want to upgrade to Spring Boot 3 /Spring 6.X, which might take a bit.
A simple way to start a background server from the dashboard would be appreciated.
Best regards,
Daniel

**Comment by rdehuyss** [comment]
Hi Daniel, that's also available in latest v5 version (5.3.4 I think).

**Comment by rdehuyss** [comment]
See also https://github.com/jobrunr/jobrunr/discussions/705

**Comment by neldrak** [comment]
Only if there IS a background server, you can stop/resume it.
But in our case, there is none in the list ;)

**Comment by rdehuyss** [comment]
true, I had not thought about that...
