### ISSUE TITLE
[BUG] NPE due to missing property at job JSON when using Yasson

### ISSUE THREAD

**Issue by mkowa42** [jobrunr/jobrunr#711]
### JobRunr Version

6.0.0

### JDK Version

OpenJDK 17

### Your SQL / NoSQL database

Postgres 13

### What happened?

When running the application with JobRunr 6 having a database with stored jobs created by a previous version of JobRunr it comes to a NPE and JobRunr stops working.

As far as I understand it's due to the missing `labels` property of the persisted job's JSON. I saw that labels on recurring jobs are a new feature introduced with version 6. Every newly persisted recurring job has that property on its JSON.

As a workaround I deleted all jobs from the jobs table which solves the problem.

My expectation would be that the `JobLabelsAdapter.adaptFromJson` method and similar deserialization code should be null-safe and can handle it with a proper default value (e.g. empty collection of labels in that particular case).

### How to reproduce?

See description.

### Relevant log output

```shell
2023-03-03 12:43:08,148 ERROR [org.job.ser.JobZooKeeper] (backgroundjob-zookeeper-pool-16-thread-2) ({}) FATAL - JobRunr encountered too many processing exceptions. Shutting down.: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:62)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.json.bind.JsonbException: Problem adapting object of type class org.jobrunr.jobs.Job to interface javax.json.JsonObject in class class org.jobrunr.utils.mapper.jsonb.JobAdapter
        at org.eclipse.yasson.internal.serializer.AdaptedObjectDeserializer.deserialize(AdaptedObjectDeserializer.java:90)
        at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:62)
        at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:51)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:59)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:66)
        at org.jobrunr.utils.mapper.jsonb.JsonbJsonMapper.deserialize(JsonbJsonMapper.java:51)
        at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
        at org.jobrunr.storage.sql.common.JobTable.toJob(JobTable.java:189)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:44)
        at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.jobrunr.storage.sql.common.JobTable.selectJobsByState(JobTable.java:125)
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobs(DefaultSqlStorageProvider.java:230)
        at org.jobrunr.storage.ThreadSafeStorageProvider.getJobs(ThreadSafeStorageProvider.java:128)
        at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.lambda$runTask$0(DeleteSucceededJobsTask.java:28)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.getJobsToProcess(ZooKeeperTask.java:85)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:57)
        at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:29)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
        at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:76)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
        at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:76)
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
        ... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "javax.json.JsonArray.iterator()" because "jsonArray" is null
        at org.jobrunr.utils.mapper.jsonb.adapters.JobLabelsAdapter.adaptFromJson(JobLabelsAdapter.java:30)
        at org.jobrunr.utils.mapper.jsonb.JobAdapter.adaptFromJson(JobAdapter.java:68)
        at org.jobrunr.utils.mapper.jsonb.JobAdapter.adaptFromJson(JobAdapter.java:25)
        at org.eclipse.yasson.internal.serializer.AdaptedObjectDeserializer.deserialize(AdaptedObjectDeserializer.java:87)
        ... 33 more
```

**Comment by rdehuyss** [comment]
Please update your profile (as asked in community guidelines).
