### ISSUE TITLE
[BUG] Exception thrown on MySQL 8 when JobRunr attempts to update succeeded-jobs-counter-cluster

### ISSUE THREAD

**Issue by stevemcleod** [jobrunr/jobrunr#717]
### JobRunr Version

6.1.1

### JDK Version

Amazon Corretto 19

### Your SQL / NoSQL database

MySQL 8.0.28 (prod) and MySQL 8.0.32 (dev)

### What happened?

When reviewing our production logs, I found this exception trace, and instructions to create a bug report.

I can reproduce the specific MySQL error directly in an SQL console as follows:

```
set @value = '1.000000000000000000000000000000';

update jobrunr_metadata
set value = cast((cast(cast(@value as char(10)) as decimal(10, 0)) + 1) as char(10))
where id = 'succeeded-jobs-counter-cluster';
```

The full stack trace in below, in the "Relevant log output" field. 

Note that this stack trace occurs many times in our logs.

### How to reproduce?

I don't have repro steps. It doesn't seem to be directly connected to our code.

### Relevant log output

```shell
org.jobrunr.server.JobZooKeeper - JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.storage.StorageException: java.sql.SQLDataException: Data truncation: Truncated incorrect CHAR(10) value: '3.000000000000000000000000000000'
Query being executed when exception was thrown:
com.mysql.cj.jdbc.ServerPreparedStatement[126]: update jobrunr_metadata set value = cast((cast(cast( value as char(10) ) as decimal(10, 0)) + 3) as char(10)) where id = 'succeeded-jobs-counter-cluster'
    at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:366)
at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:199)
at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.handleTotalAmountOfSucceededJobs(DeleteSucceededJobsTask.java:34)
at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:63)
at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:29)
at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:76)
at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:76)
at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLDataException: Data truncation: Truncated incorrect CHAR(10) value: '3.000000000000000000000000000000'
Query being executed when exception was thrown:
com.mysql.cj.jdbc.ServerPreparedStatement[126]: update jobrunr_metadata set value = cast((cast(cast( value as char(10) ) as decimal(10, 0)) + 3) as char(10)) where id = 'succeeded-jobs-counter-cluster'
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555)
at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
at jdk.internal.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:107)
at jdk.proxy2/jdk.proxy2.$Proxy13.executeUpdate(Unknown Source)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:152)
at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:133)
at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:66)
at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:363)
... 15 more
```

**Comment by stevemcleod** [comment]
I noticed there is a closed issue with a similar exception: https://github.com/jobrunr/jobrunr/issues/677

The advice there was to try setting ` jdbcCompliantTruncation=true` in the MySQL connection. I can confirm that jdbcCompliantTruncation is true for our JDBC connections.

**Comment by stevemcleod** [comment]
I looked into the failing SQL statement to see if I could help.

Here's two variants of the failing query that work with MySQL 8.0.32:

With full casting:

```
update jobrunr_metadata
set value = cast(cast(value as decimal(10,0)) + 1 as char(10))
where id = 'succeeded-jobs-counter-cluster';
```

And taking advantage of MySQL's promiscuous auto-casting:

```
update jobrunr_metadata
set value = value + 1
where id = 'succeeded-jobs-counter-cluster';
```

Is there a way I can help with fixing, and then testing, to make sure the change works across all supported storage providers?

**Comment by rdehuyss** [comment]
Hi @stevemcleod , thanks for this and your diagnose. The thing is that I still cannot reproduce this in a test case (nor in my setup, nor in an env running with MySQL) so it is hard for me to solve this issue.

I'll try again with your setup later this week.

Can you provide me with the MySQL driver you are using? Are you on MySQL AWS? Can you reproduce this issue with MySQL in docker?

**Comment by stevemcleod** [comment]
We're using the MySQL JDBC driver version 8.0.32.

The problem occurs when using MySQL with AWS, and when using MySQL locally with Docker.

I've managed to reliably reproduce the problem by directly calling `StorageProvider::publishTotalAmountOfSucceededJobs`.

```
import com.mysql.cj.jdbc.MysqlDataSource;
import org.jobrunr.configuration.JobRunr;
import org.jobrunr.storage.StorageProvider;
import org.jobrunr.storage.StorageProviderUtils;
import org.jobrunr.storage.sql.mysql.MySqlStorageProvider;

import java.sql.SQLException;

public class ScratchSpace {

    public static void main(String[] args) throws SQLException {

        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setURL("jdbc:mysql://localhost:3307/featureupvote");
        dataSource.setUser("root");
        dataSource.setPassword("password");

        // setting this to true causes JobRunr's StorageProvider::publishTotalAmountOfSucceededJobs to fail
        dataSource.setUseServerPrepStmts(true);

        StorageProvider storageProvider = new MySqlStorageProvider(dataSource, StorageProviderUtils.DatabaseOptions.CREATE);
        JobRunr.configure()
                .useStorageProvider(storageProvider)
                .useBackgroundJobServer()
                .initialize();

        storageProvider.publishTotalAmountOfSucceededJobs(1);
    }
}
```

For now, I'm going to stop our code from using MySQL's  `useServerPrepStmts` setting.

The reason we use it is because we use HikariCP as a connection pool, and [HikariCP's docs](https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration) recommend we use it.

**Comment by stevemcleod** [comment]
I've taken the liberty to rename the issue to state the cause of the problem.

**Comment by rdehuyss** [comment]
I was able to reproduce it! Thanks for the input. Looking into a fix.

**Comment by rdehuyss** [comment]
Will be released early next week.

@stevemcleod : can you verify whether the fix works for you? The new statement is:
`.update("jobrunr_metadata set value = cast(round((cast(cast( value as char(10) ) as decimal(10, 0)) + :amount), 0) as char(10)) where id = :id")`

The reason it is this complex and not the solution you proposed, is that it needs to be compatible with all SQL databases including DB2 and Oracle 🤯 .

**Comment by stevemcleod** [comment]
Thank you! That was very fast.

Regarding verifying the fix, is there a auto-build available that I can use for this?

**Comment by rdehuyss** [comment]
Only after release.

The build instructions are available at the end of the [README.md](https://github.com/jobrunr/jobrunr/blob/master/README.md) if you want.

Feel free to star the repo if you're happy with the support (or even better, get a Pro license to support further development 😉 ).
