### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amine-hamzi** [jobrunr/jobrunr#718]
### JobRunr Version

5.1.7

### JDK Version

jdk1.8.0_221

### Your SQL / NoSQL database

Postgres

### What happened?

Hi! Jobrunr!
i'm trying to use ApplyStateFilter in @JobAnnotation(filters), when i start the application i got this error message : java.lang.NoSuchMethodException com.socgen.unibank.services.interoperability.core.usecases.support.job.CompensationFilters.<init>()
 here is the filter i created :

@Component
@AllArgsConstructor
public class CompensationFilters implements ApplyStateFilter {

    private InteroperabilityRepository repository;

    public void onStateApplied(Job job, JobState oldState, JobState newState) {
        repository.handle();
    }
}

### How to reproduce?

```java
   @Recurring(cron = "16 17 * * 1-5")
    @Job(name = "Compensation job", retries = 2, jobFilters = {CompensationFilters.class})
    public void compensationTask() {
        service.handle();
    }
```

### Relevant log output

```shell
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compensationJobImpl' defined in file [D:\My directory\projets\unibank-service-interoperability\unibank-service-interoperability\build\classes\java\main\com\socgen\unibank\services\interoperability\core\usecases\support\job\CompensationJobImpl.class]: Initialization of bean failed; nested exception is org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at com.socgen.unibank.services.interoperability.ServiceInteroperability.main(ServiceInteroperability.java:9) [main/:na]
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.utils.reflection.ReflectionUtils.newInstance(ReflectionUtils.java:150) ~[jobrunr-5.3.3.jar:5.3.3]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_221]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_221]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_221]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_221]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_221]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_221]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_221]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_221]
	at org.jobrunr.jobs.filters.AbstractJobFilters.getOtherJobFilter(AbstractJobFilters.java:88) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.jobs.filters.AbstractJobFilters.addJobFiltersFromJobAnnotation(AbstractJobFilters.java:58) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.jobs.filters.AbstractJobFilters.initJobFilters(AbstractJobFilters.java:34) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.jobs.filters.AbstractJobFilters.<init>(AbstractJobFilters.java:27) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.jobs.filters.JobCreationFilters.<init>(JobCreationFilters.java:15) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.jobs.filters.JobFilterUtils.runOnCreatingFilter(JobFilterUtils.java:17) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.scheduling.AbstractJobScheduler.scheduleRecurrently(AbstractJobScheduler.java:123) ~[jobrunr-5.3.3.jar:5.3.3]
	at org.jobrunr.scheduling.RecurringJobPostProcessor$RecurringJobFinderMethodCallback.doWith(RecurringJobPostProcessor.java:97) ~[jobrunr-spring-boot-starter-5.3.3.jar:5.3.3]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:364) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:343) ~[spring-core-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.jobrunr.scheduling.RecurringJobPostProcessor.postProcessAfterInitialization(RecurringJobPostProcessor.java:39) ~[jobrunr-spring-boot-starter-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:430) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1798) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	... 16 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.jobrunr.jobs.filters.ApplyStateFilter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[na:1.8.0_221]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_221]
	at org.jobrunr.utils.reflection.ReflectionUtils.newInstance(ReflectionUtils.java:146) ~[jobrunr-5.3.3.jar:5.3.3]
	... 38 common frames omitted
```

**Comment by rdehuyss** [comment]
You are using a Pro feature ([dependency injection in your filter](https://www.jobrunr.io/en/documentation/pro/job-filters/)) in the free version. I'm afraid that's not possible in the free version.

**Comment by amine-hamzi** [comment]
Thanks for your support🙂
