### ISSUE TITLE
[BUG] withJobFilter Error on version 1.22 vs 1.21

### ISSUE THREAD

**Issue by Azyl** [jobrunr/jobrunr#72]
**Describe the bug**

JobRunr Start-up error is being thrown when using the fluent configuration on the new version 1.22 versus the old 1.21

**Environment**
I'm using version 1.22
I'm running on JDK 8
I'm using the following StorageProvider RedisStorageProvider 

**To Reproduce**
Provide a simple project or code fragment which shows how to reproduce the issue.
```java

Initialize Jobrunr with the following fluent configuration

@Bean(name = "JobRunr")
  @DependsOn("jedisPool")
  public JobScheduler initJobRunr(ApplicationContext applicationContext, JedisPool jedisPool) {
    return JobRunr.configure()
        .useStorageProvider(new JedisRedisStorageProvider(jedisPool))
        .useJobActivator(applicationContext::getBean)
        .useDefaultBackgroundJobServerIf(backgroundJobServerEnabled, backgroundJobServerWorkerCount)
        .withJobFilter(new RetryFilter(backgroundJobServerDefaultRetry))
        .useDashboardIf(dashboardEnabled, dashboardPort)
        .initialize();
  }


Error received:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.scheduling.JobScheduler]: Factory method 'initJobRunr' threw exception; nested exception is java.lang.IllegalStateException: Please configure the JobFilters before the BackgroundJobServer.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 63 more
Caused by: java.lang.IllegalStateException: Please configure the JobFilters before the BackgroundJobServer.
	at org.jobrunr.configuration.JobRunrConfiguration.withJobFilter(JobRunrConfiguration.java:67)
	at com.pixolut.stylyze.scheduler.JobRunRConfig.initJobRunr(JobRunRConfig.java:40)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$c0ae7ff0.CGLIB$initJobRunr$0(<generated>)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$c0ae7ff0$$FastClassBySpringCGLIB$$cdf17cae.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.pixolut.stylyze.scheduler.JobRunRConfig$$EnhancerBySpringCGLIB$$c0ae7ff0.initJobRunr(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 64 more
25-Nov-2020 14:30:57.780 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/stylyze.war] has finished in [73,830] ms
25-Nov-2020 14:30:57.808 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]



```

**Expected behavior**
Application starts without errors from Jobrunr initialisation

**Additional context**
The same initialisation code works without issues on 1.21

**Comment by rdehuyss** [comment]
Please read the actual error message 😉.

It says how to solve it...
