### ISSUE TITLE
[Improvement] Add support for Kotlin functions

### ISSUE THREAD

**Issue by igr** [jobrunr/jobrunr#739]
### JobRunr Version

6.1.2

### JDK Version

17

### Your SQL / NoSQL database

n/a

### What happened?

Using lambda scheduler fails on Kotlin 1.8.

### How to reproduce?

```java
        jobScheduler.create(aJob()
            .withLabels(label)
            .withDetails(object: JobLambda {
                override fun run() {
                    job()
                }
            })
```

### Relevant log output

```shell
java.lang.UnsupportedOperationException: The Kotlin version 1.8 is unsupported
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder$1.visit(KotlinJobDetailsFinder.java:61)
	at org.objectweb.asm.ClassReader.readElementValue(ClassReader.java:3141)
	at org.objectweb.asm.ClassReader.readElementValues(ClassReader.java:2993)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:608)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:87)
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder.parse(KotlinJobDetailsFinder.java:98)
	at org.jobrunr.jobs.details.KotlinJobDetailsFinder.<init>(KotlinJobDetailsFinder.java:41)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:16)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:77)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:39)
	at org.jobrunr.jobs.details.JobDetailsGenerator.toJobDetails(JobDetailsGenerator.java:18)
	at org.jobrunr.scheduling.JobBuilder.build(JobBuilder.java:192)
	at org.jobrunr.scheduling.JobScheduler.create(JobScheduler.java:73)
```
```

**Comment by rdehuyss** [comment]
You're making life to hard... Use the below:

```java
      jobScheduler.create(aJob()
            .withLabels(label)
            .withDetails { job() }
        )
```

Please star the Github repo if you like the swift support!

**Comment by rdehuyss** [comment]
It will also never work as there is no (easy) way to get a properly initialised bean from the IoC container (in your case Spring) if you just schedule a [**lambda**](https://kotlinlang.org/docs/lambdas.html).

If you change it to a [function](https://kotlinlang.org/docs/functions.html), everything will work.

So:
```
class TestService {
    fun job() {
        println("!!!!")
    }
```

And then: 
```
val testService = TestService() // can be injected
val jobId = jobScheduler.create(aJob()
    .withLabels("my label")
    .withDetails { testService.job() }
)
```

will do the trick.
