### ISSUE TITLE
[BUG] java.sql.SQLException: Access denied thrown by JobRunrMetricsAutoConfiguration

### ISSUE THREAD

**Issue by arvindkgs** [jobrunr/jobrunr#762]
### JobRunr Version

5.1.7

### JDK Version

11

### Your SQL / NoSQL database

Mysql

### What happened?

Access denied exception is being thrown by JobRunrMetricsAutoConfiguration on initiation. The credentials are valid. I have tested it. 

Workaround: I have removed JobRunrMetricsAutoConfiguration from auto configuration. It seems to work, meaning it is able to connect to db after the application starts. Also I tried to create the StorageProviderMetricsBinder and BackgroundJobServerMetricsBinder on `@PostConstruct` after main application is created. But it still fails. Is there a way to delay the creation of this class?

### How to reproduce?

```java
 // This is how storageProvider is initialised.
  @Bean
  public StorageProvider storageProvider(
      JobMapper jobMapper,
      DataSource dataSource,
      @Value("${org.jobrunr.database.table-prefix:#{null}}") String tablePrefix) {
    DefaultSqlStorageProvider storageProvider;
    if (StringUtils.isNotEmpty(tablePrefix)) {
      storageProvider =
          new DefaultSqlStorageProvider(
              dataSource,
              new AnsiDialect(),
              tablePrefix,
              StorageProviderUtils.DatabaseOptions.CREATE);
    } else {
      storageProvider =
          new DefaultSqlStorageProvider(
              dataSource, new AnsiDialect(), StorageProviderUtils.DatabaseOptions.CREATE);
    }
    storageProvider.setJobMapper(jobMapper);
    return storageProvider;
  }

}

```

### Relevant log output

```shell
Access denied for user ...@'%' (using password: YES)\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.5.jar!/:?]
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:?]
    at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:59) ~[jobrunr-5.1.7.jar!/:5.1.7]\n"},"extendedStackTrace":"org.jobrunr.storage.StorageException: java.sql.SQLException: Access denied for user 's-mf-staging-FBdWetmKQbp5KganwaH'@'%' (using password: YES)
    at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:62) ~[jobrunr-5.1.7.jar!/:5.1.7]
    at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:35) ~[jobrunr-5.1.7.jar!/:5.1.7]
    at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
    at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
    at java.util.stream.ReferencePipeline.findFirst(Unknown Source) ~[?:?]
    at org.jobrunr.storage.sql.common.JobStatsView.getJobStats(JobStatsView.java:24) ~[jobrunr-5.1.7.jar!/:5.1.7]
    at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobStats(DefaultSqlStorageProvider.java:354) ~[jobrunr-5.1.7.jar!/:5.1.7]
    at org.jobrunr.storage.AbstractStorageProvider.notifyJobStatsOnChangeListeners(AbstractStorageProvider.java:73) [jobrunr-5.1.7.jar!/:5.1.7]
    at org.jobrunr.storage.AbstractStorageProvider$NotifyOnChangeListeners.run(AbstractStorageProvider.java:177) [jobrunr-5.1.7.jar!/:5.1.7]
    at java.util.TimerThread.mainLoop(Unknown Source) [?:?]
    at java.util.TimerThread.run(Unknown Source) [?:?]\nCaused by: java.sql.SQLException: Access denied for user 's-mf-staging-FBdWetmKQbp5KganwaH'@'%' (using password: YES)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[HikariCP-3.4.5.jar!/:?]
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:?]
    at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:59)
```

**Comment by rdehuyss** [comment]
As too much personal time goes to supporting the OSS version, I'm afraid I do not give support on older JobRunr version if you're not a paying customer. Please upgrade to the latest version or contact me for a Pro subscription.
