### ISSUE TITLE
[BUG] instruction 0 not found

### ISSUE THREAD

**Issue by niallrox** [jobrunr/jobrunr#772]
### JobRunr Version

6.2.0

### JDK Version

17

### Kotlin version

1.7.22

### Your SQL / NoSQL database

MongoDB

### Bug description

Spring Boot application with background scheduled job with LocalDateTime#minusHours

### How to reproduce?

```kt
      private fun scheduleInterviewerNotification(
        time: LocalDateTime,
        interviewer: UserDto,
        stageDto: StageDto
    ) {
        jobScheduler.schedule(time.minusHours(1)) {
            telegramNotificationProducer.push(
                TelegramNotification(
                    username = interviewer.tg!!,
                    text = "${stageDto.name}.",
                )
            )
        }
    }
```

### Relevant log output

```shell
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:86) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.AbstractJobDetailsFinder$1.visitInsn(AbstractJobDetailsFinder.java:44) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2214) ~[asm-9.5.jar!/:9.5]
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[asm-9.5.jar!/:9.5]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[asm-9.5.jar!/:9.5]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[asm-9.5.jar!/:9.5]
        at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:87) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:27) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:77) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:39) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.scheduling.JobScheduler.schedule(JobScheduler.java:420) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.scheduling.JobScheduler.schedule(JobScheduler.java:402) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at org.jobrunr.scheduling.JobScheduler.schedule(JobScheduler.java:336) ~[jobrunr-6.2.0.jar!/:6.2.0]
        at com.djidjya.team.messaging.InterviewKafkaListener.scheduleCandidateAcceptNotification(InterviewKafkaListener.kt:132) ~[classes!/:na]
        at com.djidjya.team.messaging.InterviewKafkaListener.interviewScheduleResponse(InterviewKafkaListener.kt:48) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.27.jar!/:5.3.27]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.27.jar!/:5.3.27]
        at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56) ~[spring-kafka-2.8.11.jar!/:2.8.11]
        at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:347) ~[spring-kafka-2.8.11.jar!/:2.8.11]
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92) ~[spring-kafka-2.8.11.jar!/:2.8.11]
        at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53) ~[spring-kafka-2.8.11.jar!/:2.8.11]
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2670) ~[spring-kafka-2.8.11.jar!/:2.8.11]
        ... 11 common frames omitted
Caused by: java.lang.IllegalArgumentException: Instruction 0 not found
        ... 38 common frames omitted
```

**Comment by niallrox** [comment]
The time that comes to the method is parsed from the outer request
```kt
val time = LocalDateTime.parse(interviewResponse.text, DateTimeFormatter.ISO_DATE_TIME)
```

**Comment by niallrox** [comment]
Found the interesting line at stacktrace 
```shell
at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:27)
```
Source 
```java
    @Override
    public JobDetails toJobDetails(IocJobLambda lambda) {
        if (isKotlinLambda(lambda)) {
            return new KotlinJobDetailsFinder(lambda, new Object()).getJobDetails();
        } else {
            return new JavaJobDetailsFinder(lambda, toSerializedLambda(lambda)).getJobDetails();
        }
    }
```
I think jobrunr make wrong assumption about the code source ant think that is java lambda and can't resolve it. Correct me if I'm wrong.

**Comment by niallrox** [comment]
I resolved this problem by extracting function in lambda to another function, anyway I will wait for your answer!

**Comment by rdehuyss** [comment]
Can you setup a repo that reproduces this? I tried to reproduce it but I'm unable to do so. See the test below that is ✅.

```kotlin

    @Test
    fun testIssue772() {
        scheduleInterviewerNotification(LocalDateTime.now(), UserDto("id", "my name"))
        await().until {
            storageProvider.countJobs(SUCCEEDED) == 1L
        }
        val job = storageProvider.getJobs(SUCCEEDED, PageRequest.ascOnUpdatedAt(1000))[0]
        assertThat(job)
            .hasStates(SCHEDULED, ENQUEUED, PROCESSING, SUCCEEDED)
    }

    private fun scheduleInterviewerNotification(
        time: LocalDateTime,
        interviewer: UserDto
    ) {
        val testService = TestService()

        jobScheduler.schedule(time.minusHours(1)) {
            testService.doWorkWithObject(
                TestService.TestServiceNotification(
                    id = interviewer.id!!,
                    name = "${interviewer.name}."
                )
            )
        }
    }

```

And 
```kotlin
class TestService {

    fun doWork(s: String) {
        println(s)
    }

    @Job(name = "Some neat Job Display Name")
    fun doWorkWithJobName(s: String, jobName: String) {
        println("$s $jobName")
    }

    fun doWorkWithObject(notification: TestServiceNotification) {
        println("${notification.id} ${notification.name}")
    }

    data class TestServiceNotification(
        val id: String,
        val name: String?
    )
}
```

**Comment by niallrox** [comment]
https://gitlab.leha-vnuk.ru/djidjya-team/sovcombank/backend/sov-interview-service/-/blob/main/src/main/kotlin/com/djidjya/team/messaging/InterviewKafkaListener.kt

**Comment by rdehuyss** [comment]
I've reviewed it - performance wise is what you're currently doing **way better** as the amount of code that JobRunr needs parse inside the lambda is a lot less.

I think I can get it solved but prefer to wait until somebody else also has this issue. Apparently, Kotlin adds extra NOP statements so the debugger can easily attach to it.

I'll close this issue for now as you have a workaround but if I notice somebody else also having this problem, I'll see for a fix. Ideally, I can log/throw a decent message but I do not know yet how.
