### ISSUE TITLE
[BUG] Quarkus 3.0 compatibility

### ISSUE THREAD

**Issue by asputa** [jobrunr/jobrunr#777]
### JobRunr Version

6.2.0

### JDK Version

OpenJDK 17.0.7

### Your SQL / NoSQL database

Azure DB

### What happened?

When increasing the version of quarkus to 3.0.4, jobrunr does not start and there is a problem when starting the application.

Maven snippet
        <dependency>
            <groupId>org.jobrunr</groupId>
            <artifactId>quarkus-jobrunr</artifactId>
            <version>6.2.0</version>
        </dependency>

You could be proud of all the occurrences
javax.json.***
for
jakarta.json.***

Quarkus came to replace the java package.

### How to reproduce?

Start only quarkus 3.0 and newer with jobrunr 6.2.0.

Maven snippet
        <dependency>
            <groupId>org.jobrunr</groupId>
            <artifactId>quarkus-jobrunr</artifactId>
            <version>6.2.0</version>
        </dependency>

### Relevant log output

```shell
2023-05-30 08:45:22,088 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.ClassNotFoundException: javax.json.bind.JsonbException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        at org.jobrunr.quarkus.autoconfigure.JobRunrProducer$JobRunrJsonBJsonMapperProducer.jobRunrJsonMapper(JobRunrProducer.java:141)
        at org.jobrunr.quarkus.autoconfigure.JobRunrProducer_JobRunrJsonBJsonMapperProducer_ProducerMethod_jobRunrJsonMapper_407b0684a8630e2a9919953f1bc571a2125483ba_Bean.doCreate(Unknown Source)
        at org.jobrunr.quarkus.autoconfigure.JobRunrProducer_JobRunrJsonBJsonMapperProducer_ProducerMethod_jobRunrJsonMapper_407b0684a8630e2a9919953f1bc571a2125483ba_Bean.create(Unknown Source)
        at org.jobrunr.quarkus.autoconfigure.JobRunrProducer_JobRunrJsonBJsonMapperProducer_ProducerMethod_jobRunrJsonMapper_407b0684a8630e2a9919953f1bc571a2125483ba_Bean.create(Unknown Source)
```

**Comment by rdehuyss** [comment]
Please star the repo if you're happy with the support you've received! Or even better, ask your manager to get a Pro license...
