### ISSUE TITLE
[BUG] JobRunr stops working after a temporary outage of the database

### ISSUE THREAD

**Issue by FlorentBrunet** [jobrunr/jobrunr#784]
### JobRunr Version

6.2.1

### JDK Version

OpenJDK Temurin-11.0.18+10

### Your SQL / NoSQL database

Postgres 14

### What happened?

We have a backend written with Spring Boot 2.7.12. Our underlying database is Postgres 14 and it is hosted by Azure. A few days ago, we had a very short outage of the database on our production environment probably due to a maintenance operation on Azure side (from what we've seen in our logs, the database has been unreachable for around 40 seconds). As soon as the database was up and running again, all our services accessing the DB re-started to work properly. However, it appears that JobRunr completely stopped to work on the 1st failed attempt to connect to the database and that there was no supplementary attempts at re-connecting to the database to check it has been restablished.

At the precise moment that the database shutdown, we get this message in the logs:
```
JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
```

This error message comes just before the stack trace of the database which is no more reachable:
```

org.jobrunr.storage.StorageException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms
```

After the stack traces complaining that the database is unreachable, JobRunr emits those 2 final messages:
```
JobRunr BackgroundJobServer shutdown requested - waiting for jobs to finish (at most 10 seconds)
BackgroundJobServer and BackgroundJobPerformers stopped
```

After that, the only way to re-start JobRunr is by restarting the whole Spring Boot application. This is a deal-breaker for us given that our backend is intended to run for "long" periods of time (a few weeks) without any restart and given that even the best "database providers" cannot ensure a perfect 100% uptime (even with a top-tier offer from Azure, we still experience minor downtimes every now and then on Postgres).

On such a situation, we would have expected JobRunr to retry to connect to the database (at least a few times, maybe with a maximal duration after which it's "safe" to assume that the database is down for real and that there's no point in keeping trying to connect to the DB, maybe even with a few configuration properties to set those durations/number of attemps, if we want to disable/enable a "retry" mechanism, ...)

### How to reproduce?

Here is a minimal Spring Boot application that allows to reproduce the problem: https://github.com/FlorentBrunet/jobrunr-db-loss. This project contains a README.md that sums up the steps to systematically reproduce the problem, but here is the general principle:

- Launch a fully working instance of Postgres (to test locally on my computer, I've used the official Docker image of Postgres in version 14.2-alpine but the problem was initially detected on an Azure-managed Postgres).
- Launch the Spring Boot Server of the example project.
- The `JobService` defines a recurring job that should be executed every 10 seconds.
- Wait a little bit to check that the job is properly executed a few times (it emits a log with an incrementing counter).
- Shut down the database for a few seconds (to test locally, I just kill the Docker container) until JobRunr has a problem because of the temporary unavailability of the DB. I guess the time to wait is approximately the polling delay of JobRunr + the configured timeout of the connection to the DB.
    - => We get the error message "JobRunr encountered a problematic exception. Please create a bug report (if possible,
      provide the code to reproduce this and the stacktrace) - Processing will continue."
    - => We have a stack trace that looks like "org.jobrunr.storage.StorageException:
      java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after
      30003ms."
    - => And finally we have those 2 log messages from JobRunr: "JobRunr BackgroundJobServer shutdown requested -
      waiting for jobs to finish (at most 10 seconds)" and "BackgroundJobServer and BackgroundJobPerformers stopped"
- Re-launch the DB
- After that, `@Recurring` jobs are no more executed until the Spring Boot app is re-started.
- I've included another simple example in the project (see `DummyService.java`) that uses a basic access to the DB and which shows that when the database is repaired, all the data access stack (Spring Data/JPA/Hibernate/Hikari/...) is able to reconnect whithout much trouble to the DB.

### Relevant log output

```shell
2023-06-09 14:18:03.572  WARN 10604 --- [pool-1-thread-2] org.jobrunr.server.JobZooKeeper          : JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.

org.jobrunr.storage.StorageException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30005ms.
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.recurringJobsUpdated(DefaultSqlStorageProvider.java:327) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.storage.ThreadSafeStorageProvider.recurringJobsUpdated(ThreadSafeStorageProvider.java:184) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.getRecurringJobs(ProcessRecurringJobsTask.java:37) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.runTask(ProcessRecurringJobsTask.java:32) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80) ~[jobrunr-6.2.1.jar:6.2.1]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390) ~[na:na]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80) ~[jobrunr-6.2.1.jar:6.2.1]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56) ~[jobrunr-6.2.1.jar:6.2.1]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30005ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) ~[HikariCP-4.0.3.jar:na]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.recurringJobsUpdated(DefaultSqlStorageProvider.java:323) ~[jobrunr-6.2.1.jar:6.2.1]
	... 14 common frames omitted
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.8.jar:42.3.8]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712) ~[HikariCP-4.0.3.jar:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	... 3 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.8.jar:42.3.8]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.8.jar:42.3.8]
	... 15 common frames omitted

2023-06-09 14:18:30.967  INFO 10604 --- [   scheduling-1] c.a.jobrunrdbloss.service.OtherService   : dummy=7
2023-06-09 14:18:35.988  INFO 10604 --- [   scheduling-1] c.a.jobrunrdbloss.service.OtherService   : dummy=8
2023-06-09 14:18:40.971  INFO 10604 --- [       Thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer shutdown requested - waiting for jobs to finish (at most 10 seconds)
2023-06-09 14:18:40.972  INFO 10604 --- [       Thread-1] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer and BackgroundJobPerformers stopped
```

**Comment by rdehuyss** [comment]
Thanks for reporting this (and for the greatly written bug report - I wish they were all like this) but this is as expected in the OSS version, solved by JobRunr Pro and also stated clearly in the documentation. See https://www.jobrunr.io/en/documentation/pro/database-fault-tolerance/.

I think it is not JobRunr's OSS responsibility to cope with a volatile infrastructure.
