### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jhsenjaliya** [jobrunr/jobrunr#786]
### JobRunr Version

5.3.2

### JDK Version

11

### Your SQL / NoSQL database

mysql 8

### What happened?

data trunctaion issue, here is the stacktrace that asked to file the bug report.

```
2023-06-10 20:58:58,424 [WARN  ] [backgroundjob-zookeeper-pool-40-thread-2] org.jobrunr.server.JobZooKeeper - JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.storage.StorageException: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect CHAR(10) value: '65.000000000000000000000000000000'
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:366)
	at org.jobrunr.storage.ThreadSafeStorageProvider.publishTotalAmountOfSucceededJobs(ThreadSafeStorageProvider.java:199)
	at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:142)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:99)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Truncated incorrect CHAR(10) value: '65.000000000000000000000000000000'
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555)
	at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:149)
	at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:130)
	at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:66)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.publishTotalAmountOfSucceededJobs(DefaultSqlStorageProvider.java:363)
	... 10 more
```

### How to reproduce?

use MySqlStorageProvider for jobRunr

**Comment by rdehuyss** [comment]
Please upgrade to the latest version.
