### ISSUE TITLE
[BUG] Recurring job stuck in processing state

### ISSUE THREAD

**Issue by yuuzer** [jobrunr/jobrunr#794]
### JobRunr Version

6.2.2

### JDK Version

Temurin-17.0.5+8

### Your SQL / NoSQL database

MongoDB 5.0.10

### What happened?

Hello, we use JobRunr to send out approximately 600 emails on a daily basis. The first one or two executions are successful, but after that the job stuck in processing state and stay there forever. No exceptions in the log nor on the dashboard. Once we deleted the job we got the attached exception.

### How to reproduce?

```kotlin
    @Recurring(id = "send-follow-up-reminders-12utc", cron = "0 0 12 * * 1-5", zoneId = "UTC")
    @Job(name = "Send follow-up reminder emails at 12 noon UTC")
    fun sendFollowUpRemindersAt12utcJob(jobContext: JobContext) {
        sendFollowUpReminders(jobContext)
    }

    fun sendFollowUpReminders(jobContext: JobContext) {
        log.info("Loading followup reminders from QaB.")
        val reminders = quoteAndBookAirAndSeaClient.getFollowUpReminders()

        if (reminders.isEmpty()) {
            log.info("No follow-up reminders to send.")
        } else {
            log.info("Sending {} follow-up reminder(s)...", reminders.size)
            val progressBar = jobContext.progressBar(reminders.size)

            reminders.forEach { reminder ->
                val recipient = reminder.email
                val subject = "Follow-up calls for quotes in $environment are overdue"

                val content = StringBuilder("Dear ${reminder.fullName},")
                    .append(header)
                    .appendReminderLines(reminder.reminderLines)
                    .append(footer)
                    .append(envFooter)
                    .toString()

                try {
                    log.debug("Sending follow-up mail to {} with {} reminder(s)", recipient, reminder.reminderLines.size)
                    emailService.sendMessage(recipient, subject, content)
                } catch (e: Exception) {
                    log.error("Could not send reminder to $recipient: ${e.message} (${e.cause?.message ?: "-"})")
                }
                progressBar.increaseByOne()
            }
        }
    }
```

### Relevant log output

```shell
hits-document-service-6bcbdbbbcc-bfdkl 2023-06-23 06:47:08 [backgroundjob-zookeeper-pool-5-thread-2] WARN  org.jobrunr.server.JobZooKeeper - JobRunr encountered a problematic exception. Please create a bug  │
│ report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.                                                                                                        │
│ hits-document-service-6bcbdbbbcc-bfdkl java.lang.NullPointerException: Cannot invoke "org.jobrunr.jobs.Job.getUpdatedAt()" because the return value of "java.util.Map.get(Object)" is null                     │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.lambda$save$4(MongoDBStorageProvider.java:288)                                                            │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)                                                                              │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)                                                                         │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)                                                                                  │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)                                                                           │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)                                                                             │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                                  │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)                                                                                 │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:289)                                                                     │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)                                                                           │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:70)                                                                           │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)                                                            │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)                                                                                      │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)                                                                            │
│ hits-document-service-6bcbdbbbcc-bfdkl     at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)                                                                                                        │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)                                                                                │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)                                                                                       │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)                                         │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)                                                                        │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)                                                                        │
│ hits-document-service-6bcbdbbbcc-bfdkl     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rdehuyss** [comment]
I'm afraid you're not following the community guidelines that are shown to you when you create a bug.

Please do so, otherwise I can give you no support.

**Comment by yuuzer** [comment]
> I'm afraid you're not following the community guidelines that are shown to you when you create a bug.
> 
> Please do so, otherwise I can give you no support.

Hi, yes sorry. I was in a hurry, I didn't read the guide. I just updated my profile.

**Comment by rdehuyss** [comment]
Thanks. 

Does this happen each time or did this happen only one?

**Comment by yuuzer** [comment]
> Thanks.
> 
> ~Does this happen each time or did this happen only one?~
> 
> Can you setup a repo that reproduces this? Can this be related to the timeout setting of your emailService?
> 
> The exception is unrelated and is thrown because you deleted the job while your actual job is still running.

I've created a project which contains job creation and email sending (using mailhog instead of real email server), but there I was unable to reproduce the issue. I'll have a look on the email service to figure out if it's a timeout related issue.

**Comment by rdehuyss** [comment]
Hi @yuuzer - did you find what is going on? 

As I'm quite sure this is unrelated to JobRunr, I'm closing this issue. Feel free to reopen if you can show me a reproducible scenario.

**Comment by yuuzer** [comment]
> Hi @yuuzer - did you find what is going on?
> 
> As I'm quite sure this is unrelated to JobRunr, I'm closing this issue. Feel free to reopen if you can show me a reproducible scenario.

Hi, This week we will deploy a new version to production. It'll contain timeout configuration for the mail client. I'll give an update when we have the result. It's OK to keep the ticket closed.

**Comment by yuuzer** [comment]
The mail client caused the issue. The timeout was set to infinite. Thanks for your support!

**Comment by rdehuyss** [comment]
Thx! Feel free to star the repo then 😉 !
