### ISSUE TITLE
[BUG] ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0] on heavy load

### ISSUE THREAD

**Issue by mgeuer** [jobrunr/jobrunr#803]
We are facing the following exception in a test environment at our customer
**JobRunr Version:** 6.2.0
**JDK Version**: 17.0.2
**Database**: Oracle 19.16.0.0

The Stacktrace from the log:
```
org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException: Could not insert or update all objects - not all updates succeeded: [0]
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:22)
        at org.jobrunr.storage.sql.common.db.ConcurrentSqlModificationException.concurrentDatabaseModificationException(ConcurrentSqlModificationException.java:18)
        at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:154)
        at org.jobrunr.storage.sql.common.db.Sql.update(Sql.java:133)
        at org.jobrunr.storage.sql.common.MetadataTable.incrementCounter(MetadataTable.java:78)
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:276)
        at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:156)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
        at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:27)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
        at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:79)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
        at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:79)
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:59)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

It seems like this happens when the machine is under load. 
Information taken from the jobrunr_metadata:
```
  ID                                                                                                          NAME                                      OWNER                                                         VALUE                                    CREATEDAT                         UPDATEDAT
------------------------------------------------------------------------------------------------------------- ----------------------------------------- ------------------------------------------------------------- ---------------------------------------- --------------------------------- ------------------------------
id-cluster                                                                                                    id                                        cluster                                                       57c00b54-68fb-44a9-96b8-f1b5115e72ce     07-JUL-23 11.48.53.466797 AM      07-JUL-23 11.48.53.469290 AM
database_version-cluster                                                                                      database_version                          cluster                                                       6.0.0                                    07-JUL-23 11.48.53.618816 AM      07-JUL-23 11.48.53.620465 AM
CpuAllocationIrregularityNotification-BackgroundJobServer_3c4c8d36-0e45-4756-af18-28685b5a0e76                CpuAllocationIrregularityNotification     BackgroundJobServer 3c4c8d36-0e45-4756-af18-28685b5a0e76      14                                       12-JUL-23 07.48.44.382978 AM      12-JUL-23 07.48.49.410632 AM

```

**Comment by rdehuyss** [comment]
Hi @mgeuer ,

it appears that for some reason you're missing an entry in your metadata table. This is normally automatically inserted by the [JobRunr migrations](https://github.com/jobrunr/jobrunr-pro/blob/master/core/src/main/resources/org/jobrunr/storage/sql/oracle/migrations/v009__change_jobrunr_job_counters_to_jobrunr_metadata.sql#L12-L15). 

To fix this, please run the following statement:
```sql
INSERT INTO jobrunr_metadata (id, name, owner, value, createdAt, updatedAt)
VALUES ('succeeded-jobs-counter-cluster', 'succeeded-jobs-counter', 'cluster', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
```

This will fix the issue you're seeing.

**Comment by yop828** [comment]
Alas I confirm such insert statement does not appear in any of the 3 generated files 
* V000__jobrunr_v6_oracle_baseline
* V001__alter_job_table_add_dynamic_queue
* V002__create_dynamic_queue_stats_view

with the following java code 

```
import org.jobrunr.storage.sql.common.DatabaseSqlMigrationFileProvider;

class DatabaseMigration {
	public static void main(String[] args) {
		System.setProperty("databaseManager","flyway");
		System.setProperty("output","C:\\temp");
		DatabaseSqlMigrationFileProvider.main(new String[]{"oracle"});
	}
}
```

**Comment by rdehuyss** [comment]
Hi @yop828 , sorry for the late reply - I was a week off.

I'll look into this asap.

**Comment by rdehuyss** [comment]
Hi @yop828 ,

I just reread your comment and with you all is well - you have an entry in the table `JOBRUNR_METADATA` with name `succeeded-jobs-counter` so that is correct.

The Flyway integration is quite a recent feature and in that case the entry is indeed not there (explaining the bug).
