### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by rdoddi-pro** [jobrunr/jobrunr#811]
### Runtime information
- __Timestamp__: 2023-07-18T15:50:36.274141Z
- __Location__: BackgroundJobServer 938ba477-2e13-4fc7-89fe-04d235d583e3
- __JobRunr Version__: 6.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 938ba477-2e13-4fc7-89fe-04d235d583e3
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2023-07-18T15:36:10.738229Z, lastHeartbeat: 2023-07-18T15:50:28.055279Z)

#### Concurrent modified jobs:
Job id: 25bd5b22-f001-4b8d-8399-ef2f59d70d10
	Local version: 3; Storage version: 4
	Local state: SCHEDULED (at 2023-07-18T15:50:32.612881Z) ← FAILED (at 2023-07-18T15:50:32.611097Z) ← PROCESSING (updated at 2023-07-18T15:36:12.853953Z on BackgroundJobServer 938ba477-2e13-4fc7-89fe-04d235d583e3 and started at 2023-07-18T15:36:12.853953Z) ← ENQUEUED (at 2023-07-18T15:36:12.172416Z) ← SCHEDULED (at 2023-07-18T15:00:24.806339Z)
	Storage state: SUCCEEDED (at 2023-07-18T15:50:32.581106Z) ← PROCESSING (updated at 2023-07-18T15:36:12.853953Z on BackgroundJobServer 938ba477-2e13-4fc7-89fe-04d235d583e3 and started at 2023-07-18T15:36:12.853953Z) ← ENQUEUED (at 2023-07-18T15:36:12.172416Z) ← SCHEDULED (at 2023-07-18T15:00:24.806339Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:58)
	at org.jobrunr.server.zookeeper.tasks.ProcessOrphanedJobsTask.runTask(ProcessOrphanedJobsTask.java:29)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

### Runtime information
- __Timestamp__: 2023-07-24T19:17:09.464970Z
- __Location__: BackgroundJobServer 101ff83c-6c6f-4ab2-aa34-86c41b2a61fd
- __JobRunr Version__: 6.2.0
- __StorageProvider__: org.jobrunr.storage.sql.postgres.PostgresStorageProvider
- __Java Version__: 17.0.2
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 101ff83c-6c6f-4ab2-aa34-86c41b2a61fd
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2023-07-24T19:04:41.335834Z, lastHeartbeat: 2023-07-24T19:17:02.016991Z)

#### Concurrent modified jobs:
Job id: fa6bef2e-5d06-4e75-8f8b-fef2fec7f289
	Local version: 3; Storage version: 4
	Local state: PROCESSING (updated at 2023-07-24T19:17:09.125464Z on BackgroundJobServer 101ff83c-6c6f-4ab2-aa34-86c41b2a61fd and started at 2023-07-24T19:04:59.097656Z) ← ENQUEUED (at 2023-07-24T19:04:58.535332Z) ← SCHEDULED (at 2023-07-24T19:04:58.114599Z)
	Storage state: SCHEDULED (at 2023-07-24T19:16:44.826544Z) ← FAILED (at 2023-07-24T19:16:44.825529Z) ← PROCESSING (updated at 2023-07-24T19:04:59.097656Z on BackgroundJobServer 101ff83c-6c6f-4ab2-aa34-86c41b2a61fd and started at 2023-07-24T19:04:59.097656Z) ← ENQUEUED (at 2023-07-24T19:04:58.535332Z) ← SCHEDULED (at 2023-07-24T19:04:58.114599Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:76)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:46)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:75)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
Or was this perhaps on a laptop that you've put to sleep for a while?
