### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eduuts** [jobrunr/jobrunr#813]
### JobRunr Version

6.2.0

### JDK Version

JDK 1.8.0_341

### Your SQL / NoSQL database

Oracle

### What happened?

When setting up an SQL storage provider (eg. OracleStorageProvider), the url for the migrations does not support JobRunr inside a (non-exploded) WAR file, such as:
"zip:/u01/oracle/user_projects/domains/base_domain/servers/AdminServer/tmp/_WL_user/xxx-api_war/nn35lj/war/WEB-INF/lib/jobrunr-6.2.0.jar!/org/jobrunr/storage/sql/common/migrations/".

### How to reproduce?

Create a WAR file with JobRunr (as JAR) inside.
Deploy WAR file to a container, eg. Tomcat, WebLogic
[Add your code for starting JobRunr], the contents of the init() method

### Relevant log output

```shell
<Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID "3984196128410" for task "0" on [partition-name: DOMAIN]. Error is: "weblogic.application.ModuleException: java.lang.IllegalArgumentException: Unknown FileSystem required zip"
weblogic.application.ModuleException: java.lang.IllegalArgumentException: Unknown FileSystem required zip
at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
```

**Comment by rdehuyss** [comment]
Please also read the `community guidelines` for creating bugs. Your issue did not have a title.
