### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VithiyaB** [jobrunr/jobrunr#820]
### JobRunr Version

6.3.0

### JDK Version

JDK 17.0.2

### Your SQL / NoSQL database

DocumentDB

### What happened?

Jobrunr works fine with MongoDB while pointing to localhost , But while changing the DB to DocumentDB the script
 ( M007_UpdateJobsCollectionReplaceIndices.class) is not executed properly since it still refers to the Mongo scripts or not DocumentDB.
 All other 6 scripts are executed without any issues and could see tables are created in DocumentDB.
 This is happening only with 7th script.
 Please let us know if there are any additional configuration required by jobrunr to point to AWS documentdb .

### How to reproduce?

Use DocumentDB instead of MongoDB with JobRunr v6.

### Relevant log output

```shell
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.jobrunr.storage.StorageProvider]: Factory method 'mongoDBStorageProvider' threw exception with message: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.10.jar:6.0.10]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.10.jar:6.0.10]
	... 50 common frames omitted
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrationIfNecessary(NoSqlDatabaseCreator.java:70) ~[jobrunr-6.3.0.jar:6.3.0]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395) ~[na:na]
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[na:na]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:363) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrations(NoSqlDatabaseCreator.java:41) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.runMigrations(MongoDBStorageProvider.java:485) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.setUpStorageProvider(MongoDBStorageProvider.java:145) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:126) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.<init>(MongoDBStorageProvider.java:107) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.spring.autoconfigure.storage.JobRunrMongoDBStorageAutoConfiguration.mongoDBStorageProvider(JobRunrMongoDBStorageAutoConfiguration.java:27) ~[jobrunr-spring-boot-3-starter-6.3.0.jar:6.3.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.10.jar:6.0.10]
	... 51 common frames omitted
Caused by: java.lang.IllegalStateException: Error running database migration M007_UpdateJobsCollectionReplaceIndices.class
	... 74 common frames omitted
Caused by: com.mongodb.MongoCommandException: Command failed with error 303: 'Field 'partialFilterExpression' is currently not supported' on server finance-dev-documentdb-cluster.cluster-ct6rt3rypfpw.us-east-1.docdb.amazonaws.com:27017. The full response is {"ok": 0.0, "code": 303, "errmsg": "Field 'partialFilterExpression' is currently not supported", "operationTime": {"$timestamp": {"t": 1692386069, "i": 1}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:443) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:365) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:73) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:204) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:122) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:87) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:76) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:288) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:260) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.CreateIndexesOperation.lambda$execute$0(CreateIndexesOperation.java:131) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withConnectionSource(OperationHelper.java:339) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.OperationHelper.withConnection(OperationHelper.java:330) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:129) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:68) ~[mongodb-driver-core-4.9.1.jar:na]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:206) ~[mongodb-driver-sync-4.9.1.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:862) ~[mongodb-driver-sync-4.9.1.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:845) ~[mongodb-driver-sync-4.9.1.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:840) ~[mongodb-driver-sync-4.9.1.jar:na]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:825) ~[mongodb-driver-sync-4.9.1.jar:na]
	at org.jobrunr.storage.nosql.mongo.migrations.MongoMigration.lambda$createIndex$1(MongoMigration.java:39) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.utils.exceptions.Exceptions.retryOnException(Exceptions.java:67) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.migrations.MongoMigration.createIndex(MongoMigration.java:39) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.migrations.M007_UpdateJobsCollectionReplaceIndices.runMigration(M007_UpdateJobsCollectionReplaceIndices.java:27) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBCreator.runMigration(MongoDBCreator.java:70) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.mongo.MongoDBCreator.runMigration(MongoDBCreator.java:30) ~[jobrunr-6.3.0.jar:6.3.0]
	at org.jobrunr.storage.nosql.common.NoSqlDatabaseCreator.runMigrationIfNecessary(NoSqlDatabaseCreator.java:66) ~[jobrunr-6.3.0.jar:6.3.0]
	... 73 common frames omitted
```

**Comment by VithiyaB** [comment]
This is working as expected.Able to change the DB to DocumetDb
