### ISSUE TITLE
additional Spring AOT Hints for JobRunr 6.3.0 + Spring Boot 3.1.3

### ISSUE THREAD

**Issue by goafabric** [jobrunr/jobrunr#824]
### JobRunr Version

6.3.0

### JDK Version

Openjdk 17 / Graalvm 23

### Your SQL / NoSQL database

Postgres 15 / h2

### What happened?

While Spring AOT support mostly works with JobRequests, there are 2 minor problems.

1)
One is a missing ReflectionHint that could be added (example is for spring)

hints.reflection().registerType(java.util.concurrent.CopyOnWriteArrayList.class, MemberCategory.INVOKE_DECLARED_CONSTRUCTORS);

2)
The other occurs when the Storage Provider is not in Memory.
Log file attached, and i wasnt able to figure out whats going wrong here.

It may be possible to work around it, by org.jobrunr.database.skip-create=false,
and having the sqls executed via flyway on your own, though i havent tested it

An example can be found here, with a native-compile command

[(https://github.com/goafabric/jobrunr-example)](https://github.com/goafabric/jobrunr-example/tree/broken)

### How to reproduce?

execute the native-compile command

### Relevant log output

```shell
Caused by: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.getStorageProvider(SqlStorageProviderFactory.java:73) ~[na:na]
        at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.getStorageProviderByJdbcUrl(SqlStorageProviderFactory.java:44) ~[na:na]
        at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.getStorageProviderUsingDataSource(SqlStorageProviderFactory.java:36) ~[na:na]
        at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.using(SqlStorageProviderFactory.java:30) ~[na:na]
        at org.jobrunr.spring.autoconfigure.storage.JobRunrSqlStorageAutoConfiguration.sqlStorageProvider(JobRunrSqlStorageAutoConfiguration.java:32) ~[jobrunr-example:6.3.0]
        at org.jobrunr.spring.autoconfigure.storage.JobRunrSqlStorageAutoConfiguration__BeanDefinitions.lambda$getStorageProviderInstanceSupplier$0(JobRunrSqlStorageAutoConfiguration__BeanDefinitions.java:29) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[jobrunr-example:6.0.11]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[jobrunr-example:6.0.11]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[jobrunr-example:6.0.11]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[jobrunr-example:6.0.11]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:214) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202) ~[na:na]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[jobrunr-example:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[jobrunr-example:6.0.11]
        ... 33 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[jobrunr-example:na]
        at java.base@17.0.7/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[jobrunr-example:na]
        at org.jobrunr.storage.sql.common.SqlStorageProviderFactory.getStorageProvider(SqlStorageProviderFactory.java:71) ~[na:na]
        ... 47 common frames omitted
Caused by: java.nio.file.FileSystemAlreadyExistsException: null
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.resources.NativeImageResourceFileSystemProvider.newFileSystem(NativeImageResourceFileSystemProvider.java:115) ~[jobrunr-example:na]
        at java.base@17.0.7/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339) ~[na:na]
        at org.jobrunr.utils.resources.ResourcesFileSystemProvider.getFileSystem(ResourcesFileSystemProvider.java:35) ~[na:na]
        at org.jobrunr.utils.resources.ResourcesFileSystemProvider.toPath(ResourcesFileSystemProvider.java:24) ~[na:na]
        at org.jobrunr.utils.resources.ClassPathResourceProvider.toPath(ClassPathResourceProvider.java:82) ~[na:na]
        at java.base@17.0.7/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
        at java.base@17.0.7/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[jobrunr-example:na]
        at java.base@17.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[jobrunr-example:na]
        at java.base@17.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[jobrunr-example:na]
        at java.base@17.0.7/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[jobrunr-example:na]
        at java.base@17.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[jobrunr-example:na]
        at java.base@17.0.7/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[jobrunr-example:na]
        at org.jobrunr.storage.sql.common.migrations.DefaultSqlMigrationProvider.getMigrations(DefaultSqlMigrationProvider.java:17) ~[na:na]
        at org.jobrunr.storage.sql.common.DatabaseMigrationsProvider.getCommonMigrations(DatabaseMigrationsProvider.java:56) ~[na:na]
        at org.jobrunr.storage.sql.common.DatabaseMigrationsProvider.getMigrations(DatabaseMigrationsProvider.java:32) ~[na:na]
        at org.jobrunr.storage.sql.common.DatabaseCreator.getMigrations(DatabaseCreator.java:107) ~[jobrunr-example:6.3.0]
        at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrations(DatabaseCreator.java:82) ~[jobrunr-example:6.3.0]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.setUpStorageProvider(DefaultSqlStorageProvider.java:65) ~[jobrunr-example:6.3.0]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.<init>(DefaultSqlStorageProvider.java:53) ~[jobrunr-example:6.3.0]
        at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.<init>(DefaultSqlStorageProvider.java:41) ~[jobrunr-example:6.3.0]
        at org.jobrunr.storage.sql.h2.H2StorageProvider.<init>(H2StorageProvider.java:24) ~[jobrunr-example:6.3.0]
        ... 50 common frames omitted
        Suppressed: java.lang.IllegalStateException: Could not close FileSystemProvider
                at org.jobrunr.utils.resources.ClassPathResourceProvider.close(ClassPathResourceProvider.java:111) ~[na:na]
                at org.jobrunr.storage.sql.common.migrations.DefaultSqlMigrationProvider.getMigrations(DefaultSqlMigrationProvider.java:13) ~[na:na]
                ... 58 common frames omitted
        Caused by: java.lang.NullPointerException: null
                at org.jobrunr.utils.resources.ResourcesFileSystemProvider.close(ResourcesFileSystemProvider.java:42)
                at org.jobrunr.utils.resources.ClassPathResourceProvider.closeFileSystemProvider(ClassPathResourceProvider.java:129)
                at org.jobrunr.utils.resources.ClassPathResourceProvider.close(ClassPathResourceProvider.java:107)
                ... 59 common frames omitted
```

**Comment by goafabric** [comment]
yup .. having the metadata sqls migrated by flyway itself workz ... unfortunately it then needs a switching between h2 and postgreqs,
which is not easily done with native images .. up to you to decided if the migration problem can be fixed

THe native hint for CopyOnWriteArrayList.class should be added anyways, imho

Thx 4 this great product

**Comment by rdehuyss** [comment]
Hi @goafabric - thanks for the repo reproducing the issue, nice work! It's the first time this was so easy to get things up & running.

And, you're right:
- the native hint for `CopyOnWriteArrayList.class` was missing. Currently as GraalVM usage is still low, I did not yet create automated tests for JobRunr and GraalVM
- the second issue was because of Flyway. I tested it without Flyway hence I did not bump into this. Flyway opens the GraalVm `resource:\` `FileSystem` before JobRunr and apparently does not close it afterwards. JobRunr now checks whether it is already open and if so, reuses it.

**Comment by goafabric** [comment]
@rdehuyss 

Thanks to you to and for the detailed information.

For me this was the first time for such a positive reaction when opening a spring native issue somewhere.

Thx a lot and keep up the good work with jobrunr

**Comment by rdehuyss** [comment]
You're welcome!

Feel free to start the repo if you're enjoying JobRunr.

Thanks!

**Comment by goafabric** [comment]
@rdehuyss 
thx again too
i have one question, i would not want to open an extra issue, maybe you can give me a hint ?

i would like to start jobrunr, execute all the (import) tasks and then terminate ..
with spring batch thats pretty easy, with jobrunr i could not find a way, 
also tried the additional listener documentation from the pro version

**Comment by rdehuyss** [comment]
I'm not completely following tbh. What do you mean with 
> execute all the (import) tasks?

Since it's a question, can you please open this as a discussion with the extra info?
