### ISSUE TITLE
[BUG] Oracle 11g not supported - 'Offset' and 'Limit' in query

### ISSUE THREAD

**Issue by 7sepy7** [jobrunr/jobrunr#830]
### JobRunr Version

6.3.0

### JDK Version

JDK 17.0.6

### Your SQL / NoSQL database

Oracle Database 11g 11.2.0.1.0 - 64bit Production

### What happened?

After I have run my app I am getting error for query because JobRunr is using "Limit" and "Offset" for OracleDialect.
Limit and Offset are supported only after Oracle12c, and not for Oracle 11g. 
I have fixed error after commenting OracleDialect.java method 

@Override
    public String limitAndOffset(String order) {
        return " ORDER BY " + order /*+ " OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY"*/;
    }

### How to reproduce?

  
  Just simply use oracle 11g version and a JobRunr methods.
`jobScheduler.scheduleRecurrently(someCroneSchedule, () -> someService.someMethod());`

### Relevant log output

```shell
2023-09-08T07:29:07.857+02:00 ERROR 4076 --- [pool-1-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr BackgroundJobServer failed to start
2023-09-08T07:29:07.859+02:00  INFO 4076 --- [       Thread-9] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer and BackgroundJobPerformers - stopping (waiting for all jobs to complete - max 10 seconds)
2023-09-08T07:29:07.937+02:00  INFO 4076 --- [       Thread-9] org.jobrunr.server.BackgroundJobServer   : BackgroundJobServer and BackgroundJobPerformers stopped
2023-09-08T07:29:09.287+02:00  INFO 4076 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2023-09-08T07:29:09.425+02:00  WARN 4076 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2023-09-08T07:29:10.984+02:00  WARN 4076 --- [onPool-worker-1] o.j.storage.AbstractStorageProvider      : Error notifying JobStorageChangeListeners

org.jobrunr.storage.StorageException: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended

	at org.jobrunr.storage.sql.common.db.SqlSpliterator.init(SqlSpliterator.java:64) ~[jobrunr-6.0.0.jar:6.0.0]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:35) ~[jobrunr-6.0.0.jar:6.0.0]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at org.jobrunr.storage.sql.common.JobStatsView.getJobStats(JobStatsView.java:24) ~[jobrunr-6.0.0.jar:6.0.0]
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobStats(DefaultSqlStorageProvider.java:354) ~[jobrunr-6.0.0.jar:6.0.0]
	at org.jobrunr.storage.AbstractStorageProvider.lambda$notifyJobStatsOnChangeListeners$1(AbstractStorageProvider.java:77) ~[jobrunr-6.0.0.jar:6.0.0]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Caused by: java.sql.SQLSyntaxErrorException: ORA-00933: SQL command not properly ended
```

**Comment by rdehuyss** [comment]
Not following community guidelines (missing GitHub profile).

**Comment by reflyhight** [comment]
I do not clear
