### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by Abi667** [jobrunr/jobrunr#832]
### Runtime information
- __Timestamp__: 2023-08-21T19:00:28.453339500Z
- __Location__: BackgroundJobServer 233625ab-25b7-4c20-a61c-939ae58ba9ce
- __JobRunr Version__: 6.1.1
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 19.0.1
- __Is running from nested jar__: false
- __Is showing CpuAllocationNotification__: true

### Background Job Servers
- BackgroundJobServer id: 233625ab-25b7-4c20-a61c-939ae58ba9ce
(workerPoolSize: 30, pollIntervalInSeconds: 15, firstHeartbeat: 2023-08-21T18:22:44.346Z, lastHeartbeat: 2023-08-21T19:00:14.334Z)
- BackgroundJobServer id: d2464784-f4eb-4dcf-ac64-6620b86f5e03
(workerPoolSize: 30, pollIntervalInSeconds: 15, firstHeartbeat: 2023-08-21T18:39:46.658Z, lastHeartbeat: 2023-08-21T19:00:19.261Z)

#### Concurrent modified jobs:
Job id: 3e31b6d6-da02-4001-9f59-68e5eceacb43
	Local version: 3; Storage version: 4
	Local state: SUCCEEDED (at 2023-08-21T19:00:27.806951800Z) ← PROCESSING (updated at 2023-08-21T19:00:25.536614900Z on BackgroundJobServer 233625ab-25b7-4c20-a61c-939ae58ba9ce and started at 2023-08-21T19:00:12.356780500Z) ← ENQUEUED (at 2023-08-21T19:00:08.676691600Z) ← SCHEDULED (at 2023-08-21T19:00:07.357200800Z)
	Storage state: PROCESSING (updated at 2023-08-21T19:00:25.536614900Z on BackgroundJobServer 233625ab-25b7-4c20-a61c-939ae58ba9ce and started at 2023-08-21T19:00:12.356780500Z) ← ENQUEUED (at 2023-08-21T19:00:08.676691600Z) ← SCHEDULED (at 2023-08-21T19:00:07.357200800Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```

### Runtime information
- __Timestamp__: 2023-08-17T14:52:31.628745095Z
- __Location__: BackgroundJobServer 38f75bb1-67f0-46df-8e63-5b1b6819f2a3
- __JobRunr Version__: 6.1.1
- __StorageProvider__: org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider
- __Java Version__: 19
- __Is running from nested jar__: true
- __Is showing CpuAllocationNotification__: false

### Background Job Servers
- BackgroundJobServer id: 38f75bb1-67f0-46df-8e63-5b1b6819f2a3
(workerPoolSize: 30, pollIntervalInSeconds: 15, firstHeartbeat: 2023-08-16T05:39:03.737Z, lastHeartbeat: 2023-08-17T14:52:30.397Z)

#### Concurrent modified jobs:
Job id: a5a71ccd-078c-46d0-a9a4-f302982f6aea
	Local version: 26; Storage version: 30
	Local state: DELETED (at 2023-08-17T14:51:16.551914813Z) ← PROCESSING (updated at 2023-08-17T14:51:16.545825461Z on BackgroundJobServer 38f75bb1-67f0-46df-8e63-5b1b6819f2a3 and started at 2023-08-17T14:44:46.090127318Z) ← ENQUEUED (at 2023-08-17T14:44:46.080242121Z) ← SCHEDULED (at 2023-08-17T14:44:46.074284632Z)
	Storage state: ENQUEUED (at 2023-08-17T14:51:29.239226217Z) ← DELETED (at 2023-08-17T14:51:01.880177214Z) ← ENQUEUED (at 2023-08-17T14:50:39.313043484Z) ← DELETED (at 2023-08-17T14:50:36.816578646Z) ← PROCESSING (updated at 2023-08-17T14:50:31.485142214Z on BackgroundJobServer 38f75bb1-67f0-46df-8e63-5b1b6819f2a3 and started at 2023-08-17T14:44:46.090127318Z) ← ENQUEUED (at 2023-08-17T14:44:46.080242121Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:77)
	at org.jobrunr.server.zookeeper.tasks.UpdateJobsInProgressTask.runTask(UpdateJobsInProgressTask.java:18)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:71)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by rdehuyss** [comment]
Not on the latest version of JobRunr. I don't understand what I can do more (see image below) 😅.

And do not use JobRunr 6.2 but the latest version.

<img width="1296" alt="image" src="https://github.com/jobrunr/jobrunr/assets/567842/ebf99524-aafc-4e07-bc99-3ff0f855129e">


And commercial support is available with a Pro version...
