### ISSUE TITLE
[BUG] NPE during fetching of JobStats 

### ISSUE THREAD

**Issue by bangert** [jobrunr/jobrunr#840]
### JobRunr Version

6.3.1

### JDK Version

jdk-17.0.8.1+1

### Your SQL / NoSQL database

mssql

### What happened?

Hi Ronald,

my name is Thilo, i am an external consultant that has introduced jobrunr at Topdanmark - a danish insurance company.
Thanks for it!

we have the following in the log - and i dont know how to reproduce it.

### How to reproduce?

cant reproduce

### Relevant log output

```shell
Error notifying JobStorageChangeListeners java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.jobrunr.utils.reflection.ReflectionUtils.autobox(Object, java.lang.Class)" is null
	at org.jobrunr.storage.sql.common.db.SqlResultSet.asLong(SqlResultSet.java:45)
	at org.jobrunr.storage.sql.common.JobStatsView.toJobStats(JobStatsView.java:34)
	at org.jobrunr.storage.sql.common.JobStatsView.lambda$getJobStats$0(JobStatsView.java:23)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:44)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.jobrunr.storage.sql.common.JobStatsView.getJobStats(JobStatsView.java:24)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getJobStats(DefaultSqlStorageProvider.java:354)
	at org.jobrunr.storage.AbstractStorageProvider.lambda$notifyJobStatsOnChangeListeners$1(AbstractStorageProvider.java:77)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by rdehuyss** [comment]
Hi Thilio, nice to meet you! 

Does this exception happen a lot or do you only see it once in the logs?

**Comment by bangert** [comment]
@rdehuyss this does not happen a lot - but i have seen it a couple of times already

**Comment by rdehuyss** [comment]
I hope you understand that without a reproducible scenario and a JobRunr Pro license I cannot really give support (I also only have 24h / day). I've also not seen this error before.

Feel free to have a reproducible scenario or take a Pro license (and support opensource) and I'm happy to spend more time in it.
