### ISSUE TITLE
[BUG] Database migration issue with MySQL 5.7.35 on JobRunr 6.3.2

### ISSUE THREAD

**Issue by daghendrik** [jobrunr/jobrunr#844]
### JobRunr Version

6.3.2

### JDK Version

amazon corretto 11 jdk

### Your SQL / NoSQL database

MySQL 5.7.35

### What happened?

- My datasource is deliberately not configured to a schema (the connection doesn't specify the database/schema)
- I provide the JobRunr database via the [TablePrefix](https://www.jobrunr.io/en/documentation/installation/storage/)
- Migration works until [Step 14](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/resources/org/jobrunr/storage/sql/mysql/migrations/v014__improve_job_stats.sql) (Caused by: java.lang.IllegalStateException: Error running database migration v014__improve_job_stats.sql)
- Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: ANY command denied to user 'devuser'@'%' for table ''

I believe it might be related to the script not issuing a "USE db name", where "db name" is my schema/db for the JobRunr tables that I define in the Fluent API initialization (see code below). 

Because If I manually apply all the migrations steps with the same user ("devuser"), and make sure I'm using the correct schema/db there's no problem with the migration steps.

PS: I also noticed there was a missing semicolon in [MySQL Step 8](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/resources/org/jobrunr/storage/sql/mysql/migrations/v008__alter_table_jobs_increase_jobAsJson_size.sql)

### How to reproduce?

```java
        final JobScheduler jobScheduler = JobRunr.configure()
                .useStorageProvider(SqlStorageProviderFactory
                        .using(dataSource, "_runner."))
                .useDashboard()
                .initialize()
                .getJobScheduler();
```

### Relevant log output

```shell
Caused by: java.lang.IllegalStateException: Error running database migration v014__improve_job_stats.sql
	... 33 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: ANY command denied to user 'devuser'@'%' for table ''
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729)
	at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy41.execute(Unknown Source)
	at org.jobrunr.storage.sql.common.DatabaseCreator.runMigrationStatement(DatabaseCreator.java:132)
	at org.jobrunr.storage.sql.common.DatabaseCreator.runMigration(DatabaseCreator.java:114)
	... 32 more
```

**Comment by rdehuyss** [comment]
Can you please update your profile as requested in the community guidelines?

**Comment by daghendrik** [comment]
Sure, done.

**Comment by rdehuyss** [comment]
Why are you not providing a database with your DataSource? I didn't know this was even possible tbh.

**Comment by rdehuyss** [comment]
Pinging @daghendrik  - any reason you are not providing a database with your DataSource? I didn't know this was even possible tbh.

**Comment by rdehuyss** [comment]
Closing due to no response.... Also, I don't think this is a bug as most of the `Datasource`s I've seen are always with table etc.

Feel free to open a PR to solve this if you need it.
