### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tharangakothalawala** [jobrunr/jobrunr#848]
### JobRunr Version

6.0.0

### JDK Version

openjdk version "21" 2023-09-19 LTS

### Your SQL / NoSQL database

Redis

### What happened?

Integrated the JobRunr version `6.0.0` with Redis storage provider (using `lettuce` driver) with SpringBoot `2.7.14`

**Using the following JobRunr settings:**

```
org:
  jobrunr:
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
      worker-count: 20
      poll-interval-in-seconds: 15
      delete-succeeded-jobs-after: 0
      permanently-delete-deleted-jobs-after: 0
    database:
      type: 'redis-lettuce'
    dashboard:
      enabled: true
      port: 1082
      context-path: /job-runnr-demo-app
    jobs:
      default-number-of-retries: 0
```

POM:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.14</version>
        <relativePath/>
    </parent>
    <groupId>com._8x8.jobrunr-upgrade-with-redis</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>21</java.version>
        <org.jobrunr.version>6.0.0</org.jobrunr.version>
        <lettuce.version>6.1.10.RELEASE</lettuce.version>
        <commons-dbcp2.version>2.10.0</commons-dbcp2.version>

        <!-- Issue #2: usage of JedisException on a lettuce impl of 'LettuceRedisStorageProvider' when 'redis-lettuce' type is used -->
        <jedis.version>2.10.2</jedis.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jobrunr</groupId>
            <artifactId>jobrunr-pro-spring-boot-2-starter</artifactId>
            <version>${org.jobrunr.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-dbcp2</artifactId>
            <version>${commons-dbcp2.version}</version>
        </dependency>
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>${lettuce.version}</version>
        </dependency>

        <!-- Issue #2: usage of JedisException on a lettuce impl of 'LettuceRedisStorageProvider' when 'redis-lettuce' type is used -->
        <!-- Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.exceptions.JedisException -->
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>${jedis.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

## Issue 1
JonRunr fails to initialise upon SprintBoot bootup with an empty Redis store. The following exeception occured:

```
2023-10-09 11:36:53.334  INFO 86057 --- [pool-3-thread-1] org.jobrunr.server.BackgroundJobServer   : JobRunr Pro BackgroundJobServer (573ee2d4-5311-4fcd-aa3d-f9e5aa0a4402) using LettuceRedisStorageProvider and 20 BackgroundJobPerformers started successfully
2023-10-09 11:36:53.335  INFO 86057 --- [pool-3-thread-1] org.jobrunr.server.ServerZooKeeper       : Server 573ee2d4-5311-4fcd-aa3d-f9e5aa0a4402 is master (this BackgroundJobServer)
2023-10-09 11:36:53.339 ERROR 86057 --- [pool-4-thread-3] org.jobrunr.server.BackgroundJobServer   : Unexpected exception running `CheckIfAllJobsExistTask`

org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.tasks.CheckIfAllJobsExistTask.run(CheckIfAllJobsExistTask.java:67) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.stream()" because the return value of "org.jobrunr.storage.StorageProvider.getDistinctRecurringJobSignatures()" is null
	at org.jobrunr.server.tasks.CheckIfAllJobsExistTask.getDistinctRecurringJobSignaturesThatDoNotExistAnymore(CheckIfAllJobsExistTask.java:132) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.tasks.CheckIfAllJobsExistTask.run(CheckIfAllJobsExistTask.java:48) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	... 6 common frames omitted

2023-10-09 11:36:53.341  INFO 86057 --- [           main] o.j.dashboard.JobRunrDashboardWebServer  : JobRunr Pro Dashboard using LettuceRedisStorageProvider started at http://localhost:1082/job-runnr-demo-app/dashboard
2023-10-09 11:36:53.356  INFO 86057 --- [pool-4-thread-2] o.j.server.tasks.MigrateFromV5toV6Task   : Start migration of recurring jobs from v5 to v6
2023-10-09 11:36:53.361 ERROR 86057 --- [pool-4-thread-2] o.j.server.tasks.MigrateFromV5toV6Task   : Error migrating recurring jobs from v5 to v6

java.lang.NullPointerException: Cannot invoke "org.jobrunr.storage.Page.getItems()" because "recurringJobs" is null
	at org.jobrunr.server.tasks.MigrateFromV5toV6Task.getRecurringJobs(MigrateFromV5toV6Task.java:80) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.tasks.MigrateFromV5toV6Task.migrateRecurringJobs(MigrateFromV5toV6Task.java:44) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.tasks.MigrateFromV5toV6Task.run(MigrateFromV5toV6Task.java:35) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2023-10-09 11:36:53.620  INFO 86057 --- [           main] c._.j.demo.DemoApplication               : Started DemoApplication in 1.902 seconds (JVM running for 2.392)
```

**Observations:**

The following keys were created part of the bootup:

```
127.0.0.1:6379> KEYS *
1) "metadata:succeeded-jobs-counter-cluster"
2) "set:metadata"
3) "metadata:id-cluster"
```

## Issue 2

I had to include the Jedis driver library due to the following class not found error. An exception from the jedis library was used in the lettuce implementation on class, `LettuceRedisStorageProvider`

```
Caused by: java.lang.NoClassDefFoundError: redis/clients/jedis/exceptions/JedisException
	at org.jobrunr.spring.autoconfigure.storage.JobRunrLettuceStorageAutoConfiguration.jedisStorageProvider(JobRunrLettuceStorageAutoConfiguration.java:22) ~[jobrunr-pro-spring-boot-2-starter-6.0.0.jar:6.0.0]
	at org.jobrunr.spring.autoconfigure.storage.JobRunrLettuceStorageAutoConfiguration$$EnhancerBySpringCGLIB$$6685c048.CGLIB$jedisStorageProvider$0(<generated>) ~[jobrunr-pro-spring-boot-2-starter-6.0.0.jar:6.0.0]
	at org.jobrunr.spring.autoconfigure.storage.JobRunrLettuceStorageAutoConfiguration$$EnhancerBySpringCGLIB$$6685c048$$FastClassBySpringCGLIB$$ceeda4aa.invoke(<generated>) ~[jobrunr-pro-spring-boot-2-starter-6.0.0.jar:6.0.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.29.jar:5.3.29]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.29.jar:5.3.29]
	at org.jobrunr.spring.autoconfigure.storage.JobRunrLettuceStorageAutoConfiguration$$EnhancerBySpringCGLIB$$6685c048.jedisStorageProvider(<generated>) ~[jobrunr-pro-spring-boot-2-starter-6.0.0.jar:6.0.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.29.jar:5.3.29]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.exceptions.JedisException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	... 42 common frames omitted
```

### How to reproduce?

compile and build the attached repo.
[demo.zip](https://github.com/jobrunr/jobrunr/files/12845912/demo.zip)

### Relevant log output

```shell
java.lang.NullPointerException: Cannot invoke "org.jobrunr.storage.Page.getItems()" because "recurringJobs" is null
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.getRecurringJobs(ProcessRecurringJobsTask.java:155) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.getRecurringJobsToRunThatRunMoreThanOncePerMinute(ProcessRecurringJobsTask.java:105) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.getRecurringJobsToRun(ProcessRecurringJobsTask.java:49) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.zookeeper.tasks.ProcessRecurringJobsTask.runTask(ProcessRecurringJobsTask.java:42) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:48) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4305) ~[na:na]
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:60) ~[jobrunr-pro-6.0.0.jar:6.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

**Comment by rdehuyss** [comment]
Hi @tharangakothalawala ,

I notice you use JobRunr Pro but to be honest, I do not know you. Also, JobRunr Pro issues should go in the JobRunr Pro repo where customers have access.

Can you please explain me how you got access to JobRunr Pro?

**Comment by tharangakothalawala** [comment]
I am working for @8x8 who is a paid customer of JobRunr. (@biggms8x8 fyi)

**Comment by rdehuyss** [comment]
Hi @biggms8x8 , @tharangakothalawala - let's move this to JobRunr Pro. I'll also invite @tharangakothalawala to the Pro repo.
