### ISSUE TITLE
[BUG] JobRunr encountered a problematic exception

### ISSUE THREAD

**Issue by felixng313** [jobrunr/jobrunr#849]
### JobRunr Version

6.3.2

### JDK Version

OpenJDK 18

### Kotlin Version

1.9.0

### Quarkus Version

3.4.2

### Your SQL / NoSQL database

Posgresql 14

### What happened?

A bug happened!

### How to reproduce?

```kotlin
     jobScheduler.enqueue { myService.doSimpleJob("test") }
```

### Relevant log output

```shell
2023-10-15 14:31:40,080 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /fruits failed, error id: 4a16c2cc-4bc9-49f0-be0d-35d71d338a31-1: org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43)
	at org.jobrunr.jobs.details.instructions.AllJVMInstructions.get(AllJVMInstructions.java:86)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder$1.visitInsn(AbstractJobDetailsFinder.java:44)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2214)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:87)
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:27)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:77)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:39)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:118)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:100)
	at com.nextgen.adminapi.controller.TestController.getDefault(TestController.kt:29)
	at com.nextgen.adminapi.controller.TestController$quarkusrestinvoker$getDefault_375ed2a9bffef31c12401c8abc8245dd1adaf11e.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Instruction 1 not found
	... 25 more
```

**Comment by rdehuyss** [comment]
Not following community guidelines.

**Comment by rdehuyss** [comment]
There is a special bug template that asks you to update your Github profile. As an open-source developer, I would like to know whom we're helping for free.
