### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by arkusiarun** [jobrunr/jobrunr#854]
### Runtime information
- __Timestamp__: 2023-10-23T09:09:52.885Z
- __Location__: BackgroundJobServer 6b3eaaeb-249b-47c1-84c8-143f04e8b6c9
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 1.8.0_202
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: e16215ee-50b1-4efc-9720-a5209e7b3566
(workerPoolSize: 64, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:09:51.881Z, lastHeartbeat: 2023-10-23T09:09:51.889Z)

#### Concurrent modified jobs:
Job id: 1d161a2e-9e6d-454e-8574-3b48112290bf
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:09:52.823Z) ← SCHEDULED (at 2023-10-23T09:09:52.776Z)
	Storage state: ENQUEUED (at 2023-10-23T09:09:52.813Z) ← SCHEDULED (at 2023-10-23T09:09:52.776Z)
Job id: c922940d-b0df-4981-9795-4166cc331de4
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:09:52.823Z) ← SCHEDULED (at 2023-10-23T09:09:52.776Z)
	Storage state: ENQUEUED (at 2023-10-23T09:09:52.813Z) ← SCHEDULED (at 2023-10-23T09:09:52.776Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Runtime information
- __Timestamp__: 2023-10-23T09:10:54.837Z
- __Location__: BackgroundJobServer 0d0e4849-eb6f-4da3-b222-d8c0a51574a4
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 1.8.0_372
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: c3839665-8d97-4ff8-9ece-66aad3658686
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:10:53.919Z, lastHeartbeat: 2023-10-23T09:10:53.983Z)
- BackgroundJobServer id: 9cb9f21b-7fa0-4355-a1c7-2ea3c3497a36
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:10:53.992Z, lastHeartbeat: 2023-10-23T09:10:54.013Z)
- BackgroundJobServer id: c3369ac8-796f-45a7-85f7-7d72cb605b01
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:10:53.993Z, lastHeartbeat: 2023-10-23T09:10:53.999Z)
- BackgroundJobServer id: ab5722f0-0818-4dcb-9012-49cce20b7d2f
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:10:54.022Z, lastHeartbeat: 2023-10-23T09:10:54.027Z)
- BackgroundJobServer id: cb930dfa-08c2-4f67-b4d0-a6c16e7257f0
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:10:54.033Z, lastHeartbeat: 2023-10-23T09:10:54.039Z)

#### Concurrent modified jobs:
Job id: d7df6f52-9179-4bcb-a069-0606914c5253
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:10:54.827Z) ← SCHEDULED (at 2023-10-23T09:10:54.815Z)
	Storage state: ENQUEUED (at 2023-10-23T09:10:54.826Z) ← SCHEDULED (at 2023-10-23T09:10:54.815Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

### Runtime information
- __Timestamp__: 2023-10-23T09:11:45.335Z
- __Location__: BackgroundJobServer aabac834-caed-43a2-acc5-25132ba13555
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 1.8.0_372
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 73d204c2-b896-4302-8957-d0804b568091
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.538Z, lastHeartbeat: 2023-10-23T09:11:44.922Z)
- BackgroundJobServer id: 25c51b69-8c9f-4a32-8381-6bb8032a0eea
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.708Z, lastHeartbeat: 2023-10-23T09:11:44.933Z)
- BackgroundJobServer id: 4850f345-82fb-4c08-bcad-036a3776dc97
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.759Z, lastHeartbeat: 2023-10-23T09:11:44.927Z)
- BackgroundJobServer id: 6868d0aa-3879-48eb-8d50-26033b7e4cf3
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.910Z, lastHeartbeat: 2023-10-23T09:11:45.065Z)
- BackgroundJobServer id: d47ed45c-bd92-4351-b736-c42bebf0bedb
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.944Z, lastHeartbeat: 2023-10-23T09:11:45.102Z)
- BackgroundJobServer id: ce988af9-acee-4e08-9e0f-7b426b2ffee6
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.951Z, lastHeartbeat: 2023-10-23T09:11:44.984Z)
- BackgroundJobServer id: 7830318d-45a9-4b32-9705-a5d532a53987
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.005Z, lastHeartbeat: 2023-10-23T09:11:45.103Z)
- BackgroundJobServer id: 4fa0841d-b352-46a1-8e52-cef11a424071
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.012Z, lastHeartbeat: 2023-10-23T09:11:45.068Z)
- BackgroundJobServer id: e265a5a1-978e-461b-8d21-0b6843a80186
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.104Z, lastHeartbeat: 2023-10-23T09:11:45.154Z)

#### Concurrent modified jobs:
Job id: c984bb8d-98c2-456e-9e7b-9697c19aafe3
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:11:45.302Z) ← SCHEDULED (at 2023-10-23T09:11:45.293Z)
	Storage state: ENQUEUED (at 2023-10-23T09:11:45.303Z) ← SCHEDULED (at 2023-10-23T09:11:45.293Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

### Runtime information
- __Timestamp__: 2023-10-23T09:11:45.335Z
- __Location__: BackgroundJobServer 655ef02c-25f5-46ea-a4e1-1198bc1f981b
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 1.8.0_372
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 73d204c2-b896-4302-8957-d0804b568091
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.538Z, lastHeartbeat: 2023-10-23T09:11:44.922Z)
- BackgroundJobServer id: 25c51b69-8c9f-4a32-8381-6bb8032a0eea
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.708Z, lastHeartbeat: 2023-10-23T09:11:44.933Z)
- BackgroundJobServer id: 4850f345-82fb-4c08-bcad-036a3776dc97
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.759Z, lastHeartbeat: 2023-10-23T09:11:44.927Z)
- BackgroundJobServer id: 6868d0aa-3879-48eb-8d50-26033b7e4cf3
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.910Z, lastHeartbeat: 2023-10-23T09:11:45.065Z)
- BackgroundJobServer id: d47ed45c-bd92-4351-b736-c42bebf0bedb
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.944Z, lastHeartbeat: 2023-10-23T09:11:45.102Z)
- BackgroundJobServer id: ce988af9-acee-4e08-9e0f-7b426b2ffee6
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.951Z, lastHeartbeat: 2023-10-23T09:11:44.984Z)
- BackgroundJobServer id: 7830318d-45a9-4b32-9705-a5d532a53987
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.005Z, lastHeartbeat: 2023-10-23T09:11:45.103Z)
- BackgroundJobServer id: 4fa0841d-b352-46a1-8e52-cef11a424071
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.012Z, lastHeartbeat: 2023-10-23T09:11:45.068Z)
- BackgroundJobServer id: e265a5a1-978e-461b-8d21-0b6843a80186
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.104Z, lastHeartbeat: 2023-10-23T09:11:45.154Z)

#### Concurrent modified jobs:
Job id: 55760832-b9b1-4a31-8dab-b0e1b7c4dd50
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:11:45.303Z) ← SCHEDULED (at 2023-10-23T09:11:45.292Z)
	Storage state: ENQUEUED (at 2023-10-23T09:11:45.302Z) ← SCHEDULED (at 2023-10-23T09:11:45.292Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

### Runtime information
- __Timestamp__: 2023-10-23T09:11:45.536Z
- __Location__: BackgroundJobServer 89be21d1-1966-47e8-a15a-0eeb342f5d80
- __JobRunr Version__: 5.3.1
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 1.8.0_372
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 73d204c2-b896-4302-8957-d0804b568091
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.538Z, lastHeartbeat: 2023-10-23T09:11:44.922Z)
- BackgroundJobServer id: 25c51b69-8c9f-4a32-8381-6bb8032a0eea
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.708Z, lastHeartbeat: 2023-10-23T09:11:44.933Z)
- BackgroundJobServer id: 4850f345-82fb-4c08-bcad-036a3776dc97
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.759Z, lastHeartbeat: 2023-10-23T09:11:44.927Z)
- BackgroundJobServer id: 6868d0aa-3879-48eb-8d50-26033b7e4cf3
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.910Z, lastHeartbeat: 2023-10-23T09:11:45.065Z)
- BackgroundJobServer id: d47ed45c-bd92-4351-b736-c42bebf0bedb
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.944Z, lastHeartbeat: 2023-10-23T09:11:45.102Z)
- BackgroundJobServer id: ce988af9-acee-4e08-9e0f-7b426b2ffee6
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:44.951Z, lastHeartbeat: 2023-10-23T09:11:44.984Z)
- BackgroundJobServer id: 7830318d-45a9-4b32-9705-a5d532a53987
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.005Z, lastHeartbeat: 2023-10-23T09:11:45.103Z)
- BackgroundJobServer id: 4fa0841d-b352-46a1-8e52-cef11a424071
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.012Z, lastHeartbeat: 2023-10-23T09:11:45.068Z)
- BackgroundJobServer id: e265a5a1-978e-461b-8d21-0b6843a80186
(workerPoolSize: 32, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-23T09:11:45.104Z, lastHeartbeat: 2023-10-23T09:11:45.154Z)

#### Concurrent modified jobs:
Job id: 2f7cb913-b164-4320-b1c2-0c5bf31a7a02
	Local version: 1; Storage version: 2
	Local state: ENQUEUED (at 2023-10-23T09:11:45.535Z) ← SCHEDULED (at 2023-10-23T09:11:45.527Z)
	Storage state: ENQUEUED (at 2023-10-23T09:11:45.534Z) ← SCHEDULED (at 2023-10-23T09:11:45.527Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:207)
	at org.jobrunr.server.JobZooKeeper.checkForScheduledJobs(JobZooKeeper.java:118)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:97)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by rdehuyss** [comment]
Not using latest version.
