### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by Amimul1234** [jobrunr/jobrunr#861]
### Runtime information
- __Timestamp__: 2023-10-28T15:58:20.521161Z
- __Location__: BackgroundJobServer 280a727d-8a7c-4a91-bb6d-29b709a4b6a0
- __JobRunr Version__: 5.3.3
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 11
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: ac781c6d-9360-46b2-ab26-de9f1ff0fda5
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-26T06:29:59.549832Z, lastHeartbeat: 2023-10-28T16:58:26.258704Z)
- BackgroundJobServer id: 280a727d-8a7c-4a91-bb6d-29b709a4b6a0
(workerPoolSize: 192, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-28T16:55:24.354508Z, lastHeartbeat: 2023-10-28T16:57:14.564142Z)

#### Concurrent modified jobs:
Job id: 889e960c-6d7d-4201-a7ea-5f1464d19f38
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-10-28T15:58:18.353741Z on BackgroundJobServer 280a727d-8a7c-4a91-bb6d-29b709a4b6a0 and started at 2023-10-28T15:57:13.236052Z) ← ENQUEUED (at 2023-10-28T15:57:07.799819Z)
	Storage state: SCHEDULED (at 2023-10-28T15:58:24.961413Z) ← FAILED (at 2023-10-28T15:58:24.961136Z) ← PROCESSING (updated at 2023-10-28T15:57:13.236052Z on BackgroundJobServer 280a727d-8a7c-4a91-bb6d-29b709a4b6a0 and started at 2023-10-28T15:57:13.236052Z) ← ENQUEUED (at 2023-10-28T15:57:07.799819Z)
Job id: efc4c505-2f0b-43f3-8d86-6dc583f273a4
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-10-28T15:58:18.353749Z on BackgroundJobServer 280a727d-8a7c-4a91-bb6d-29b709a4b6a0 and started at 2023-10-28T15:57:13.236053Z) ← ENQUEUED (at 2023-10-28T15:57:06.934215Z)
	Storage state: SCHEDULED (at 2023-10-28T15:58:24.961443Z) ← FAILED (at 2023-10-28T15:58:24.961251Z) ← PROCESSING (updated at 2023-10-28T15:57:13.236053Z on BackgroundJobServer 280a727d-8a7c-4a91-bb6d-29b709a4b6a0 and started at 2023-10-28T15:57:13.236053Z) ← ENQUEUED (at 2023-10-28T15:57:06.934215Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

### Runtime information
- __Timestamp__: 2023-10-28T16:41:17.138529Z
- __Location__: BackgroundJobServer 5413e282-a77e-4112-8047-27323f6bba3a
- __JobRunr Version__: 5.3.3
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 11
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: ac781c6d-9360-46b2-ab26-de9f1ff0fda5
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-26T06:29:59.549832Z, lastHeartbeat: 2023-10-28T17:41:27.588981Z)
- BackgroundJobServer id: 5413e282-a77e-4112-8047-27323f6bba3a
(workerPoolSize: 192, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-28T17:37:14.912274Z, lastHeartbeat: 2023-10-28T17:41:16.535850Z)

#### Concurrent modified jobs:
Job id: f8831a8d-2d7a-462f-b9d7-fc6d02274ddd
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-10-28T16:41:16.535980Z on BackgroundJobServer 5413e282-a77e-4112-8047-27323f6bba3a and started at 2023-10-28T16:40:18.465098Z) ← ENQUEUED (at 2023-10-28T16:40:15.896517Z)
	Storage state: SCHEDULED (at 2023-10-28T16:41:30.072810Z) ← FAILED (at 2023-10-28T16:41:30.072588Z) ← PROCESSING (updated at 2023-10-28T16:40:18.465098Z on BackgroundJobServer 5413e282-a77e-4112-8047-27323f6bba3a and started at 2023-10-28T16:40:18.465098Z) ← ENQUEUED (at 2023-10-28T16:40:15.896517Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

### Runtime information
- __Timestamp__: 2023-10-28T16:47:58.429484Z
- __Location__: BackgroundJobServer 111e4bd2-1471-4a04-953f-bf57f3c1321b
- __JobRunr Version__: 5.3.3
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 11
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: ac781c6d-9360-46b2-ab26-de9f1ff0fda5
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-26T06:29:59.549832Z, lastHeartbeat: 2023-10-28T17:48:12.792023Z)
- BackgroundJobServer id: 111e4bd2-1471-4a04-953f-bf57f3c1321b
(workerPoolSize: 192, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-28T17:46:43.607533Z, lastHeartbeat: 2023-10-28T17:47:39.505837Z)

#### Concurrent modified jobs:
Job id: 84631542-ac62-409b-b622-004921929cb9
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-10-28T16:47:32.872281Z on BackgroundJobServer 111e4bd2-1471-4a04-953f-bf57f3c1321b and started at 2023-10-28T16:47:15.291074Z) ← ENQUEUED (at 2023-10-28T16:47:14.270188Z)
	Storage state: SCHEDULED (at 2023-10-28T16:48:15.783014Z) ← FAILED (at 2023-10-28T16:48:15.782778Z) ← PROCESSING (updated at 2023-10-28T16:47:15.291074Z on BackgroundJobServer 111e4bd2-1471-4a04-953f-bf57f3c1321b and started at 2023-10-28T16:47:15.291074Z) ← ENQUEUED (at 2023-10-28T16:47:14.270188Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

### Runtime information
- __Timestamp__: 2023-10-28T17:58:59.155450Z
- __Location__: BackgroundJobServer 8366d8c9-e434-491d-a107-763f238fa5f9
- __JobRunr Version__: 5.3.3
- __StorageProvider__: org.jobrunr.storage.sql.mysql.MySqlStorageProvider
- __Java Version__: 11
- __Is running from nested jar__: false

### Background Job Servers
- BackgroundJobServer id: ac781c6d-9360-46b2-ab26-de9f1ff0fda5
(workerPoolSize: 8, pollIntervalInSeconds: 15, firstHeartbeat: 2023-10-26T06:29:59.549832Z, lastHeartbeat: 2023-10-28T18:59:14.910001Z)

#### Concurrent modified jobs:
Job id: d05a30c0-58a9-40ff-91d2-5a52850413ff
	Local version: 2; Storage version: 3
	Local state: PROCESSING (updated at 2023-10-28T17:57:42.249671Z on BackgroundJobServer 8366d8c9-e434-491d-a107-763f238fa5f9 and started at 2023-10-28T17:57:12.090841Z) ← ENQUEUED (at 2023-10-28T17:57:04.036426Z)
	Storage state: SCHEDULED (at 2023-10-28T17:58:20.947281Z) ← FAILED (at 2023-10-28T17:58:20.947062Z) ← PROCESSING (updated at 2023-10-28T17:57:12.090841Z on BackgroundJobServer 8366d8c9-e434-491d-a107-763f238fa5f9 and started at 2023-10-28T17:57:12.090841Z) ← ENQUEUED (at 2023-10-28T17:57:04.036426Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:223)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by rdehuyss** [comment]
Not running latest version.
