### ISSUE TITLE
[BUG] Micronaut example project not working when it natively compiled with GraalVM

### ISSUE THREAD

**Issue by navrocky** [jobrunr/jobrunr#867]
### JobRunr Version

6.3.2

### JDK Version

GraalVM JDK 17 

### Your SQL / NoSQL database

PostgeSQL 15

### What happened?

When I compile micronaut example project with `./gradlew nativeCompile` it does not work at runtime and fails with such error:

```
18:31:48.597 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [org.jobrunr.micronaut.autoconfigure.RecurringMethodProcessor]

Message: Error setting field value: No field 'applicationContext' found for type: org.jobrunr.micronaut.autoconfigure.JobRunrFactory
Path Taken: new RecurringMethodProcessor(JobScheduler jobScheduler) --> new RecurringMethodProcessor([JobScheduler jobScheduler])
```

It looks like the cause is injecting a private field in JobRunrFactory. Similar problem described here https://github.com/micronaut-projects/micronaut-core/issues/3782#issuecomment-834578825

### How to reproduce?

```
sdk use java 17.0.9-graal
./gradlew nativeCompile
cd build/native/nativeCompile
./example-jobrunr-micronaut
```

### Relevant log output

```shell
18:31:48.597 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [org.jobrunr.micronaut.autoconfigure.RecurringMethodProcessor]

Message: Error setting field value: No field 'applicationContext' found for type: org.jobrunr.micronaut.autoconfigure.JobRunrFactory
Path Taken: new RecurringMethodProcessor(JobScheduler jobScheduler) --> new RecurringMethodProcessor([JobScheduler jobScheduler])
io.micronaut.context.exceptions.DependencyInjectionException: Error instantiating bean of type  [org.jobrunr.micronaut.autoconfigure.RecurringMethodProcessor]

Message: Error setting field value: No field 'applicationContext' found for type: org.jobrunr.micronaut.autoconfigure.JobRunrFactory
Path Taken: new RecurringMethodProcessor(JobScheduler jobScheduler) --> new RecurringMethodProcessor([JobScheduler jobScheduler])
        at io.micronaut.context.AbstractInitializableBeanDefinition.setFieldWithReflection(AbstractInitializableBeanDefinition.java:957)
        at org.jobrunr.micronaut.autoconfigure.$JobRunrFactory$Definition.inject(Unknown Source)
        at org.jobrunr.micronaut.autoconfigure.$JobRunrFactory$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1675)
        at org.jobrunr.micronaut.autoconfigure.$JobRunrFactory$JobScheduler0$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
        at org.jobrunr.micronaut.autoconfigure.$RecurringMethodProcessor$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2893)
        at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3518)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistrations(DefaultBeanContext.java:3470)
        at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3440)
        at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:983)
        at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:909)
        at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:886)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:2017)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:290)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3337)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3690)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:345)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:198)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:322)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:308)
        at org.jobrunr.examples.Application.main(Application.java:8)
Caused by: java.lang.NoSuchFieldError: No field 'applicationContext' found for type: org.jobrunr.micronaut.autoconfigure.JobRunrFactory
        at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredField$2(ReflectionUtils.java:294)
        at java.base@17.0.9/java.util.Optional.orElseThrow(Optional.java:403)
        at io.micronaut.core.reflect.ReflectionUtils.getRequiredField(ReflectionUtils.java:294)
        at io.micronaut.context.AbstractInitializableBeanDefinition.setFieldWithReflection(AbstractInitializableBeanDefinition.java:950)
        ... 50 common frames omitted
```

**Comment by rdehuyss** [comment]
Thanks for the issue but to be honest, the amount of Micronaut usage compared to Spring Boot is so low that at this time I will not look into this, unless a JobRunr Pro customer asks for it.

Feel free to open a PR.

**Comment by rdehuyss** [comment]
P.s.: the community guidelines ask to have your linkedin profile or company on your github profile. If this is not added, future issues will be closed without response.
