### ISSUE TITLE
[BUG] Deserialization issue with Quarkus and jsonb with native executable

### ISSUE THREAD

**Issue by tms0** [jobrunr/jobrunr#887]
### JobRunr Version

6.3.3

### JDK Version

GraalVM

### Your SQL / NoSQL database

MongoDB

### What happened?

Hi,

There is a deserialization issue with Quarkus and jsonb when running as native executable. It works fine but if a job fails then the error happens. I can't figure out why...

Here's the stack trace : 
```
2023-12-04 14:12:25,652 WARN  [org.job.ser.JobZooKeeper] (backgroundjob-zookeeper-pool-8-thread-2) JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.: jakarta.json.bind.JsonbException: Problem adapting object of type class org.jobrunr.jobs.Job to interface jakarta.json.JsonObject in class class org.jobrunr.utils.mapper.jsonb.JobAdapter
        at org.eclipse.yasson.internal.deserializer.AdapterDeserializer.deserialize(AdapterDeserializer.java:45)
        at org.eclipse.yasson.internal.deserializer.DeserializationModelCreator.lambda$deserializerChainInternal$13(DeserializationModelCreator.java:170)
        at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:138)
        at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:62)
        at org.jobrunr.utils.mapper.jsonb.JsonbJsonMapper.deserialize(JsonbJsonMapper.java:51)
        at org.jobrunr.jobs.mappers.JobMapper.deserializeJob(JobMapper.java:20)
        at org.jobrunr.storage.nosql.mongo.mapper.JobDocumentMapper.toJob(JobDocumentMapper.java:75)
        at com.mongodb.client.internal.MappingIterable.lambda$forEach$0(MappingIterable.java:62)
        at com.mongodb.client.internal.MongoIterableImpl.forEach(MongoIterableImpl.java:118)
        at com.mongodb.client.internal.MappingIterable.forEach(MappingIterable.java:62)
        at com.mongodb.client.internal.MappingIterable.into(MappingIterable.java:67)
        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.findJobs(MongoDBStorageProvider.java:463)
        at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.getScheduledJobs(MongoDBStorageProvider.java:309)
        at org.jobrunr.storage.ThreadSafeStorageProvider.getScheduledJobs(ThreadSafeStorageProvider.java:133)
        at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.lambda$runTask$0(ProcessScheduledJobsTask.java:25)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.getJobsToProcess(ZooKeeperTask.java:89)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:57)
        at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
        at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
        at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
        at java.base@21.0.1/java.util.Arrays$ArrayList.forEach(Arrays.java:4305)
        at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
        at java.base@21.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base@21.0.1/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
        at java.base@21.0.1/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
Caused by: jakarta.json.bind.JsonbException: Unable to deserialize property 'doNotRetry' because of: Error setting value on: org.jobrunr.jobs.states.FailedState@137d1a0a
        at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:80)
        at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:31)
        at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:57)
        at org.eclipse.yasson.internal.deserializer.DefaultObjectInstanceCreator.deserialize(DefaultObjectInstanceCreator.java:29)
        at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
        at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
        at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
        at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
        at org.eclipse.yasson.internal.DeserializationContextImpl.deserializeItem(DeserializationContextImpl.java:138)
        at org.eclipse.yasson.internal.DeserializationContextImpl.deserialize(DeserializationContextImpl.java:127)
        at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:55)
        at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:62)
        at org.jobrunr.utils.mapper.jsonb.JobRunrJsonb.fromJsonValue(JobRunrJsonb.java:90)
        at org.jobrunr.utils.mapper.jsonb.adapters.JobHistoryAdapter.adaptFromJson(JobHistoryAdapter.java:44)
        at org.jobrunr.utils.mapper.jsonb.JobAdapter.adaptFromJson(JobAdapter.java:70)
        at org.jobrunr.utils.mapper.jsonb.JobAdapter.adaptFromJson(JobAdapter.java:25)
        at org.eclipse.yasson.internal.deserializer.AdapterDeserializer.deserialize(AdapterDeserializer.java:43)
        ... 33 more
Caused by: jakarta.json.bind.JsonbException: Error setting value on: org.jobrunr.jobs.states.FailedState@137d1a0a
        at org.eclipse.yasson.internal.deserializer.ValueSetterDeserializer.deserialize(ValueSetterDeserializer.java:40)
        at org.eclipse.yasson.internal.deserializer.types.TypeDeserializer.deserialize(TypeDeserializer.java:41)
        at org.eclipse.yasson.internal.deserializer.ValueExtractor.deserialize(ValueExtractor.java:44)
        at org.eclipse.yasson.internal.deserializer.ValueExtractor.deserialize(ValueExtractor.java:24)
        at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:85)
        at org.eclipse.yasson.internal.deserializer.PositionChecker.deserialize(PositionChecker.java:34)
        at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:46)
        at org.eclipse.yasson.internal.deserializer.NullCheckDeserializer.deserialize(NullCheckDeserializer.java:26)
        at org.eclipse.yasson.internal.deserializer.ObjectDeserializer.deserialize(ObjectDeserializer.java:78)
        ... 49 more
Caused by: java.lang.IllegalArgumentException: Can not set boolean field org.jobrunr.jobs.states.FailedState.doNotRetry to java.lang.Integer
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.fieldaccessor.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:266)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.fieldaccessor.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:270)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.fieldaccessor.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:95)
        at java.base@21.0.1/java.lang.reflect.Field.set(Field.java:836)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:217)
        at java.base@21.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:179)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:186)
        at java.base@21.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:98)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:96)
        at java.base@21.0.1/java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:959)
        at java.base@21.0.1/java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:936)
        at java.base@21.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:105)
        at java.base@21.0.1/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.base@21.0.1/java.lang.invoke.LambdaForm$MH/0x00000004015a3c00.invoke_MT(LambdaForm$MH)
        at org.eclipse.yasson.internal.deserializer.ValueSetterDeserializer.deserialize(ValueSetterDeserializer.java:37)
        ... 57 more

```

### How to reproduce?

Project to reproduce issue: https://github.com/tms0/jobrunr-jsonb-issue

**Comment by rdehuyss** [comment]
To be honest, as long as no Pro customer asks me to support this, I'm afraid I won't look into it.

Again, a matter of where to spend my time.

**Comment by tms0** [comment]
I totally understand.

Do you mind if we reverse the json mapper choice (https://github.com/jobrunr/jobrunr/blob/c9ebf57260a138a389e887602e280e698caba320/framework-support/jobrunr-quarkus-extension/deployment/src/main/java/org/jobrunr/quarkus/extension/deployment/JobRunrExtensionProcessor.java#L202C21-L202C21) to take jackson in first? I can submit a PR for it. For reasons beyond my control, I have both jsonb and jackson in my project...

**Comment by rdehuyss** [comment]
Two things:
- isn't this a bug in JSON-B? JobRunr does nothing special here... Perhaps create a big report there?
- regarding your question, I'm a bit hesitant as the default in Quarkus (as far as I know) is  JSON-B.

**Comment by tms0** [comment]
>     * isn't this a bug in JSON-B? JobRunr does nothing special here... Perhaps create a bug report there?

I have absolutely no idea, I searched for this error and didn't find anything...
 
>     * regarding your question, I'm a bit hesitant as the default in Quarkus (as far as I know) is  JSON-B.

As I understand, they offer the same level of support for Jackson and JSON-B, but they didn't put one above the other. For example in this guide https://quarkus.io/guides/rest-json, they use jackson.

**Comment by rdehuyss** [comment]
After some thought, I'm ok with moving Jackson first. Can you create a PR for this?

**Comment by rdehuyss** [comment]
Workaround in v7 where Jackson comes first by means of PR #913.

**Comment by tms0** [comment]
Thanks, I made it on a local branch, totally forgot to push it!
