### ISSUE TITLE
[BUG] Synchronization problem

### ISSUE THREAD

**Issue by ochsenius** [jobrunr/jobrunr#89]
**Describe the bug**
Hi, sometimes some nodes throws an exception and don´t work anymore. I guess the data is too concurrent.

**Environment**
I'm using version 1.2.5
I'm running on JRE / JDK 12.0.2
I'm using the following StorageProvider AmazonDocumentDBStorageProvider  (on cluster)

**To Reproduce**
put 3 nodes with 2 seconds delay with 8 threads each connected to DocumentDB.
Maybe with redis should work better? anyhow, this should not happends.

**Expected behavior**
I expect the jobrunner don´t stop working.

**Additional context**
Log:

2021-01-24 13:10:15,094 ERROR o.j.s.JobZooKeeper [backgroundjob-zookeeper-pool-4-thread-2] FATAL - JobRunr encountered too many processing exceptions. Shutting down.
org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
        at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:43) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:80) [jobrunr-1.2.5.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: f7b4a5f8-4c6a-436f-8850-1a911c9b3064
        at org.jobrunr.server.concurrent.ConcurrentJobModificationResolver.resolve(ConcurrentJobModificationResolver.java:38) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:189) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:176) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:123) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.runMasterTasks(JobZooKeeper.java:90) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:68) ~[jobrunr-1.2.5.jar!/:?]
        ... 6 more

2021-01-24 13:09:00,115 WARN o.j.s.JobZooKeeper [backgroundjob-zookeeper-pool-4-thread-2] JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue.
org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: efc8614e-0514-4db3-a9cf-708b5010da83, a73d635a-7d8a-4f6e-bf8a-a04bfb6aa5df
        at org.jobrunr.server.concurrent.ConcurrentJobModificationResolver.resolve(ConcurrentJobModificationResolver.java:38) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:189) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:176) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.checkForSucceededJobsThanCanGoToDeletedState(JobZooKeeper.java:123) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.runMasterTasks(JobZooKeeper.java:90) ~[jobrunr-1.2.5.jar!/:?]
        at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:68) [jobrunr-1.2.5.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]

**2021-01-24 13:10:25,100 INFO o.j.s.BackgroundJobServer [backgroundjob-zookeeper-pool-4-thread-2] BackgroundJobServer and BackgroundJobPerformers stopped**

**Comment by rdehuyss** [comment]
Hi, thanks for this bug report! I think I found the reason. 

Am I correct to understand that:
-  you use a `PollIntervalInSeconds` of 2?
- this error happened on the same server?

**Comment by ochsenius** [comment]
Yes, I put it in 3 seconds but it happens again.

**Comment by ochsenius** [comment]
should I use an other Storage?

**Comment by ochsenius** [comment]
this error happens on every node sometimes, and sometimes all nodes stop reading from the storage but they are always writing. I have 2 - 4 nodes , but only one node (the first who connect to the remote server) receive the data that we have to process. That node write to DocumentDB and also process the queue and I expected that every node process the queue too.

**Comment by rdehuyss** [comment]
I world configure at least 5 sec as pollInterval. 

I'm looking into a way of finding the exact cause as this is a difficult issue.

**Comment by ochsenius** [comment]
Ok thanks. If I put 5 seconds and y have twice the nodes I would have the same problem?
Do you recommend that I should use an other storage. Maybe the problem is in the replica of DocumentDB?

**Comment by rdehuyss** [comment]
Well, I can't promise anything as only one other person had the issue and I was unable to reproduce it.

I can guarantee that if you keep the 15 seconds, then you can add as many nodes as you want - this is how most people run it. 
Currently, I don't think it is related to DocumentDB. There is an extensive test-suite that is run against each StorageProvider, including DocumentDB.

Over the next week(s), I'll add more logging to JobRunr (it's not easy as the logs are also distributed) which will help pinpoint the issue.

What is exactly the reason that you want to put the `pollIntervalInSeconds` so low?

**Comment by ochsenius** [comment]
Hi, I need to process data from GPS. The data has already a delay and I can´t add 15 seconds more. The data must be processed as they arrived, but it arrive only in 1 websocket, and only in 1 node, so I need to distribute it in a storage so others can process it. Id did a work around to distribute the load myself and use jobrunr in memory, now is working fine.

**Comment by rdehuyss** [comment]
Hi @ochsenius , I tried to reproduce it with the same settings as you but was unable to do so.

Could you please try again with v1.3.0? If such an error occurs, JobRunr will suggest to generate a Github issue with a lot of debug info so that it is easier to diagnose for me.

Thx!
