### ISSUE TITLE
[BUG] Unsupported class file major version 61 -  even with JDK version 21

### ISSUE THREAD

**Issue by eltonkent** [jobrunr/jobrunr#924]
### JobRunr Version

6.3.4

### JDK Version

Open JDK 21.0.1

### Your SQL / NoSQL database

H2

### What happened?

I'm running a sample on Java version 21.  Enqueuing a job causes the following crash. 
Thanks for your support.

### How to reproduce?

```java
   jobScheduler.enqueue(t -> task.run());
// or 
   BackgroundJob.enqueue(t -> task.run());
```

### Relevant log output

```shell
2024-01-31T11:37:41.681-05:00 DEBUG 56990 --- [  restartedMain] <redacted>  : Java version:  21.0.1
java.lang.IllegalArgumentException: Unsupported class file major version 61
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
        at org.jobrunr.jobs.details.AbstractJobDetailsFinder.parse(AbstractJobDetailsFinder.java:86)
        at org.jobrunr.jobs.details.JavaJobDetailsFinder.<init>(JavaJobDetailsFinder.java:27)
        at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:27)
        at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:94)
        at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:45)
        at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:169)
        at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:152)
```

**Comment by rdehuyss** [comment]
JobRunr 6.3.4 needs ASM 9.5 as a transitive dependency but you have a lower version on your classpath.
