### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eltonkent** [jobrunr/jobrunr#930]
### JobRunr Version

6.3.4

### JDK Version

OpenJDK  17

### Your SQL / NoSQL database

H2

### What happened?

JacksonHibernate uses the javax/persistence package. Which is at odds with the changes in Spring Boot 3.

### How to reproduce?

```java
   BackgroundJob.enqueue(() -> service.helpMe());
```

### Relevant log output

```shell
java.lang.NoClassDefFoundError: javax/persistence/Transient
	at com.fasterxml.jackson.datatype.hibernate5.HibernateAnnotationIntrospector.hasIgnoreMarker(HibernateAnnotationIntrospector.java:69)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasIgnoreMarker(AnnotationIntrospectorPair.java:334)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:604)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:445)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:286)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:393)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:225)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1525)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1473)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:578)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:856)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:330)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4793)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:4038)
	at org.jobrunr.utils.mapper.jackson.JacksonJsonMapper.serialize(JacksonJsonMapper.java:63)
	at org.jobrunr.jobs.mappers.JobMapper.serializeJob(JobMapper.java:16)
	at org.jobrunr.storage.sql.common.db.Sql.setParams(Sql.java:208)
	at org.jobrunr.storage.sql.common.db.Sql.insertOrUpdate(Sql.java:151)
	at org.jobrunr.storage.sql.common.db.Sql.insert(Sql.java:125)
	at org.jobrunr.storage.sql.common.JobTable.insertOneJob(JobTable.java:172)
	at org.jobrunr.storage.sql.common.JobTable.save(JobTable.java:71)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.save(DefaultSqlStorageProvider.java:176)
	at org.jobrunr.scheduling.AbstractJobScheduler.saveJob(AbstractJobScheduler.java:133)
	at org.jobrunr.scheduling.AbstractJobScheduler.enqueue(AbstractJobScheduler.java:108)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:170)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:152)
	at org.jobrunr.scheduling.BackgroundJob.enqueue(BackgroundJob.java:108)
```

**Comment by rdehuyss** [comment]
Not related to JobRunr.
