### ISSUE TITLE
[BUG] JobRunr does not support MySQL 8

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#94]
**Describe the bug**
The logs mention the following:

```java
java.lang.UnsupportedOperationException: Cannot autobox 2021-02-06T07:49:46.118800 of type java.time.LocalDateTime to java.time.Instant
	at org.jobrunr.utils.reflection.autobox.InstantTypeAutoboxer.autobox(InstantTypeAutoboxer.java:25) ~[jobrunr-1.2.4.jar:na]
	at org.jobrunr.utils.reflection.autobox.InstantTypeAutoboxer.autobox(InstantTypeAutoboxer.java:8) ~[jobrunr-1.2.4.jar:na]
	at org.jobrunr.utils.reflection.autobox.Autoboxer.lambda$autobox$1(Autoboxer.java:36) ~[jobrunr-1.2.4.jar:na]
	at java.base/java.util.Optional.map(Optional.java:265) ~[na:na]
	at org.jobrunr.utils.reflection.autobox.Autoboxer.autobox(Autoboxer.java:36) ~[jobrunr-1.2.4.jar:na]
	at org.jobrunr.utils.reflection.ReflectionUtils.autobox(ReflectionUtils.java:268) ~[jobrunr-1.2.4.jar:na]
	at org.jobrunr.storage.sql.common.db.SqlResultSet.asInstant(SqlResultSet.java:56) ~[jobrunr-1.2.4.jar:na]
	at org.jobrunr.storage.sql.common.BackgroundJobServerTable.toBackgroundJobServerStatus(BackgroundJobServerTable.java:120) ~[jobrunr-1.2.4.jar:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at org.jobrunr.storage.sql.common.db.SqlSpliterator.tryAdvance(SqlSpliterator.java:44) ~[jobrunr-1.2.4.jar:na]
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
```

**Environment**
I'm using version 1.2.4
I'm running on JRE / JDK 11
I'm using the following StorageProvider MySqlStorageProvider

**Comment by rdehuyss** [comment]
Resolved in commit #defde41
