### ISSUE TITLE
[BUG] IllegalStateException: Can not find variable 3 in stack

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#942]
### JobRunr Version

6.2.4

### JDK Version

Java 17

### Your SQL / NoSQL database

NA

### What happened?

The issue is ` Can not find variable 3 in stack`.

The reason for it is that the Java `SerializedLambda` returns an unknown `implMethodKind`.

### How to reproduce?

Please see Github project https://github.com/rdehuyss/jobrunr-issue-serialized-lambda.

See also https://stackoverflow.com/questions/78023608/identical-java-serializedlambda-returns-different-implmethodkind

### Relevant log output

```shell
Exception in thread "main" org.jobrunr.JobRunrException: JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace)
	at org.jobrunr.JobRunrException.shouldNotHappenException(JobRunrException.java:33)
	at org.jobrunr.jobs.details.JobDetailsBuilder.getLocalVariable(JobDetailsBuilder.java:50)
	at org.jobrunr.jobs.details.instructions.VisitLocalVariableInstruction.invokeInstruction(VisitLocalVariableInstruction.java:20)
	at org.jobrunr.jobs.details.instructions.AbstractJVMInstruction.invokeInstructionAndPushOnStack(AbstractJVMInstruction.java:18)
	at org.jobrunr.jobs.details.JobDetailsBuilder.invokeInstructions(JobDetailsBuilder.java:92)
	at org.jobrunr.jobs.details.JobDetailsBuilder.getJobDetails(JobDetailsBuilder.java:70)
	at org.jobrunr.jobs.details.AbstractJobDetailsFinder.getJobDetails(AbstractJobDetailsFinder.java:82)
	at org.jobrunr.jobs.details.JavaJobDetailsFinder.getJobDetails(JavaJobDetailsFinder.java:14)
	at org.jobrunr.jobs.details.JobDetailsAsmGenerator.toJobDetails(JobDetailsAsmGenerator.java:18)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator$CacheableJobDetails.getJobDetails(CachingJobDetailsGenerator.java:77)
	at org.jobrunr.jobs.details.CachingJobDetailsGenerator.toJobDetails(CachingJobDetailsGenerator.java:39)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:118)
	at org.jobrunr.scheduling.JobScheduler.enqueue(JobScheduler.java:100)
	at org.jobrunr.scheduling.BackgroundJob.enqueue(BackgroundJob.java:57)
	at org.example.GeoService.run(GeoService.java:32)
	at org.example.Main.main(Main.java:18)
Caused by: java.lang.IllegalStateException: Can not find variable 3 in stack
```

**Comment by rdehuyss** [comment]
Solved by commit f0edc10.
