### ISSUE TITLE
Severe JobRunr Exception

### ISSUE THREAD

**Issue by davidbrazeltonallied** [jobrunr/jobrunr#949]
### Runtime information
- __Timestamp__: 2024-02-26T21:30:24.878252Z
- __Location__: BackgroundJobServer 6c72c464-1154-4994-a476-41a8632260e9
- __JobRunr Version__: 5.3.4
- __StorageProvider__: org.jobrunr.storage.sql.mariadb.MariaDbStorageProvider
- __Java Version__: 11.0.13
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 43aa2107-f151-4b62-b016-f641ba0d5359
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-15T21:19:29.063484Z, lastHeartbeat: 2024-02-26T21:30:20.590182Z)
- BackgroundJobServer id: 6c72c464-1154-4994-a476-41a8632260e9
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-26T21:26:23.270252Z, lastHeartbeat: 2024-02-26T21:30:23.587877Z)
- BackgroundJobServer id: d9a6e678-25a9-4839-9158-271d347a0886
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-26T21:26:24.874326Z, lastHeartbeat: 2024-02-26T21:30:10.269464Z)

#### Concurrent modified jobs:
Job id: 3310fb45-d7ae-4e0b-982f-290ffc96f525
Occurred at: 2024-02-26T21:30:24.878218Z
	Local version: 6; Storage version: 7
	Local state: DELETED (at 2024-02-26T21:29:39.801014Z) ← PROCESSING (updated at 2024-02-26T21:29:39.778489Z on BackgroundJobServer 6c72c464-1154-4994-a476-41a8632260e9 and started at 2024-02-26T21:28:24.377175Z) ← ENQUEUED (at 2024-02-26T21:28:20.797641Z)
	Storage state: DELETED (at 2024-02-26T21:29:26.628104Z) ← PROCESSING (updated at 2024-02-26T21:29:24.681745Z on BackgroundJobServer 6c72c464-1154-4994-a476-41a8632260e9 and started at 2024-02-26T21:28:24.377175Z) ← ENQUEUED (at 2024-02-26T21:28:20.797641Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:219)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

### Runtime information
- __Timestamp__: 2024-02-26T21:31:56.341646Z
- __Location__: BackgroundJobServer d9a6e678-25a9-4839-9158-271d347a0886
- __JobRunr Version__: 5.3.4
- __StorageProvider__: org.jobrunr.storage.sql.mariadb.MariaDbStorageProvider
- __Java Version__: 11.0.13
- __Is running from nested jar__: true

### Background Job Servers
- BackgroundJobServer id: 43aa2107-f151-4b62-b016-f641ba0d5359
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-15T21:19:29.063484Z, lastHeartbeat: 2024-02-26T21:31:50.677547Z)
- BackgroundJobServer id: 6c72c464-1154-4994-a476-41a8632260e9
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-26T21:26:23.270252Z, lastHeartbeat: 2024-02-26T21:31:53.691521Z)
- BackgroundJobServer id: d9a6e678-25a9-4839-9158-271d347a0886
(workerPoolSize: 2, pollIntervalInSeconds: 15, firstHeartbeat: 2024-02-26T21:26:24.874326Z, lastHeartbeat: 2024-02-26T21:31:55.388348Z)

#### Concurrent modified jobs:
Job id: c64183f1-b0b4-41e9-962c-a48dddd826d2
Occurred at: 2024-02-26T21:31:56.341608Z
	Local version: 4; Storage version: 5
	Local state: DELETED (at 2024-02-26T21:30:26.143818Z) ← PROCESSING (updated at 2024-02-26T21:30:26.123669Z on BackgroundJobServer d9a6e678-25a9-4839-9158-271d347a0886 and started at 2024-02-26T21:29:56.014944Z) ← ENQUEUED (at 2024-02-26T21:29:52.860684Z) ← SCHEDULED (at 2024-02-26T21:29:52.843997Z)
	Storage state: DELETED (at 2024-02-26T21:30:13.345217Z) ← PROCESSING (updated at 2024-02-26T21:30:11.014538Z on BackgroundJobServer d9a6e678-25a9-4839-9158-271d347a0886 and started at 2024-02-26T21:29:56.014944Z) ← ENQUEUED (at 2024-02-26T21:29:52.860684Z) ← SCHEDULED (at 2024-02-26T21:29:52.843997Z)

### Exception
```java
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.JobZooKeeper.processJobList(JobZooKeeper.java:219)
	at org.jobrunr.server.JobZooKeeper.updateJobsThatAreBeingProcessed(JobZooKeeper.java:91)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by rdehuyss** [comment]
I don't provide support unless you upgrade to the latest version.
