### ISSUE TITLE
[BUG] java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Mananchawla16** [jobrunr/jobrunr#957]
### JobRunr Version

6.3.5

### JDK Version

17

### Your SQL / NoSQL database

DocumentDb 4.0.0

### What happened?

1. Two jobs scheduled to be run at almost the same time are concurrently getting modified  in the DB.
 Consider Job A scheduled to be triggered at Sat Mar 09 10:52:13 PST 2024
 Consider Job B scheduled to be triggered at Sat Mar 09 10:52:15 PST 2024
 These jobs were concurrently updated in the DB giving ConcurrentJobModificationException.
3. There are multiple warnings for multiple such jobs getting updated. Multiple exceptions of ConcurrentJobModificationException getting triggered
4.  After several such warnings for multiple jobs, the jobrunr stopped working saying "JobRunr encountered too many processing exceptions". All kubernetes pods came down
5. On restart of the pods, the jobrunr is not coming back up giving the error "An unrecoverable error occurred. Shutting server down... java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "this.masterId" is null"

### How to reproduce?

Unfortunately reproducing it involves having one or more jobs that simultaneously get scheduled and are concurrently modified. This happens regularly in our usecase.
Here is a set of log messages that illustrate the issue:

Phase 1:  Two jobs scheduled to run at the same time are concurrently getting updated in the DB:

```
Storage state: ENQUEUED (at 2024-03-09T18:42:44.175209622Z) ← SCHEDULED (at 2024-03-08T18:52:15.605886650Z)
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 14 common frames omitted
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: 9d9f3f76-c852-451f-95b9-baf5bf0cff3f, d16936a3-98f9-4969-9af7-d0e63d93c777
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:291)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 14 common frames omitted
```

Phase 2 : Multiple warnings that two jobs are getting updated concurrently
```
[2024-03-09T18:42:44,239+0000]-[WARN ]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[69]-JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue. org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:67)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: 9d9f3f76-c852-451f-95b9-baf5bf0cff3f, d16936a3-98f9-4969-9af7-d0e63d93c777
Concurrent modified jobs:
Job id: 9d9f3f76-c852-451f-95b9-baf5bf0cff3f
	Job Name: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(ScheduleTriggerRequest())
	Job Signature: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleTriggerRequest)
	Local version: 1; Storage version: 2
```

Phase 3: After several such warnings for multiple jobs, the jobrunr stopped working and all kubernetes pods came down
```
[2024-03-09T19:12:44,317+0000]-[ERROR]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[65]-FATAL - JobRunr encountered too many processing exceptions. Shutting down.
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException 	
          at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81) 	
          at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:67) 	
          at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59) 	
          at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26) 	
          at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47) 	
          at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80) 	
          at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204) 	
          at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80) 	
          at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56) 	
          at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) 	
          at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) 	
          at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) 	
          at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 	
          at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 	
          at java.base/java.lang.Thread.run(Thread.java:833) 
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: ba00057e-abd9-4f84-955f-afbced9a477e 
## Concurrent modified jobs: Job id: ba00057e-abd9-4f84-955f-afbced9a477e 	
Job Name: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(ScheduleTriggerRequest()) 	
Job Signature: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleTriggerRequest) 	
Local version: 1; 
Storage version: 1
```

Phase 4: On restarting the pods are not coming up

```
2:07:34.187 PM	

[2024-03-11T08:37:34,187+0000]-[ERROR]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.s.ServerZooKeeper]-[58]-An unrecoverable error occurred. Shutting server down... java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "this.masterId" is null
	at org.jobrunr.server.ServerZooKeeper.determineIfCurrentBackgroundJobServerIsMaster(ServerZooKeeper.java:123)
	at org.jobrunr.server.ServerZooKeeper.announceBackgroundJobServer(ServerZooKeeper.java:77)
	at org.jobrunr.server.ServerZooKeeper.run(ServerZooKeeper.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by rdehuyss** [comment]
Hi @Mananchawla16 , thanks for updating your profile.

In theory, the issue you mention cannot happen as JobRunr uses optimistic locking to prevent these kind of `ConcurrentJobModificationException`s. On top of that, there are multiple customers running more than 1000 jobs that start at the same time without any problems. That being said, there can always be a corner case we did not find yet.

Could you create a simple github repo that reproduces this? This helps us as it saves us a lot of time to try to reproduce this.

**Comment by Mananchawla16** [comment]
> Hi @Mananchawla16 , thanks for updating your profile.
> 
> In theory, the issue you mention cannot happen as JobRunr uses optimistic locking to prevent these kind of `ConcurrentJobModificationException`s. On top of that, there are multiple customers running more than 1000 jobs that start at the same time without any problems. That being said, there can always be a corner case we did not find yet.
> 
> Could you create a simple github repo that reproduces this? This helps us as it saves us a lot of time to try to reproduce this.
Hey @rdehuyss, Thank you for taking the time to reply. 
Can the ConcurrentJobModificationException also come when there is an issue with job updation in mongodb?
Also, do you have any idea why does the jobrunr not come back up even after restart of the pods?
I'd try to create a simple repo to reproduce as well. Thank you again

**Comment by Mananchawla16** [comment]
Hey @rdehuyss, Thank you for taking the time to reply.
Can the ConcurrentJobModificationException also come when there is an issue with job updation in mongodb?
Also, do you have any idea why does the jobrunr not come back up even after restart of the pods?
I'd try to create a simple repo to reproduce as well. Thank you again

**Comment by rdehuyss** [comment]
No idea why it is not coming up again. If you see the code of [ServerZooKeeper](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java), this can also not happen in theory:
- first the [server announces itself](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java#L76) saving the server ID (the `UUID`) in the DB. 
- then it determines whether it is the master (the master is the longest running server).
  - it [queries](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java#L120) the `StorageProvider` again to have the `UUID` of the longest running server 
  - if we just start and we don't know the `masterId` yet, we [assign the `masterId`](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java#L122) with the previous result.
  
So, I don't see a case where this can be null (nor do over 5000 integration tests 😊). As the server announces itself, there should always be at least one server announced and thus UUID returned when [querying for longest running server](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/storage/nosql/mongo/MongoDBStorageProvider.java#L183-L191) in the database.

**Comment by Mananchawla16** [comment]
@rdehuyss In what cases can longestRunningBackgroundJobServerId be null, because that is where it is erroring out? 
Reference: [assign the masterId](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/ServerZooKeeper.java#L122)

**Comment by rdehuyss** [comment]
None that I know of.

**Comment by neha2016** [comment]
Hi @rdehuyss 
I hope you're having a good day. I work with Manan in the same team.  
I had done some POCs with Jobrunr back in 2021 and we had few correspondences as well back then.  In my POCs and tests, everything seemed to be working just fine. However, now that we're getting ready to go live, we've been experiencing some issues that we'd like to get resolved.

I noticed that you're suggesting using the paid version of the library for expedited support, but we'd love to explore other options before going down that route.  Based on our understanding of Jobrunr's promise to provide basic scheduling functionalities, we believe that the non-paid version should be able to handle the issues we're experiencing, and we're more than happy to lend a hand to help identify the root cause of the problem. If we do create the public version of the code (which btw will mostly include creating a schedule with Amazon document DB), would you be open to help us narrow down the issue using that code (want to ensure that our efforts will not be in vain 😊 )?

We saw a few GitHub issues that might be related to our problem, and we'd be super appreciative if you could collaborate with us to investigate them and see if it could be causing our issue. We'd be more than happy to hop on a call to discuss this in more detail.
1. https://github.com/jobrunr/jobrunr/issues/89
2. https://github.com/jobrunr/jobrunr/issues/232
3.  https://github.com/jobrunr/jobrunr/issues/210/

Anyway, I just wanted to thank you for developing Jobrunr; it's a fantastic piece of software, and we're thankful for your hard work.

**Comment by rdehuyss** [comment]
Hi @neha2016 , 

If you can reproduce the issue in a minimal example with Amazon Document DB, I will definitely have a look. I prefer not to hop on a call at this time, I would first like to see the issue reproduced.  

Regarding the issues you mention: in the early days of JobRunr we indeed had issues like that but most of them are solved (there is no such issue that I know of for the moment). On top of that, JobRunr processes about 1.000.000.000 per 24h these days (collected via anonymous data usage) without any problems.

My gut feeling tells me this is something related to how you use JobRunr at Intuit but again if you're able to setup a minimal GitHub repo that reproduces the issue, we will look into it asap.

**Comment by neha2016** [comment]
Thanks a lot for taking the time @rdehuyss 
We will be getting back to you with a reproducible version soon.

**Comment by Mananchawla16** [comment]
Hey @rdehuyss, thank you so much for taking out your valuable time to help us. I have created the following repo that will help you understand how we configure the document db and the usecase for which we are using jobrunr.
Hopefully this will help you to replicate this issue.
https://github.com/Mananchawla16/schedulerrepo
Please let me know if you have any questions or need any more details.
Thank you again

**Comment by rdehuyss** [comment]
Hi @Mananchawla16 , does it fail with the exception you have?

**Comment by Mananchawla16** [comment]
Hey, the ConcurrentJobModificationException comes sometimes not always but it came through this code only. And the An _unrecoverable error occurred. Shutting server down... java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because "this.masterId" is null_ comes through this code. Thank you

**Comment by rdehuyss** [comment]
Hi @Mananchawla16, @neha2016,

we just went through your reproducing example project and from our side, this reproducer is way too big and as you mention the issue comes only sometimes. 
Typically, reproducing repositories are small (see issue https://github.com/jobrunr/jobrunr/issues/959 as an example) and reproduce the issue exactly.

JobRunr is open-source (which != free) so feel free to have a look and try to find the root cause of the issue you're encountering and open a PR but as it stands, I'm afraid we cannot help you. See also https://github.com/jobrunr/jobrunr/discussions/769.

Feel free to re-open the issue once you have a repository with max 10 classes that reproduces the issue always / instantly (so not sometimes).

**Comment by neha2016** [comment]
Hi @rdehuyss Thanks for the response.
We're observing the issue of ConcurrentModificationExceptions occur only when we're using more than 1 nodes of Document DB. If it's just a single document DB node, then the issue doesn't occur. 
Is there any recommendation around the cluster setting of Document DB?

**Comment by neha2016** [comment]
Hi @rdehuyss 
It looks like ConcurrentModificationExceptions is an expected behaviour and infact the result of optimistic locking. That means, when one of the processes fails to work on a job because another process is already working on that job, it does throw that exception. Could you please confirm if that's correct understanding?
But if too many such exceptions happen, the kubernetes process itself dies due to ```
`[ERROR]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[65]-FATAL - JobRunr encountered too many processing exceptions. Shutting down.
org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException `
``` and the pod post that doesn't come back by itself again. Is that also expected behavior?

**Comment by rdehuyss** [comment]
Hi @neha2016 ,

If an `ConcurrentJobModificationException` happens, this is handled by the [BackgroundJobPerformer](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/BackgroundJobPerformer.java#L69-L80).

Only for the server where [updateJobStateToProcessingRunJobFiltersAndReturnIfProcessingCanStart](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/BackgroundJobPerformer.java#L69-L80) returns true, the job will start processing. This guarantees that only one service will process the actual job.

All other possible `ConcurrentJobModificationExceptions` are handled by the [DefaultConcurrentJobModificationResolver](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/server/concurrent/DefaultConcurrentJobModificationResolver.java). 

The reason why you may see such a `ConcurrentJobModificationException` is when you use the `StorageProvider` api and update jobs while processing which is not allowed as explained in the [Job JavaDoc](https://github.com/jobrunr/jobrunr/blob/master/core/src/main/java/org/jobrunr/jobs/Job.java#L27-L34). 

On top of that you did not share the information we need to diagnose such problems. It comes right after: 
```
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: ba00057e-abd9-4f84-955f-afbced9a477e 
## Concurrent modified jobs: Job id: ba00057e-abd9-4f84-955f-afbced9a477e 	
Job Name: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(ScheduleTriggerRequest()) 	
Job Signature: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleTriggerRequest) 	
Local version: 1; 
Storage version: 1
```
There is more logging which starts as below and provides us with critical information to resolve such issues.
```
Local state: ...
Storage state: ...
```

On top of that, as soon as such an error is encountered, the Dashboard offers to create an issue for you automatically with all the info we need.

I hope this helps,
Ronald

**Comment by neha2016** [comment]
Thanks a ton Ronald for the response.

Maybe the below examples can help

Example 1
`[2024-03-20T12:43:41,864+0000]-[WARN ]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[69]-JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue. org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:67)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
	at org.jobrunr.server.zookeeper.tasks.DeleteSucceededJobsTask.runTask(DeleteSucceededJobsTask.java:29)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: f849173b-81da-4022-9f3c-4746f5245ad1
## Concurrent modified jobs:
Job id: f849173b-81da-4022-9f3c-4746f5245ad1
	Job Name: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(ScheduleTriggerRequest())
	Job Signature: com.intuit.scheduler.library.services.ScheduleJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleTriggerRequest)
	Local version: 4; Storage version: 5`
	
	`Storage state: DELETED (at 2024-03-20T12:43:41.845781933Z) ← SUCCEEDED (at 2024-03-19T00:42:47.872814334Z) ← PROCESSING (updated at 2024-03-19T00:42:47.844754693Z on BackgroundJobServer 9a7ba87f-a018-496d-9768-01e1e2559ff1 and started at 2024-03-19T00:42:47.844754693Z) ← ENQUEUED (at 2024-03-19T00:42:47.831369633Z) ← SCHEDULED (at 2024-03-19T00:42:02.676069628Z)
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 14 common frames omitted
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: f849173b-81da-4022-9f3c-4746f5245ad1
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:291)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 14 common frames omitted`
	
Example 2
`	Storage state: ENQUEUED (at 2024-03-20T12:41:41.722405989Z) ← SCHEDULED (at 2024-03-20T12:40:07.592895039Z)
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 14 common frames omitted
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: a4d4f79d-2756-472b-9c99-dd8af4a3799b
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:291)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 14 common frames omitted`

`[2024-03-20T12:41:41,750+0000]-[WARN ]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[69]-JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue. org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:67)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: a4d4f79d-2756-472b-9c99-dd8af4a3799b
## Concurrent modified jobs:
Job id: a4d4f79d-2756-472b-9c99-dd8af4a3799b
	Job Name: com.intuit.scheduler.library.services.ScheduleRecurringJobRequestHandler.run(ScheduleRecurringTriggerRequest(repeatCount=2, repeatInterval=[5 minutes, 5 minutes]))
	Job Signature: com.intuit.scheduler.library.services.ScheduleRecurringJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleRecurringTriggerRequest)
	Local version: 1; Storage version: 2`

Example 3
`Storage state: SCHEDULED (at 2024-03-20T12:42:42.311200675Z)
	at org.jobrunr.server.concurrent.DefaultConcurrentJobModificationResolver.resolve(DefaultConcurrentJobModificationResolver.java:50)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:79)
	... 14 common frames omitted
Caused by: org.jobrunr.storage.ConcurrentJobModificationException: The following jobs where concurrently updated: e8fd828c-f86a-4472-9e22-ec0cc8aae0b1
	at org.jobrunr.storage.nosql.mongo.MongoDBStorageProvider.save(MongoDBStorageProvider.java:291)
	at org.jobrunr.storage.ThreadSafeStorageProvider.save(ThreadSafeStorageProvider.java:112)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:75)
	... 14 common frames omitted`	
	
`[2024-03-20T12:44:41,912+0000]-[WARN ]-["backgroundjob-zookeeper-pool-8-thread-1"  cid=, clu=]-[o.j.server.JobZooKeeper]-[69]-JobRunr encountered a problematic exception. Please create a bug report (if possible, provide the code to reproduce this and the stacktrace) - Processing will continue. org.jobrunr.SevereJobRunrException: Could not resolve ConcurrentJobModificationException
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:81)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:67)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.processJobList(ZooKeeperTask.java:59)
	at org.jobrunr.server.zookeeper.tasks.ProcessScheduledJobsTask.runTask(ProcessScheduledJobsTask.java:26)
	at org.jobrunr.server.zookeeper.tasks.ZooKeeperTask.run(ZooKeeperTask.java:47)
	at org.jobrunr.server.JobZooKeeper.lambda$runMasterTasksIfCurrentServerIsMaster$0(JobZooKeeper.java:80)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4204)
	at org.jobrunr.server.JobZooKeeper.runMasterTasksIfCurrentServerIsMaster(JobZooKeeper.java:80)
	at org.jobrunr.server.JobZooKeeper.run(JobZooKeeper.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.jobrunr.server.concurrent.UnresolvableConcurrentJobModificationException: The following jobs where concurrently updated: e8fd828c-f86a-4472-9e22-ec0cc8aae0b1
## Concurrent modified jobs:
Job id: e8fd828c-f86a-4472-9e22-ec0cc8aae0b1
	Job Name: com.intuit.scheduler.library.services.ScheduleRecurringJobRequestHandler.run(ScheduleRecurringTriggerRequest(repeatCount=1, repeatInterval=[5 minutes]))
	Job Signature: com.intuit.scheduler.library.services.ScheduleRecurringJobRequestHandler.run(com.intuit.scheduler.library.entities.ScheduleRecurringTriggerRequest)
	Local version: 1; Storage version: 1`

**Comment by rdehuyss** [comment]
@neha2016 , again there is information missing and you did not properly format your stacktraces.

This is an [example](https://github.com/jobrunr/jobrunr/issues/949) of what JobRunr creates automatically for you, why can you not provide it? Did you change code of JobRunr?

**Comment by rdehuyss** [comment]
Hi @neha2016, @Mananchawla16,

First of all, I still don't understand why you cannot provide us with the necessary info to help you.  JobRunr offers you to automatically create a GitHub issue in case you have the exception you're having: see the video at https://www.jobrunr.io/en/blog/2021-02-07-v1.3. This is how other developers report us these kind of issues as it helps us diagnose the root cause. 

Second, I just cloned [the reproducer repo](https://github.com/Mananchawla16/schedulerrepo) you provided earlier on and to be honest, I'm **really disappointed**.

Your `pom.xml` mentions the following:
```xml
<dependency>
    <groupId>org.jobrunr</groupId>
    <artifactId>jobrunr-spring-boot-starter</artifactId>
    <version>${jobrunr.version}</version> <!-- in the pom.xml in your example rep, jobrunr.version is set to 6.3.5 -->
</dependency>
```

This cannot work. As of release 6, `jobrunr-spring-boot-starter` has been deprecated as mentioned in the [breaking changes](https://www.jobrunr.io/en/blog/2023-01-29-jobrunr-v6.0.0/#breaking-changes) section of our release notes in v6 and has been replaced by `jobrunr-spring-boot-3-starter`. If you look at Maven Central, the last version of [jobrunr-spring-boot-starter](https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-starter) is **5.3.3** and as of v6, this has been moved to the artifact [jobrunr-spring-boot-3-starter](https://mvnrepository.com/artifact/org.jobrunr/jobrunr-spring-boot-3-starter).


### My conclusion
- if you cannot even take the time to read the release notes 
- if you cannot even take the time to provide us with an example repo where the code compiles instead of getting the following exception: `Could not find artifact org.jobrunr:jobrunr-spring-boot-starter:pom:6.3.5 in central (https://repo.maven.apache.org/maven2)`

then our **support ends here**. This is an exact example of what is causing [open-source developer burnout](https://github.com/jobrunr/jobrunr/discussions/769) and makes me work until 9pm.

This conversation is locked as of now. If you need any further support from our side, we will require you to take a Pro subscription.

P.s.: you can also thank my colleague, @auloin (please send him chocolates), to tell me about github issue #569 which is probably the cause of the problems you're seeing.
