### ISSUE TITLE
[BUG] Spring Boot GraalVM native mode build fails if Bean is defined via `JavaConfig`

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#962]
### JobRunr Version

6.3.5

### JDK Version

GraalVM 21

### Your SQL / NoSQL database

NA

### What happened?

When building a GraalVM native mode application with JobRunr using `JobRequest`/`JobRequestHandler` where the `JobRequestHandler` is defined in the JavaConfig the native build fails with the following error message:

```java
2024-03-16T08:43:02.427+01:00  INFO 21548 --- [worker] [           main] com.example.worker.WorkerApplication     : Starting WorkerApplication using Java 21.0.2 with PID 21548 (/Users/rdehuyss/Projects/JobRunr/bugs/spring-graalvm/worker/target/classes started by rdehuyss in /Users/rdehuyss/Projects/JobRunr/bugs/spring-graalvm/worker)
2024-03-16T08:43:02.428+01:00  INFO 21548 --- [worker] [           main] com.example.worker.WorkerApplication     : No active profile set, falling back to 1 default profile: "default"
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local1>" is null
        at org.jobrunr.utils.reflection.ReflectionUtils.toClass(ReflectionUtils.java:65)
        at org.jobrunr.spring.aot.JobRunrBeanFactoryInitializationAotProcessor.registerAllJobRequestHandlers(JobRunrBeanFactoryInitializationAotProcessor.java:103)
```

### How to reproduce?

See the reproducing example at https://github.com/spring-tips/jobrunr

**Comment by rdehuyss** [comment]
Solved in branch v7.
