### ISSUE TITLE
[BUG] java.lang.IllegalStateException: zip file closed in RunningOnJava11OrLowerWithinFatJarNoS

### ISSUE THREAD

**Issue by ctron-te** [jobrunr/jobrunr#99]
**Describe the bug**
```
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:920) ~[na:na]
        at java.base/java.util.zip.ZipFile.stream(ZipFile.java:647) ~[na:na]
        at java.base/java.util.zip.ZipFile$1.stream(ZipFile.java:1136) ~[na:na]
        at java.base/java.util.jar.JarFile.stream(JarFile.java:536) ~[na:na]
        at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoS
qlMigrationProvider.getMigrationsFromJarUrlConnection(RunningOnJava11OrLowerWithinFatJarNoSq
lMigrationProvider.java:30) ~[jobrunr-1.3.0.jar!/:na]
        at org.jobrunr.storage.nosql.common.migrations.RunningOnJava11OrLowerWithinFatJarNoS
qlMigrationProvider.getMigrations(RunningOnJava11OrLowerWithinFatJarNoSqlMigrationProvider.j
ava:20) ~[jobrunr-1.3.0.jar!/:na]
        at org.jobrunr.storage.nosql.common.NoSqlDatabaseMigrationsProvider.getMigrations(No
SqlDatabaseMigrationsProvider.java:27) ~[jobrunr-1.3.0.jar!/:na]
```
**Environment**
I'm using version 1.3.0
I'm running on JRE / JDK openjdk version "11.0.10" 2021-01-19
I'm using the following StorageProvider Redis

**To Reproduce**
I get this error when running inside a fat jar. It works fine when running through intelliJ

**Expected behavior**
Should work as expected within a fatj jar

**Additional context**

**Comment by rdehuyss** [comment]
Could you setup a Github project that reproducties it?

I'm really busy with some personal stuff and these projects that reproduce the error save me a lot of time.

**Comment by ctron-te** [comment]
sure let me try

**Comment by ctron-te** [comment]
ok that was easy actually:
1. `$ git clone git@github.com:jobrunr/example-spring.git`
2. Edit `build.gradle` to use version `1.3.0`
3. `$ ./gradlew assemble`
3. `$ java -jar webapp/build/libs/webapp-1.0.jar`

This is not happening on 1.2.0 so I will revert to that for now. Perhaps this was caused by the changes to Redis Storage

**Comment by rdehuyss** [comment]
Hi @ctron-te , @wijnandtop, @cathalbahn, this is a fix related to running JobRunr inside Spring Boot nested jar on Java 11 or lower.

Could you guys double check if all is fine? Steps to do so:
- checkout JobRunr master
- run ./gradlew clean publishToMavenLocal
- in your project, replace the JobRunr version to 1.0.0-SNAPSHOT
- test and report back

Reason I'm asking is that it is really difficult to write unit tests for this (it's related to recent Spring changes and they do some weird stuff related to jar loading. I now tried an approach so that Spring does not intervene).

Thx!

**Comment by ctron-te** [comment]
Sorry @rdehuyss I was off for a few days. I tried the snapshot version. The original problem disappears but I now get the following error:

```
2021-03-03 13:46:31.030  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v000__create_migrations_table.sql}
2021-03-03 13:46:31.036  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v001__create_job_table.sql}
2021-03-03 13:46:31.046  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v002__create_recurring_job_table.sql}
2021-03-03 13:46:31.050  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v003__create_background_job_server_table.sql}
2021-03-03 13:46:31.059  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v004__create_job_stats_view.sql}
2021-03-03 13:46:31.087  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v005__update_job_stats_view.sql}
2021-03-03 13:46:31.091  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v006__alter_table_jobs_add_recurringjob.sql}
2021-03-03 13:46:31.100  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v007__alter_table_backgroundjobserver_add_delete_config.sql}
2021-03-03 13:46:31.104  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v008__alter_table_jobs_increase_jobAsJson_size.sql}
2021-03-03 13:46:31.106  INFO 30146 --- [           main] o.j.storage.sql.common.DatabaseCreator   : Running migration SqlMigrationByZipEntry{name=org/jobrunr/storage/sql/common/migrations/v009__change_jobrunr_job_counters_to_jobrunr_metadata.sql}
2021-03-03 13:46:31.286  WARN 30146 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerAdapter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter]: Factory method 'requestMappingHandlerAdapter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageConverters' defined in class path resource [org/springframework/boot/autoconfigure/http/HttpMessageConvertersAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.autoconfigure.http.HttpMessageConverters]: Factory method 'messageConverters' threw exception; nested exception is java.lang.NoSuchMethodError: org/springframework/http/converter/support/AllEncompassingFormHttpMessageConverter.getPartConverters()Ljava/util/List; (loaded from jar:file:/Users/ctron/tmp/example-spring/webapp/build/libs/webapp-1.0.jar!/BOOT-INF/lib/spring-web-5.2.9.RELEASE.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@1eae6a53) called from class org.springframework.boot.autoconfigure.http.HttpMessageConverters (loaded from jar:file:/Users/***/tmp/example-spring/webapp/build/libs/webapp-1.0.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.4.1.jar!/ by org.springframework.boot.loader.LaunchedURLClassLoader@1eae6a53).
```

**Comment by rdehuyss** [comment]
Hi @ctron-te , 

At first sight, this looks unrelated to JobRunr but more like a Spring version mismatch. In the error message, JobRunr is also not referenced.

I tested this with the JobRunr spring example project and with these changes all is fine. I'll see if I have some time to push a branch on the JobRunr spring example project which works with Redis.

**Comment by ctron-te** [comment]
yes agreed. Not sure what happened.
It sounds like it's ok to release and then I can test that released version on our service running JobRunr
