### ISSUE TITLE
[BUG] RecurringJobNotFoundException when migrating to v7.0.0 - when recurring job cron is disabled and entity never existed in recurring_jobs table.

### ISSUE THREAD

**Issue by gwieczorek-it** [jobrunr/jobrunr#990]
### JobRunr Version

7.0.0

### JDK Version

openjdk-21

### Your SQL / NoSQL database

Postgres 15

### What happened?

- Migration from v6.3.8 to v7.0.0
- jobrunr-pro-spring-boot-3-starter

Problem migrating Recruing jobs with new `org.jobrunr.jobs.annotations.Recurring` annottation, when we have disabled scheduler in specific environments.

Cron defined as "-" for local / test / other_not_important environments, where we do not run specific recurring jobs at all.

In previous version - recurring job entity was not added to recurring_jobs table.
When updating version error is raised due to missing entity.

> Caused by: org.jobrunr.storage.RecurringJobNotFoundException: Recurring job with id exchange-rates-fetch-and-save does not exist
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.lambda$getRecurringJobById$4(DefaultSqlStorageProvider.java:450)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.jobrunr.storage.sql.common.DefaultSqlStorageProvider.getRecurringJobById(DefaultSqlStorageProvider.java:450)
	at org.jobrunr.storage.StorageProvider.deleteRecurringJob(StorageProvider.java:360)
	at org.jobrunr.scheduling.AbstractJobScheduler.deleteRecurringJob(AbstractJobScheduler.java:137)
	at org.jobrunr.scheduling.RecurringJobPostProcessor$RecurringJobFinderMethodCallback.doWith(RecurringJobPostProcessor.java:96)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:366)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:342)
	at org.jobrunr.scheduling.RecurringJobPostProcessor.postProcessAfterInitialization(RecurringJobPostProcessor.java:43)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:438)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1789)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	... 25 common frames omitted

### How to reproduce?

```kotlin

    @Job(name = "Test job")
    @Recurring(
        id = "test-job-id",
        cron = "\${scheduler.test-job.crontab}"
    )
    fun executeTask() {
        println("test jon")
    }

```

and in some env yamls we have:
```yaml
scheduler.test-job.crontab: "-"
```

**Comment by rdehuyss** [comment]
Thanks for reporting, merged to master and will be solved in JobRunr Pro v9.0.2.
